### ISSUE TITLE
PoC: Package language-server as a library

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#10010]
Recent Hubert's investigations have brought up issue of `Api.Runtime` envelop serialization and deserialization overhead. It has already been tracked as

- #5741

and a possible suggestion to avoid such overhead was outlined in

- #5419

Ultimately that leads to [Making Language Server Part of the IDE](https://github.com/enso-org/enso/issues/7683#issuecomment-1698818418) - that solves the _versioning problem_. However to get to that we need to **move language server** code to _hosted area_ - e.g. place it into `polyglot/java`.

By packaging the language server implementation as an Enso library `Standard.Language_Server` and bundling it together with the IDE we will always guarantee the he [language server protocol](https://github.com/enso-org/enso/blob/develop/docs/language-server/protocol-language-server.md) version required by the IDE is the same as the one supported by the  `Standard.Language_Server` library.

```[tasklist]
### Tasks
- [x] Remove dependency of runner on language-server and its libraries - #10536
- [ ] Package `language-server` code into `polyglot/java` directory of some (maybe `Standard.Language_Server` or ` Standard.Visualization` library)
- [ ] Change _boot sequence_ to launch such server
- [ ] Make sure the language server code can still send _the same_ messages to `runtime.jar`
```

When this is achieved, change the server to call into _runtime via builtins_.

**Comment by JaroslavTulach** [comment]
- since #14245
- and #13178
- the `ydoc-server` is a separate `.so` library
- #14142 will remove networking layer from language server
- and move it into the `ydoc-server` library
- I guess that's basically what this PoC PR was calling for
