### ISSUE TITLE
Store FramePointer in the IR and cache it

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#10129]
This inquiry is inspired by this [IrToTruffle code](https://github.com/enso-org/enso/blob/e9452ea8ad3bf6fc3216d785117b554a8318dbf0/engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala#L1685). First of all it, takes `Occurance` from the IR:
```java
          val useInfo = name
            .unsafeGetMetadata(
              AliasAnalysis,
              "No occurrence on variable usage."
            )
            .unsafeAs[AliasInfo.Occurrence]

          val framePointer = scope.getFramePointer(useInfo.id)
```
and it converts it into `FramePointer` to do that it needs a `scope` also coming from the IR (some parent).  The conversion of `Occurence` via `LocalScope` is non-trivial as observed by 
- #9235

However, **we don't have to do it at all**! All we need is the `FramePointer` (a pair of integers), we don't need all the scopes & co. As such:

Let's compute `FramePointer` onces, before **generating caches** and then just load it.

```[tasklist]
### Tasks
- [ ] Implement an `IRPass` to compute the `FramePointer` and store it as _metadata_
- [ ] Change `IrToTruffle` to just read `FramePointer`
- [ ] Ideally make sure `AliasInfo` & co. isn't read from caches at all
- [ ] Verify some benchmark times have improved
```

**Comment by hubertp** [comment]
Could potentially eliminate a lot of deserialization that is currently done for AliasAnalysis, e.g. 
![Screenshot from 2024-07-10 20-36-49](https://github.com/enso-org/enso/assets/292128/a1b25218-9efb-40ef-81fd-f074d2b21471)
