### ISSUE TITLE
Vue.js SPA displaying benchmark results - e.g. website 2.0

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#10212]
## Current solution (bad)
The current website with plots of all the benchmarks is a static website generated from a Jinja template by [website_regen.py script](https://github.com/enso-org/enso/blob/develop/tools/performance/engine-benchmarks/website_regen.py) hosted with GitHub pages on https://enso-org.github.io/engine-benchmark-results/.

This has many disadvantages:
- Hard to maintain. Especially with some Javascript code in the HTML template.
- The resulting web pages are huge and very slow to load, because they contain all the data inside Javascript embedded in the HTML.
- The [Google charts JS library](https://developers.google.com/chart) used by the template is ugly and difficult to work with and with insufficient documentation.
- It is very difficult to add any dynamic behavior like loading data on demand or comparing results of two branches.

## Motivation
There are requests for new features in the current website:
- Plot also Enterprise edition benchmarks along with Community edition.
- Compare results from a custom branch to the results of the `develop` branch.
  - Currently handled only by the [bench_download.py cmd line script](https://github.com/enso-org/enso/blob/develop/tools/performance/engine-benchmarks/bench_download.py). 
- Display standard deviation.

It is easier to implement the current features along with the requested ones from scratch using VueJS than to add them to the current template solution.

## VueJS proposal
Let's implement a single page application with VueJS and use some more responsive, sophisticated and better documented plotting library, like [ChartJS](https://www.chartjs.org/). The data will be fetched from the [cache](https://github.com/enso-org/engine-benchmark-results/tree/main/cache) directory in the same repo. We only need some `index.json` file that maps names of the files to their timestamps. **There is no need for any sophisticated backend or a database yet**. Just build static single page application with VueJS and host it on GitHub pages. Access to the cache directory in the same repo should be straightforward. The application won't be needed to regenerate on a daily basis, just when new features are added.

A prototype is being developed in https://github.com/enso-org/engine-benchmark-results/tree/vue

## Benchmark data upload
The data for the benchmarks are uploaded daily by the [Benchmarks Upload GH Action](https://github.com/enso-org/enso/actions/workflows/bench-upload.yml) into the directory https://github.com/enso-org/engine-benchmark-results/tree/main/cache as JSON files. Note that *this task does not need any change to the data uploading functionality*.

## Related
- https://github.com/enso-org/enso/issues/5714
- https://github.com/enso-org/enso/issues/9355

There is a [branch with working (to some extent) UI](https://github.com/enso-org/engine-benchmark-results/tree/vue). Let's finish this and **make the new UI visible**. These are the minimal steps that have to be done:

```[tasklist]
### Tasks
- [ ] modify the [main benchmarking page](https://github.com/enso-org/engine-benchmark-results/blob/main/index.html) to contain **three links** (not just two). The new link will point to _experimental Vue.js based SPA_.
- [ ] Merge `vue` branch into `main`.
- [ ] Generate static HTML pages from Vue with something like `vite generate static`. Put them into [view subdirectory](https://enso-org.github.io/engine-benchmark-results/view/). Ensure that our manually maintained `index.html` points to the index as generated by `vite`.
- [x] Generate `index.json` by executing [construct_index.py](https://github.com/enso-org/engine-benchmark-results/blob/vue/scripts/construct_index.py) by an CI job
- [x] verify the SPAs display some data from the generated indexes
```
No need for any further automation right now. Being able to see latest benchmark results in the Vue.js SPA (preferably also from other than develop branch) is good enough starting point.

**Comment by Akirathan** [comment]
Priority is high because the results of Oracle GraalVM (Enterprise Edition) benchmarks, implemented on 2024-03-12 in https://github.com/enso-org/enso/pull/9322 are stored only as GH artifacts so far that are dropped after 3 months without any recovery or backup. The initial results are already dropped. Let's make sure they are stored permanently in [engine-benchmark-results repo](https://github.com/enso-org/engine-benchmark-results).

**Comment by JaroslavTulach** [comment]
Let's finish integration of this new, cool, Vue.js based SPA!

![current tasklist](https://github.com/user-attachments/assets/e930a5f4-c976-4cd7-ae7c-f805363e27f0)

Added three essential tasks to finish this issue.
