### ISSUE TITLE
June 2024 Release blockers

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10356]
```[tasklist]
### Tasks
- [ ] https://github.com/enso-org/enso/issues/10341
- [ ] https://github.com/enso-org/enso/issues/10354
- [ ] https://github.com/enso-org/cloud-v2/issues/1328
- [ ] https://github.com/enso-org/enso/issues/10359
- [ ] https://github.com/enso-org/enso/pull/10358
- [ ] https://github.com/enso-org/enso/issues/10364
- [x] Repair NASDAQ example.
- [ ] https://github.com/enso-org/enso/pull/10368
- [ ] https://github.com/enso-org/enso/pull/10373
- [ ] https://github.com/enso-org/enso/pull/10375
- [ ] https://github.com/enso-org/enso/pull/10372
- [ ] https://github.com/enso-org/enso/issues/10282
- [ ] https://github.com/enso-org/enso/pull/10384
```

**Comment by jdunkerley** [comment]
June release completed.
