### ISSUE TITLE
Doc Panel Issues

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#10435]
```[tasklist]
### Tasks
- [x] Pasting Images
- [x] Numbered lists reset on re-opening
- [ ] https://github.com/enso-org/enso/issues/10678
- [x] Doc Panel does not save its position on close
- [x] Images don't appear until panel is closed and re-opened. Link appears on initial creation.
- [x] Doc panel resizing not working
```
## Pasting Images
- When pasting in docs from an external source (e.g. Preppin'Data), the links to the images come in and initially appear.
- After closing the documentation panel and re-opening, the images are replaced by ![ ] https://foo...jpg
- If I edit the source code to change to ![Image] https://foo....jpg, the images work fine.
https://drive.google.com/file/d/19K5V6w6-jwEIdYUr6LT3XOcHSl933UYF/view?usp=drive_link

## Numbered lists reset on re-opening
- Resets to 1. 1. 1.
https://drive.google.com/file/d/19Tl9qLLSBGozy6OWNK3n5z-DRymxgpHX/view?usp=drive_link

## Documentation panel becomes unstable if there are emojis like 🗝️ or 😀  but not 1️⃣
If you add these to a doc panel, you can't delete them and the window becomes unstable. Can remove via VS Code, but that seems to mess up the placement of all components on the graph editor...

## Doc Panel does not save its position on close
- https://drive.google.com/file/d/19Xx7gD9QBohL_HhDR41VTO5jpDAX7OII/view?usp=drive_link

## Images don't appear until panel is closed and re-opened. Link appears on initial creation.
 - https://drive.google.com/file/d/19ZcIpnKposqrCm5eC4mk7Tyk81RI1QHS/view?usp=drive_link

- Lost the ability to resize the doc panel

- ~~Lost the ability to scroll in the doc panel~~
I have more text below the final words in the screenshot but I can't scroll to see them....

![Image](https://github.com/enso-org/enso/assets/4699705/1241fb2a-3aa2-4afb-b2c0-979869e4142f)

**Comment by vitvakatu** [comment]
Can’t reproduce “Doc Panel does not save its position on close” on the latest develop.
Also, “Numbered lists reset on re-opening” only happens in dev builds; I didn’t find a way to reproduce it with the Electron build. 

“Images don't appear until panel is closed and re-opened. Link appears on initial creation.” – fixed, PR to be opened.

**Comment by vitvakatu** [comment]
Everything except for emojis was fixed, closing this task now, splitting emoji into a separate one.
