### ISSUE TITLE
July 2024 Release Requirements

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10638]
```[tasklist]
### Tasks
- [ ] #10629
- [ ] https://github.com/enso-org/enso/pull/10599
- [ ] https://github.com/enso-org/enso/pull/10597
- [ ] https://github.com/enso-org/enso/pull/10563
- [x] Additional options menu is hard to open.
- [ ] https://github.com/enso-org/enso/issues/10651
- [ ] Update all embedded examples with refreshed versions.
- [x] Drop down arrows are sideways.
- [ ] Drop down placement is too far left.
- [ ] https://github.com/enso-org/enso/issues/10720
- [ ] https://github.com/enso-org/cloud-v2/issues/1400
```
