### ISSUE TITLE
Dropdown problems

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10666]
A few dropdown regressions/defects:

```[tasklist]
### Tasks
- [x] When more options than fit, the next option should be half cropped so the user can see there are more options
- [x] Scroll bar has gone, which means I can't scroll if I don't have a scrollwheel
- [x] Z-Order is wrong, should appear on top of the wheel menu
- [x] I think the left hand edge of the dropdown should align with the left hand edge of the widget that opens it
```

2023.2:

<img width="356" alt="image" src="https://github.com/user-attachments/assets/1207ad2f-4680-43c1-b2ac-91f52d470d1c">

2023.3.1-rc1

<img width="379" alt="image" src="https://github.com/user-attachments/assets/3517cfba-23e7-4131-b151-69d8bb641686">

**Comment by farmaazon** [comment]
May regressed in #10607 - I simplified CSS there, and probably simplified too much without taking notice.

**Comment by kazcw** [comment]
@AdRiley 

> Scroll bar has gone, which means I can't scroll if I don't have a scrollwheel

Overlay scrollbars are now default for Electron/Chrome on OS X. Shall we override it to get something more like the previous behavior?
