### ISSUE TITLE
Remove AliasAnalysis metadata from LocalScope

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#10833]
[LocalScope](https://github.com/enso-org/enso/blob/develop/engine/runtime-compiler/src/main/scala/org/enso/compiler/context/LocalScope.scala) is used in many places. It is referenced by some runtime objects, like `MethodRootNode`. The problem is that `LocalScope` contains references to AliasAnalysis metadata (e.g., AliasGraph in https://github.com/enso-org/enso/blob/develop/engine/runtime-compiler/src/main/scala/org/enso/compiler/context/LocalScope.scala#L34).

Loading AliasAnalysis metadata in `IrToTruffle` is potentially very slow, as the size of the metadata is enormous. Therefore, we should avoid using AliasAnalysis metadata in `IrToTruffle` altogether. This first PR (#10729) removed some usages and introduced new, lightweight, `FramePointer` metadata. In this task, let's remove the references to AliasAnalysis metadata from `LocalScope` altogether.

```[tasklist]
### Tasks
- [ ] ~~Remove references to `AliasAnalysis` metadata from `LocalScope`.~~
- [x] Ensure that the startup time is improved
- [x] Try to apply Jaroslav's suggestion from https://github.com/enso-org/enso/pull/10729#pullrequestreview-2242249968
```

Follow-up of #10129

**Comment by JaroslavTulach** [comment]
A step towards [10% speedup](https://github.com/enso-org/enso/pull/10837#issuecomment-2293766695) seems possible, but:

> ... still see more than 500 of AliasAnalysis metadata being read ... coming from `EnsoRootNode.buildFrameDescriptor()` - we need to find a build to build the descriptor ... without needing `AliasAnalysis`.

**Comment by JaroslavTulach** [comment]
Since #10837 the `LocalScope` can be constructed without loading `AliasAnalysis` data - if needed the data can be loaded later. Since #10906 we can build `FrameDescriptor` without loading these `AliasAnalysis` data at all. With #10996 we fix the caches to be able to load `Hello_World.enso` without needing any `AliasAnalysis`. To track use:

```bash
./enso --log-level trace --run xyz.enso | grep "] Scope"
```

I believe we are done.
