### ISSUE TITLE
August 2024 Release Requirements

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10952]
```[tasklist]
### Tasks
- [ ] https://github.com/enso-org/enso/issues/10947
- [ ] https://github.com/enso-org/enso/issues/10948
- [ ] https://github.com/enso-org/enso/issues/10888
- [ ] https://github.com/enso-org/enso/issues/10592
- [ ] https://github.com/enso-org/enso/issues/10927
- [ ] https://github.com/enso-org/enso/issues/10925
- [ ] https://github.com/enso-org/enso/issues/10949
- [x] Dragging two files on to the graph editor at the same time results in the same variable name
- [ ] Switching Data.read to Delimited and then to Auto Detect leaves extra arguments in the component
- [ ] #6105
- [ ] https://github.com/enso-org/enso/pull/10963
- [ ] https://github.com/enso-org/enso/issues/10976
- [ ] https://github.com/enso-org/enso/issues/10983
```
