### ISSUE TITLE
Epic: Documentation Panel version 1

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11184]
```[tasklist]
### Tasks
- [ ] https://github.com/enso-org/enso/issues/10669
- [ ] https://github.com/enso-org/enso/issues/10059
- [ ] https://github.com/enso-org/enso/issues/9970
- [ ] https://github.com/enso-org/enso/issues/11302
- [ ] https://github.com/enso-org/enso/issues/11240
- [ ] https://github.com/enso-org/enso/issues/10052
```

**Comment by AdRiley** [comment]
Next Epic: https://github.com/enso-org/enso/issues/11977
