### ISSUE TITLE
Epic: Table.new graphical input version 1

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11183]
```[tasklist]
### Tasks
- [ ] https://github.com/enso-org/enso/issues/10759
- [ ] https://github.com/enso-org/enso/issues/10760
- [ ] https://github.com/enso-org/enso/issues/10862
- [ ] https://github.com/enso-org/enso/issues/10863
- [ ] https://github.com/enso-org/enso/issues/10861
- [ ] https://github.com/enso-org/enso/issues/11150
- [ ] https://github.com/enso-org/enso/issues/10864
- [ ] https://github.com/enso-org/enso/issues/10865
- [ ] https://github.com/enso-org/enso/issues/11350
- [ ] https://github.com/enso-org/enso/issues/11434
```
