### ISSUE TITLE
New documentation panel

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#11240]
```[tasklist]
### Tasks
- [x] Yjs: Panel <-> AST sync (Y.Text)
- [x] First parser: Header
- [x] First decorator: Link
- [x] Image decorator (with project image URL support)
- [x] Remaining parsers: Bulleted list, numbered list, blockquote
- [x] CSS for all markdown syntax
- [ ] https://github.com/enso-org/enso/issues/11302
- [x] Yjs: Code editor <-> AST sync
- [x] Fix panel slide-in animation
- [x] --- PR replacing Lexical doc editor ---
- [x] https://github.com/enso-org/enso/issues/11598
- [x] https://github.com/enso-org/enso/issues/11599
```

**Comment by farmaazon** [comment]
I guess it's closed because we don't need the rest of the points?

**Comment by kazcw** [comment]
- Toolbar: #11660
- Numbered lists, content size estimation: Moved to #11772
