### ISSUE TITLE
Move documentation into documented AST node

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#11302]
Eliminate `Ast.Documented`; add a `documentation` field to documentable syntax nodes (method definition, assignment, type definition, constructor definition, case-of branch). Introduce a node type for "free documentation" that couldn't be attached to anything.

This will enable better warnings: Currently, documentation can be attached to any line; however, documentation attached to some expression types is never used. By explicitly attaching documentation only to syntactic constructs that accept it, we can emit a warning when documentation occurs elsewhere.

This will simplify edits in the frontend: Currently adding or removing documentation changes the AST structurally. This particularly complicates switching to Y.Text-based documentation synchronization.
```[tasklist]
### Tasks
- [ ] https://github.com/enso-org/enso/pull/11324
- [ ] https://github.com/enso-org/enso/pull/11346
- [ ] https://github.com/enso-org/enso/issues/11293
- [ ] https://github.com/enso-org/enso/pull/11364
- [ ] https://github.com/enso-org/enso/pull/11374
- [ ] https://github.com/enso-org/enso/pull/11441
```
