### ISSUE TITLE
Parser roadmap

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#11442]
### Changes to previously-accepted syntax
- [x] Disallow a confusing constructor argument default value syntax: #10812
- [x] Fix surprising #8024

### New syntax features
- [x] #6408
- [ ] https://github.com/enso-org/enso/issues/11443
- [ ] #5198
- [ ] Multi-line function applications (ArgumentBlockApp)
- [ ] Exponentiated numeric literals?
- [ ] Tuple literals (supported in parser)
- [ ] String interpolation (supported in parser)
- [ ] Regex literals (unresolved design questions): #7391
- [ ] Dictionary literals (design not finalized, may not require parser changes): #6162

### Frontend APIs
- [ ] See: #10752
- [ ] https://github.com/enso-org/enso/issues/11461

### Error/warning improvements
- [ ] Error recovery for improperly-closed text literal: #5450
- [ ] Error recovery for unclosed vector: #6041
- [ ] Allow indented (plain) comments anywhere: #5443
- [ ] New warning: Operator section in void context (e.g. #11203, #9944)
- [ ] New warning: Non multiple of 4 block spacing (e.g. #8858, #9419)
- [ ] Better error: for unexpected block containing only documentation: #7827
- [ ] Better error: when assignment occurs in expression context: #6211
- [ ] Doc parser: Ensure test case covers #5674

### Documentation
- [x] https://github.com/enso-org/enso/issues/11462
