### ISSUE TITLE
Wasting 100MB by `Standard.Image`: Implement `polyglot/lib`

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#11483]
I've just checked sizes of various libraries inside of Enso distribution:
```bash
enso/built-distribution/enso-engine-*/enso-*/lib/Standard$ du -s * | sort -n
164     Geo
196     Searcher
324     Examples
2616    Visualization
4052    Microsoft
4464    Test
16732   Tableau
25272   AWS
44120   Google_Api
46848   Database
48392   Table
63616   Base
72004   Snowflake
118976  Image
```
e.g. the `Standard.Image` library **occupies 118MB**! Why? Because its `opencv.jar` internally contains various ~10MB huge binaries for each supported platform. 
```bash
Standard$ unzip -l Image/0.0.0-dev/polyglot/java/opencv-4.7.0-0.jar | grep nu.*opencv.*470 
 20426616  2023-03-28 02:41   nu/pattern/opencv/linux/ARMv7/libopencv_java470.so
 28689512  2023-03-28 02:41   nu/pattern/opencv/linux/ARMv8/libopencv_java470.so
 64297552  2023-03-28 02:41   nu/pattern/opencv/linux/x86_64/libopencv_java470.so
 22088596  2023-03-28 02:41   nu/pattern/opencv/osx/ARMv8/libopencv_java470.dylib
 54792848  2023-03-28 02:41   nu/pattern/opencv/osx/x86_64/libopencv_java470.dylib
 69675008  2023-03-28 02:41   nu/pattern/opencv/windows/x86_32/opencv_java470.dll
108318208  2023-03-28 02:41   nu/pattern/opencv/windows/x86_64/opencv_java470.dll
```
If we, remove these _native libraries_ and keep just a single one for the platform we build the distribution for we:
- save bunch of disk space
- save CPU time while starting (wasted by extracting these libs to temporary directory)
- **extract at build time** rather than during runtime
- make it easier for _native image_ to link to such extracted library

# Specification

The solution is to enhance [HostClassLoader](https://github.com/enso-org/enso/blob/3e23e72beded8bdf5a0508f9b84f007f35e2b125/engine/runtime/src/main/java/org/enso/interpreter/runtime/HostClassLoader.java#L17) and override its [findLibrary](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/ClassLoader.html#findLibrary(java.lang.String)) method to perform **native library search**. We will adhere to the [NetBeans specification](https://bits.netbeans.org/23/javadoc/org-openide-modules/org/openide/modules/doc-files/api.html#jni) - we are using it anyway in when [building enso4igv](https://github.com/enso-org/enso/blob/3e23e72beded8bdf5a0508f9b84f007f35e2b125/.github/workflows/enso4igv.yml#L72) as the libraries layout is:

```bash
$ unzip -l enso4igv*nbm | grep /lib/ | cut -d / -f3- | grep -v /$
lib/aarch64/libenso_parser.dylib
lib/enso_parser.dll
lib/libenso_parser.so
lib/x86_64/libenso_parser.dylib
```

You may place the native libraries (DLL or shared-object) beneath a `polyglot/lib` directory of an [Enso Library with Polyglot Java libraries](https://github.com/enso-org/enso/blob/c48e662cd1d75a9bd48a778e87a8614b3f900679/docs/polyglot/java.md). If your native library file names for different architectures or operating systems clash, you may _create subdirectories_ under `polyglot/lib` for each _supported platform_ and nested subdirectories for each supported _operating system_. The directory names must match `System.getProperty("os.arch")` and `System.getProperty("os.name").replaceAll(" .*$", "").toLowerCase(Locale.ENGLISH)` respectively. The `System.loadLibrary` call originating from the library code will try to locate the library file in the following order of directories:
```
    polyglot/lib/
    polyglot/lib/<arch>/
    polyglot/lib/<arch>/<os>/
```
so you may place e.g. _64-bit Linux version_ of a `foo` library in a file `polyglot/lib/amd64/linux/libfoo.so` and _64-bit Windows version_ in `polyglot/lib/amd64/windows/foo.dll` (or also `polyglot/lib/amd64/foo.dll` and of course in `polyglot/lib/foo.dll`). 

### Justification

The [OpenCV SharedLoader](https://github.com/openpnp/opencv/blob/develop/src/main/java/nu/pattern/OpenCV.java#L200) seems to be using `System.loadLibrary` and thus, if our `HostClassLoader` supports `findLibrary`, it should load it from `polyglot/lib` directory rather than [extracting it to temporary location](https://github.com/openpnp/opencv/blob/develop/src/main/java/nu/pattern/OpenCV.java#L222) on each startup.

```[tasklist]
### Tasks
- [ ] Update documentation to talk about [polyglot/lib](https://github.com/enso-org/enso/blob/c48e662cd1d75a9bd48a778e87a8614b3f900679/docs/polyglot/java.md) - copy the **specification** there
- [ ] Override `HostClassLoader.findLibrary` method - [example](https://github.com/apache/netbeans/blob/9897ef7483875b1266f2a146c8e81253f3871f00/platform/o.n.bootstrap/src/org/netbeans/StandardModule.java#L628)
- [ ] Modify build to extract the `nu/pattern/opencv/*/*` libraries at appropriate place in `built-distribution/**/Standard/Image/polyglot/lib`
- [ ] Modify the build to **repackage** `opencv*.jar` and remove the libraries in there
- [ ] Modify the final packaging step to ignore _libraries for other OSes_ - thus minimize garbage
- [ ] Make sure MacOSX signing continues to work
```

**Comment by Akirathan** [comment]
Extracting anything from a `jar` archive during build time can be (easily) managed by setting various `assembly` sbt settings. I believe that I would be able to define build settings/tasks to do any kind of transformation for the jar. Once you know how should the resulting jar look like, which files should be removed from it, just let me know and I will create a patch of `build.sbt` that achieves that.

**Comment by JaroslavTulach** [comment]
> * HostClassLoader will just search native libraries in all the projects

+1, there already is work on class loader/layer per library in #10714
