### ISSUE TITLE
Graph Editor Look&Feel improvements.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#11510]
```[tasklist]
### From James's PR
- [ ] https://github.com/enso-org/enso/issues/11532
- [ ] https://github.com/enso-org/enso/issues/11533
- [ ] https://github.com/enso-org/enso/issues/11534
- [ ] https://github.com/enso-org/enso/issues/11535
- [ ] https://github.com/enso-org/enso/issues/11536
- [ ] https://github.com/enso-org/enso/issues/11664
```

```[tasklist]
### Tasks
- [ ] https://github.com/enso-org/enso/issues/11631
- [ ] https://github.com/enso-org/enso/issues/11632
- [ ] https://github.com/enso-org/enso/issues/11633
- [ ] https://github.com/enso-org/enso/issues/11634
- [x] If a default value Numeric/Text widget should be italic not bold. - only when value is not set (is a placeholder) - we don't make it for values entered by user which happens to be equal to the default - (0)
- [x] Default cursor on the icon. - (0)
- [x] @AdRiley to give a halo design.
- [ ] https://github.com/enso-org/enso/issues/11508
- [ ] https://github.com/enso-org/enso/issues/11507
```

```[tasklist]
### To Prototype
- [ ] https://github.com/enso-org/enso/issues/11702
```

**Comment by somebody1234** [comment]
i think ideally there should be a way to force all visualizations to be opaque - e.g. if they want to take a screenshot of multiple visualizations?
