### ISSUE TITLE
Add back helper buttons for doc panel

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11660]
<img width="211" alt="image" src="https://github.com/user-attachments/assets/963eb9ee-a5ed-453c-8754-0754bf217269">

```[tasklist]
### Tasks
- [ ] https://github.com/enso-org/enso/issues/11968
- [ ] https://github.com/enso-org/enso/issues/11969
- [ ] https://github.com/enso-org/enso/issues/11970
```

**Comment by farmaazon** [comment]
Refinement notes:
* Each formatting may have it's own problems and corner cases in application; they should be considered one by one (starting with simplest approach).
* Worth splitting:
   1. Inline formatting + Links - 5
   2. Single-lines: Headings, lists, quotes - 3
   3. Multi-lines: code blocks - 2

**Comment by AdRiley** [comment]
Tracked by larger epic
