### ISSUE TITLE
Documentation editor small issues

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#11772]
```[tasklist]
### Tasks
- [ ] #11791
- [ ] Fix rendering of nested lists (bullet should be inside indent, alternately-colored)
- [ ] Render numbered lists (currently displayed as unordered)
- [ ] Fix pasting Markdown (e.g. copying from editor to itself--currently redundant markup inserted)
- [ ] Place cursor at text position clicked (currently shifted when markup is shown)
- [ ] Provide estimated sizes of lazily-loaded images to improve scrollbar smoothness
- [ ] Support reference links
```
