### ISSUE TITLE
Remove TODO from doc strings

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#1201]
### Summary

Documentation strings are exposed to the user in the searcher so they should not contain `TODO` notes.
<img width="501" alt="Zrzut ekranu 2020-10-8 o 13 35 23" src="https://user-images.githubusercontent.com/12892578/95453762-bc494080-096b-11eb-91b8-1b56aaeb5329.png">

### Value

Better UX
### Specification

- [ ] Work with @iamrecursion and @kustosz to determine the style for writing enso library documentation.
- [ ] Document this style in `docs/style-guide/enso.md`.
- [ ] Once we have the ability to define shadow modules for bultin definitions.
- [ ] Go through all of the standard library documentation and make sure that they are up to spec.
- [ ] This may involve fixing bad or out-of-date APIs. 

### Acceptance Criteria & Test Cases

No `TODO` notes visible from the searcher
