### ISSUE TITLE
Interpreter/Runtime Cleanup

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#1236]
### Summary
Maintaining delivery timelines has meant that we've incurred some not insignificant technical debt in the interpreter. Furthermore, time and experience has shone the light on a multitude of suboptimal approaches and problems that are contributing to performance deficits across the board.

To that end, this epic deals with cleaning up these pieces of debt and various issues in the interpreter, focusing on maintaining the current functionality while allowing us to progress more efficiently in the future.

### Value
We won't be constantly bumping up against these deficiencies as we add new features to the runtime and interpreter.

### Specification
This epic is considered to be complete when all of the following issues have been completed. _PLEASE NOTE_ that many of these tasks have long estimates as they involve a fair amount of research. We have tried to be pessimistic here, but it is likely that not _all_ of them will take this long.

- [x] Evaluate the performance impact of multi-tier compilation (#1225). This one is very important as we need to be able to provide feedback to the Graal folks if this causes probelms for us ASAP.
- [ ] Implement a system for the representation of builtin objects (#1239). Adding further interop capabilities will often involve adding new builtin objects, and having this will ensure that we can create maintainable code while doing so.
- [ ] Add compiler and runtime support for shadow definitions (#1175). This will allow us to document builtins properly, as is required for the searcher.
- [ ] Use the truffle `@TypeSystem` properly (#1235). This will contribute to both code simplifications and performance improvements across the board, but particularly with foreign language interop.
- [ ] Investigate interop performance (#1237). This will be important for providing efficient FFI for JDBC in the database library and R for the dataframes library.
- [ ] Fix the issues with capturing of lambda scopes (#1195), removing a current massive footgun and performance (memory usage) issue with the language. This is particularly bad as closure is very common in Enso.
- [ ] Add support for unboxed atoms (#1238). This will drastically improve language performance by eliminating a whole level of boxing.
- [ ] Experiment with scope flattening for pattern matches (#1228). While the way we currently do these is fairly elegant, it isn't great for performance. We can do better by optimising the pattern match desugaring plan, similar to how [dotty](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala) does it.
- [ ] Add support for unboxed vectors (#1132). This will ensure that vectors of numbers (common in data analytics) do not incur the performance overhead of boxing.
- [x] Fix argument passing to polyglot constructors (#1163). Removal of a usability wart.
- [ ] Fix the semantics of re-exports for imported modules (#1172), making the language more predictable for users.
- [ ] Allow defining module methods with `here.method` syntax (#1138), making the language more predictable for users.
- [ ] Fix default arguments forcing of a returned lambda (#1124), removing a semantic wart that makes the language confusing.

### Acceptance Criteria & Test Cases

- [ ] The above-listed tasks have been completed.
- [ ] No regressions have resulted in interpreter functionality or performance.
