### ISSUE TITLE
Dataframes Library

### ISSUE THREAD

**Issue by kustosz** [enso-org/enso#1252]
### Summary
As a data-processing oriented, Enso must provide a rich set of tools related to working with tabular data. This epic tracks the implementation of a fundamental library in this class of use cases.

### Value
Enso can serve as a base tool for working with tabular data and related serialization formats.

### Specification
This epic is considered complete when all of the following tasks are completed.

- [x] #1253 CSV Parsing
- [ ] #1255 CSV Writing
- [x] #1256 Column-wise stats and `describe` function
- [x] #1257 Row Filtering
- [x] #1258 NA Handling
- [x] #1259 Sorting tables
- [x] #1260 Joining tables
- [x] #1262 Grouping and aggregating records
- [ ] #1263 Additional serialization formats

### Acceptance Criteria & Test Cases
All of the above functionality is implemented.
