### ISSUE TITLE
Visualizations Performance

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#1358]
### Summary

An umbrella topic for issues that should improve the visualizations performance.

### Value

Better UX.

### Specification

- [x] Improve Json to_text Performance #1357
- [ ] Run Initial Suggestions Indexing in Background #1329
- [x] Return Cached Value during Visualisation Update #1360
- [x] Safepoint without invalidation #1367
- [x] Optimize updates for engine. https://github.com/enso-org/ide/issues/1008
- [ ] Always assign new expression to a value https://github.com/enso-org/ide/issues/1067

### Acceptance Criteria & Test Cases

> On small values, like few numbers, the WHOLE thing (GUI -> backend -> GUI) should be way below 16ms . Everything bigger is a problem and needs to be fixed — @wdanilo

**Comment by 4e6** [comment]
```
vehicles_text = Base.File.read "/tmp/vehicles.json"
Bench.measure (Base.Json.parse vehicles_text) "parse" 1 10
```

```
parse/iteration:0: 602.64ms
parse/iteration:1: 611.52ms
parse/iteration:2: 393.43ms
parse/iteration:3: 330.32ms
parse/iteration:4: 299.82ms
parse/iteration:5: 272.57ms
parse/iteration:6: 251.13ms
parse/iteration:7: 234.96ms
parse/iteration:8: 238.91ms
parse/iteration:9: 206.49ms
```

Benchmark shows how the performance of is improved during the consequent invocations when the JVM is gathering more profiling information. Fixing the https://github.com/enso-org/ide/issues/1008 should also help with that.

**Comment by 4e6** [comment]
## Update

The intermediate update after applying the optimizations.

```py
main =
    f = Enso_Project.root / "vehicles.json"
    j = Json.parse f.read
    operator1 = j.get "vehicles"
    operator2 = operator1.items . at 42
    operator3 = operator2.get "latitude"
    operator4 = operator3.value
    operator4 + 1
```

The result of executing the visualization of the `operator4 + 1`expression in the program above. 

- Run ~20 visualization commands beforehand to warm up the JVM.
- Laptop in the power save mode (disconnected from the AC) to see more clearly the operations that take the longest time.
- CPU: Intel Core i7-8665U @ 8x 4.8GHz

```
[info] [2020-12-29T10:50:58.174Z] [akka.actor.ActorSystemImpl] GOT TextMessage.Strict({"jsonrpc":"2.0","id":91,"method":"executionContext/attachVisualisation","params":{"expressionId":"dbee192f-3918-4c10-9755-12140b355353","visualisationConfig":{"executionContextId":"0f60ae2f-97f3-4da1-a79a-7e4bfdfb6401","expression":"x -> x.to_json.to_text","visualisationModule":"Vehicles_Test.Main"},"visualisationId":"2149f5d6-6912-405d-a550-99f988b76863"}})
[info] [2020-12-29T10:50:58.175Z] [org.enso.languageserver.runtime.ContextRegistry] AttachVisualisation dbee192f-3918-4c10-9755-12140b355353
[info] [2020-12-29T10:50:58.177Z] [enso] Executing command: AttachVisualisationCmd...
[info] [2020-12-29T10:50:58.177Z] [enso] Submitting job: UpsertVisualisationJob...
[info] [2020-12-29T10:50:58.179Z] [enso] Executing job: UpsertVisualisationJob...
[info] [2020-12-29T10:50:58.179Z] [enso] >> Evaluating expression dbee192f-3918-4c10-9755-12140b355353
[info] [2020-12-29T10:50:58.196Z] [enso] << Evaluating expression dbee192f-3918-4c10-9755-12140b355353
[info] [2020-12-29T10:50:58.197Z] [enso] Job UpsertVisualisationJob finished.
[info] [2020-12-29T10:50:58.197Z] [enso] Submitting job: ExecuteJob...
[info] [2020-12-29T10:50:58.198Z] [enso] Executing job: ExecuteJob...
[info] [2020-12-29T10:50:58.198Z] [enso] Run program List(InstrumentFrame(ExplicitCall(MethodPointer(Vehicles_Test.Main,Main,main),None,Vector()),org.enso.interpreter.instrument.RuntimeCache@11815d28)), List(dbee192f-3918-4c10-9755-12140b355353), false
[info] [2020-12-29T10:50:58.202Z] [enso] ON_COMPUTED 1916c4e7-2540-4bda-a214-572ae22931a2 Nothing
[info] [2020-12-29T10:50:58.203Z] [enso] ON_COMPUTED 9cc4dd42-b7a7-4baa-baa7-4974d6ef918c Nothing
[info] [2020-12-29T10:50:58.204Z] [enso] ON_COMPUTED b07bb9ca-20e1-47f4-a7ca-063815bd523c Nothing
[info] [2020-12-29T10:50:58.204Z] [enso] ON_COMPUTED d4b90c85-92f2-43db-b521-412183412731 Nothing
[info] [2020-12-29T10:50:58.205Z] [enso] ON_COMPUTED f1e4a059-7035-45d2-be6f-3a3d80e1ad7e Nothing
[info] [2020-12-29T10:50:58.206Z] [enso] ON_COMPUTED 0dc66972-43cc-4981-9865-18231d1bb6fe Nothing
[info] [2020-12-29T10:50:58.206Z] [enso] ON_COMPUTED bd82d931-9569-4219-b58f-8e175540ebba null
[info] [2020-12-29T10:50:58.206Z] [enso] ON_COMPUTED 815c2f8d-c24e-4aa3-9edc-093cbc4cc28a Number
[info] [2020-12-29T10:50:58.207Z] [enso] ON_COMPUTED ca3cd884-2e17-43c6-914e-bc96a7d97174 Number
[info] [2020-12-29T10:50:58.207Z] [enso] ON_COMPUTED dbee192f-3918-4c10-9755-12140b355353 Number
[info] [2020-12-29T10:50:58.207Z] [enso] Executing expression visualisation dbee192f-3918-4c10-9755-12140b355353
[info] [2020-12-29T10:50:58.21Z] [enso] Sending expression visualisation dbee192f-3918-4c10-9755-12140b355353
[info] [2020-12-29T10:50:58.211Z] [enso] ON_COMPUTED d4750708-9413-42ef-93b4-f5661eca6ad2 Number
[info] [2020-12-29T10:50:58.212Z] [org.enso.languageserver.runtime.ContextEventsListener] VisualisationUpdate 0f60ae2f-97f3-4da1-a79a-7e4bfdfb6401
[info] [2020-12-29T10:50:58.212Z] [org.enso.languageserver.protocol.binary.BinaryConnectionController] Receive visualisation update
[info] [2020-12-29T10:50:58.213Z] [org.enso.languageserver.protocol.binary.BinaryConnectionController] Send visualisation update to outbound channel
```

Timestamp (ms) | Operation time (ms) | Operation | Processing Entity 
| --- | --- | --- | --- |
0 | 0 | IDE sends the message (the message appears on the WebSocket in Chrome dev-tools) | IDE 
4 | 4 | Language server registers the message | LS
7 | 3 | Language server parses the JSON-RPC message, routes the message to the engine, and starts the Engine response listener | LS
9 | 2 | Engine starts the visualization Job | E
26 | 17 | Engine evaluates the visualization expression `x -> x.to_json.to_text` into a callable Enso function | E
28 | 2 | Engine starts the execution Job | E
37 | 9 | Execution reaches the visualized node (the value is computed) | E
40 | 3 | Execute the visualization expression on the computed value | E
43 | 3 | The visualization value routed from the Engine to the WebSocket | LS
51 | 8 | IDE receives the message (the message appears on the WebSocket in Chrome dev-tools) | LS

Participating entities:
- **IDE** the Enso IDE
- **LS** the Language Server
- **E** the Engine

The roundtrip takes ~50ms on average in the power save mode, and ~25ms when attached to the AC.
