### ISSUE TITLE
Text Editor 2.0

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#1754]
### Summary

The text editor is currently not very usable. The following things should be possible after implementing this epic:

* [ ]  Scrolling the text vertically and horizontally (this requires clipping support in EnsoGL). (https://github.com/enso-org/ide/issues/1012)
* [ ]  Selecting text in multiple lines (this will probably be provided by https://github.com/enso-org/enso/issues/1752).  See also https://github.com/enso-org/ide/issues/714
* [ ]   Proper focus management. Clicking outside of the text editor should make it lose focus. (https://github.com/enso-org/ide/issues/1598)
* [ ]  Operations such as "jump by the word" or "jump to the end of the line" should use shortcuts default for the OS, if such shortcuts are defined in a default way for that particular OS. For example, macOS defines most of the shortcuts in a standard way across all text fields in the system and we do not follow these standards. (https://github.com/enso-org/ide/issues/748)
* [ ]  There should be an icon to open/close the text editor.  See also https://github.com/enso-org/ide/issues/1547
* [ ]   There should be syntax highlighting in the text editor. This should be pretty simple to implement - parser includes a lexer, which just outputs a list of text chunks with their names, like "number literal". For each name, we can just assign a color and use the text API to color the text (as we do on nodes already). (https://github.com/enso-org/ide/issues/1599)
* [ ]  All popular text operations, like selecting a word by double-clicking it should work. These operations do already work, so its just important not to break them and test them extensively after implementing the epic.
