### ISSUE TITLE
Universal Conversions for Enso

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#1808]
### Summary
Data science often involves working with many similar types of data. To that end, it is very important that a language designed to make data science easy makes it easy to convert between formats.

Currently, Enso is stuck in a situation where there is no standard for converting between types. To rectify this, we want to introduce the `from`, method, that converts a known value to a value of a given type.

### Value

We will have a unified method to convert between values of different types, as well as good support for it in the IDE.

### Specification

- [x] Implement syntactic support for the new `.from` definitions both at the top level and in complex types (#1809).
- [x] Implement compiler support for both definitions and usages of `.from` (#1810).
- [ ] Implement runtime support for limited multiple-dispatch for `.from` (#1811).
- [ ] Update the standard library to use this new mechanism (#1812).
- [ ] Implement tooling support for `.from` conversions such that the IDE can properly discover and suggest these conversions (#1813).

### Acceptance Criteria & Test Cases

- [ ] All of the above spec points have been completed.
