### ISSUE TITLE
Band-Aid the Parser Performance

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#1852]
### Summary
One of the largest pain points for users of Enso at the moment is the fact that it has to precompile the entire standard library on every project load. This is, in essence, due to the fact that the current parser is _abysmally_ slow, and incredibly demanding. The obvious solution to improve this is to take the parser out of the equation in its entirety, by serialising the parser's output.

This epic exists to track the work of serialising the parser's output and re-using it wherever possible in the compiler pipeline. This will allow bypassing the slow parser entirely.

### Value

Much better UX for our users.

### Specification

- [x] Design and specify the serialisation format and serialisation mechanisms, as well as the storage locations and data for the IR. Specify carefully the _portability guarantees_ for this IR, and be conservative (#1856).
- [x] Make the runtime aware of cache locations (#1870).
- [x] Allow breaking module links in `BindingsMap` (#1871).
- [x] Serialise the IR to disk (#1872).
- [x] Deserialise the IR and integration test (#1873).

### Acceptance Criteria & Test Cases

- [x] The above spec points have been completed.
