### ISSUE TITLE
Maintenance & Stability - GUI

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#2195]
This is an epic which gather all tasks related to maintaining project and improve stability, like CI improvements, postponed refactoring etc. and any other stuff making developers' lives worse.
```[tasklist]
### Tasks
- [ ] https://github.com/enso-org/enso/issues/7546
- [ ] Resign from nightly features
- [x] Reduce allocator pressure (less Boxes, Rcs and RefCells)
- [x] Finish refactoring repository structure (engine + docs merging)
- [ ] Overview utilities, check if really needed and add a document summarizing them all.
- [ ] Build engine from source on Apple Silicon
```
