### ISSUE TITLE
Graph Editor Improvements and Fixes

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#2263]
### In Review
- [ ] Node selection modes (multi selection, add / remove selection)
- [ ] Ability to change text on nodes via API.

### Todo
- [ ] Proper coloring of input ports and mouse while dragging a connection.
- [ ] Ability to change text on nodes via GUI.
- [ ] Expose ability to switch themes (dark / light).
- [ ] Fix old visual elements state. After selected node is removed and new is created, it looks like it was already selected.
- [ ] Mouse port selection not working after scene pan.
- [ ] Mouse cursor has wrong position after scene resize.
- [ ] Mouse gets blurry after zoom out.
- [ ] Drop edge creation on background click.
- [ ] Connect nodes by drag (not only by source and target click).
- [ ] Connect nodes starting from input ports.
- [ ] Allow connections to go up.
- [ ] Edge gets desynchronized when panning scene during edge connection.
- [ ] Add time offset for output port glow (minimize accidental blinks).
- [ ] Disconnect edge source and target by clicking on edges.
- [ ] When zooming out, node text should disappear.
- [ ] Connection end is displayed below node, should be above.
- [ ] Colors are mixed in sRGB space, should be in LAB CIECH (edges below nodes do not look properly)
- [ ] Ability to set edge color based on type.
- [ ] Make area selection work.
- [ ] The current data path should be exposed when node is selected.
- [ ] Different style of the "last selected node".
- [ ] Make graph editor zoom x1 a "stop-gap" when zooming in / out.
