### ISSUE TITLE
Refactor crates and directory structure

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#2269]
The current directory structure should be refactored, so it will better reflect the logical structure of our projects. 

# The new structure

the directories marked with `#` are rust crates (contains Cargo.toml and src, skipped in the list for brevity), `//` is a commentary.
```
- build
  - ... // the build directory from 
  


- app

  - engine
    - ... // the old contents of the engine except parser
    
  # gui
    # controller
      # engine-protocol
      # engine-models
      # double-representation
    # view
      # graph-editor
      # debug-scenes
        # ...
    - language
      # ast
      # parser
      # span-tree
    # analytics
  
  - ide-desktop
    - ... // all the current electron building stuff
      
      
    
- lib

  - rust
    # ensogl
      # examples
        # ... // every debug scene is a crate  
      # core  // should be decomposed to more crates in the future
      # components
        # slider
        # list_view
        # ...
        # text 
	      # msdf-gen
    	  # embedded-fonts
        # drop-manager
      - app  // this will contain a crate with parts of core related to application level management
        - themes
          # hardcoded // the previous "theme" crate
    # callback
    # config // lack of docs, should be generalized to read any configuration file
    # frp
    # shortcuts
    # system
    # shapely
    # logger
    # parser
      # ast
      # automata  
      # flexer  
      # flexer-testing      
      # lexer 
      # lazy-reader     
      # parser-jni  
    # prelude // the old ide/utils and macro-utils crates will be mGlerged in. The "heavy" utilities (like serde or futures extensions) will be turned on by the features flag.
    # data-structures // the old data crate. the "text" module is a duplicate with structures in ensogl-text crate, so it will be refactored.
    # generics		   
    # optics     
    - not-used # things to be removed if not used for long time.
      # eval-tt
      # web-test
      
  - scala
    - ... // the current contents of lib/scala 
```

# Tasks
* [ ] #3147
* [ ] #3148
* [ ] Move all "lib" crates to their place (ensogl and crates in current gui/src/rust/lib) + rearrange crates inside the ensogl directory.
* [ ] Refactor `config` crate
* [ ] Refactor the text module in `data-structures` crate.
* [ ] Split IDE to gui and ide-desktop + fix build scripts.
* [ ] Finish refactoring ide-gui controller: move code to engine-models and ide-controller, refactor integration between controller and view

**Comment by farmaazon** [comment]
I've updated the description with the new proposal.

It is a little big bigger than just "refactoring crates": we've decided to try also fix the overall repository layout after merge.

**Comment by farmaazon** [comment]
Additionally, I propose to not make "impl" directory, but just put the crate a level up, for example instead of 
```
- ast
  # impl
  # macros
```
we'll have
```
# ast
  # macros
```

**Comment by MichaelMauderer** [comment]
Should the proposal above also include some other folder of the engine repo, like `st-bits`? @4e6 might be best to advise on how they fit in.

**Comment by farmaazon** [comment]
I updated proposition with the last iteration of @wdanilo 's calls. If nobody raises any issue with it, then I assume it's agreed (excluding the parts covered by three dots so far).

> Should the proposal above also include some other folder of the engine repo, like `st-bits`? @4e6 might be best to advise on how they fit in.

Yes, @4e6 if you see how to split stuff between `app/engine` and `lib/scala` (or potentially other directories), update the proposition. I know the engine's part very little, and that's why I rather leave three dots in some places. In fact, I'd like to restrain from doing any changes in engine except just placing the "old" engine repository in new `app/engine`.

**Comment by 4e6** [comment]
Putting the "old" engine repo in a new `app/engine` directory should work just fine. 

Regarding the `std-bits` directory. We could refactor its contents into i.e. `lib/scala/std`, but it might be a bigger task. I'd rather leave the engine structure as is, at least for now.

**Comment by farmaazon** [comment]
Ok, so I assume the "proposition" is accepted by everyone concerned, and I can start implementing it.

Because I'll touch almost everything in the repository, this epic should be somehow coordinated with the work of others. I added the tasks' list to the description, and I want to take them from top to bottom, omitting those blocked for some reason.

@MichaelMauderer and @4e6: please let me know if you want to alter the list, for example want to have some changes earlier or postponed, to avoid heavy conflicts with other's work.

@mwu-tow proposed postponing the first task (moving engine) until he finishes his work on CI, otherwise the CI would need to be fixed twice, so I'll mark the first task as blocked.
