### ISSUE TITLE
Edge drawing refactoring and improvements

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/enso#2352]
- [ ] Refactoring of the whole edge drawing codebase and using new edge shapes abstractions.
- [ ] Edge lines create loop when dragging from input port.
- [ ] Edge do not work correctly when zoomed / panned (ex https://github.com/enso-org/ide/issues/635).
    ![image](https://user-images.githubusercontent.com/1428930/86479147-e4f9e280-bd4b-11ea-8382-8110df0e320d.gif)
- [ ] Disable snapping to input ports when dragging input connection (ex https://github.com/enso-org/ide/issues/659)
- [ ] Short edge shapes do not render correctly (ex https://github.com/enso-org/ide/issues/658)
    ![image](https://user-images.githubusercontent.com/1428930/87245477-e743f700-c445-11ea-8cef-92a8ae1ef02c.gif)
- [ ] Edges / interaction areas should get thicker when zooming out.
- [ ] Edges created from Input Ports do not overlay nodes (ex https://github.com/enso-org/ide/issues/672).
- [ ] Click-and-drag on edge should be allowed, just as on input ports.
- [ ] Re-think the splitting of upward edges. First of all, Y-axis aligned nodes have no splitting (see gif below). Secondly, depending on which node is slightly above, the splitting gets inverted, which is unexpected.
    ![2020-07-20 20 35 41](https://user-images.githubusercontent.com/1623053/87973460-d68c2480-cac8-11ea-9194-6f76c91a2e87.gif)
- [ ] Allow disconnecting connected input ports through clicking on the port (ex enso-org/ide#683 )
- [ ] All other visual bugs with edges that will appear during testing - this task is about FINISHING edge implementation and make it cover ALL edge cases.
