### ISSUE TITLE
Searcher shows methods tagged as `private`

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#2510]
### General Summary

In Standard Library we have external, user-facing functions and methods as well as some internal helpers tagged as `private`. Those private things should be hidden from regular user and available just for very advanced one. This mean they should not be displayed in the searcher.
### Steps to Reproduce

i.e. open searcher and start typing `map`
### Expected Result

`map_helper` should not be visible
### Actual Result

<img width="533" alt="Zrzut ekranu 2020-10-6 o 11 13 36" src="https://user-images.githubusercontent.com/12892578/95182548-13f97780-07c5-11eb-841f-f7f157ea8664.png">

### Tasks 

* [ ] Update scala documentation parser
* [ ] Read the tags in IDE and filter suggestions
* [ ] Add shortcut for showing private/text_only entities.

### Enso Version

core     : 2.0.0-alpha.0
build    : aeffc7a
electron : 8.1.1
chrome   : 80.0.3987.141
