### ISSUE TITLE
Visualizing inputs in entered function. 

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/enso#2587]
### General Summary
If we enter a function we get no indication of which variables are coming in as input variables. Instead, we just have variable names.

 In the following example, the function takes `text3` and input, but if we enter the node, this is not readily observable.

![Peek 2020-11-20 15-52](https://user-images.githubusercontent.com/1428930/99813817-74136580-2b48-11eb-97f0-5760d325c398.gif)

### Motivation
Designing a function with inputs would be much more intuitive, if we had some input nodes that tell us what inputs are available to the current function, and even more if we could edit those inputs. Right now we always would have to switch levels to edit the function signature and have no indication inside the function what inputs are available.

### Specification
- Inputs should be visible as nodes on the scene with a special shape. Users should be able to create multiple nodes for the same input.
- On top of the graph editor, there should be a horizontal list of inputs. Users can drag the names (left, right) to sort, they should also be able to add, or remove the inputs.
- The inputs should be visible in the searcher.

### Tasks
* [ ] Show input nodes on the scene
   * [ ] (GUI) A "input type" for nodes in Graph Editor
   * [ ] List of inputs on top of Graph Editor
   * [ ] (Controllers) Read inputs of the current function and display them
   * [ ] (?) Creating many nodes for a single input
* [ ] (Controllers) Implement connections with inputs.
* [ ] Adding new inputs (in list at any position + in searcher)
* [ ] Removing inputs
* [ ] Adding input nodes (dragging from the input list).
* [ ] Removing input nodes
* [ ] Reordering inputs
    * [ ] (Engine) Refactoring: reordering arguments
    * [ ] Reordering input ports (use engine refactoring method in a blocking manner).
