### ISSUE TITLE
Searcher inserts unnecessary imports & doesn't rename conflicting imports

### ISSUE THREAD

**Issue by kustosz** [enso-org/enso#2692]
### General Summary
The IDE often imports modules that are not at all needed – for example it often happens that a module defining a given type would get imported when calling a method on it, even though it is completely unnecessary. E.g.

```
main =
    foo = Enso_Project.data / "foo.txt"
    foo.read
```
Calling `read` on `foo` from the searcher will result in `import Base.System.File`, even though this import is completely unnecessary! (I already have a file, it is defined in the `Base.System.File` module, so is the `read` method, therefore no import necessary).

This functionality is at its worst with conflicting module names. Happens a lot when working with Http:
1. There are `Base.Network.Http.Response.Body` and `Base.Network.Http.Request.Body` modules.
2. I imported the `Request` one to construct a request.
3. I then perform the request and get a response.
4. Calling any method on the response will unnecessarily import the `Response` module _and_ not rename it!
5. This results in a name clash (the name `Body` cannot be disambiguated) and the request-body-creating flow is now broken! The only way I can fix it to close the IDE, edit the file in vim (removing the `Response` import, which also loses all of my node-positions metadata) and start the IDE again.

### Steps to Reproduce
Call methods on different types using the searcher and notice the imports list grow unwieldy

### Expected Result
Clean import list without name conflicts

### Actual Result
Unnecessary imports & flow-breaking name conflicts

### Tasks
* [x] Does not put imports when picking a method suggestion.
* [ ] Support new import syntax in a double representation.
* [ ] Make use of searcher/import when adding/modifying node with picked suggestions.
* [ ] enso-org/ide#1696

### Enso Version
https://github.com/enso-org/ide/actions/runs/504397217

**Comment by radeusgd** [comment]
Related issue: https://www.pivotaltracker.com/n/projects/2539304/stories/181309938

<blockquote><div><strong><a href="https://www.pivotaltracker.com/n/projects/2539304/stories/181309938">Auto-import does not work for Atom constructors - Pivotal Tracker</a></strong></div></blockquote>
