### ISSUE TITLE
Documentation Viewer 2.0

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/enso#3067]
### Summary
Update the documentation viewer to the design of the Searcher 2.0.

## Design 

![image](https://user-images.githubusercontent.com/1428930/128432547-26b69683-4564-416b-a727-28548bb52cc4.png)

### Value
Better UX and discoverability.

### Specification
- [ ] enso-org/ide#1728
- [ ] enso-org/ide#1729
- [ ] enso-org/ide#1730
- [x] enso-org/ide#1731
- [x] enso-org/ide#1732
- [x] https://github.com/enso-org/enso/issues/1901
- [ ] Update engine documentation with alias tags
- [ ] Add action to show source code to examples.
