### ISSUE TITLE
Data analysts should have suggestions with conversion functions (from method)

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4133]
This task is automatically imported from the old Task Issue Board and it was originally created by Dmitry Bushev.
Original issue is [here](https://www.pivotaltracker.com/story/show/180312850).
<hr />

### Why

**As data analyst**
**I want** to see suggestions for data types that I can convert my data to
**So that** I can do my job quicker

### Acceptance Criteria

```gherkin
Scenario: 
Given Enso suggestions system
When asked for a `.from` suggestions with a given data type
Then replies with a complete list of conversions
```

## Tasks:
- [X] Create an index that maps from a source type to a concrete .from definition.
- [X] Ensure that .from definitions get added to and removed from this as needed.
- [X] Provide the suggestions updating mechanism.

## Comments:
**Dmitry Bushev** reports a new **STANDUP** for today (2021-11-22):

**Today:** Continue with the Universal Conversions task (suggestions system). Implemented a table and database object to work with the conversions. It should be finished by 2021-12-01.

**Next Day:** Next day I will be working on the [##180312850 task](https://www.pivotaltracker.com/story/show/180312850). Continue working on the suggestions system, write tests for the conversions table, update JSON API to support conversions. (Enso Bot - Nov 22, 2021)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for today (2021-11-23):

**Today:** Continue with the Universal Conversions task (suggestions system). Cleaned up API a bit and started updating the language server. When updating the logic that finds the diff between two modules, stumbled upon an issue with the conversions. Found a workaround, but it will take additional (unexpected) time to implement. It should be finished by 2021-12-01.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180312850). Continue working on the suggestions system (Enso Bot - Nov 23, 2021)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for today (2021-11-24):

**Today:** I was trying to upgrade GraalVM today, because there is an issue with Windows CI and the update could help (they reduced the memory footprint of native programs in the new version). Unable to do that because the new GraalVM version slows down our benchmarks. Created an issue about that. It should be finished by 2021-11-24.

**Next Day:** Next day I will be working on the [##180312850 task](https://www.pivotaltracker.com/story/show/180312850). Continue working on the suggestions system (Enso Bot - Nov 24, 2021)
<hr />
**Dmitry Bushev** reports a new **🔴 DELAY** for today (2021-11-25):

**Summary:** There is **7 days** delay in implementation of the [Data analysts should have suggestions with conversion functions (from method) (#180312850) task](https://www.pivotaltracker.com/story/show/180312850).
It **will cause 0 days delay** for the delivery of this sprint.

**Delay Cause:** It's not a delay. I screwed up the estimate (and set it `today`) when posting my last update. I'm still planning to finish this task next week. (Enso Bot - Nov 25, 2021)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for today (2021-11-30):

**Today:** Working on the tooling support of the Universal Conversions. Was finishing the suggestions updating mechanism It should be finished by 2021-12-01.

**Next Day:** Next day I will be working on the [##180312850 task](https://www.pivotaltracker.com/story/show/180312850). Finish the tooling support for the Universal Conversions. Write tests covering the language server part (Enso Bot - Nov 30, 2021)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for today (2021-12-01):

**Today:** Working on the tooling support of the Universal Conversions. Work on the tests took more than expected but still was able to finish in time. Created a PR in the end. It should be finished by 2021-12-01.

**Next Day:** Next day I will be working on the [##180495871 task](https://www.pivotaltracker.com/story/show/180495871). I will help Edward and start implementing the first task of his story: "Ensure that conversion methods are generated to a particular spot in the scope.", which I extracted into a separate issue. (Enso Bot - Dec 1, 2021)
<hr />
