### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4140]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/180508283).
<hr />

The first task for someone new. Meant to serve as a placeholder before actual tasks are assigned.

## Tasks:
- [X] Read the handbook
- [X] Get the build environment set up
- [X] Report any feedback about handbook &  onboarding
- [X] Find your next task on Pivotal

## Comments:
**Mateusz Czapliński** reports a new **STANDUP** for today (2021-12-02):

**Today:** Successfully built and started Enso IDE with `./run watch`. Continuing reading the day-1 guide & rest of handbook. Had meetings with @MichaelMauderer & with @farmazon, about first steps and initial introduction to each other. It should be finished by 2021-12-03.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180508283). Continue reading the handbook, and report feedback about any issues I had with it, to complete #180508283. Then, start reading, understanding, and working on #180504109. (Enso Bot - Dec 2, 2021)
<hr />
**Mateusz Czapliński** reports a new **STANDUP** for today (2021-12-03):

**Today:** Finished reading the handbook. Opened PRs & issues to handbook & enso repositories with proposed improvements or observed questions/doubts. It should be finished by 2021-12-03.

**Next Day:** Next day I will be working on the [##180504109 task](https://www.pivotaltracker.com/story/show/180504109). Start reading, understanding, and working on #180504109. (Enso Bot - Dec 3, 2021)
<hr />
	@akavel The onboarding tasks are finished by now, I think. Do you mind closing this task if that is true? (Michael Mauderer - Dec 10, 2021)
<hr />
	@michael_mauderer makes sense, will do right now, thanks! (Mateusz Czapliński - Dec 10, 2021)
<hr />
