### ISSUE TITLE
User and Developers should not see warnings about views being created but not registered.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4142]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/180504109).
<hr />

### Why

**As** Developer
**I want ** To be able to see whether the code I have implemented generates any new warnings
**So that ** I can make sure my code is working as intended

### Acceptance Criteria

```gherkin
Scenario:
Given  I open the developer console
When running the Enso IDE and opening a default project
Then I do not see any warnings about views being created but not registered 
```

**Notes:**

The warnings look like this:

```
[W] The view 'ProjectView' was created but never registered, performing automatic registration. You should always register available 
views as soon as possible to enable their default shortcuts and spread the information about their API.```

Related:
- https://github.com/enso-org/enso/issues/3093
- https://enso.youtrack.cloud/issue/IDE-3093

## Tasks:
- [X] Register all `View`s during initialization
- [X] Make sure `register` fn's docs mention that it registers keyboard shortcuts for shortcuts window
- [X] Change `FloatLabel` to not implement the `View` trait
- [X] Change `CloseButton` (`View<Shape>`) to not implement the `View` trait




## Comments:
I found some Views that don't currently seem to report a warning when I'm opening some random project, but they still have a `fn label() -> &'static str`; I'm currently assuming they should most probably also be registered, and will attempt to do that as part of the task. (Examples include: `Scrollbar`, `FloatLabel`, `TopButtons`, & more.) (Mateusz Czapliński - Dec 6, 2021)
<hr />
**Mateusz Czapliński** reports a new **STANDUP** for today (2021-12-06):

**Today:** Merged 2 PRs pending for #180508283 and opened one more. Started working on #180504109. Discussed & set an estimate. Reproduced the scenario from the story and added registration calls for all Views producing warnings for a sample project. Started tracking other Views that are not currently producing warnings for a sample project, but might still need to be registered. Added a registration call for a View visible only in Cloud IDE. It should be finished by 2021-12-08.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180504109). Discuss further with the Team which of the not-currently-producing-warnings Views need vs. need not be registered.

**Additional Information:** "CloseButton" View is currently implemented in a complex way which may need extra caution and/or work when registering. "FloatLabel" is currently in a private module, so it may require extra work if it needs to be registered. (Enso Bot - Dec 6, 2021)
<hr />
