### ISSUE TITLE
Failed to decode a notification: unknown variant `executionContext/visualisationEvaluationFailed`

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4151]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/180622673).
<hr />

### Steps to reproduce

1. Create a new project with name = "Unnamed"
2. Open the project
3. Open the Developer Console
4. Edit the Enso code to achieve the below snippet (or modify file on disk and reopen the project):

```
from Base import all

main =
    a = 1
    b = "hello"
    c = " world"
    IO.println b + c
```

### Expected

No errors in Developer Console.

### Actual

The following error is visible in Developer Console:

> index.js:10026  controller::ide::Desktop.Project Controller
> [E] Error emitted by the JSON-RPC data connection: Failed to decode a notification: unknown variant `executionContext/visualisationEvaluationFailed`, expected one of `file/event`, `executionContext/expressionValuesComputed`, `executionContext/expressionUpdates`, `executionContext/executionFailed`, `executionContext/executionComplete`, `executionContext/executionStatus`, `search/suggestionsDatabaseUpdates`, `file/rootAdded`, `file/rootRemoved`..

### Additional notes

- imported from: https://enso.youtrack.cloud/issue/IDE-2682

## Tasks:
- [X] investigate
- [X] fix bad Enso syntax in IDE's internal preprocessor
- [X] write a test for ensuring that IDE's internal preprocessor keeps being valid Enso code
- [X] properly deserialize and handle `visualisationEvaluationFailed` messages in IDE
- [X] ensure that an issue with `PanicSentinel` passed to the preprocessor is addressed

## Comments:
**Mateusz Czapliński** reports a new **STANDUP** for today (2021-12-14):

**Today:** During most of the day, I continued investigating the previous assigned ticket (#180623036). Found an earlier initial discussion on #engine Discord, and continued the discussion, ending with a proposal of a simpler implementation approach, endorsed by @dmitry on Discord (see a comment in the ticket). By the end of the day, I unassigned myself from the ticket, in order to leave actual implementation to a member of the Engine team (as suggested by @wdanilo). Afterwards, I started investigating #180622673 It should be finished by 2021-12-14.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180622673). Continue investigating the issue. (Enso Bot - Dec 14, 2021)
<hr />
There seem to be two rather orthogonal parts to this issue:

 1. Whether IDE should correctly parse the `executionContext/visualisationEvaluationFailed` message, and what it should do with it; for example, maybe dump the error in some readable way to Dev Console, so that users have a way to debug errors in custom visualizations they wrote?
 2. Fixing the actual error in the visualisation code: tracking the file & location of the actual error through network tab leads to [an inline snippet for displaying error visualisations][snip], specifically to the `"{ message: \"\"}"` fragment, and it seems to be complained at with: `Syntax error: Type operators are not currently supported at runtime.`

[snip]: https://github.com/enso-org/enso/blob/567ddd701c0e631ccf1a2ad2bb81a65c3deb5dce/app/gui/view/graph-editor/src/builtin/visualization/native/error.rs#L34  (Mateusz Czapliński - Dec 15, 2021)
<hr />
**Mateusz Czapliński** reports a new **🔴 DELAY** for today (2021-12-15):

**Summary:** There is **5 days** delay in implementation of the [Failed to decode a notification: unknown variant `executionContext/visualisationEvaluationFailed` (#180622673) task](https://www.pivotaltracker.com/story/show/180622673).
It **will cause 0 days delay** for the delivery of this sprint.

**Delay Cause:** mistakenly submitted incorrect End Date for the task initially. (Enso Bot - Dec 15, 2021)
<hr />
**Mateusz Czapliński** reports a new **🔴 DELAY** for today (2021-12-15):

**Summary:** There is **6 days** delay in implementation of the [Failed to decode a notification: unknown variant `executionContext/visualisationEvaluationFailed` (#180622673) task](https://www.pivotaltracker.com/story/show/180622673).
It **will cause 0 days delay** for the delivery of this sprint.

**Delay Cause:** mistakenly submitted incorrect End Date for the task initially. (Enso Bot - Dec 15, 2021)
<hr />
**Mateusz Czapliński** reports a new **STANDUP** for today (2021-12-15):

**Today:** Continued investigating. Found two related issues, and documented them in a comment in the issue. Found a solution to syntax error, by changing string formatting. Reported an issue to Engine of not supporting " escape codes in "-delimited strings. Had a call with Adam to understand basics of the FRP framework, and to talk about nuances of errors in Enso graphs. It should be finished by 2021-12-20.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180622673). Verify if the string formatting fix fully resolves the issue as reported. Find a way to include the internally used Enso snippet in CI/CD, so that its breakage could be detected earlier. Discuss if visualisation errors should be reported in a proper way in Dev Console (instead of a deserialization error), or handled in some different way. (Enso Bot - Dec 15, 2021)
<hr />
**Mateusz Czapliński** reports a new **🔴 DELAY** for today (2021-12-16):

**Summary:** There is **2 days** delay in implementation of the [Failed to decode a notification: unknown variant `executionContext/visualisationEvaluationFailed` (#180622673) task](https://www.pivotaltracker.com/story/show/180622673).
It **will cause 0 days delay** for the delivery of this sprint.

**Delay Cause:** After a quick local fix to 2 bugs described before, a 3rd bug was found underneath. It took over half day to debug, and introducing a unit test to protect against a regression in the future will be a considerable effort, as the snippet of Enso code is used in IDE internally, while it needs to be executed with Enso runtime for tests (thus presumably in Scala CI/CD).

**Possible solutions:** Could not introduce the test - but this risks future regressions that will be similarly hidden and hard to notice as the current one, as well as similarly hard to debug after being noticed. (Enso Bot - Dec 16, 2021)
<hr />
NOTE: Apart from 2 issues described above, a 3rd issue was found underneath: the `x` passed to the preprocessor is a `PanicSentinel` (a "poison value"), and calling `x.catch` on it doesn't "disarm" the panic, but instead triggers a "rethrow". This results in the preprocessor panicking, with misleading error text from user's code. This seems also to be a regression, because from some observations in code, calling `catch` on a Panic value was seemingly correct in some older version of Enso.

Given that 2 bugs due to changes in Enso already accrued in this snippet and were not detected quickly, I believe it is a solid argument for an attempt to include evaluation of this snippet (in the same version as used by the IDE code) in Engine CI. (Mateusz Czapliński - Dec 16, 2021)
<hr />
**Mateusz Czapliński** reports a new **STANDUP** for today (2021-12-16):

**Today:** Continued investigating. Found third related issue, and documented it in a comment in the ticket. Found a solution to Panic.recover in case of a PanicSentinel argument passed to the snippet. Started working on a test case for the snippet for Engine CI. It should be finished by 2021-12-22.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180622673). Continue trying to find a way to include in Engine CI the Enso snippet used internally by the IDE, so that its breakage could be detected earlier. Discuss if visualisation errors should be reported in a proper way in Dev Console (instead of a deserialization error), or handled in some different way. (Enso Bot - Dec 16, 2021)
<hr />
As to panic propagation through visualisations (see `PanicSentinel` keyword before in this ticket), per [discussion on Discord][disco], I understand it is currently assumed to be OK to propagate a panic through a visualisation and possibly surface it as an error in Developer Console.

[disco]: https://discord.com/channels/401396655599124480/921406091189977099/921414191976415303 (Mateusz Czapliński - Dec 17, 2021)
<hr />
**Mateusz Czapliński** reports a new **STANDUP** for today (2021-12-17):

**Today:** Implemented visualisationEvaluationFailed message deserialization & printing in IDE. Discussed further with Dmitry & Adam how to handle processing of a panic by an error visualisation. Started working on a test in Engine that would verify that the script used in IDE is parsing & running successfully. It should be finished by 2021-12-22.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180622673). Continue working on the test. Consult challenges with Dmitry. Make the test use exactly the same snippet file. If successful, open a regular PR. (Enso Bot - Dec 17, 2021)
<hr />
**Mateusz Czapliński** reports a new **STANDUP** for today (2021-12-20):

**Today:** Finished writing & debugging the test. Opened a PR and fixed review comments. It should be finished by 2021-12-20.

**Next Day:** Next day I will be working on the [##180311771 task](https://www.pivotaltracker.com/story/show/180311771). Start looking into how to implement the story.

**Additional Information:** The ticket is hard for me to understand at the moment, but I expect to have a meeting with Michael to explain to me a bit more about it soon today. (Enso Bot - Dec 20, 2021)
<hr />
