### ISSUE TITLE
Enso developers should have tooling to do time based profiling of their code

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4157]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/180311768).
<hr />

## Why
To improve the performance of Enso, we need to be able to do profiling of the application.

**As developer**
**I want** to be able to add performance measures to the codebase 
**So that** I can measure how long actions, like opening a project,  in the product take

## Acceptance Criteria

```gherkin
Scenario: 
Given I want to know how long thigns take in our product
When I plan performance enhancements of the product
Then I want to know which parts of the application are slow.
```

## Resources
https://github.com/enso-org/design/blob/wip/wd/profiling/designs/profiling/implementation.md

https://github.com/enso-org/design/blob/wip/wd/profiling/designs/profiling/implementation.md#interactive-results

## Tasks:
- [X] Create Rust API (incl. conditional compilation)
- [X] Create JS API
- [X] Profiling information is available in the Chrome dev tools

## Comments:
**Michael Mauderer** reports a new **STANDUP** for today (11/16/2021):

**Today:** Started working on the new performance logger. Playing around with the API and JS integration. It should be finished by 2021-11-23.

**Next Day:** Next day I will be working on the [#180311774 task](https://www.pivotaltracker.com/story/show/180311774). Trying the data export and making sure the information we retrieve can be used the way we want. Checking that we can integrate information in the dev tool like we want to.

**Additional Information:** I'm living about 1 km from the peak of an extinct volcano. (Enso Bot - Nov 16, 2021)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (11/17/2021):

**Today:** Working on the performance logger. Getting the JS interop up and running and wrapping it in a nice API. Fighting a bit with slow build times. It should be finished by 2021-11-23.

**Next Day:** Next day I will be working on the [##180311768 task](https://www.pivotaltracker.com/story/show/180311768). Hopefully be able to get the JS performance data in a nice format, and looking at how to mirror the API in JS (or maybe make the rust crate available for use on the JS side, but will do a bit of reading on that first).

**Additional Information:** I think maybe my hard drive is dying, running IO intensive tasks is slow and leads to high system latency. Need to get a new one, probably. Working on Windows in the meantime. That runs of a different SSD and seems to be a bit faster. (Enso Bot - Nov 17, 2021)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (11/18/2021):

**Today:** Working on the performance logger. Playing around with API and data retrieval and coming up with an API that will allow us to measure intervals that start in JS but end in rust. It should be finished by 2021-11-23.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180311768). Cleaning up the API, testing it some more, and then tomorrow or Monday open a PR.

**Additional Information:** NVMe drive helped a lot. Cuts compile time in half. Still not superfast, but much better. (Enso Bot - Nov 18, 2021)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (2021-11-19):

**Today:** Working on the performance logger. Finalizing API. Need to think a bit more about whether the Rust code can be used from JS easily, or whether it is easier to just port part of the logging also to TS. It should be finished by 2021-11-23.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180311768). Finish clean up of export and JS part of the API. (Enso Bot - Nov 19, 2021)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2021-11-22):

**Today:** Working on the performance logger. Still need to finalize the report creation and JS API, and clean up the code. This was delayed a bit due to TL tasks. I expect PR to land by the end of today or some time tomorrow. It should be finished by 2021-11-25.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180311768). Finish clean up of export and JS part of the API. (Enso Bot - Nov 23, 2021)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for yesterday (2021-11-22):

**Summary:** There is **2 days** delay in implementation of the [Enso developers should have tooling to do time based profiling of their code (#180311768) task](https://www.pivotaltracker.com/story/show/180311768).
It **will cause 0 days delay** for the delivery of this sprint.

**Delay Cause:** The estimated end date for the task shifted a bit as the initial estimate did not properly account for TL tasks also taking uptime.  So, not an issue with the task, just a planning mistake.

**Possible solutions:** Better plan that TL is not spending 100% time on dev when estimating end date. (Enso Bot - Nov 23, 2021)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2021-11-23):

**Today:** Mostly working on TL tasks and handbook discussions. Think the PR might still land tomorrow, if tomorrow has less TL and planning going on. It should be finished by 2021-11-25.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180311768). Finish clean up of export and JS part of the API. (Enso Bot - Nov 24, 2021)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for yesterday (2021-11-24):

**Summary:** There is **1 day** delay in implementation of the [Enso developers should have tooling to do time based profiling of their code (#180311768) task](https://www.pivotaltracker.com/story/show/180311768).
It **will cause 0 days delay** for the delivery of this sprint.

**Delay Cause:** The estimated end date for the task shifted a bit due to TL tasks taking up more time.

**Possible solutions:** Better plan that TL is not spending 100% time on dev when estimating end date. (Enso Bot - Nov 25, 2021)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2021-11-24):

**Today:** Again mostly working on TL tasks (PR reviews, discussions) and handbook PRs. This will delay the PR for #180311768 by another day. It should be finished by 2021-11-26.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180311768). Finally, finish clean up of export and JS part of the API. (Enso Bot - Nov 25, 2021)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (2021-11-25):

**Today:** Finally some progress on my dev task. Made good progress with finalizing the API and report generation. Still need to do some tweaking of the JS integration and output formatting. That should be doable tomorrow. It should be finished by 2021-11-26.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180311768). Finish JS API and performance report formatting.

**Additional Information:** If it should spill over again, I will finish it over the weekend. (Enso Bot - Nov 25, 2021)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for today (2021-11-26):

**Summary:** There is **2 day** delay in implementation of the [Enso developers should have tooling to do time based profiling of their code (#180311768) task](https://www.pivotaltracker.com/story/show/180311768).
It **will cause 2 days delay** for the delivery of this sprint.

**Delay Cause:** I see more TL related tasks/meeting for today. So, that might will push the PR  probably to end  of today / the weekend. Since Monday is also a TL heavy day, final revisions on the PR  will unlikely be finished before Tuesday.

**Possible solutions:** Better account for available dev time when  estimating end date. (Enso Bot - Nov 26, 2021)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (2021-11-29):

**Today:** Working on the JS API mostly. I've spent a bit of time to get the new library integrated into our build system but run into troubles. Need to resolve this  with someone who knows this better than I do (probably Wojciech). Since this took me quite a bit of time, one thing is still missing before I can open a PR: the console grouping of the tasks, but that should be straightforward as we have a similar system already in place for the normal logging. It should be finished by Invalid DateTime.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180311768). Resolving build issue with Wojciech and then open PR. (Enso Bot - Nov 29, 2021)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2021-11-29):

**Today:** Finished the PR on this task. It should be finished by Invalid DateTime.

**Next Day:** Next day I will be working on the [##180311774 task](https://www.pivotaltracker.com/story/show/180311774). Implement reviews. Get started on the next task in the profiling epic.

**Additional Information:** Tomorrow is St Andrews Day, a public holiday in Scotland. (Enso Bot - Nov 30, 2021)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for yesterday (2021-12-01):

**Summary:** There is **2 day** delay in implementation of the [Enso developers should have tooling to do time based profiling of their code (#180311768) task](https://www.pivotaltracker.com/story/show/180311768).
It **will cause 0 days delay** for the delivery of this sprint.

**Delay Cause:** Public holiday + large review feedback. (Enso Bot - Dec 2, 2021)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for yesterday (2021-12-01):

**Summary:** There is **3 day** delay in implementation of the [Enso developers should have tooling to do time based profiling of their code (#180311768) task](https://www.pivotaltracker.com/story/show/180311768).
It **will cause 0 days delay** for the delivery of this sprint.

**Delay Cause:** Previous retported delay seemed to have been off due to weekend.

**Possible solutions:** Might be good for the bot to tell about the current estimated end date when rejecting a stand-up for an invalid end date. (Enso Bot - Dec 2, 2021)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2021-12-01):

**Today:** Started work on the revision from the review. Had some meetings, and did some prep for onboarding/planning and PR reviews. It should be finished by 2021-12-03.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180311768). Chat with Mateusz. Finish the review iteration. (Enso Bot - Dec 2, 2021)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2021-12-02):

**Today:** Worked on the revisions, refactoring both the JS and RS API. Had a good intro chat with Mateusz. Minor TL tasks. It should be finished by 2021-12-03.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180311768). Finish the documentation updates on the PR. have 1on1 meetings with the team. (Enso Bot - Dec 3, 2021)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for yesterday (2021-12-09):

**Summary:** There is **7 day** delay in implementation of the [Enso developers should have tooling to do time based profiling of their code (#180311768) task](https://www.pivotaltracker.com/story/show/180311768).
It **will cause 0 days delay** for the delivery of this sprint.

**Delay Cause:** Sickness + review changes taking more time than expected. (Enso Bot - Dec 10, 2021)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2021-12-09):

**Today:** Catching up after being sick. Almost finished the revisions of the API as requested in the review. It should be finished by 2021-12-10.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180311768). Finish the API update: a few docs needs updating and a little of code simplification left to do.  Probably some reviews. (Enso Bot - Dec 10, 2021)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for the provided date (2021-12-10):

**Summary:** There is **3 day** delay in implementation of the [Enso developers should have tooling to do time based profiling of their code (#180311768) task](https://www.pivotaltracker.com/story/show/180311768).
It **will cause 0 days delay** for the delivery of this sprint.

**Delay Cause:** Review changes to rework the API to be generated via proc macro from a config file.

**Possible solutions:** Overall, this task should have been broken down much further earlier in the planning process to deliver smaller parts of the API which could have been reviewed separately. (Enso Bot - Dec 13, 2021)
<hr />
**Michael Mauderer** reports a new **STANDUP** for the provided date (2021-12-10):

**Today:** Finished the revisions for the Rust API to use Proc Macros to generate the profilers from a config file, also updated the JS APi to be generated from the same config file. Still lacking some docs to explain the macros. It should be finished by 2021-12-13.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180311768). Finish the docs needed to explain the proc macro usage. This should be the last work on this task. Planning for next sprint. (Enso Bot - Dec 13, 2021)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (2021-12-13):

**Today:** Finished the revisions on the PR for the profiling. PR. Planning and prep for planning meetings and looking at getting started with the next task. It should be finished by 2021-12-13.

**Next Day:** Next day I will be working on the [##180311774 task](https://www.pivotaltracker.com/story/show/180311774). Planning follow-up tasks, and getting started on adding profiling reports on the GUI. (Enso Bot - Dec 13, 2021)
<hr />
