### ISSUE TITLE
Enso developers should be able to obtain a reproducible build environment with Nix

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4177]
This task is automatically imported from the old Task Issue Board and it was originally created by Keziah Wesley.
Original issue is [here](https://www.pivotaltracker.com/story/show/180895312).
<hr />

**As** Enso developer
**I want** to be able to obtain a reproducible build environment by running `nix-shell` in the project directory
**So that** I can work on Enso on my NixOS machine, and any other machine with the Nix package manager installed

I have already implemented this during my first two days, in order to get Enso building on my computer. I'm nominating it for inclusion in the repo since it allows any future developer who has Nix to get started working on Enso with a single standard command.

## Tasks:
- [X] write the nix scripts
- [ ] modify the nix script to be usable as a Nixpkgs overlay
- [ ] host the overlay in a separate repository
- [ ] link to the overlay in the developer docs somewhere

## Comments:
This needs review for: whether the nix scripts should be included in-repo; and maybe: design choices, by another nix user (Keziah Wesley - Jan 12, 2022)
<hr />
In consideration of the review on PR#3221, it seems like the best approach is to publish these scripts somewhere outside the main repo. Although the scripts are in a working state, this issue now tracks the (small) changes to the scripts necessary to accomplish that (Keziah Wesley - Jan 13, 2022)
<hr />
I published it here for now: https://github.com/kazcw/enso-nix (Keziah Wesley - Feb 2, 2022)
<hr />
