### ISSUE TITLE
Enso developers should have a straightforward way to obtain profiling information with minimal performance overhead

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4186]
This task is automatically imported from the old Task Issue Board and it was originally created by Keziah Wesley.
Original issue is [here](https://www.pivotaltracker.com/story/show/180922202).
<hr />

# Why

Developers working on performance (or trying not to introduce regressions while working on features) need profiling information.

Obtaining this information must not impact performance excessively, so that the information is accurate.

How to choose the boundaries of a measured task should be straightforward, so that the information is easy to interpret.

# Acceptance criteria
```gherkin
Scenario: 
GIVEN I am a developer (or a CI job)
WHEN I collect profiling information
THEN performance should not differ excessively from when profiling is disabled
```

```gherkin
Scenario: 
GIVEN I am a developer investigating Enso's performance
WHEN I want to increase the level of detail measured relating to a certain operation's performance
THEN it should be easy to choose the right boundaries for the newly instrumented segment
```

# Performance

### Current approach (for comparison)

I fixed the big performance bug (https://github.com/enso-org/enso/pull/3225), but performance is still not great. There's some room for incremental optimization (eliminate expensive API calls made by `get_latest_performance_entry`, and do all the WASM->JS data conversion in `mark_start_interval` so we don't have to do the same conversions twice), but the minimum overhead with this approach is probably around 0.5ms (3% of a 60Hz frame) per profiling call (start/end).

### Minimizing performance impact during measurement

We could do better than that by deferring the WASM->JS conversion.
- in the `start` / `end` calls use the JS FFI only to obtain timestamps, recording profiling info in WASM memory
- after profiling ends, pass all the profiling records into JS to register them with the Performance API

This requires the app to know when profiling information is being recorded; to achieve that, we can support invoking the profiler programmatically (implemented with the `console.profile()` and `console.endProfile()` interface). We'd want two interfaces to that functionality: a switch to enable profiling the startup phase (this would be convenient to have anyway), and profile-start and profile-end functions invocable from the console for non-startup profiling.

# API

While using the `profiling` library, I was faced with a question: where should I define boundaries of a `task`? This seems like an open-ended decision, and the choice made affects interpretation of the results. The strategy I decided on is based on consideration of the role of explicit calls to profiling functions in a larger profiling strategy.

I think the core of our profiling strategy should be the callgraph profiling functionality built-in to V8; it is efficient, detailed, and works without cluttering the code with instrumentation. Anything it does, we shouldn't duplicate--we can't do better than an API that has direct insight into V8 execution internals. While builtin callgraph profiling covers a lot of profiling needs, it has two gaps:
1. async: in a callgraph, async tasks are split up, which makes it difficult to determine where they ultimately start and end during high-level optimization
2. inlining: in release mode, inlining causes a loss of detail that can be needed for low-level optimization

### 1. Profiling async tasks

Segments of code that are executed sequentially--that is, that don't contain an invocation of `.await`--can easily be inspected in the callgraph. What a profiling library can add is insight into the lifetimes of async tasks. Therefore, we can standardize our usage of our profiling library: the start and end points of each measurement should indicate the bounds of an async block. We can enforce this usage through the API: the profiling library is used by annotating an `async fn` with an attribute macro that wraps its body with instrumentation.

I expect the very-high-level `section`s that we'll want to profile will correspond to `async fn` invocations, but I haven't investigated that yet. (If it turns out that that isn't the case, we could also have a `measure_section` API.)

### 2. Profiling details in the presence of inlining

Since callgraph profiling is the most lightweight option available to us, it should be the basis of fine-grained measurements. However, when profiling with optimizations enabled, a lot of detail is lost from the callgraph due to inlining. So, a minimal-overhead API for fine-grained profiling would be a set of function-annotation attribute macros that prevent inlining at certain profiling-levels.

## Tasks:
- [ ] create an API to control the profiler [<=1 day]
- [ ] create a low-level-profiling library, which provides attribute macros that conditionally prevent inlining [1 day]
- [ ] create an async-profiling library, which provides an attribute macro that instruments an `async fn`, and uses the deferred-JsValue-conversion strategy [4 days]

## Comments:
	@michael_mauderer in response to your query for thoughts on alternative profiling approaches, I started with an analysis of my experiences using the existing profiling library and it evolved into this design doc. What do you think? (Keziah Wesley - Jan 14, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for today (2022-01-14):

**Today:** interrupted work using the new profiling library to design a faster, simpler-to-use replacement It should be finished by 2022-01-14.

**Next Day:** Next day I will be working on the [##180922202 task](https://www.pivotaltracker.com/story/show/180922202). either #180922202 or start implementing the optimization described in #180886818

**Additional Information:** (correcting previous standup for today, I had the wrong issue #) (Enso Bot - Jan 14, 2022)
<hr />
	@michael_mauderer actually, this story has components that can be considered separately:
(1). API for instrumentation-based high-level profiling: I'm going to split this out into a separate issue, because this is not a concrete proposal at this point--first I need to do some investigation to confirm or refute the proposition that anything we need to measure that spans multiple nodes in the callgraph would be be observable in an async task graph; if that proves true I can flesh out a more detailed design
(2). API for low-level profiling (0-overhead, but can't span `await` points): There's one design question: should we use a proc-macro to define custom attributes for convenience, something like `#[profiling(level=detail)]`, or do it without any support code and directly annotate functions like `#[cfg_attr(feature="enable-detail-profiling", inline(never))]`. I favor the latter approach because it's self-documenting.
(3). Instrumentation performance: the decision we need to make is whether it would be sufficient to optimize the current approach to reach 0.5ms / call (worst case: debug mode, slow laptop); or we need to implement deferred-FFI, which would support the lowest possible overhead for instrumentation-based profiling. If we are going to use (2)  for low-level profiling, instrumentation would only be needed for tasks large enough to potentially span more than one frame, so maybe 0.5ms would be tolerable. Optimizing the current approach would take about a day of work; implementing deferred-FFI would take about 3 days, and the resulting profiling library would be a bit more complex. (Keziah Wesley - Jan 15, 2022)
<hr />
This looks quite promising. In general being able to have profiling run across async points would be really useful, as we do want to measure communication overhead with the backend, which will definite span async points and will even have start and end points in different parts of the call graph. Consider the span of "open project" which will include multiple network requests to the backend. 

I like the idea of defining a proc macro like that, and was thinking the same thing when I stated using the same API to cover the whole body of functions. But it might just be for convenience in those cases where we do want to measure the entire body of a function/method, and also provide an API that can be used to cover custom code blocks.

Regarding performance. The request from WD is, that "- when you'd be writing the benchmarks, compare them to just code pushing &'const str to a vector - the difference should be close to 0". So, I think we might need an alternative that does not interoperate with JS. This requirement stems from the fact that the profiling is supposed to also be used in the core rendering library.
The requirement for interoperability with the JS performance console is gone for this profiling, though. The only interop would be to collect data from JS for reporting purposes. 

One additional thing that might be worth investigating: what is the best way to do WASM benchmarks. Currently, we only have some example scenes that run code we can manually inspect. We should probably loot better ways, using something like `cargo bench` or similar. Or extend our custom scenes to work as a benchmark that can return the desired results. 
 (Michael Mauderer - Jan 17, 2022)
<hr />
	We need various types of profiling data for different type of profiling. The 3 different aspects of implementation are instrumentation (discussed above); measurements, and graphs (see "Implementation" sections below):

# High-level profiling (async tasks, startup processes and complete interaction-response sequences)

## Profiling output: Measures

Intervals. To handle performance variance, we'll want to run a process multiple times and take the average.

### Target measures

User-observable measures. Generally a target will be: the time between when the user initiates some action, and the app completes its response.

An important target is **startup time**. There are a few measures that can be used to assess startup time; I think the most inclusive would be the time until we start consistently rendering frames on time (this will be after everything "settles", i.e. the project list populates and no further changes occur). We should also find a measure that defines when the main content has rendered--they are both important, since render time is important to how long startup seems to take, but the user may not actually be able to use the app until settling time.

**Regression tests** should be based on target measures, since target measures correspond to user experience.

### Task measures

Internal measures. When performing an optimization, task measures are the first thing to look at, since a change's effects will be easiest to assess in terms of the smallest task containing it.

### Implementation

To achieve minimum overhead, instrumentation should be implemented as in "Minimizing performance impact during measurement" above: during measurement, record timestamps; after measurement completes, submit results.

A demanding case is startup measurement--we must:
- load the page a designated number of times
- collect measurements from the batch of page loads
- report on average measurements

Most other measures will make use of simulated events (invoking an interaction handler directly), which will often not require reloading.

#### Backend

I don't see any existing framework that meets our needs; most profiling tools are designed around sample-based profiling that isn't effective for shedding light on async processes. However, the backend we need will not be too much work to implement.

The backend code runs inside the app being profiled; consists of a WebSocket connection and its event handlers; needs: access to measurements saved by instrumentation, ability to trigger events like reload-page, simulate-interaction. The backend will be lightweight, but we could ensure it has 0 impact on measurements by not loading it until startup is completed. (To make that work, we'd invert the usual relationship and have the profiler listen for connections from the profilee.)

#### Frontend: time for some dogfooding?

When it comes to specifying the action to be measured and presenting the results, I think the tool for the job could actually be Enso.

Enso is well-suited to expressing a profiling plan, which would be along the lines of:
- repeat a specified of action a specified number of times (advanced version: repeat a dynamic number of times depending on how much variance is encountered)
- gather one or more specified measurements
- for A/B comparison, do all that over again when version B is available (to implement this, the backend could provide a build ID that's distinct for each compilation)
- render a visualization (box plots are probably the main output; sometimes bar charts might be useful)
- In interactive use, display the chart. For regression tests, we could integrate with the GitHub API: if a PR is tagged as having a performance component (i.e. startup-time), a required check is added for regression testing; we keep an Enso process running on reference hardware to take the appropriate measurements; the profile uses the measurements to post to GitHub both a Pass/Fail result and a comment including the performance impact chart.

Packaged together with the backend, the resulting Enso app would be the first (as far as I can find) tool for profiling async Rust under WASM.

My main question is, are we ready for this? I don't know if Enso's backend and frontend have the features and stability to make this practical yet. If we aren't there yet, we might want to create a frontend in Rust to use until we can replace it with the Enso app. (If we go that route, it should be functional and maintainable enough that it won't be a source of endless frustration if we never end up getting around to implementing its successor; the road to hell is paved with "this will be replaced later anyway"). (it would be simplest to use the Browser Console as the interface, but we can't because having the console open has a drastic effect on WASM performance.)

## Profiling output: Control-flow graphs

We need a way to visualize the relationships between processes; a callgraph side-by-side with a similarly-formatted graph of task measures is invaluable for optimizing async task scheduling.

Unfortunately, it's not possible to average two graphs of this type in a way that doesn't lose these relationships, so these graphs are prone to a lot of variance; they are useful more for qualitative information than quantitative.

### Implementation

Emitting data to the User Timing API is convenient to use and simple to implement (we should defer the necessary FFI until after measurement is complete for 0-impact).

# Low-level profiling (debugging dropped frames)

As far as output data, this is the simplest type of profiling: only synchronous function calls can cause dropped frames, so callgraphs are informative; we don't need to explicitly repeat measurements, because measurements repeat themselves many times per second, and the variance is an important part of the data. We'll want to gather some statistics (FPS during an operation), but aggregating that kind of measure is simple and cheap.

However gathering this data has more logistical challenges:
- Exact timings are important enough we'll often have to measure in release mode, which means long build times and loss of some debug info.
- Automating some of these tests (e.g. to measure FPS while dragging something) requires a framework that can simulate mouse inputs, like Selenium. (Do we have any Selenium experts?) (Keziah Wesley - Jan 18, 2022)
<hr />
One additional consideration re: instrumentation implementation--performance.now is not always as accurate as performance.mark. In Chrome it is typically +/- 100us (there may be ways of increasing that accuracy in some cases). But since 0.5ms impact per call in unacceptable, performance.now is the only option. For any fine-grained measurements where 100us inaccuracy in excessive, we will need to rely on callgraph profiling. (Keziah Wesley - Jan 18, 2022)
<hr />
Thanks for that write up! Let's discuss this during the meeting today. I think after that, we should revisit the original design document and create a PR to update it. We can have further discussions about details there (and might be able to get feedback from other people, too).  (Michael Mauderer - Jan 19, 2022)
<hr />
A few things already to mention before the discussion meeting.

> An important target is startup time.

We will probably have more than one "startup time" that will have a similar flow in terms of dropped frames: (1) starting the application and (2) opening a project

> Low-level profiling

There is already some functionality for this in EnsoGL, which we will use. In the first iteration, we should focus on the interval-based approach. 

> Automating some of these tests 

This is super important and there will probably(?) be another epic about allowing us to better automate testing with the GUI and backend. And the moment we have test scenes (for example `lib/rust/ensogl/example/sprite-system-benchmark/src/lib.rs`), that can be controlled as far as the API allows it at the moment. The test scenes are probably also the most likely candidate for implementing our benchmarking. 

 (Michael Mauderer - Jan 19, 2022)
<hr />
On the call, we decided we need an explicitly hierarchical measurement API.

This kind of API can only be call-site based; it is incompatible with the function annotations idea we discussed earlier (at least, without some major hacking to instrument the Web Executor and Futures internals).

Also, the User Timing API doesn't support hierarchical measurement, and as a result the format Chrome DevTools can't represent a hierarchy of user measurements. We will need to either emit our data in a different format and explore it with different tools, or find a way to shoehorn it into Chrome's format as a different datatype from user measurement (callgraphs are of course hierarchical, maybe we could represent it as a parallel callgraph). (Keziah Wesley - Jan 20, 2022)
<hr />
I think "hierarchical" doesn't exactly describe the relationships between measurements that we need to capture. Although Target Measures can probably be structured hierarchically, they are composed of async tasks, which are fundamentally not hierarchical. I think what we really want to know is, when a task has to yield, what task was it awaiting? I.e. there is a parent-child relationship at *particular points*, but not between whole tasks. The best way to capture, represent, and use this information needs some thought. (Keziah Wesley - Jan 20, 2022)
<hr />
	A few comments from my side:
- **Fixing performance now**. As we've been chatting on the call, fixing tasks now does not make too much sense, as we will probably spend time fixing the wrong places. E.g. the WASM compilation pipeline – we are OK with it taking a little bit longer, however, opening projects, switching projects, working with graphs, entering nodes is way more important. The startup time is important too, however, before we decide what to fix we need to understand what is the **gain/cost ratio** (how much we will gain spending how much time). I believe that the profiling framework task has enough parts that 2 people can implement it side by side (e.g. one person implementing the core of the framework, while second person implementing loading the graph to chrome or making CI-oriented performance regression tooling). In case there would be a problem with task distribution, lets have a call :)

- **How to define startup time** – I like the idea to define its end as a point when the rendering "settles down". This can easily be discovered in the App - after the Graph Editor intialization, we should be done with it. As I mentioned during the call, there are several things that we should improve there - like distribute shader compilation between frames, but this will be handled after we discover the most important performance cases.

- **Clarity of the comments / docs.** The notes you've posted @kazcw are sometimes not clear to me. For example, there is a section named "Task measures". It's content is "Internal measures. When performing an optimization, task measures are the first thing to look at, since a change's effects will be easiest to assess in terms of the smallest task containing it.". And TBH, I don't uderstand it. Is is a general concept description, is it a name for some API that you plan to introduce, what is it? In such cases I need better explanation, preferably with examples or API mockup to understand what the concept is about. But no worries, I think that instead of doing that here, we can just add it to the design doc. Just please make sure that all the concepts are properly described there (properly = clear for the reader with information about the API and at least scratch of info how it will work under the hood).

- **Implementation section** – I completely agree.

- **Backend** – please be careful with naming. Backend in Enso means our Language Server + Compiler. When I was reading it, I was initially thinking this section will be about backend responds performance measurements (how fat backend responds to GUI). Then, after reading more content I came to a conclusion that I dont know what this section is about. It describes "backend" as "The backend code runs inside the app being profiled; consists of a WebSocket connection and its event handlers" – what is the backend then? I don't understand this section TBH. EDIT: oh, is the backend something like additional application that will be run side by side Enso and will re-load it, gather statistics between runs, etc? If so, there is a rule we try to follow when writing docs or introducing new concepts in comments – please describe from high perspective this concept as the first sentence in the given section. Such description should tell what this concept is about, preferably mentioning its user (the user can be end-user, developer, or another system) and an example usage.

- **dogfooding** – as discussed on the call, I feel we will have too many problems with it now. Maybe in the future, but now lets do it as simple as possible.

- **Profiling output: Control-flow graphs**. There is a sentence "We need a way to visualize the relationships between processes;" – 1) why do we NEED it? 2) what kind of processes? This is again about clarity of the description – please make it clear, preferably with an example of what you mean here. Also (and this is very important), please remember that we do not want to implement now the best profiling framework in the world now – **we want to have "good enough" framework which will be 1) close to 0-cost 2) will give us enough information of what parts of the app are slow 3) will give us the possibility to discover performance regressions automatically. We will be extending it in the future, however, we should not spend more time on it than it is necessary to get the minimal results we want. We have 10 months to deliver production ready Enso and this is not much time :)**

- **Simulating UX events** – we will not use selenium! We can simulate UX events by emitting events via our FRP engine.

**TO SUM THIS UP:**
I'm waiting for the fixes to the design doc – this should be really PR to it. Please take care of describing the concepts clearly, showing the desired API and when introducing new concepts, describing how they would work preferably with examples. (Wojciech Daniło - Jan 21, 2022)
<hr />
**Keziah Wesley** reports a new **🔴 DELAY** for today (2022-01-21):

**Summary:** There is **1 day** delay in implementation of the [Enso developers should have a straightforward way to obtain profiling information with minimal performance overhead (#180922202) task](https://www.pivotaltracker.com/story/show/180922202).
It **will cause 0 days delay** for the delivery of this sprint.

**Delay Cause:** designing takes time (Enso Bot - Jan 22, 2022)
<hr />
**Keziah Wesley** reports a new **🔴 DELAY** for today (2022-01-21):

**Summary:** There is **10 days** delay in implementation of the [Enso developers should have a straightforward way to obtain profiling information with minimal performance overhead (#180922202) task](https://www.pivotaltracker.com/story/show/180922202).
It **will cause 0 days delay** for the delivery of this sprint.

**Delay Cause:** designing takes time (Enso Bot - Jan 22, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for today (2022-01-21):

**Today:** revising the PR for profiling design doc update (#180922202) It should be finished by 2022-01-25.

**Next Day:** Next day I will be working on the [##180922202 task](https://www.pivotaltracker.com/story/show/180922202). further iteration on #180922202 (Enso Bot - Jan 22, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for today (2022-01-24):

**Today:** worked out most of the last details for the profiling design doc PR; investigated the root cause of variance and found an additional strategy that should help the averages converge faster, will finish updating doc for that tomorrow morning It should be finished by 2022-01-25.

**Next Day:** Next day I will be working on the [##180922202 task](https://www.pivotaltracker.com/story/show/180922202). finish up PR for #180922202

**Additional Information:** Day got cut short today, the power went out in half the town. It wasn't even windy! (Enso Bot - Jan 25, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for today (2022-01-25):

**Today:** Finished draft PR, incorporating discussion from meetings today. It should be finished by 2022-01-25.

**Next Day:** Next day I will be working on the [##181038002 task](https://www.pivotaltracker.com/story/show/181038002). Start implementing the core measurement functionality described in #180922202. (Enso Bot - Jan 25, 2022)
<hr />
**Keziah Wesley** reports a new **🔴 DELAY** for today (2022-01-26):

**Summary:** There is **3 days** delay in implementation of the [Enso developers should have a straightforward way to obtain profiling information with minimal performance overhead (#180922202) task](https://www.pivotaltracker.com/story/show/180922202).
It **will cause 0 days delay** for the delivery of this sprint.

**Delay Cause:** big design change (Enso Bot - Jan 26, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for today (2022-01-26):

**Today:** Revising PR, incorporating feedback from recent review and discussions. It should be finished by 2022-01-28.

**Next Day:** Next day I will be working on the [##180922202 task](https://www.pivotaltracker.com/story/show/180922202). Continue revising PR (Enso Bot - Jan 26, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for today (2022-01-27):

**Today:** Revising PR It should be finished by 2022-01-28.

**Next Day:** Next day I will be working on the [##180922202 task](https://www.pivotaltracker.com/story/show/180922202). Finish revising PR for review so far (Enso Bot - Jan 27, 2022)
<hr />
