### ISSUE TITLE
Update to GraalVM 21.3.0

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4194]
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/180303532).
<hr />

# Summary
There is a new version of [GraalVM](https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.3.0) released, and we need to update our project.

# Value
- New GraalVM brings smaller native images with faster startup time
- Project don't have outdated dependencies

## Tasks:
- [X] Run runtime benchmarks before upgrading with `sbt runtime/bench`
- [X] Bump GraalVM version in `build.sbt`, `Dockerfile`, and `signArchives.js` ide task. (you can grep for `21.1.0`)
- [X] As a sanity check, run the runtime benchmarks again after the upgrade. The benchmark will end unsuccessfully if the new values are larger than the previous run.

## Blockers:
[#180464494](https://www.pivotaltracker.com/story/show/#180464494) resolved

## Comments:
**Marcin Kostrzewa** reports a new **STANDUP** for yesterday (2022-01-19):

**Today:** Dumped some of my thoughts on the issue to prepare it for Jaroslav to take over It should be finished by 2022-01-19.

**Next Day:** Next day I will be working on the [##180956811 task](https://www.pivotaltracker.com/story/show/180956811). Back to types (Enso Bot - Jan 20, 2022)
<hr />
**Edward Kmett** reports a new **🔴 DELAY** for today (2022-02-05):

**Summary:** There is **21 days** delay in implementation of the [Update to GraalVM 21.3.0 (#180303532) task](https://www.pivotaltracker.com/story/show/180303532).
It **will cause 0 days delay** for the delivery of this sprint.

Was just handed this.

**Delay Cause:** Was just handed this.

**Possible solutions:** Hand it off earlier? (Enso Bot - Feb 6, 2022)
<hr />
**Edward Kmett** reports a new **STANDUP** for today (2022-02-05):

**Today:** Went through Jaroslav's changes for updating Graal. Should be easy enough to merge. It should be finished by 2022-02-09.

**Next Day:** Next day I will be working on the [##180956811 task](https://www.pivotaltracker.com/story/show/180956811). Back to working on the type system with wdanilo and marcin on Monday, then I'll finish this up.

**Additional Information:** I'm giving myself an extra couple of days in terms of end date based on my past experiences trying to get things through our Byzantine merge process, and due to the concurrent type system exploration, and just in case the merge doesn't go well, but I expect to be "done" on Tuesday. (Enso Bot - Feb 6, 2022)
<hr />
**Edward Kmett** reports a new **STANDUP** for yesterday (2022-02-07):

**Today:** Merged together jaroslav's changes with HEAD. This ran afoul of some issues with the way sbt build steps don't quite link up properly in our build system. It should be finished by 2022-02-09.

**Next Day:** Next day I will be working on the [##180956811 task](https://www.pivotaltracker.com/story/show/180956811). Will allow myself to be interrupt driven by availability of marcin and wdanilo to talk about type system stuff. Finishing this patch otherwise. (Enso Bot - Feb 8, 2022)
<hr />
**Edward Kmett** reports a new **STANDUP** for today (2022-02-08):

**Today:** Figured out the broken build steps with a bit of help from Marcin. Have been playing whack-a-mole finding all the locations where CI redundantly stores the same graalvm version number, and finding broken build steps and bad caching behavior. It should be finished by 2022-02-09.

**Next Day:** Next day I will be working on the [##180303532 task](https://www.pivotaltracker.com/story/show/180303532). Will allow myself to be interrupt driven by availability of marcin and wdanilo to talk about type system stuff. I expect this patch should be done early on in the day. From there I plan to transition to default arguments for atom constructors. (Enso Bot - Feb 8, 2022)
<hr />
**Edward Kmett** reports a new **🔴 DELAY** for today (2022-02-09):

**Summary:** There is **2 days** delay in implementation of the [Update to GraalVM 21.3.0 (#180303532) task](https://www.pivotaltracker.com/story/show/180303532).
It **will cause 0 days delay** for the delivery of this sprint.

Will spend the time in the meantime working on default arguments for atoms.

**Delay Cause:** Two blocking issues on the merge. One is that graal changed the way it resolves the version of gcc to compile native-images with. The other is that the code signing logic that dmitry wrote for osx relies on a file that isn't included in the 21.3.0 distribution. Will consult with both to get this to done.

**Possible solutions:** mwu wants to fix the compiler logic the right way and integrate it with the rest of the environment setup. For the other we _could_ remove some of the logic in the code signing step that marks certain files read-only, but I'd rather consult with dmitry to get this done right before hopping over Chesterton's fence. (Enso Bot - Feb 9, 2022)
<hr />
**Edward Kmett** reports a new **STANDUP** for today (2022-02-09):

**Today:** Two blocking issues. One is around the way native-image looks for the compiler, which mwu is going to look into, and the other around code signing on macs which is dmitry facing. It should be finished by 2022-02-11.

**Next Day:** Next day I will be working on the [##180956811 task](https://www.pivotaltracker.com/story/show/180956811). I'll interleave design work on the type system with @wdanilo and marcin, with working on support for default arguments for atoms, while blocked on this. (Enso Bot - Feb 9, 2022)
<hr />
**Edward Kmett** reports a new **STANDUP** for today (2022-02-10):

**Today:** This task is mostly blocked on ci fixes. Spent ~1.5 hours looking into Apple's code signing machinery to see if I could/should unblock part of this myself. Inconclusive. It should be finished by 2022-02-11.

**Next Day:** Next day I will be working on the [##180956811 task](https://www.pivotaltracker.com/story/show/180956811). More work on default arguments for atoms. Possibly a type system meeting(?) (Today's meeting was cancelled.) 1:1 with Sylwia.

**Additional Information:** The other 2.5 hours of my time were spent on starting the default arguments for atoms task. Part 1 of which is adding the extra information about default arguments to the binding map. (Enso Bot - Feb 11, 2022)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for today (2022-02-11):

**Today:** Was working on fixing the CI. Fixed the macOS package signing. Was debugging the native build-related issues with musl. Turned out the Graal doc on native builds was updated and I believe we need to update the build script accordingly. The musl bundle we're using is not mainained anymore and may cause troubles in the future. It should be finished by 2022-02-11.

**Next Day:** Next day I will be working on the [##180916527 task](https://www.pivotaltracker.com/story/show/180916527). Switching back to the components API task. (Enso Bot - Feb 11, 2022)
<hr />
**Edward Kmett** reports a new **STANDUP** for today (2022-02-11):

**Today:** Merged. It should be finished by 2022-02-11.

**Next Day:** Next day I will be working on the [##180956811 task](https://www.pivotaltracker.com/story/show/180956811). Back to default arguments for atoms. Possibly a type system meeting(?) Still waiting on a type system design document to debate / ratify.

**Additional Information:** Had 1:1 with Sylwia. Flipped over to default arguments for atoms. Will work on documentation for from conversions if/when i get blocked if @kustosz isn't available at that time. Question: What is the preferred format if you finish one task and start on another in the same day? Right now I just report on the one task, which loses some resolution, but I also worry about drowning in fractional-standups. (Enso Bot - Feb 11, 2022)
<hr />
