### ISSUE TITLE
Adjust compilation workflow to new `wasm-bindgen`

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4198]
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/180303561).
<hr />

## Description
Currently, we are using a very old `wasm-bindgen` binding. It has several issues and often blocks us from using newer versions of other libraries who already moved to a newer version. Moreover, it started causing some compilation warnings/errors a few months ago that do not break compilation but may do so in the future.

## Resources
In the past, we created a patch for `wasm-bindgen` to use it with our GUI loader. In the past, the generated code from `wasm-bindgen` was tightly coupled and did not allow for downloading and compiling WASM in a custom way (e.g. to show loader for the download). There were many new versions since then and there is probability that this does not apply anymore. If it does, we should create a patch and a PR to `wasm-bindgen`.

## Tasks:
- [X] Update `wasm-bindgen` to the newest version.
- [X] Be sure that during compilation of the IDE no errors or warnings are emitted.
- [ ] Submit a PR with a patch to `wasm-bindgen` repo if needed.
