### ISSUE TITLE
Developers should be able to build and test desktop IDE on M1 Mac

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4207]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/180544972).
<hr />

There are multiple issues with building desktop IDE on Mac with M1 chip.
Namely: 

1. installation of required dependencies is a bit painful (see https://github.com/enso-org/enso/issues/3136). We need to mention solutions in the contributing guide, not some random issue.
2. Building WASM packages in release mode is not working because of https://github.com/rustwasm/wasm-pack/issues/913
3. Building package requires manual installation of `vips` package (see https://github.com/nuxt/image/issues/204 for similar issue)
4. Signing doesn't work because binaries went into `client/mac-arm64` directory instead of `client/mac`
5. IDE's renderer process crashes on Electron v11 (see https://github.com/electron/electron/issues/27497)

## Tasks:
- [X] Update docs with instructions on additional actions for M1 Mac
- [X] Fix building WASM packages in release mode
- [X] Fix binaries signing
- [X] Fix renderer crash

## Comments:
**Ilya Bogdanov** reports a new **STANDUP** for today (2021-12-10):

**Today:** mostly playing with building Enso on M1 Mac. Update to Electron v12 went smoothly, signing fix is easy, but `wasm-opt` issue is harder. Apparently updating to the latest `wasm-pack` breaks everything, but I want to try to do that to get optimized builds. Also quickly checked exceptions in visualizations (#180560409) and applied some fixes to Welcome Screen (#180312485). It should be finished by 2021-12-16.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180544972). continue working on M1 support (Enso Bot - Dec 10, 2021)
<hr />
**Ilya Bogdanov** reports a new **STANDUP** for today (2021-12-13):

**Today:** I was trying to get latest `wasm-pack` working with Enso in order to update it later to the most recent version with M1 bugfix for wasm-opt. It seems that they've broken something between version 0.10.1 (latest release) and the latest master. The diff is not huge, but it's the bug is rather obscure. Basically it triggers repeatable cargo watch calls, similar to https://github.com/watchexec/cargo-watch/issues/131. Also our custom patching of rust-js glue code stopped working for me without any visible reason. To sum it up, I face a pretty varied set of issues, and I need more time to carefully investigate them. Besides, I was checking scrolling visualizations bug spotted by Sylwia It should be finished by 2021-12-16.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180544972). I will continue working on M1 support (Enso Bot - Dec 13, 2021)
<hr />
**Ilya Bogdanov** reports a new **STANDUP** for today (2021-12-14):

**Today:** I spent the day investigating several distinct issues around webpack, wasm-pack and our whole build pipeline on Mac. The issues are absolutely insane, but I think I will be able to fix them in time It should be finished by 2021-12-16.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180544972). I will try to mitigate all the spotted issues and also update our contributing docs for M1 Mac (Enso Bot - Dec 14, 2021)
<hr />
**Ilya Bogdanov** reports a new **STANDUP** for today (2021-12-15):

**Today:** Writing docs, applying and testing fixes for spotted issues with M1 Mac It should be finished by 2021-12-16.

**Next Day:** Next day I will be working on the [##180560409 task](https://www.pivotaltracker.com/story/show/180560409). prepare PR for #180544972 and also start working on source map support for visualizations (Enso Bot - Dec 15, 2021)
<hr />
There is a subtask not marked as done - about building WASM in release mode. Until its working ,this should not be accepted. (Wojciech Daniło - Feb 8, 2022)
<hr />
	@wdanilo This was a mistake, building WASM in release mode is fully supported in current develop. Marked it as done. Also sorry for a late response, I missed a notification.  (Ilya Bogdanov - Feb 11, 2022)
<hr />
