### ISSUE TITLE
Developers should be able to use the rustc version in line with the Rust 1.58.0 release

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4212]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/180963065).
<hr />

## Description
This ensures our code is compiled with an up-to-date compiler, which allows us to use more new rust features, avoids us into running old compiler bugs, potentially speeds up compilation and ensures that all our dependencies still support the compiler version we use. 

This requires bumping of the tool chain in the `rust-toolchain.toml` and fixing all new errors and warnings that appear. In general, this should not take too long, but if larger fixing of legacy code is required, this should be spun out into a separate task that is blocking this chore.

## Tasks:
- [X] Bump compiler version
- [X] Check new warnings / errors
- [X] Create separate tasks for larger refactoring required to fix warnings / errors
- [X] Fix all warnings / errors

## Blockers:
[#181123429](https://www.pivotaltracker.com/story/show/#181123429) resolved

## Comments:
**Michael Mauderer** reports a new **STANDUP** for the provided date (2022-02-11):

**Today:** Worked on investigating what is breaking on wasm-bindgen bump. Made some good progress tracking down something that seems to cause the breakage. (For details see IDE thread) It should be finished by 2022-02-15.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180963065). Further work on wasm-bindgen bump.

**Additional Information:** End date completely shot in the dark. might be today, might be later. But during planning we might want to re-prioritise in case this is not resolved yet. (Enso Bot - Feb 14, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (2022-02-14):

**Today:** Created more minimal examples of the failing wasm-bindgen build (down from our build and up from the minimal hello-world example) to track the root cause of the error. I think I found the solution for the issues (see thread for more infos). It should be finished by 2022-02-15.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180963065). Some last sanity checking, then moving on to planning for planning meeting and choosing the next task. (Enso Bot - Feb 14, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (2022-02-15):

**Today:** Finished the wasm-bindgen/rustrc bump PR, which is now waiting for final review and merge. Wrote feedback to the wasm-bingen-issue. Had 1on1 meetings. It should be finished by 2022-02-15.

**Next Day:** Next day I will be working on the [##181266457 task](https://www.pivotaltracker.com/story/show/181266457). Prepare planning meeting, after that get started on the next profiling task as planned.

**Additional Information:** Next task is tentative until planning confirmation. (Enso Bot - Feb 15, 2022)
<hr />
