### ISSUE TITLE
Run-graphs of the profiling data

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4232]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/181266457).
<hr />

## Team
Technical Designer: MM
Implementer: MM
Acceptance/QA: KW

## Why

**As** Developer or Project Manager
**I want** to easily see an overview of the product performance
**So that** I can make decisions about the state of performance and targets for improvements.

## Acceptance Criteria

```gherkin
Scenario: 
GIVEN I want to see a sample graph
WHEN I run the demo scene `run-graph`
THEN I see a demo run graph
```

## Notes
* Create demo scene to render mock data
* Vis should be flame graph like (like Chrome dev console), implemented in EnsoGL
* Basic rectangles + mouse zoom/pan
* Note gap between adjacent bars staying 1px (use shape z-zoom)
* Labels should be shown on hover only using mouse API

## Resources
Design section relevant to this task
https://github.com/enso-org/design/blob/main/epics/profiling/implementation.md#run-graphs

## Tasks:
- [X] Set up demo scene
- [X] Set up dummy data (e.g., serde for profiling data)
- [X] Set up rendering of basic rectangles based on data
- [X] Ensure correct processing or parent profiler information
- [X] Add correct rendering of gaps between bars
- [X] Add label on hovering of shapes

## Comments:
**Michael Mauderer** reports a new **STANDUP** for today (2022-02-16):

**Today:** Planning meeting & prep. Meeting with Wojciech to discuss details of the profiling data visualisation. Got started on the implementation (setting up a new demo scene with basic shape support) It should be finished by 2022-02-22.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/181266457). Work on the rendering of the basic building blocks of the visualisation. Create some dummy data. (Enso Bot - Feb 16, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-02-17):

**Today:** Worked on the demo scene rendering. Took a bit longer than expected to get back into all the details of our rendering. Have a working demo scene with some dummy shapes now. Then realized a deadline for feedback is looming and switched to preparing the requested feedback. It should be finished by 2022-02-22.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/181266457). Finish feedback. Integrate dummy data for rendering and set up rendering algorithm transforming data to shape positions/sizes. (Enso Bot - Feb 18, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for the provided date (2022-02-18):

**Today:** Submitted the feedback. Created a first visualisation based on some dummy data. It should be finished by 2022-02-22.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/181266457). Clean up the code and the integration with the profiling framework. Fix some small issues related to hovering. Also need to do some reviewing and QAing.

**Additional Information:** Took some time to get back into our component rendering system. There are a few things that  are tricky to debug at times (usually "why does nothing happen/show up") (Enso Bot - Feb 20, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-02-21):

**Today:** Was working on code clean-up and better dummy data (I am using the profiling framework directly to generate the data no instead of mocking allowing for a better API and a more useful example). This took a bit longer than expected, so I need to finish the cleanup + docs tomorrow morning. It should be finished by 2022-02-22.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/181266457). Finish clean up the code and documentation, open PR. (Enso Bot - Feb 22, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (2022-02-22):

**Today:** Opened the PR for the flame graph implementation. Did code reviews. Started planning for next week. It should be finished by 2022-02-22.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/181266457). Planning meeting prep, planning meeting and starting on the next task (as determined by planning meeting) (Enso Bot - Feb 22, 2022)
<hr />
**Acceptance/QA** review set to **pass** (Keziah Wesley - Mar 3, 2022)
<hr />
