### ISSUE TITLE
Developers should be able to use the rustc version in line with the Rust 1.59.0 release

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4249]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/181414331).
<hr />

## Description
This ensures our code is compiled with an up-to-date compiler, which allows us to use more new rust features, avoids us into running old compiler bugs, potentially speeds up compilation and ensures that all our dependencies still support the compiler version we use. 

This requires bumping of the tool chain in the `rust-toolchain.toml` and fixing all new errors and warnings that appear. In general, this should not take too long, but if larger fixing of legacy code is required, this should be spun out into a separate task that is blocking this chore.

## Tasks:
- [ ] Bump compiler version
- [ ] Check new warnings / errors
- [ ] Create separate tasks for larger refactoring required to fix warnings / errors
- [ ] Fix all warnings / errors
