### ISSUE TITLE
Enso developers should be able to generate profiling reports with enough details to identify the main time-consuming startup tasks.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4277]
This task is automatically imported from the old Task Issue Board and it was originally created by Keziah Wesley.
Original issue is [here](https://www.pivotaltracker.com/story/show/181499507).
<hr />

## Team
Technical Designer: KW
Implementer: KW
Acceptance/QA: MM

## Why
Having the profiling framework in place, we should extend its usage enough to see where most time is spent during startup.

**As** a developer
**I want** to generate a performance report showing what is taking time during startup.
**So that** I can easily spot performance issues or set up automated performance checks. 

## Acceptance Criteria

```gherkin
Scenario: 
Given I have the Enso application
When I use the hotkey to emit a JSON event log of an (interactive) startup workflow,
Then a rendering of the log with the `flame_graph` tools or the `measurement` tool should have no unidentified work lasting longer than 50ms at a time.
```

## Resources
https://github.com/enso-org/design/blob/wip/wd/profiling/designs/profiling/implementation.md#batch-results

## Tasks:
- [X] Implement profiling necessary to tell idle time from unprofiled working time
- [X] Add handling of inner async blocks to #[profile] so high-level profiling can capture common patterns
- [X] Add enough profiling to be capture evey unprofiled task that consumes more than 50ms during startup

## Blockers:
[#180311774](https://www.pivotaltracker.com/story/show/#180311774) resolved

## Comments:
**Keziah Wesley** reports a new **STANDUP** for today (2022-03-08):

**Today:** PR'd #180311774. Starting on more detailed instrumentation.e. It should be finished by 2022-03-08.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/181499507). Start on more detailed instrumentation. (Enso Bot - Mar 8, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for today (2022-03-08):

**Today:** PR'd #180311774. Starting on more detailed profiling: wrote some supporting instrumentation today. It should be finished by 2022-03-08.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/181499507). Hunt down the unprofiled slow functions. (Enso Bot - Mar 8, 2022)
<hr />
**Keziah Wesley** reports a new **🔴 DELAY** for today (2022-03-09):

**Summary:** There is **2 days** delay in implementation of the [Enso developers should be able to generate profiling reports with enough details to identify the main time-consuming startup tasks. (#181499507) task](https://www.pivotaltracker.com/story/show/181499507).
It **will cause 0 days delay** for the delivery of this sprint.

**Delay Cause:** I accidentally set the end date to "today" when I started it yesterday; this is just a correction of that. (Enso Bot - Mar 9, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for today (2022-03-09):

**Today:** Responding to review on #180311774. Some implementation work on #181499507: extended #[profile] functionality to support async blocks in profiled functions automatically, which turns out to be a common use case. It should be finished by 2022-03-10.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/181499507). Hunt down the unprofiled slow functions. (Enso Bot - Mar 9, 2022)
<hr />
**Keziah Wesley** reports a new **🔴 DELAY** for today (2022-03-10):

**Summary:** There is **1 day** delay in implementation of the [Enso developers should be able to generate profiling reports with enough details to identify the main time-consuming startup tasks. (#181499507) task](https://www.pivotaltracker.com/story/show/181499507).
It **will cause 0 days delay** for the delivery of this sprint.

**Delay Cause:** Needed to make `#[profile]` a bit smarter to cleanly handle the common pattern of `fn`s with `async` blocks. (Enso Bot - Mar 10, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for today (2022-03-10):

**Today:** Adding more profiling. It should be finished by 2022-03-11.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/181499507). Find the remaining unprofiled slow functions. (Enso Bot - Mar 10, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for today (2022-03-11):

**Today:** Added more profiling. We now have enough data to account for every dropped frame during startup! It should be finished by 2022-03-11.

**Next Day:** Next day I will be working on the [##181151201 task](https://www.pivotaltracker.com/story/show/181151201). TBD after meeting. (Enso Bot - Mar 11, 2022)
<hr />
**Keziah Wesley** reports a new **🔴 DELAY** for today (2022-03-16):

**Summary:** There is **6 days** delay in implementation of the [Enso developers should be able to generate profiling reports with enough details to identify the main time-consuming startup tasks. (#181499507) task](https://www.pivotaltracker.com/story/show/181499507).
It **will cause 0 days delay** for the delivery of this sprint.

**Delay Cause:** Partly the detour to investigating the labels issue; partly I decided to implement proper determination of async interval rows, which we used a shortcut for previous that requires an overly restrictive data model. (Enso Bot - Mar 16, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for today (2022-03-16):

**Today:** Finishing the additional-profiling PR: Needed to relax the data model a bit to cleanly allow async profilers to sometimes run under @on_frame, which meant I had to implement logic for calculating rows for async intervals that we were able to do the initial flamegraph implementation without. It should be finished by 2022-03-17.

**Next Day:** Next day I will be working on the [##181499507 task](https://www.pivotaltracker.com/story/show/181499507). Finish the additional-profiling PR. (Enso Bot - Mar 16, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for yesterday (2022-03-17):

**Progress:** I finished the profiling-application-details PR. It should be finished by 2022-03-17.

**Next Day:** Next day I will be working on the [##181610155 task](https://www.pivotaltracker.com/story/show/181610155). Report and fix an issue with assignment of various IDs. (Enso Bot - Mar 18, 2022)
<hr />
