### ISSUE TITLE
Developers should spend less time waiting for wasm-opt.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4329]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/182176154).
<hr />

## Description
The old version of `wasm-opt` can take a really long time (up to 15minutes) when running a release build. The new version is up to 10x as fast and will make all development workflows much faster.

## Tasks:
- [X] Create issue for bumping `wasm-opt in` our builds
- [X] Update docs to mention bumping wasm-opt as an optional build step
- [X] Create wasm-bindgen PR to bump wasm-opt.

## Comments:
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-05-12):

**Progress:** Looked at doing a new release build for windows, which is not currently  supported by the new build scripts. Setting up a new dev environment for this, does not seem to be an ideal use of time though, so moved on to coordinating and planning for next tasks. Started investigating regression in previous PR. It should be finished by 2022-05-13.

**Next Day:** Next day I will be working on the [##182176154 task](https://www.pivotaltracker.com/story/show/182176154). Fix regression in PR. Follow up on wasm-opt updates (create docs, PRs, etc). Write up some Profiling Epic tasks. (Enso Bot - May 13, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for the provided date (2022-05-13):

**Progress:** Fixed PR regression, ready to merge. Created docs for wasm-opt integration. Created upstream PR for wasm-pack to update wasm-opt. Started looking at upcoming tasks for profiling epic. It should be finished by 2022-05-13.

**Next Day:** Next day I will be working on the [##182176154 task](https://www.pivotaltracker.com/story/show/182176154). Planning for Performance Epic. Start looking at Component Browser tasks to help out. (Enso Bot - May 16, 2022)
<hr />
