### ISSUE TITLE
Enso IDE developers should be able to profile defined workflows with a batch mode

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4330]
This task is automatically imported from the old Task Issue Board and it was originally created by Keziah Wesley.
Original issue is [here](https://www.pivotaltracker.com/story/show/181775808).
<hr />

## Why

The Enso IDE should provide a [https://github.com/enso-org/design/blob/d913f20c658dbccc1777a8bc2e6503aead3050a6/epics/profiling/implementation.md#batch-mode](profiling batch mode) that supports measurement of defined workflows.

**As** an IDE developer
**I want** to be able to measure multiple workflows easily
**So that** I can compare the performance of different tasks to prioritize improvements
**And so that** I can identify common causes of performance issues in different tasks.

**As** an IDE developer
**I want** to be able to measure workflows reproducibly
**So that** I can compare performance before and after changes.

## Acceptance Criteria

```gherkin
Scenario: 
Given I have the Enso application
When  I run the application with the command line argument `--profile`
Then a performance report is generated and stored at `temp/enso/profiling/<date-with-time>.json`  and it contains information about top-level events in the application.
```
[TODO: Determine API for running different workflows]

## Tasks:
- [ ] Create a debug scene(?) that runs a workflow and exits
- [ ] Get arguments in to the debug scene
- [ ] Get profile output into a file

## Comments:
	# Workflow-runner design

The first question is how to implement the core workflow-runner of batch mode. An ideal workflow-runner would be able to run the same code paths as the real application, up to differences that don't have any significant effect on performance; it would also distinguish time spent waiting for the frontend to work, vs time spent waiting for the backend.

## Present debug-scene mechanisms are unsuitable

We have talked about using the debug scene mechanism. The IDE has two types of debug scenes:
- `lib/rust/ensogl` debug scenes
- `app/gui/view` debug scenes

Neither of these mechanism is inclusive enough to produce accurate timings: They are render- and view- level (respectively), and don't use the real controllers. Our profiling data shows that some significant work is done in the controllers (especially `controller::graph::Graph::new`); or initiated from `presenters` (`presenter::graph::Graph::init`), whose behavior is closely entwined with controller operation.

## A "mode" for the main entry point would be simple and effective

We could produce accurate timings without too much work by implementing a mode for the main app. The resulting data would be accurate because we'd be timing the real code, and the implementation would not be too difficult because the mode would need trigger only some small deviations from usual behavior:
- [Ideally, disable real mouse/keyboard inputs to prevent accidental interference; this is not essential if it turns out to be complicated to implement.]
- At some specific time after normal startup has completed (unless the workflow to be measured is startup time itself), initiate a workflow-specific series of artificial events simulating an interaction.
- When the series of events completes, dump a profile and exit.

[It may be useful to support use of mock language server / project managers to enable measurement of isolated frontend work time to complete faster and more consistently, but that is not essential in the initial implementation.]

The downside of this approach is that it mixes code that exists only for development purposes in with the main application code. However performance, code complexity, and code size impacts should be minimal because as described above, little deviation from normal behavior should be needed. (Keziah Wesley - Apr 4, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for today (2022-04-04):

**Progress:** Implementing batch mode. Started on the core workflow-running functionality. It should be finished by 2022-04-07.

**Next Day:** Next day I will be working on the [##181775808 task](https://www.pivotaltracker.com/story/show/181775808). Finish the workflow-running functionality. (Enso Bot - Apr 5, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for today (2022-04-05):

**Progress:** Implementing batch mode arguments and profile-saving. It should be finished by 2022-04-07.

**Next Day:** Next day I will be working on the [##181775808 task](https://www.pivotaltracker.com/story/show/181775808). Define some basic debug-workflows. (Enso Bot - Apr 5, 2022)
<hr />
**Keziah Wesley** reports a new **🔴 DELAY** for today (2022-04-26):

**Summary:** There is **20 days** delay in implementation of the [Enso IDE developers should be able to profile defined workflows with a batch mode (#181775808) task](https://www.pivotaltracker.com/story/show/181775808).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** Backend data collection pushed batch mode to the back burner for a while (Enso Bot - Apr 27, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for yesterday (2022-04-25):

**Progress:** Finished implementing data integration/format changes. Started designing the profiling workflow API (the remaining component of batch mode). It should be finished by 2022-04-27.

**Next Day:** Next day I will be working on the [##181775808 task](https://www.pivotaltracker.com/story/show/181775808). Implementing profiling workflows (Enso Bot - Apr 27, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for today (2022-04-26):

**Progress:** Implementing profiling workflows. It should be finished by 2022-04-27.

**Next Day:** Next day I will be working on the [##181775808 task](https://www.pivotaltracker.com/story/show/181775808). Finish workflows (Enso Bot - Apr 27, 2022)
<hr />
**Keziah Wesley** reports a new **🔴 DELAY** for today (2022-04-27):

**Summary:** There is **1 day** delay in implementation of the [Enso IDE developers should be able to profile defined workflows with a batch mode (#181775808) task](https://www.pivotaltracker.com/story/show/181775808).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** Mis-entered estimated completion date. (Enso Bot - Apr 27, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for today (2022-04-27):

**Progress:** Functionality is working. Needs some details addressed. It should be finished by 2022-04-28.

**Next Day:** Next day I will be working on the [##181775808 task](https://www.pivotaltracker.com/story/show/181775808). Clean up implementation and PR. (Enso Bot - Apr 27, 2022)
<hr />
**Keziah Wesley** reports a new **🔴 DELAY** for today (2022-04-29):

**Summary:** There is **1 day** delay in implementation of the [Enso IDE developers should be able to profile defined workflows with a batch mode (#181775808) task](https://www.pivotaltracker.com/story/show/181775808).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** Underestimated complexity of making use of electron events. (Enso Bot - Apr 30, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for yesterday (2022-04-28):

**Progress:** Spent some time on an extra feature I thought would be a straightforward application of the new functionality, but ended up struggling with electron APIs. It should be finished by 2022-04-29.

**Next Day:** Next day I will be working on the [##181775808 task](https://www.pivotaltracker.com/story/show/181775808). Clean up implementation and PR. (Enso Bot - Apr 30, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for today (2022-04-29):

**Progress:** Implemented the remaining details; batch-mode PR is ready, though blocked by the format changes PR. It should be finished by 2022-04-29.

**Next Day:** Next day I will be working on the [##181775808 task](https://www.pivotaltracker.com/story/show/181775808). TBD after meeting. (Enso Bot - Apr 30, 2022)
<hr />
**Keziah Wesley** reports a new **🔴 DELAY** for yesterday (2022-05-02):

**Summary:** There is **4 days** delay in implementation of the [Enso IDE developers should be able to profile defined workflows with a batch mode (#181775808) task](https://www.pivotaltracker.com/story/show/181775808).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** User friendly interface needed more details (and Electron APIs) than expected (Enso Bot - May 4, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for today (2022-05-03):

**Progress:** Finished PR. Also merged new profiling format. It should be finished by 2022-05-03.

**Next Day:** Next day I will be working on the [##181775808 task](https://www.pivotaltracker.com/story/show/181775808). Define some profilable workflows. (Enso Bot - May 4, 2022)
<hr />
**Keziah Wesley** reports a new **🔴 DELAY** for yesterday (2022-05-04):

**Summary:** There is **3 days** delay in implementation of the [Enso IDE developers should be able to profile defined workflows with a batch mode (#181775808) task](https://www.pivotaltracker.com/story/show/181775808).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** Some refactoring needed (Enso Bot - May 6, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for yesterday (2022-05-04):

**Progress:** Implementing review. Designing a panic hook solution that can be PR'd upstream. It should be finished by 2022-05-06.

**Next Day:** Next day I will be working on the [##181775808 task](https://www.pivotaltracker.com/story/show/181775808). Implementing review. (Enso Bot - May 6, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for today (2022-05-05):

**Progress:** Implementing rest of review. It should be finished by 2022-05-06.

**Next Day:** Next day I will be working on the [##181775808 task](https://www.pivotaltracker.com/story/show/181775808). Finish last fixes to docs / small macro change; submit `console_error_panic_hook` changes as upstream PR. Implement collapse-nodes and add-and-edit-node workflows to have the script collecting real data before next meeting. (Enso Bot - May 6, 2022)
<hr />
**Keziah Wesley** reports a new **STANDUP** for the last Friday (2022-05-06):

**Progress:** Finished last fixes to docs / small macro change; submitted console_error_panic_hook changes as upstream PR. Debugged some tooling issues that come up while investigating possible workflow implementations. It should be finished by 2022-05-06.

**Next Day:** Next day I will be working on the [##181775808 task](https://www.pivotaltracker.com/story/show/181775808). TBD after meeting. (Enso Bot - May 9, 2022)
<hr />
	Commit by Kaz Wesley
https://github.com/enso-org/enso/commit/0e904b225664e23d28fb6b1806ba4cef6f15f2a1
enso

Profiling batch mode (#3428)

Implement a command that launches the application, runs a series of steps (a "workflow"), writes a profile to a file, and exits.

See: [#181775808](https://www.pivotaltracker.com/story/show/181775808)

# Important Notes
- The command to capture run and profile is used like: `./run profile --workflow=new_project --save-profile=out.json`. Defining some more workflows (collapse nodes, create node and edit value) comes next; they are implemented with the same infrastructure as the integration-tests.
- The `--save-profile` option can also be used when profiling interactively; when the option is provided, capturing a profile with the hotkey will write a file instead of dumping the data to the devtools console.
- If the IDE panics, the error message is now printed to the console that invoked the process, as well as the devtools console. (If a batch workflow fails, this allows us to see why.)
- New functionality (writing profile files, quitting on command, logging to console) relies on Electron APIs. These APIs are implemented in `index.js`, bridged to the render process in `preload.js`, and wrapped for use in Rust in a `debug_api` crate. (Wojciech Daniło - May 10, 2022)
<hr />
