### ISSUE TITLE
Enso Parser 2.0

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#435]
### Summary
Due to the current parser being severely deficient for the needs of both the Engine and IDE teams, we're embarking on the creation of a new version of the parser from scratch in Rust. It will support:

- An integrated macro system that perserves operator precedence.
- Low-level tokenised parsing.
- Extremely high performance.
- A high-level AST that identifies the constructs in the _surface language_, and can be used by both the IDE and Engine teams.
- A wrapper in scala that handles automated generation of scala classes via JNI, without the need for serialisation and deserialisation.

### Value
The new parser implementation will provide significantly increased performance, and also compile directly for rust, avoiding one of the major problems that the IDE has with the current ScalaJS parser.

### Specification
Each of these steps should land on master without causing any breakage.

- [x] Set up the repository and CI to support the development of the new parser.
- [x] Extract the prelude from the IDE repository (#938).
- [x] Understand `flexer` (#939), and add more tests (#981).
- [x] Automate the generation of this rust code at build time (#942). 
- [x] Design and implement the `Reader` abstraction (#984). 
- [x] Design the `flexer` code generation phase (#940).
- [x] Generate code from the flexer DFA (#943).
- [x] Write the enso lexer (#944).
- [x] Benchmark the Enso lexer (#985).
- [ ] Macro system part 1 (#1265).
- [ ] Infer operator associativity (#1103).
- [ ] Implement operator precedence handling (#1104).

There is also the task of integrating the Rust code with the existing JVM-hosted runtime:

- [x] Create a stub AST for experiments (#1003). 
- [x] Generate Scala classes from the Rust AST (#1004). 
- [x] Automate this generation as part of the SBT build (#1005). 
- [x] Stub out the JNI parser interface (#1006).
- [ ] Automate generation of the JNI bindings (#1049).
- [ ] Instantiate the Scala AST from the Rust AST (#1007).
- [ ] Define the true JNI parser interface (#1008).

### Acceptance Criteria & Test Cases

- We have a new parser written in rust.
- It supports outputting an AST that represents the _high-level_ syntax of Enso.
- The new parser is very performant, as shown by benchmarks.

**Comment by kustosz** [comment]
There's a slight issue with the current parser parser and application operators and lambdas, keep it in mind when designing the new parser. The issue is in applying standard rules to `->`. `map [1, 2, 3] $ x -> x + 1` should parenthesise as `map [1, 2, 3] $ (x -> x + 1)`, but `x -> foo $ x + 1` should parenthesise as `x -> (foo $ x + 1)`, which suggests that `->` should have different precedence on it's two sides

**Comment by kustosz** [comment]
Also currently the associativity system is deeply broken (or I'm not understanding it at all). It goes for the looks like an arrow thingy logic, which I don't mind, but I think it's implemented wrong? It thinks `<|` (the semantic equivalent of haskell's `$`) is left-assoc, which is clearly wrong (because I want `foo <| bar <| baz` to be `foo <| (bar <| baz)`. So this should be right. By symmetry `|>` should be left-assoc. But `->` must be right-assoc.
@wdanilo agrees that the issue above is real and `->` should be a special case

**Comment by kuniss** [comment]
For the JNI part -- take a look at [JNA](https://github.com/java-native-access/jna) . It may make the implementation easier.
We had good experiences integrating our C libraries into our Java  code base with it.
Not sure, how well this works with Scala, but [this article](https://www.sderosiaux.com/articles/2016/08/03/jna-java-native-access-enjoy-the-native-functions/) suggests it works...

For volatile APIs we have used jenerator (mentioned on the JNA github page) to generate Java interfaces avoiding manual code changes.

**Comment by iamrecursion** [comment]
Thanks for the pointer @kuniss! @Josef-Vonasek, do you think this can help with part of your current stuff?

**Comment by iamrecursion** [comment]
See #1521.
