### ISSUE TITLE
Enso Beta Compiler Improvements

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#436]
### Summary
With the parser improved dramatically, it's time to return to improving the compiler and the syntactic support alongside it. 

### Value
The compiler can better support the full-blooded vision of Enso, the language.

### Specification
Each of the following steps should land on master with the compiler in a working state. 

- [ ] Handle access modifiers properly (#452).
- [ ] Handle pattern matching function definitions (#456). 
- [ ] Handle naming properly (#457).
- [ ] Handle cyclic imports (#449). 
- [ ] Remove the need for explicit `.call` (#473).
- [ ] Handle assignment modes properly (#458). 
- [ ] Handle reserved names properly (#462). 
- [ ] Handle operator `.` properly (#463). 
- [ ] Handle suspended blocks properly (#455).
- [ ] Runtime support for warnings (#475).
- [ ] Fix syntax-related crashes (#448).

### Acceptance Criteria & Test Cases

- The above-listed specification points have been completed and have all landed on master.
- They are accompanied by rigorous tests and benchmarks to ensure that there are no functionality regressions and that performance is acceptable.
