### ISSUE TITLE
Position Manager for Incremental (not as) Simple Edits

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4387]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/182412796).
<hr />

### Why

**As Enso user**
**I want quick IDE updates when performing even more complicated edits **
**So that insertion, removal of text literals are supported **

### Acceptance Criteria

```gherkin
Scenario: 
Given program with a number `1`
When changing that number to `1000`
Then such a change is treated as a simple edit and handled properly without reparsing full source
```

**Notes:**

#182323784 successfully demonstrated there is a value in recognizing so called _simple edits_ and handling them more effectively without full re-parsing.

The aim of this story is to productize this behavior. Primarily make it work for additions/removal of characters as changing number of digits is a common operation when moving a _slider_.

## Tasks:
- [X] Update test to closely represent the **acceptance criteria**
- [X] Implement PositionManager
- [X] Make sure `Source` behind the Truffle `Node` can be replaced
- [X] Remember result of previous searches for faster subsequent change
- [X] Support other Literal than Number: Text
- [X] Dispose the PatchedModuleValues when full reparse happens
- [X] Properly hook with parser for updated literal values
- [X] Fix failures in `RuntimeVisualisationsTest` & co.

## Blockers:
[#182451420](https://www.pivotaltracker.com/story/show/#182451420) resolved

## Comments:
**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2022-06-08):

**Progress:** Implementing improvements from previous planning with Wojciech and Marcin: Don't iterate nodes that are clearly "off". Initial implementation of "position manager" can handle 1 -> 1000 change as a "simple edit". Meetings & discussions. It should be finished by 2022-06-15.

**Next Day:** Polishing "position manager" code. (Enso Bot - Jun 9, 2022)
<hr />
**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2022-06-09):

**Progress:** Working on PR-3508: Edward suggested [Fingertree data structure](https://en.wikipedia.org/wiki/Finger_tree) for position manager... learning. Expanding `IncrementalUpdatesTest` to test also changes in `Text` literal. Implementing text literal updates: https://github.com/enso-org/enso/pull/3508/commits/6797f59c82ecf29b71b71ce150229c4be52c5195; Discussions, reviews of PR-3509 - lead to investigation of our `EpbLanguage` simplification: https://www.pivotaltracker.com/n/projects/2539304/stories/182435117 It should be finished by 2022-06-15.

**Next Day:** Get review on _incremental updates_ PR-3508 to polish it for production (Enso Bot - Jun 10, 2022)
<hr />
	I've just bisected the failures in `RuntimeVisualizationsTest` and the first failing commit is: https://github.com/enso-org/enso/pull/3508/commits/31648adb39548983b077f4bb0d0fe2ae3fd5fb9a - if I apply following diff to it, the `RuntimeVisualizationsTest` starts to work:
```
diff --git a/engine/runtime/src/main/java/org/enso/interpreter/node/expression/literal/IntegerLiteralNode.java b/engine/runtime/src/main/java/org/enso/interpreter/node/expression/literal/IntegerLiteralNode.java
index dbf69d68d..0c7707cec 100644
--- a/engine/runtime/src/main/java/org/enso/interpreter/node/expression/literal/IntegerLiteralNode.java
+++ b/engine/runtime/src/main/java/org/enso/interpreter/node/expression/literal/IntegerLiteralNode.java
@@ -7,7 +7,7 @@ import org.enso.interpreter.runtime.tag.Patchable;
 
 /** A representation of integer literals in Enso. */
 @NodeInfo(shortName = "IntegerLiteral")
-public final class IntegerLiteralNode extends ExpressionNode implements Patchable {
+public final class IntegerLiteralNode extends ExpressionNode {
   private final long value;
 
   private IntegerLiteralNode(long value) {
@@ -35,7 +35,6 @@ public final class IntegerLiteralNode extends ExpressionNode implements Patchabl
     return this.value;
   }
 
-  @Override
   public Object parsePatch(String text) {
     try {
       return Long.valueOf(text);
@@ -44,8 +43,8 @@ public final class IntegerLiteralNode extends ExpressionNode implements Patchabl
     }
   }
 
-  @Override
-  public boolean hasTag(Class<? extends com.oracle.truffle.api.instrumentation.Tag> tag) {
-    return tag == Patchable.Tag.class || super.hasTag(tag);
-  }
+//  @Override
+//  public boolean hasTag(Class<? extends com.oracle.truffle.api.instrumentation.Tag> tag) {
+//    return tag == Patchable.Tag.class || super.hasTag(tag);
+//  }
 }
```
time to investigate why! (jaroslavtulach - Jun 10, 2022)
<hr />
**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2022-06-10):

**Progress:** Affected by internet outage. Review of Text.write: https://github.com/enso-org/enso/pull/3518#discussion_r894140877; Polishing Incremental Small edits according to reviews; Debugging & bisecting failing `RuntimeVisualisationsTest`; Dmitry helped me realize that `IdExecutionInstrument` does not intercept the program execution properly. It should be finished by 2022-06-15.

**Next Day:** Fix `RuntimeVisualisationsTest` (Enso Bot - Jun 11, 2022)
<hr />
**Jaroslav Tulach** reports a new **STANDUP** for today (2022-06-12):

**Progress:** Debugging `RuntimeVisualisationsTest`; found limitations of Truffle; Sent note to Truffle maintainers: https://graalvm.slack.com/archives/CNQSB2DHD/p1655021883246019; got one of the `RuntimeVisualisationsTest` working: https://github.com/enso-org/enso/pull/3508/commits/f37250c896fbc2b143cebf4a61fe982fc37d03d6; two other are still failing - debugging: something broken in `truffleCodegenInline` It should be finished by 2022-06-15.

**Next Day:** Continue debugging and fixing RuntimeVisualisationsTest (Enso Bot - Jun 12, 2022)
<hr />
	Reported two related issues: 
- #182451341 - `isTopFrame` is slow
- #182451420 - filtering shall be done on `Node` tags, not sections (jaroslavtulach - Jun 13, 2022)
<hr />
**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2022-06-13):

**Progress:** Debugging and fixing tests for incremental updates: https://github.com/enso-org/enso/pull/3508/commits/eb865ea1e749a464b1c26e0c8d0a791117868268; reported GraalVM issue to OracleLabs guys: https://github.com/oracle/graal/issues/4643; another test fixed: https://github.com/enso-org/enso/pull/3508/commits/b85e4558c62f53a989916aa451aa5998c36163f3; reported two performance stories into the backlog: 182451341 and 182451420 It should be finished by 2022-06-15.

**Next Day:** Focus on improving re-parsing; co-operate with Dmitry on 182451420 as it seems to be a blocker (Enso Bot - Jun 14, 2022)
<hr />
Looks like the `RuntimeInstrumentTest` is [failing on instrumentation of lambdas](https://www.pivotaltracker.com/story/show/182451420/comments/231747032) - we may need proper solution with tagging nodes as described in #182451420  as the current solution with `IndexRange` is [too inclusive](https://github.com/enso-org/enso/pull/3508/files#r896353045) - e.g. it includes also lambdas. (jaroslavtulach - Jun 14, 2022)
<hr />
Remember results of previous searches - **done** as of https://github.com/enso-org/enso/pull/3508/commits/c15657082fb39fd3bff35613f6ed6592933c8a2a (jaroslavtulach - Jun 14, 2022)
<hr />
**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2022-06-14):

**Progress:** properly parsing changed literals: https://github.com/enso-org/enso/pull/3508/commits/c80567afc22fc2c0df8435d25efdb16814264492; talking to OracleLabs team: https://github.com/oracle/graal/issues/4643#issuecomment-1155146681; multiple edits in a row test & lot of debugging; subsequent edits search already modified nodes first: https://github.com/enso-org/enso/pull/3508/commits/c15657082fb39fd3bff35613f6ed6592933c8a2a It should be finished by 2022-06-15.

**Next Day:** Focus on unblocking #182412796 by trying to fix #182451420 (Enso Bot - Jun 15, 2022)
<hr />
**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2022-06-15):

**Progress:** Removed `LocationFilter` and now the PR is green, ready to be integrated: https://github.com/enso-org/enso/pull/3508 It should be finished by 2022-06-15.

**Next Day:** Merge the PR; track it as #182451420; plan the next improvements (Enso Bot - Jun 16, 2022)
<hr />
https://github.com/enso-org/enso/pull/3508 has been merged, so this task is finished. (jaroslavtulach - Jun 16, 2022)
<hr />
