### ISSUE TITLE
Remove GraalVM Logging & Caching Instrument Hack by having Generic LiteralNode

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4392]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/182485854).
<hr />

While working #182412796 we found out problem in communication between the two instruments we have and [reported that to GraalVM team](https://github.com/oracle/graal/issues/4643). There is no simple solution to overcome this GraalVM limitation. #182412796 solved the problem by global "map", but we need better solution. Let's implement it as part of this task!

### Resources

There are few `*LiteralNode` classes in engine. Let's replace them by single one. It shall not affect peak performance. Then, instead of using _caching instrument/listener_ - directly `Node.replace` the `LiteralNode` by `PatchedLiteralNode` in the AST - modify the value directly in the `PatchedLiteralNode`.

## Tasks:
- [X] Unify all LiteralNode classes into one
- [X] Benchmark the peak performance; avoid regression
- [X] Create PatchedLiteralNode
- [X] Remove _caching instrument_ in `PatchedModuleValues`

## Blockers:
[#182412796](https://www.pivotaltracker.com/story/show/#182412796) resolved

## Comments:
**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2022-06-21):

**Progress:** _Single_ `LiteralNode` has been integrated: https://github.com/enso-org/enso/pull/3536; Analyzing and discussing `sbt` issue with `javafmt`: https://discord.com/channels/401396655599124480/988485281260916817/988802778296115200; debugging Enso launcher to place `--dumpGraphs` option. It should be finished by 2022-06-21.

**Next Day:** Finish `--dumpGraphs` option for Enso4IGV. (Enso Bot - Jun 22, 2022)
<hr />
