### ISSUE TITLE
implement by-type pattern matches

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4597]
This task is automatically imported from the old Task Issue Board and it was originally created by Marcin Kostrzewa.
Original issue is [here](https://www.pivotaltracker.com/story/show/183188846).
<hr />

This task covers a change and standardization of pattern matching on values by their type. 
1. Make pattern matching with the following syntaxes: 
```
case foo of
    v: My_Type ->
    v: My_Type _ _ _ ->
```
work by inspecting the type of `foo` (as defined by `TypesLibrary`). Notice how the `_` may be skipped in type.
2. Remove the current special cases for by-type matches (for time, date, and the like) and fix the stdlib to use the new syntax
3. Make the special cases _just_ match on the type value, not the instances (like the existing type branch):
```
case Vector of 
    Vector -> IO.println "foo"
    _ -> IO.println "bar"
```
should print "foo" and
```
case [1,2,3] of 
    Vector -> IO.println "foo"
    _ -> IO.println "bar"
```
should print "bar"
Same for all special cases we have (for date, text, numbers, etc.)

Discord [discussion link](https://discord.com/channels/401396655599124480/1014518926421545101/1016709245925867520).

## Tasks:
- [X] Remove `Array.Array` & co. special support in ArrayBranchNode
- [X] Make sure type pattern matching works on _date_, _time_, _array_, _vector_ builtin types
- [X] Use InteropLibrary.getMetaObject to make matching work on any type
- [X] Check it works on Java exception instances - `ex : IllegalStateException`

## Blockers:
[#183219169](https://www.pivotaltracker.com/story/show/#183219169) resolved
[#183188858](https://www.pivotaltracker.com/story/show/#183188858) resolved

## Comments:
**Hubert Plociniczak** reports a new **STANDUP** for yesterday (2022-09-22):

**Progress:** Rewrote tests for type_of, started looking at type pattern matching and making the (old) parser accept the requested syntax. It should be finished by 2022-09-29.

**Next Day:** Next day I will be working on the [##183188846 task](https://www.pivotaltracker.com/story/show/183188846). Continue work on type pattern matching. Might need to park it for some time until statics are done. (Enso Bot - Sep 23, 2022)
<hr />
**Hubert Plociniczak** reports a new **STANDUP** for the last Friday (2022-09-23):

**Progress:** Continued work on by-type pattern matching. (old) Parser now accepts new syntax, now working on the actual checks. Rewrote tests for `type_of` to use `is_same_object` (can't use `==` because of dispatch feature that will be implemented in statics). It should be finished by 2022-09-29.

**Next Day:** Next day I will be working on the [##183188846 task](https://www.pivotaltracker.com/story/show/183188846). Continue work on type pattern matching. (Enso Bot - Sep 26, 2022)
<hr />
**Hubert Plociniczak** reports a new **STANDUP** for yesterday (2022-09-26):

**Progress:** Continued work on by-type pattern matching. Got some basic example working. Still spent some time on addressing remaining comments for `type_of` but it got finally merged. It should be finished by 2022-09-29.

**Next Day:** Next day I will be working on the [##183188846 task](https://www.pivotaltracker.com/story/show/183188846). Continue work on type pattern matching. (Enso Bot - Sep 27, 2022)
<hr />
**Hubert Plociniczak** reports a new **STANDUP** for today (2022-09-27):

**Progress:** More tweaks to by-type pattern matching. Started removing special branch nodes (vector, file, date/time are gone) and tests pass. Draft PR is up. It should be finished by 2022-09-29.

**Next Day:** Next day I will be working on the [##183188846 task](https://www.pivotaltracker.com/story/show/183188846). Removing remaining special branch nodes. (Enso Bot - Sep 27, 2022)
<hr />
**Hubert Plociniczak** reports a new **STANDUP** for yesterday (2022-09-28):

**Progress:** Continued journey into replacing pattern matching on constructors with types. Polyglot Arrays proved to be a bit stubborn, especially because of a different type representation between languages. Draft PR reflects the solution. It should be finished by 2022-09-29.

**Next Day:** Next day I will be working on the [##183188846 task](https://www.pivotaltracker.com/story/show/183188846). Continue replacing other special branch nodes and make the PR ready for review. (Enso Bot - Sep 29, 2022)
<hr />
**Hubert Plociniczak** reports a new **STANDUP** for yesterday (2022-09-29):

**Progress:** Finished translating type pattern matching for text and numbers, which was problematic for polyglot values (different languages were returning inconsistent semantics in Truffle). Should be almost ready for review after more testing, which will delay it by a day. It should be finished by 2022-09-29.

**Next Day:** Next day I will be working on the [##183188846 task](https://www.pivotaltracker.com/story/show/183188846). Add more unit tests to type pattern matching and move on to reported import bug. (Enso Bot - Sep 30, 2022)
<hr />
**Hubert Plociniczak** reports a new **🔴 DELAY** for the last Friday (2022-09-30):

**Summary:** There is **4 days** delay in implementation of the [implement by-type pattern matches (#183188846) task](https://www.pivotaltracker.com/story/show/183188846).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** Realized that we also want to pattern match on types in a nested position. Plus address PR review (Enso Bot - Oct 3, 2022)
<hr />
**Hubert Plociniczak** reports a new **STANDUP** for the last Friday (2022-09-30):

**Progress:** More testing. Added support for pattern matching on types in a nested position (initially wasn't planning on supporting it but well). It should be finished by 2022-10-03.

**Next Day:** Next day I will be working on the [##183415837 task](https://www.pivotaltracker.com/story/show/183415837). Address PR review and move on to the next ticket. (Enso Bot - Oct 3, 2022)
<hr />
**Hubert Plociniczak** reports a new **STANDUP** for yesterday (2022-10-03):

**Progress:** Even more testing. Fixed a bug in type patterns in alias analysis, added benchmarks that revealed some interesting insights. Ready for merge. It should be finished by 2022-10-03.

**Next Day:** Next day I will be working on the [##183415837 task](https://www.pivotaltracker.com/story/show/183415837). Investigate importing issues (Enso Bot - Oct 4, 2022)
<hr />
Created a follow up on the first task in https://www.pivotaltracker.com/story/show/183463844 (Hubert Plociniczak - Oct 5, 2022)
<hr />
