### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4606]
This task is automatically imported from the old Task Issue Board and it was originally created by Keziah Wesley.
Original issue is [here](https://www.pivotaltracker.com/story/show/183443355).
<hr />

They can be inline or apply to the following item in the block, so they need special handling early in parsing. I'll probably add them to line-segmenting to ensure that anywhere we build blocks, we handle these.

## Tasks:
- [X] Interpret a `@Foo` nospace group as an `Annotated`
- [X] Inline annotations: In `resolve_operator_precedence`, treat a bodyless `Annotated` as a unary operator that consumes its operand to build a complete `Annotated`.
- [X] Multiline annotations: When building a block, if a line consists of a bodyless `Annotated`, it should consume the next non-empty line.

## Comments:
**Keziah Wesley** reports a new **STANDUP** for yesterday (2022-10-06):

**Progress:** Implemented most of Annotations. It should be finished by 2022-10-07.

**Next Day:** Next day I will be working on the [#183417662 task](https://www.pivotaltracker.com/story/show/183417662). Finish Annotations; work on Doc Comments (Enso Bot - Oct 8, 2022)
<hr />
