### ISSUE TITLE
Add `Is_Empty`, `Not_Empty`, `Like` and `Not_Like` to `Filter_Condition`

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4621]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/183389890).
<hr />

- Add `Is_Empty` and `Not_Empty` to `Filter_Condition`:

```python
    ## Is equal to "" or Nothing (Text only)?
    Is_Empty

    ## Is not equal to "" and Nothing (Text only)?
    Not_Empty
```

- Add `Like` and `Not_Like` to `Filter_Condition`:

```python
    ## Does the value match the SQL pattern (Text only)?
    Like pattern:Text

    ## Does the value not match the SQL pattern (Text only)?
    Not_Like pattern:Text
```

- Add support for filtering on this to `Table`, `Vector`, `List` and `Range` (as implemented).
- Add BETWEEN as a vector op on Column.

```
## PRIVATE
   Convert a SQL like to a Regular Expression
is_like Text -> (Text -> Boolean)
is_like sql_like =
    sql_regex = "^" + (sql_like.replace "\" "\\" . replace "." "\" . replace "_" "." . replace "%" ".*?") + "$"
    output text = text.matches sql_regex
    output
```

- If applied on an invalid value type should result in an `Invalid_Value_Type` error.

## Tasks:
- [X] Empty in Base
- [X] Like in Base
- [X] Between
- [X] Empty in Table
- [X] Like in Table
- [X] Empty, Like in Database
- [X] Tests for Empty and Like in Table
- [X] Between in Database
- [X] Avoid preprocessing the Like pattern in every iteration for in-memory backend

## Comments:
**Radosław Waśko** reports a new **STANDUP** for yesterday (2022-10-06):

**Progress:** Got the Filter_condition on base types PR ready for merging. Next task: Extended Filter_Condition with Is_Empty and Like (and Not_Empty and Not_Like), for both In-memory and Database; amended Database Between to use SQL `BETWEEN` instead of `<= AND >=`. It should be finished by 2022-10-07.

**Next Day:** Next day I will be working on the [#183389945 task](https://www.pivotaltracker.com/story/show/183389945). Add one optimization to computation of vectorized Like in the in-memory backend (currently due to our architecture limitations the SQL->Regex conversion is recomputed for each cell which is wasteful). Get the PR reviewed and merged, start work on the next task: extending Filter_Condition with Is_In. (Enso Bot - Oct 7, 2022)
<hr />
