### ISSUE TITLE
Add support for `Is_In` and `Not_In` to `Filter_Condition`

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4623]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/183389945).
<hr />

```python
    ## Is the value contained in `values`?
    Is_In values:Vector

    ## Is the value not contained in `values`?
    Not_In values:Vector
```

## Tasks:
- [X] Add Is_In to Base
- [ ] Add Is_In to Table
- [ ] Add Is_In to Database

## Comments:
**Radosław Waśko** reports a new **STANDUP** for the provided date (2022-10-07):

**Progress:** FInished the optimization for the Like operation, PR is waiting for review. Started work for Is_In - implemented it for Base types and was discussing how to approach it in the Table to be efficient while we do not have good hashing support, analysing how to approach this. It should be finished by 2022-10-11.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/183389945). Implementing the Is_In operation for Table. (Enso Bot - Oct 10, 2022)
<hr />
**Radosław Waśko** reports a new **STANDUP** for yesterday (2022-10-10):

**Progress:** Finally got the other pending PR merged (Like, Empty). Implemented the Enso fallback for Table Is_In and added Is_In tests. Started work on the optimized implementation for the builtin types but there is still some stuff to figure out how to approach it. It should be finished by 2022-10-11.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/183389945). Continue implementing the specialized version for in-memory backend, see if I can get a PR ready. (Enso Bot - Oct 11, 2022)
<hr />
**Radosław Waśko** reports a new **🔴 DELAY** for yesterday (2022-10-11):

**Summary:** There is **2 days** delay in implementation of the [Add support for `Is_In` and `Not_In` to `Filter_Condition` (#183389945) task](https://www.pivotaltracker.com/story/show/183389945).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** I underestimated the task at the beginning, especially incuding that I wanted to handle the last parts of https://www.pivotaltracker.com/story/show/183390314 along the way (as I've been doing it in parts with other filter tasks). Also I didn't count the time needed for reviews and fixing the build after a pull (I had some issues with Rust installation).

**Possible solutions:** Make the initial estimates a bit more conservative (although I feel that if I do the larger estimate, I have less pressure to finish the task quicker (even though I want to :)) - so I tend to do a riskier estimate to motivate myself - but then I don't always manage to reach the more ambitious estimate and need to report the delay). (Enso Bot - Oct 12, 2022)
<hr />
**Radosław Waśko** reports a new **STANDUP** for yesterday (2022-10-11):

**Progress:** Implemented the vectorized Is_In in Table (various variants for builtin types). It should be finished by 2022-10-13.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/183389945). Add some missing docs, implement Is_In for Database, prepare the PR for review. (Enso Bot - Oct 12, 2022)
<hr />
**Radosław Waśko** reports a new **STANDUP** for today (2022-10-12):

**Progress:** Added a few more tests, implemented Is_In for Database and prepared the PR for review. Started work on the next task - new API for filter_blank_rows. Initial implementation with blanks is done. It should be finished by 2022-10-13.

**Next Day:** Next day I will be working on the [#183390394 task](https://www.pivotaltracker.com/story/show/183390394). Get the other PR merged, implement also handling NaNs in the missing filter. Add tests for the new cases. (Enso Bot - Oct 12, 2022)
<hr />
**Radosław Waśko** reports a new **🔴 DELAY** for yesterday (2022-10-13):

**Summary:** There is **1 day** delay in implementation of the [Add support for `Is_In` and `Not_In` to `Filter_Condition` (#183389945) task](https://www.pivotaltracker.com/story/show/183389945).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** Found a BoolStorage bug introduced ages ago that went under our radar and surfaced during this PR, had to investigate and fix it. Attemtping a few more refactors after CR that took a bit more than I'd expect. (Enso Bot - Oct 14, 2022)
<hr />
**Radosław Waśko** reports a new **STANDUP** for yesterday (2022-10-13):

**Progress:** Investigating and fixing a bug in BoolStorage, adding more tests to more carefully ensure we don't regress. Applying review suggestions. Implemented a much more optimized version of Is_In for BoolStorage (for 4 cases out of 8 it works in O(1), in other cases it uses bitwise operations so it performs 64 bits at once instead of iterating bit-by-bit and using expensive bitshfits at each step) - did not measure the speedup as it's not currently crucial, but it should be significant. It should be finished by 2022-10-14.

**Next Day:** Next day I will be working on the [#183390394 task](https://www.pivotaltracker.com/story/show/183390394). Finish an experiment of generifying storages to make the Java code "more typed".  Get the PR merged finally. Then go back to fill_blank_rows: implement also handling NaNs in the missing filter. Add tests for the new cases. (Enso Bot - Oct 14, 2022)
<hr />
