### ISSUE TITLE
Undo/Redo

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#464]
### Specification
Undo and redo support should be implemented in Enso. It is important that this will be implemented in a way that is easy and natural to use. For example, after editing code, undo should not remove the last typed character, but the last word or line. Let's call a set of atomic actions that should be reverted in a single undo step, a "step-action". The following "step-actions" should be implemented as part of this epic:

In the text editor, undo/redo should work just as in IntelliJ Idea. In particular:
   - No matter how many letters and spaces you write, undo will undo all of them UNTIL you moved your cursor, created a new line, or performed undo/redo action.
   - Moving cursor is considered a step-action.
   - When a cursor disappears from the screen during undo or redo an action, the text editor should scroll to its new position (all corner cases, like multi cursors, should be handled as in IntelliJ Idea).
   
In the graph editor, the following "step-actions" should be implemented as part of this epic:
   - Selecting a node
   - Moving a node
   - Changing the view (entering/exiting node)
   - Creating a connection
   - Opening / closing visualizations
   - Changing the type of the visualization
   - Editing a node (text rules should apply here).
   - An action performed from visualizations (like deleting a column from within table vis - probably in the future, but worth noting now).

There is at least one interesting corner case to be considered here. One of the highest priority issues in the IDE board is to keep the visualization state (like geo-map pan and zoom) part of project metadata. However, we do not want map panning/zooming to be handled by undo/redo. We need to think of how to handle it.

Also, please note that the whole undo / redo mechanism should work on text or AST snapshots. It means, that every state should be encoded either as code or metadata change. In particular, it means that the visualization state or node selection should become part of the metadata as part of this epic.

### [OLD] Specification
This section needs to be cleaned according to the new Specification.

- [ ] Design undo and redo (#485).
- [ ] Implement the undo functionality (#484).
- [ ] Implement the redo functionality (#483).

### Acceptance Criteria & Test Cases

- We have working undo/redo functionality.
- All changes to the protocol have been recorded in the enso protocol design document.
