### ISSUE TITLE
Investigate why Vector 2x times slower than Array

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4640]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/183249415).
<hr />

[PR-3667](https://github.com/enso-org/enso/pull/3667) introduces [VectorBenchmarks](https://github.com/enso-org/enso/pull/3667/commits/96ad6f4210d9b059dafe83fe2c7db111b0f95c50) and makes sure the `Array` access isn't slower than `Vector` one.

However, now it shows that `Vector` access is twice as slow than `Array`. There is no real reason for that - while it invokes more code, the code is _partially evaluated_ and the difference shall disappear.

Investigate why the `Vector` access is slower and fix or propose a fix.

## Tasks:
- [X] Use IGV to analyze differences between `Vector` and `Array` benchmarks
- [X] Does it make sense to have `unsafe_at` method at all? Can it be replaced with `at`?
- [X] Speed up (or propose) speed up for the `Vector` case

## Comments:
**Hubert Plociniczak** reports a new **STANDUP** for the last Friday (2022-10-14):

**Progress:** Started debugging perf differences between Vector and Array. Turns out a combination of `if` + `thunk` execution might be a killer. It should be finished by 2022-10-18.

**Next Day:** Next day I will be working on the [#183249415 task](https://www.pivotaltracker.com/story/show/183249415). Continue investigation (Enso Bot - Oct 17, 2022)
<hr />
Spent significant time trying to optimize it with no success but here is conclusion on where does the slowdown come from.

When executing VectorBenchmarks one can consistently reproduce this 2x slowdown for Vector. Maybe surprisingly this slowdown stems from the possibility of retrieving elements of a Vector using a negative index:
https://github.com/enso-org/enso/blob/develop/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso#L150
```
actual_index = if index < 0 then self.length + index else index
```

If we don't involve `self.length`, which in the benchmark isn't called at all, then the slowdown is 1.5.x. If the conditional is removed all together then the performance of Vector is roughly the same as Array.
There isn't much information why Graal decides not to inline that particular expression (and it really does not do it), there are also no obvious deoptimizations happening.
Other than a polymorphic split happening for the `ifThenElseNode` node (due to `ConditionProfile`) nothing is really out of ordinary. (Hubert Plociniczak - Oct 18, 2022)
<hr />
To run benchmarks execute:
```
sbt > runtime/benchOnly org.enso.interpreter.bench.benchmarks.semantic.VectorBenchmark
``` (Hubert Plociniczak - Oct 18, 2022)
<hr />
**Hubert Plociniczak** reports a new **STANDUP** for yesterday (2022-10-17):

**Progress:** Still debugging. Having fun with IGV and inlining logs. It should be finished by 2022-10-18.

**Next Day:** Next day I will be working on the [#183249415 task](https://www.pivotaltracker.com/story/show/183249415). Continue investigation (Enso Bot - Oct 18, 2022)
<hr />
**Hubert Plociniczak** reports a new **STANDUP** for today (2022-10-18):

**Progress:** Slowly giving up on forcing Graal to perform the optimization. However found workaround - move conditional check used in `Vector.at` to a builtin method and what we get is the same performance as Array. It should be finished by 2022-10-18.

**Next Day:** Next day I will be working on the [#183249415 task](https://www.pivotaltracker.com/story/show/183249415). Create a PR of the workaround, document findings, add information on how to get inlining logs. (Enso Bot - Oct 18, 2022)
<hr />
**Hubert Plociniczak** reports a new **🔴 DELAY** for yesterday (2022-10-19):

**Summary:** There is **1 day** delay in implementation of the [Investigate why Vector 2x times slower than Array (#183249415) task](https://www.pivotaltracker.com/story/show/183249415).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** Doing some additional QA and adding some documentation. (Enso Bot - Oct 20, 2022)
<hr />
**Hubert Plociniczak** reports a new **STANDUP** for yesterday (2022-10-19):

**Progress:** Cleaning up the PR, making sure graph looks alright. Various meetings. It should be finished by 2022-10-19.

**Next Day:** Next day I will be working on the [#183266964 task](https://www.pivotaltracker.com/story/show/183266964). Pick up next work item. (Enso Bot - Oct 20, 2022)
<hr />
