### ISSUE TITLE
Add missing @TruffleBoundary and verify it in the CI gate

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4659]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/183136313).
<hr />

Work on #182486022 (as recorded in [doc](https://docs.google.com/document/d/1yZmj4y-mOswTUHFzYkV7FM6Vh9P9LLXj-plAW3bVzbI/edit#heading=h.p19u06oiwh9i)) has revealed that there are many places where `@TruffleBoundary` annotation is missing:
- https://github.com/enso-org/enso/pull/3638/commits/8fc7bb446c65f0035b590fd4501fff52f403ecd4
- https://github.com/enso-org/enso/pull/3638/commits/c758d8e20f6b41d85a5b9dac90100bad36e3ae6b
- https://github.com/enso-org/enso/pull/3638/commits/b13540ca329ddc7d45446ac26108204766c61252
- https://github.com/enso-org/enso/pull/3638/commits/a894b6836e041980a70df1d5a960cf8231b8b235
- https://github.com/enso-org/enso/pull/3638/commits/6b37f0161dd2f09228e656942a178e59f67c1584

Missing `@TruffleBoundary` slows down Truffle compilation, makes Truffle generate more code than necessary.

The only way to verify the `@TruffleBoundary` annotations are where needed is to build Enso by Native Image tool - it performs closed world analysis and contains list of _blacklisted methods_ - when one of them is included in the PE code, the `native-image` tool fails.

## Tasks:
- [X] Add missing @TruffleBoundary annotation
- [X] Create buildNativeImage sbt task for for engine-runner
- [X] Include buildNativeImage task in the CI gate
- [X] Print result of main (if not Nothing)

## Comments:
Printing result of main is proposed as https://github.com/enso-org/enso/pull/3696 (jaroslavtulach - Sep 12, 2022)
<hr />
This task may be negatively influenced by GraalVM's [PR-4200](https://github.com/oracle/graal/issues/4200). Should you see `NullPointerException` when analyzing some `sqlite` class, try to avoid processing such class by Native Image. For example by removing the JAR from classpath for now - it is not needed for running the runtime engine anyway. (jaroslavtulach - Sep 13, 2022)
<hr />
**Hubert Plociniczak** reports a new **STANDUP** for yesterday (2022-09-20):

**Progress:** Updated native-image generation PR, required re-running profiling and adding more TruffleBoundary annotations and some fight with sbt to workaround Graal bug. Started addressing some comments for type_of PR, fighting with tests. It should be finished by 2022-09-21.

**Next Day:** Next day I will be working on the [##183136313 task](https://www.pivotaltracker.com/story/show/183136313). Finish tests for type_of, pick up next work item. (Enso Bot - Sep 21, 2022)
<hr />
**Hubert Plociniczak** reports a new **STANDUP** for the last Wednesday (2022-09-21):

**Progress:** More work on native-image generation, runner now accepts arguments from CLI. Tweaks to type_of comparison It should be finished by 2022-09-21.

**Next Day:** Next day I will be working on the [##183136313 task](https://www.pivotaltracker.com/story/show/183136313). Address any review comments for native-image. type_of fun (Enso Bot - Sep 23, 2022)
<hr />
The remaining task is to include `buldNativeImage` task in the CI gate. Adding Michal. (jaroslavtulach - Sep 29, 2022)
<hr />
> The remaining task is to include buldNativeImage task in the CI gate. Adding Michal.

This was delivered as part of https://github.com/enso-org/enso/pull/3743 (Michał Urbańczyk - Oct 27, 2022)
<hr />
	I see following references to `build_native_runner` in the PR-3743:
- https://github.com/enso-org/enso/pull/3743/files#diff-ea60ff5aeb616417435257cd2db1ff269f456af86c54c2f9c46cb7a17f4f63e1R259
- https://github.com/enso-org/enso/pull/3743/files#diff-ea60ff5aeb616417435257cd2db1ff269f456af86c54c2f9c46cb7a17f4f63e1R270
- https://github.com/enso-org/enso/pull/3743/files#diff-ea60ff5aeb616417435257cd2db1ff269f456af86c54c2f9c46cb7a17f4f63e1R411

The 2nd one executes `engine-runner-native/buildNativeImage`. The 3rd one is commented out - e.g. we are building the Native image, but we are not testing whether it can evaluate something. Correct?
 (jaroslavtulach - Oct 31, 2022)
<hr />
