### ISSUE TITLE
Searcher

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#466]
### Summary
The searcher is one of the most important parts of the Enso user experience, providing users with intelligent autcomplete and context-aware suggestions, as well as examples and documentation all in one place. Without it, we severely compromise the IDE's UX, and hence we need to get it implemented. 

### Value
The IDE will be able to support the searcher properly.

### Specification

- [x] Design the searcher (#713).
- [x] Implement the suggestions database (#587).
- [x] Implement the update API for the searcher (#440 ).
- [x] Implement the requests API for the searcher (#439 ).
- [x] Integrate the searcher database with the runtime and the API (#438).

### Acceptance Criteria & Test Cases

- The above specification has been completed.
- The above tasks are ready to be integrated with the IDE.
- The engine protocol specification is up to date with respect to any changes.
