### ISSUE TITLE
Engine reads sensible defaults for functions for IDE to be displayed

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4707]
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/183222597).
<hr />

## Who:

Engine Team

## Why:

**As** an IDE Developer when I open the component browser
**I want **to see visualization of function with provided sensible defaults
**So **that the User will have a suggestion on how the data output might look and what to expect in his workflow.

## AC:

```gherkin
Scenario:
GIVEN I have a newly created project opened in Enso IDE, and select one of 5 components with sensible defaults provided
WHEN I open the component browser, select/hoover one of those components, 
THEN I will be able to see a sample visualization of those sensible default data in the visualization preview panel.
```

## Notes:

This task should check if we can serve the Libs sensible data for functions from Engine side to IDE to be displayed properly. It needs to be checked on first 5 defaults chosen by Libs team. Later on we will check the rest sensible defaults as those will be provided by ongoing task: “Methods in standard library should have sensible defaults where possible”.

## Tasks:
- [X] “Table.select_columns ==> Select the first column by default by name”
- [X] “Text.trim ==> Remove any whitespace from start or end of text"
- [X] "Vector.compute ==> compute the Count of a Vector"
- [X] “Date.add_work_days ==> add a single work days”
- [X] "Table.order_by ==> sort the Table by one or more Column"

## Blockers:
[#182720308](https://www.pivotaltracker.com/story/show/#182720308) resolved

## Comments:
Sub Tasks 2-5 will be provided as soon as Jaems will start work on https://www.pivotaltracker.com/story/show/182720308 (Greg Ociepka - Sep 8, 2022)
<hr />
Added a set of 5 functions with reasonable defaults. (James Dunkerley - Nov 11, 2022)
<hr />
I am verifying the behavior on
```
enso$ git log | head -n1
commit 5a0aad16eb9a74e23915cbd7b1c891b63020c769
```
and I see that `Text.trim` by defaults removes whitespace from both start and end. Here is a visual proof:
 (jaroslavtulach - Nov 22, 2022)
<hr />
I can see that `Vector.compute` really computes the count by default:

 (jaroslavtulach - Nov 22, 2022)
<hr />
`add_work_days` really adds one working day:
 (jaroslavtulach - Nov 22, 2022)
<hr />
`Table.selectcolumns` really selects just the first column. The following example for of all creates a table with columns `B` and `C` and then applies `selectcolumns` without parameters. `B` is selected:
 (jaroslavtulach - Nov 22, 2022)
<hr />
`Table.order_by` reorders an Excel table by first column by default:
 (jaroslavtulach - Nov 22, 2022)
<hr />
**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2022-11-22):

**Progress:** Engine really reads defaults: #183222597; Proposal to rewrite `List` and eliminate _unsafe operations_: https://www.pivotaltracker.com/story/show/183578531/comments/234387800; document about hashing: https://docs.google.com/document/d/10Ee2lJy2LUNfVf4EsToJJmRF2ZVGjPpGE2tNEmC9ruQ; meetings and discussions It should be finished by 2022-11-22.

**Next Day:** Prepare BigInteger PR for integration (Enso Bot - Nov 23, 2022)
<hr />
