### ISSUE TITLE
Upgrade to Graal 22.x

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4714]
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/182845176).
<hr />

We should consider upgrading GraalVM (currently 22.2) to get latest goodies.
Blocked by:
- `FrameSlot` got deprecated and should be removed from our codebase
-  Need to install JS manually since it is no longer part of Graal distro
- Rewrite to [TruffleString](https://github.com/oracle/graal/blob/master/truffle/docs/TruffleStrings.md) - that may be a major ~ few thousand of lines ~ rewrite...

By updating to 22.3 we get an [interop bugfix](https://github.com/oracle/graal/issues/4741) we requested.

## Tasks:
- [X] Rewrite local variable access as `FrameSlot` methods were removed
- [X] Update build scripts as `js` is no longer pre-installed
- [X] Get and test the https://github.com/oracle/graal/issues/4741 interop bugfix
- [X] TruffleLanguage.Env.newContextBuilder() has been deprected - used in `EpbContext`
- [X] Use quick build option (-Ob) in native image dev builds
- [X] Add basic support for `NodeLibrary`

## Comments:
Related #181249401 (Dmitry Bushev - Aug 1, 2022)
<hr />
**Pavel Marek** reports a new **🔴 DELAY** for today (2022-10-05):

**Summary:** There is **1 day** delay in implementation of the [Upgrade to Graal 22.x (#182845176) task](https://www.pivotaltracker.com/story/show/182845176).
It **will cause 1 day delay** for the delivery of this weekly plan.

**Delay Cause:** I needed some more time to properly understand how builtin methods/types work in the context of Enso evaluation, e.g., `==` operator. (Enso Bot - Oct 5, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-10-25):

**Progress:** Resolved problem with clean local build, merged latest develop, trying to understand Enso IR, created simple script for formatting the IR. It should be finished by 2022-10-27. (Enso Bot - Oct 25, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-10-26):

**Progress:** Pair programming session with Jaroslav. Trying to understand where are all the frame slots constructed from the IR. It should be finished by 2022-10-27. (Enso Bot - Oct 26, 2022)
<hr />
**Pavel Marek** reports a new **🔴 DELAY** for today (2022-10-27):

**Summary:** There is **5 days** delay in implementation of the [Upgrade to Graal 22.x (#182845176) task](https://www.pivotaltracker.com/story/show/182845176).
It **will cause 5 days delay** for the delivery of this weekly plan.

I have to manually traverse IR of method's body prior to MethodRootNode allocation. I also have to tweak build script to manually install js, and maybe even to use -Ob option when building native image.

**Delay Cause:** Too many things to be done on this PR. (Enso Bot - Oct 27, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-10-27):

**Progress:** After many debugging attempts, I came to the conclusion, that I cannot simply reuse the logic of traversing the IR to gather all the slot indexes before the corresponding MethodRootNode is created, as it is too tightly couple with Truffle nodes allocation.
  I will have to create a (preferably simple) procedure that traverses IR of method's body and assigns slot indexes for all the local variables before MethodRootNode is created.
  I have already fixed this for method's arguments trivially by replacing some lines of code. It should be finished by 2022-11-01. (Enso Bot - Oct 27, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-10-28):

**Progress:** Write some engine tests for local scope building. Investigating where to put the logic for traversing the IR of function body and arguments. A separate procedure, or integrate it in current ExpressionProcessor? How to represent local scopes for inner functions? Reuse LocalScope? Writing simple code that processes IR and looking at what is possible. It should be finished by 2022-11-01.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/182845176). Continue at IR investigation and playing with IrToTruffle. (Enso Bot - Oct 28, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-10-31):

**Progress:** IR processing, learning/struggling with Scala a bit, I already decided where the IR processing should be, looking into nested function scopes. It should be finished by 2022-11-01.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/182845176). Continue playing with IR processing and nested function scopes. (Enso Bot - Oct 31, 2022)
<hr />
**Pavel Marek** reports a new **🔴 DELAY** for yesterday (2022-11-01):

**Summary:** There is **6 days** delay in implementation of the [Upgrade to Graal 22.x (#182845176) task](https://www.pivotaltracker.com/story/show/182845176).
It **will cause 6 days delay** for the delivery of this weekly plan.

**Delay Cause:** Still processing IR. I have to come up with a separate procedure and tests for local variable slot index scanning. (Enso Bot - Nov 2, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for yesterday (2022-11-01):

**Progress:** Still processing IR. Comming up with some tests alongside CompilerTests, changing API of the local variable scanner. Decided that child scopes will not inherit variables from parent scopes. It should be finished by 2022-11-07. (Enso Bot - Nov 2, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-11-02):

**Progress:** Created unit tests in Scala with default compiler config, simple tests with local vars, arguments and nested functions work. Rewriting scanner's API so that IrToTruffle is able to use the scanner before method processing. It should be finished by 2022-11-07. (Enso Bot - Nov 2, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-11-03):

**Progress:** Before ClosureRootNodes are created for nested functions with child scopes at runtime via LazyBodyNode, we need to gather all the local variable frame indexes for the FrameDescriptor. Gathering the indexes is not a problem, it is just a simple traversal of the IR, problem is how to uniquely identify a particular (child) scope by both ExpressionProcessor and local var index scanner. After trying to implement the identification myself, I figured out that AliasAnalysis info can be (easily) used for this purpose. Using AliasAnalysis will also ensure that modifications to ExpressionProcessor, and the rest of IrToTruffle, will be minimal. It should be finished by 2022-11-07.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/182845176). Use AliasAnalysis info for identification of child scopes, rewrite some tests. (Enso Bot - Nov 3, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-11-04):

**Progress:** Trying to implement local variable frame index gathering functionality as a separate compiler pass. I have found out that I cannot add additional metadata to AliasAnalysis without changing its semantics, hence the new compiler pass. Implemented the prototype of the compiler pass and some tests. The advantage of using a separate compiler pass with new metadata is performance (its done just once per IR parsing) and relative simplicity of implementation and testing. It should be finished by 2022-11-07. (Enso Bot - Nov 4, 2022)
<hr />
**Pavel Marek** reports a new **🔴 DELAY** for today (2022-11-07):

**Summary:** There is **7 days** delay in implementation of the [Upgrade to Graal 22.x (#182845176) task](https://www.pivotaltracker.com/story/show/182845176).
It **will cause 7 days delay** for the delivery of this weekly plan.

We need to gather all frame indexes for local variables and arguments before any RootNode is created. RootNodes are created from various places in `IrToTruffle`, both during the (Truffle) codegen phase, and during runtime (when some method is called and its body is lazily replaced). The new compiler pass (`FrameIndexAnalysis`) attaches metadata to certain IRs. These metadata may not be present on IRs used for creating RootNodes in `IrToTruffle`.

**Delay Cause:** Struggling with modifications to alias analysis compiler pass / new compiler pass and linking the new "frame index" metadata to LocalScope/RootNode creation from IrToTruffle.

**Possible solutions:** Try to add another metadata type to alias analysis, link frame indexes to `Scope` and/or definition occurences. For potentially missing occurences, attach only frame indexes. (Enso Bot - Nov 7, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-11-07):

**Progress:** Struggling with linking the metadata from custom compiler pass to the LocalScopeRootNode creation. Digging deeper into the possibility of adding frame index metadata to alias analysis. It should be finished by 2022-11-14. (Enso Bot - Nov 7, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-11-08):

**Progress:** A new compiler pass seems like a dead end now. Trying out a different idea - just create `FrameDescriptor` and frame slot index mapping in `LocalScope` lazily from the ammended scope information from alias analysis. Seems to be the best idea so far - already implemented, all the tests are passing except for 8 tests. It should be finished by 2022-11-14.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/182845176). Fix remaining tests, check benchmark regressions, start tests on the CI. (Enso Bot - Nov 8, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-11-09):

**Progress:** Frame slot index related functionality seems to work, all tests are passing. Investigating failure in native image build. It should be finished by 2022-11-14.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/182845176). Fix native image build failure, check benchmarks, remove more deprecations. (Enso Bot - Nov 9, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for yesterday (2022-11-10):

**Progress:** Debugging the failure in native image, caused by NPE during bytecode parsing of some class in substratevm. Seems like an internal bug in 22.1.0. Upgrade to 22.3.0 resolves this issue. Enable quick build mode when building non-release version of Enso. It should be finished by 2022-11-14. (Enso Bot - Nov 11, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-11-11):

**Progress:** Fixing native image related issues. Trying to understand "Encoding two deopt entries in the same bci error" - quick fixed just by putting some `toDisplayString` methods behind truffle boundaries. Bumped into another weird native image issue with multi threading - `Environment.isCreateThreadAllowed` returns true, but `Environment.createThread` throws `IllegalStateException` with "Multi threaded access is not allowed for language js". Is this a bug in native image 22.3.0? Why was this not failing in 21.3.0? Will "fix" this with a workaroud - do not call `isCreateThreadAllowed`, but try to create a thread instead and catch `IllegalStateException`. Or revert to plain `java.lang.Thread`? We use them just in `SerializationManager` anyway. Probably going to discuss this with Jaroslav. It should be finished by 2022-11-14. (Enso Bot - Nov 11, 2022)
<hr />
> Environment.isCreateThreadAllowed returns true, but Environment.createThread throws IllegalStateException with "Multi threaded access is not allowed for language js". Is this a bug in native image 22.3.0?

I have noticed the problem in current version when taking the system to the extreme. However the problem was rare/obscure. I don't know why it happens more frequently with 22.3. Where exactly it happens? Could you replace the call with `createSystemThread`? That'd certainly be better than `java.lang.Thread` - system threads are managed by Truffle, they just cannot enter an execution context... (jaroslavtulach - Nov 14, 2022)
<hr />
> Where exactly it happens?

From https://github.com/enso-org/enso/blob/develop/engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala#L61 the threads are created by `env.createThread` (https://github.com/enso-org/enso/blob/develop/engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala#L54) , and that is exactly where it happens.

> Could you replace the call with `createSystemThread`?

Most probably yes. We don't need to access the execution context from the thread anyway. (Pavel Marek - Nov 14, 2022)
<hr />
**Pavel Marek** reports a new **🔴 DELAY** for today (2022-11-14):

**Summary:** There is **3 days** delay in implementation of the [Upgrade to Graal 22.x (#182845176) task](https://www.pivotaltracker.com/story/show/182845176).
It **will cause 3 days delay** for the delivery of this weekly plan.

**Delay Cause:** Basically ready to be merged, I am expecting some fixes in tests. I have published the PR for review just tonight, expecting at least 3 days for reviews. (Enso Bot - Nov 14, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-11-14):

**Progress:** Fixed native-image related issues. Add build task that install native-image and js GU components. sqlite dependency removed from native-image build (engine-runner-native project completely removed). Removed deprecated native-image options. Remove other deprecated Truffle API calls. It should be finished by 2022-11-17. (Enso Bot - Nov 14, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-11-15):

**Progress:** Fixed few tests, waiting for reviews. It should be finished by 2022-11-17. (Enso Bot - Nov 15, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-11-16):

**Progress:** Working on support for `NodeLibrary`, so that enso can run with chrome devtools. Looking for inspiration from simplelanguage, FastR, GraalPython, and our own `ReplDebuggerInstrument`. It should be finished by 2022-11-17. (Enso Bot - Nov 16, 2022)
<hr />
**Pavel Marek** reports a new **🔴 DELAY** for today (2022-11-17):

**Summary:** There is **5 days** delay in implementation of the [Upgrade to Graal 22.x (#182845176) task](https://www.pivotaltracker.com/story/show/182845176).
It **will cause 5 days delay** for the delivery of this weekly plan.

**Delay Cause:** The migration to frame slot indexes caused the default chromeinspector support to malfunction. With Jaroslav, we agreed that we should implement at least basic support for inspection, i.e., running enso with --inspect option. I have to implement NodeLibrary messages for some of our nodes in order to support that. For now, I plan only to have a very basic support for inspection, that is to show local variables with their values, and also variables from parent scopes. Module scopes will not be supported yet. This is part of story https://www.pivotaltracker.com/story/show/183798184 (Enso Bot - Nov 17, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-11-17):

**Progress:** Integrating `NodeLibrary` messages for `BlockNode` and `StatementNode`. So far, local variables with their values are visible in chrome inspector. It should be finished by 2022-11-22.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/182845176). Finish basic support for parent scopes, i.e., nested methods. Module scopes will be implemented in https://www.pivotaltracker.com/story/show/183798184 (Enso Bot - Nov 17, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-11-18):

**Progress:** Adding tests to `DebuggingEnsoTest`, adding support for displaying local variables in caller stack frames. Debugging why, in chrome inspector, I can't see local variables of caller stack frames. Getting some inspiration from graalpython, graaljs, FastR, and simplelanguage. Fixed proper local variable displaying in nested methods. Fixed proper wrapping of `ExpressionNode` in `BlockNode`. Adding arbitrary expression evaluation, module scopes, and variable rewrites in the future should not be that difficult. It should be finished by 2022-11-22. (Enso Bot - Nov 18, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-11-21):

**Progress:** Finished `NodeLibrary` implementation - chrome inspector displays values for local variables, arguments, both for current method and its callers. Names of local variables correspond to their actual identifiers, which is a slight improvement over the past implementation. The whole debugging support is tracked in https://www.pivotaltracker.com/story/show/183855919 (Add expression evaluation) and https://www.pivotaltracker.com/story/show/183798184 (Display module scopes). There are few tests and review to be done, but I don't expect anything huge missing. It should be finished by 2022-11-22. (Enso Bot - Nov 21, 2022)
<hr />
**Pavel Marek** reports a new **🔴 DELAY** for yesterday (2022-11-22):

**Summary:** There is **2 days** delay in implementation of the [Upgrade to Graal 22.x (#182845176) task](https://www.pivotaltracker.com/story/show/182845176).
It **will cause 2 days delay** for the delivery of this weekly plan.

**Delay Cause:** I spent a lot of time trying to analyze the error in pattern matching on polyglot values. Seems like an internal bug in Truffle. I will report an issue in graal. (Enso Bot - Nov 23, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for yesterday (2022-11-22):

**Progress:** Fixed issue with pattern matching on polyglot values, took a lot of time. Seems like an internal bug in Truffle. I am going to report an issue in graal for that. It should be finished by 2022-11-24. (Enso Bot - Nov 23, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for yesterday (2022-11-23):

**Progress:** Created issue https://github.com/oracle/graal/issues/5485 in Truffle. Fixed small build issue with build on Mac OS. Final small refactorings. Merged. Follow-up issues solved by cleaning github runners via the clean action. Will check potential benchmark regressions tomorrow. It should be finished by 2022-11-24. (Enso Bot - Nov 24, 2022)
<hr />
