### ISSUE TITLE
Slider implementation

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4719]
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/183686915).
<hr />

## Team
Technical Designer: Wojciech Danilo
Implementer: Galin Bajlekov
Acceptance/QA: Wojciech Danilo

## Why
A slider is one of the most important widgets we will be displaying on nodes. It allows users to manipulate numerical values easily. 

**As** a data analysts
**I want** to be able to easily manipulate numerical values
**So that** I can test different hypotheses and see the results in real time. To learn more about the high-level idea, see https://www.youtube.com/watch?v=ef2jpjTEB5U .

## Technical Description
There is already a slider implementation here: `lib/rust/ensogl/component/selector/src/lib.rs` and a demo scene here: `lib/rust/ensogl/example/slider/src/lib.rs` (run it with `./run gui watch --skip-wasm-opt --wasm-profile dev --crate-path ./lib/rust/ensogl/example/slider`). However, the implementation was created long time ago, when our rendering engine was not as powerful as it is now, so it is using deprecated components, it is not working correctly in few places, and also, it does not implement everything we want to have. I wouldd suggest looking at it, but implementing it from scratch. The new component should be named `Slider` - create a new example scene for it on the beginning of your work.

Requirements:
- The slider should look like in the attached screenshot.
- Interactions with the slider:
  - After clicking the slider with the mouse, the slider should not move. There should be 0-lag between mouse movement and slider movement.
  - After clicking and dragging the slider vertically, the mouse precision should change. Imagine vertical areas above and below the slider of the same height as the slider. When the mouse moves to one of these areas, the mouse x-position difference is multiplied by some factor. The area above the slider should have the 1.0 precision, the area above this area, 10.0 precision, the next area, 100.0 precision. The area below the slider should have 0.1 precision. The area below it, 0.01 precision, etc. So, for example, if the user clicks the slider and moves the mouse above the slider, every horizontal pixel will change the slider value by 1. If the user moves mouse even higher, every horizontal pixel will change the slider value by 10. When moving the mouse vertically, the precision should be applied to the whole movement, starting when the user pressed the slider, so if user pressed the slider, moved the mouse right, and then up, the slider value should change (the precision should be applied to the total horizontal movement the user did). The size of the areas and the distance of them from the upper and lower slider boundary should be configurable.
  - The displayed value should have different style if it is set to default or non-default value. In the latter case, the text should be bold. We might want to also change its colors, so all colors should be controlled from FRP inputs.
  - After cmd + LMB, the slider should get back to its default value. 
  

- The API should be provided by `define_frp_endpoints_2!` macro. For an example usage, see `lib/rust/ensogl/component/text/src/component/text.rs`. All public API should be controlled via FRP only, this includes:
  - Setting slider width and height (`set_width`, `set_height`).
  - Setting slider default value. 
  - Setting slider value.
  - Setting slider min and max value. 
  - Enabling and disabling slider (grading it out, so it is not editable by mouse).
  - Controlling whether the label should be shown or not.
  - Controlling slider colors (every slider element).
  - Setting the slider precision. By default, this should be `0.1`. When dragging the slider, it should snap to the precision points. 
  - The slider value should be aligned to the dot `.` if the precision was not integer. This means, that if multiple sliders with the same width will be shown one over the other, the horizontal dot position will be the same in all of them. Please note, that we will probably not use monospaced fonts everywhere, and thus, the slider value should be 3 texts - the part before the dot, the dot, and the part after the dot.
  - Setting the slider name - it should be displayed on the left side of the slider (see the screenshot). There should be also an option to display it inside of the slider (controlled by an FRP input, like `display_label_inside`, or something similar). 
- All visual elements (such as width and height setting, or the slider value setting) should be animated. For width and height (the size), there should be an FRP input `skip_size_animation` that can be called by the API user when needed.
- For every parameter, there should be FRP output emitting the value on change, like `width` and `height`).

## Tasks:
- [X] create Slider component
- [X] create demo scene for Slider
- [X] create draft PR
- [X] implement Slider functionality
- [X] implement Slider API

## Comments:
 (Wojciech Daniło - Nov 1, 2022)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2022-11-01):

**Progress:** Set up build environment and ran the corresponding demo scene for the slider widget. Getting acquainted with the relevant code. End date is a placeholder, as I can't estimate the complexity yet. It should be finished by 2022-11-04.

**Next Day:** Next day I will be working on the [#183686915 task](https://www.pivotaltracker.com/story/show/183686915). I'll be studying the FRP implementation and how UI drawing, user input events and widget state is handled. (Enso Bot - Nov 1, 2022)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2022-11-02):

**Progress:** I'm getting a better overview of the structure of UI components. Created a simple custom component to verify my understanding, but can't get it to render yet (I'm probably still missing some details). It should be finished by 2022-11-04.

**Next Day:** Next day I will be working on the [#183686915 task](https://www.pivotaltracker.com/story/show/183686915). I'll retrace my steps to figure out what is still missing to get a component rendered (and look for advice if I don't quickly find the issue). Then I'll continue building up the new slider component. (Enso Bot - Nov 2, 2022)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2022-11-03):

**Progress:** I finally have a working rudimentary slider (mouse input handling and shape rendering). It should be finished by 2022-11-04.

**Next Day:** Next day I will be working on the [#183686915 task](https://www.pivotaltracker.com/story/show/183686915). I'll integrate the slider's state in the FRP network, add visual elements and continue implementing behaviors as defined in the task. (Enso Bot - Nov 3, 2022)
<hr />
**Galin Bajlekov** reports a new **🔴 DELAY** for today (2022-11-04):

**Summary:** There is **5 days** delay in implementation of the [Slider implementation (#183686915) task](https://www.pivotaltracker.com/story/show/183686915).
It **will cause 5 days delay** for the delivery of this weekly plan.

**Delay Cause:** Initial end date was a placeholder, as I'm still finding my way around the codebase and can't estimate the complexity of the task yet. (Enso Bot - Nov 4, 2022)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2022-11-04):

**Progress:** Expanded slider component with min/max boundaries and precision scaling. Component value is now stored in FRP, still some issues with updating. It should be finished by 2022-11-09.

**Next Day:** Next day I will be working on the [#183686915 task](https://www.pivotaltracker.com/story/show/183686915). I'll investigate further the value updating issues, and will work on the text layout of the component. (Enso Bot - Nov 4, 2022)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2022-11-07):

**Progress:** I'm getting more comfortable with the framework. I've debugged and fixed the remaining issues from last time, and am working more towards the specification rather than just figuring out how to get a basic slider running. It should be finished by 2022-11-09.

**Next Day:** Next day I will be working on the [#183686915 task](https://www.pivotaltracker.com/story/show/183686915). I'll continue implementing features and API as per the specification. (Enso Bot - Nov 7, 2022)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2022-11-08):

**Progress:** Today I was working on improving the slider behavior with adjusted precision (snapping to increments, value display with correct precision). I've reviewed the progress so far with Wojciech, and we have agreed to narrow the scope of the initial pull request and aim for a merge on Friday. It should be finished by 2022-11-09.

**Next Day:** Next day I will be working on the [#183686915 task](https://www.pivotaltracker.com/story/show/183686915). I'll continue implementing features and API as per the specification, and incorporate comments from the review. (Enso Bot - Nov 8, 2022)
<hr />
**Galin Bajlekov** reports a new **🔴 DELAY** for today (2022-11-09):

**Summary:** There is **2 days** delay in implementation of the [Slider implementation (#183686915) task](https://www.pivotaltracker.com/story/show/183686915).
It **will cause 2 days delay** for the delivery of this weekly plan.

**Delay Cause:** I wasn't able to estimate the complexity of the task earlier due to still getting used to the codebase. I've reviewed the task progress and deliverables with Wojciech and we've settled on an end date Friday 11-11 with a reduced scope. (Enso Bot - Nov 9, 2022)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2022-11-09):

**Progress:** I implemented most of the slider functionality today. It should be finished by 2022-11-11.

**Next Day:** Next day I will be working on the [#183686915 task](https://www.pivotaltracker.com/story/show/183686915). I'll finalize the few missing items as per the specification, clean up the code and prepare it for review. (Enso Bot - Nov 9, 2022)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2022-11-10):

**Progress:** I've finalized the initial slider implementation and cleaned up the code for review. It should be finished by 2022-11-11.

**Next Day:** Next day I will be working on the [#183686915 task](https://www.pivotaltracker.com/story/show/183686915). I'll work on the slider branch review, and time allowing, work on the slider implementation items that were postponed to after the review. (Enso Bot - Nov 10, 2022)
<hr />
**Galin Bajlekov** reports a new **🔴 DELAY** for today (2022-11-11):

**Summary:** There is **3 days** delay in implementation of the [Slider implementation (#183686915) task](https://www.pivotaltracker.com/story/show/183686915).
It **will cause 3 days delay** for the delivery of this weekly plan.

**Delay Cause:** Quite a few code style issues came up during a review of the PR yesterday evening. I've been working on fixing them today, but the work will extend into Monday. (Enso Bot - Nov 11, 2022)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2022-11-11):

**Progress:** Today I worked on fixing code style issues that came up during review of the PR. It should be finished by 2022-11-14.

**Next Day:** Next day I will be working on the [#183686915 task](https://www.pivotaltracker.com/story/show/183686915). I'll continue processing the comments from the PR review. (Enso Bot - Nov 11, 2022)
<hr />
**Galin Bajlekov** reports a new **🔴 DELAY** for today (2022-11-14):

**Summary:** There is **2 days** delay in implementation of the [Slider implementation (#183686915) task](https://www.pivotaltracker.com/story/show/183686915).
It **will cause 2 days delay** for the delivery of this weekly plan.

**Delay Cause:** Fixing code style issues took longer than I had anticipated. I've resolved the open comments, but expect more input in another round of reviewing. (Enso Bot - Nov 14, 2022)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2022-11-14):

**Progress:** Today I wrapped up fixing code style issues that came up during last week's review of the PR. It should be finished by 2022-11-16.

**Next Day:** Next day I will be working on the [#183686915 task](https://www.pivotaltracker.com/story/show/183686915). I'll prepare the PR itself and go through the checklist and CI failures. I also expect a review of the technical implementation of the slider component. (Enso Bot - Nov 14, 2022)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2022-11-15):

**Progress:** Finally submitted the slider component PR for proper review. It should be finished by 2022-11-16.

**Next Day:** Next day I will be working on the [#183686915 task](https://www.pivotaltracker.com/story/show/183686915). I'll work on fixing the PR review comments. (Enso Bot - Nov 15, 2022)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2022-11-16):

**Progress:** I've addressed comments on the PR and created a new task containing the follow-up features of the slider component. It should be finished by 2022-11-16.

**Next Day:** Next day I will be working on the [#183816694 task](https://www.pivotaltracker.com/story/show/183816694). I'll start implementing the follow-up features of the slider component. (Enso Bot - Nov 16, 2022)
<hr />
