### ISSUE TITLE
Update Standard.Database types and errors.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4757]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/183324312).
<hr />

## Types

- **`.Connection.Connection`**: `Connection.Connection_Data`  
  ⇒ `Connection.Value jdbc_connection`  
  **Private constructor not presented to users. Use `Data.connect`.**
- **`.Internal.JDBC_Connection`**: `JDBC_Connection.JDBC_Connection_Data`  
  ⇒ `JDBC_Connection.Value connection`  
  **Private constructor not presented to users. Use `Data.connect`.**
- **`.Internal.Postgres.Postgres_Connection`**: `Postgres_Connection.Postgres_Connection_Data`  
  ⇒ `Postgres_Connection.Value connection`  
  **Private constructor not presented to users. Use `Data.connect`.**
- **`.Internal.SQLite.SQLite_Connection`**: `SQLite_Connection.SQLite_Connection_Data`  
  ⇒ `SQLite_Connection.Value connection`  
  **Private constructor not presented to users. Use `Data.connect`.**
- **`.Connection.Connection_Options`**: `Connection_Options.Connection_Options_Data`  
  ⇒ `Properties.Overrides vector`  
- **`.Data.Table`**: `Table.Table_Data`  
  ⇒ `Table.Value java_table`  
  **Private constructor not presented to users.**
- **`.Data.Column`**: `Column.Column_Data`  
  ⇒ `Column.Value java_column`  
  **Private constructor not presented to users.**
- **`.Data.SQL`**: `SQL_Type.SQL_Type_Data`  
  ⇒ `SQL_Type.Value ...`  
  **Private constructor not presented to users. Static methods used.**
- **`.Data.SQL`**: `Builder.Builder_Data`  
  ⇒ `Builder.Value ...`  
  **Private constructor not presented to users. Static methods used.**
- **`.Data.SQL`**: `Statement.Statement_Data`  
  ⇒ `Statement.Value ...`  
  **Private constructor not presented to users.**
- **`.Internal.Base_Generator`**: `Internal_Dialect.Internal_Dialect_Data`  
  ⇒ `Base_Dialect.Value ...`  
  **Private constructor not presented to users.**
- **`.Internal.Postgres.Postgres_Dialect`**: `Postgres_Dialect.Postgres_Dialect_Data`  
  ⇒ `Postgres_Dialect.Value ...`  
  **Private constructor not presented to users.**
- **`.Internal.Redshift.Redshift_Dialect`**: `Redshift_Dialect.Redshift_Dialect_Data`  
  ⇒ `Redshift_Dialect.Value ...`  
  **Private constructor not presented to users.**
- **`.Internal.SQLite.SQLite_Dialect`**: `SQLite_Dialect.SQLite_Dialect_Data`  
  ⇒ `SQLite_Dialect.Value ...`  
  **Private constructor not presented to users.**
- **`.Internal.IR`**: `Context.Context_Data`  
  ⇒ `Context.Value ...`  
  **Private constructor not presented to users.**
- **`.Internal.IR`**: `Internal_Column.Internal_Column_Data`  
  ⇒ `Internal_Column.Value ...`  
  **Private constructor not presented to users.**
- **`.Internal.IR`**: `Order_Descriptor.Order_Descriptor_Data`  
  ⇒ `Order_Descriptor.Value ...`  
  **Private constructor not presented to users. Add a static method to make it.**
- **`.Internal.Postgres.Pgpass`**: `Pgpass_Entry.Pgpass_Entry_Data`  
  ⇒ `Pgpass_Entry.Value ...`  
  **Private constructor not presented to users.**

## Errors

- **`.Data.Table`**: `Integrity_Error.Integrity_Error_Data`  
  ⇒ `.Errors: Integrity_Error.Error ...`  
  **Move into the Errors namespace.**
- **`.Data.Internal.Helpers`**: `Unsupported_Name_Error.Unsupported_Name_Error_Data`  
  ⇒ `.Errors: Unsupported_Name.Error ...`  
  **Move into the Errors namespace.**

- **`.Errors`**:  
  **Follow the pattern for the Error types in Standard.Base.**
  **Note:** `Sql_Error` will remain with the `_Error` suffix.

## Tasks:
- [X] Standard.Database.Errors
- [X] Unsupported_Name
- [X] Integrity_Error
- [X] Connection, Postgres, SQLite, JDBC
- [X] Column, Table
- [X] Dialect, Postgres, SQLite, Redshift
- [X] Connection_Options
- [X] SQL_Type, Statement, Internal_Column, Context, Order_Description
- [X] Builder
- [X] PGpass

## Blockers:
[#181908162](https://www.pivotaltracker.com/story/show/#181908162) resolved
