### ISSUE TITLE
Revisit Compatibility with GraalVM Java 11 Builds

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#476]
### Summary
Scala 2.13.2 (see #634), has improved the language's compatibility with the JDK 11 module system. This means that we should revisit updating our GraalVM platform's JDK version.

### Value
This would bring us the benefits of a much newer version of Java for the java portions of the codebase, as well as the performance improvements to the underlying JVM that come with the upgrade. It also means that we're on a JDK version that will be supported for longer. 

### Specification

- [x] Try and upgrade our codebase to use a JDK 11-based GraalVM build.
- [x] Explore the issues with compilation on Java 11 (#586)
- [x] Analyse module definitions in Truffle API JARs in Maven and Graal Distribution (#432)
- [x] Explore if module support in sbt would fix the issue (#428)
- [x] Explore possibility of altering permissions of Zinc's ClassLoader (#431)
- [x] Implement a chosen solution that allows us to migrate to Java 11 (#430)
- [x] Ensure that all tests still pass and that the benchmarks don't regress (#429)
-  ~If it is not possible, provide a summary in the `doc/` folder as to why.~

### Acceptance Criteria & Test Cases

- The above specification has been completed.
