### ISSUE TITLE
Language server message to evaluation stop and restart execution

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4765]
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/183861991).
<hr />

When a user makes a mistake and i.e. start processing too big data, he should be able to stop the calculation. After stopping the evaluation and fixing the issue he should be able to restart the evaluation without reloading the IDE.  The IDE part is tracked as #183862007, this pivotal tracks necessary changes on the engine/language server side.

There should be a message in [the protocol](https://github.com/enso-org/enso/blob/d3846578cceb4844f1f94d4e7ca51762bba3fada/docs/language-server/protocol-project-manager.md) that allows the IDE to request a stop in the evaluation. There should be a mean for the IDE to restart the evaluation when the issue is fixed (if not present already). 

Once the message arrives one can talk to `IdExecutionInstrument` or use [Context.interrupt](https://www.graalvm.org/sdk/javadoc/org/graalvm/polyglot/Context.html#interrupt-java.time.Duration-) to stop the execution.

## Tasks:
- [ ] Message to interrupt execution
- [ ] Verify there is a way to restart execution
- [ ] Enhance `IdExecutionInstrument` to interrupt execution when requested

## Comments:
**Dmitry Bushev** reports a new **STANDUP** for today (2022-12-06):

**Progress:** Picked up the task. Implemented Language Server API types. Started working on the engine logic. It should be finished by 2022-12-09.

**Next Day:** Next day I will be working on the [#183861991 task](https://www.pivotaltracker.com/story/show/183861991). Continue working on the task (Enso Bot - Dec 6, 2022)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for today (2022-12-07):

**Progress:** Continue working the task. Implemented the engine logic. Testing was a bit tricky, ended up creating a separate suite that runs the context with async command flow. Created the PR It should be finished by 2022-12-09.

**Next Day:** Next day I will be working on the [#183861991 task](https://www.pivotaltracker.com/story/show/183861991). Continue working on the task (Enso Bot - Dec 7, 2022)
<hr />
