### ISSUE TITLE
[PRIO] Allow arbitrary expression evaluation in Chrome devtools inspection

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4774]
This task is automatically imported from the old Task Issue Board and it was originally created by Pavel Marek.
Original issue is [here](https://www.pivotaltracker.com/story/show/183855919).
<hr />

Since https://www.pivotaltracker.com/story/show/182845176, we implemented a basic support for inspections in Chrome devtools - values of local variables, arguments, for any stack frame. There is no support for arbitrary expression evaluation yet.

Current implementation is in `org.enso.interpreter.runtime.scope.DebugLocalScope`, and tests in `org.enso.interpreter.test.DebuggingEnsoTest`. We should extend it so that it supports also expression evaluation.

Some implementation notes:
- Should we allow users to redefine variables, or introduces new variables to some scope? *No, no new variables*. Changing values of existing is however OK.
  - Might be difficult to implement correctly in the presence of *PE (partial evaluation)* - if there is some assumption about a particular value in a Truffle `Frame`, and we will change the value from `DebugLocalScope`, the assumption will not get invalidated automatically.
- Get inspiration from Graalpython, Simplelanguage, FastR, ...

## Tasks:
- [X] Implement expression evaluation in `DebugLocalScope` (or at other appropriate place)
- [X] Add tests to `DebuggingEnsoTest`
- [X] Fix NPE when displaying a polyglot value in local vars
- [X] Add option to rewrite local variable (if it is easy)

## Blockers:
[https://www.pivotaltracker.com/story/show/182845176](https://www.pivotaltracker.com/story/show/https://www.pivotaltracker.com/story/show/182845176) resolved
[#183958493](https://www.pivotaltracker.com/story/show/#183958493) resolved

## Comments:
**Pavel Marek** reports a new **STANDUP** for the provided date (2022-11-25):

**Progress:** Breakpoints in debug testing do not work, investigating why. Because of that, we cannot use DebuggerTester in our debugging test, which is a bit inconvenient. Created https://www.pivotaltracker.com/story/show/183892554 . Bumped into NullPointerException comming from chromeinspector once there is a host object in the local scope, seems like a bug in Truffle tooling. I will consult this with GraalVM devs on Slack. Meanwhile, I am implementing a simple workaround, such that the host object values are not displayed in the chromeinspector, just their names. It should be finished by 2022-11-29. (Enso Bot - Nov 27, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for yesterday (2022-11-28):

**Progress:** Reported https://github.com/oracle/graal/issues/5513 and finished workaround for it - all host objects are wrapped and displayed as simple strings, even if it is an interop value. Investigating how values are writter to stack frames via chromeinspector, and expression evaluation. It should be finished by 2022-11-29. (Enso Bot - Nov 29, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for yesterday (2022-11-29):

**Progress:** Syntactically correct expression evaluation works. Modification of local variables, and variables in caller stack work. Only syntacticlly incorrect expression should be handled now. I will probably try evaluating them in inner contexts, or duplicating Enso compiler. It should be finished by 2022-11-29. (Enso Bot - Nov 30, 2022)
<hr />
**Pavel Marek** reports a new **🔴 DELAY** for today (2022-11-30):

**Summary:** There is **3 days** delay in implementation of the [[PRIO] Allow arbitrary expression evaluation in Chrome devtools inspection (#183855919) task](https://www.pivotaltracker.com/story/show/183855919).
It **will cause 3 days delay** for the delivery of this weekly plan.

**Delay Cause:** This feature is a bit more complicated than I originally thought. Mostly because our `Compiler` implicitly prints errors and warnings to the context's output. Looking into possibilities how to work around that. Probably with inner contexts. Dealing with issue with wrong usages of sharing layers. (Enso Bot - Nov 30, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-11-30):

**Progress:** Trying to understand inner contexts (TruffleContext) and its implications on sharing layers. Looking into its usages accross GraalPython, TruffleRuby, GraalJs, simplelang and tests in truffle... It should be finished by 2022-12-02. (Enso Bot - Nov 30, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-12-01):

**Progress:** Inline parsing handled by the new parser. Also fails fast when the inline parsing request contains some undesirable expressions, like assignments, imports, etc. Correctly fails when given syntactically incorrect values and unknown identifiers. The expression evaluation now works pretty well, at least one thing to do is to propagate errors from parser or compiler to the `DebugException`, so that there is some reasonable error message in the chromeinspector console. It should be finished by 2022-12-02.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/183855919). Propagate error messages from parser and compiler to the debugger console. Maybe add more tests, e.g., for expr evaluation in caller frames. (Enso Bot - Dec 1, 2022)
<hr />
**Pavel Marek** reports a new **🔴 DELAY** for yesterday (2022-12-05):

**Summary:** There is **7 days** delay in implementation of the [[PRIO] Allow arbitrary expression evaluation in Chrome devtools inspection (#183855919) task](https://www.pivotaltracker.com/story/show/183855919).
It **will cause 7 days delay** for the delivery of this weekly plan.

The delay of one week is very pessimistic. I don't intend to spent that much time on this issue. Theoretically, the associated PR could be merged tomorrow, but I still want to test more complex cases.

**Delay Cause:** Dealing with issues coming from Truffle side - https://github.com/oracle/graal/issues/5513 (Enso Bot - Dec 6, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for yesterday (2022-12-05):

**Progress:** Add tests for stepping into / stepping over. These tests work, but the behavior of step over in chromeinspector is still weird. Trying to adjust `StatementTag` by removing `StatementNode`, attaching this tag directly to some `ExpressionNode`s, without success. Leaving the "weird" behavior of stepping over for now. In chromeinspector, we still hit some NullPointerExceptions from Truffle. Writing more tests. It should be finished by 2022-12-09. (Enso Bot - Dec 6, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for the provided date (2022-12-02):

**Progress:** Added --inspect-path option that forwards to --inspect.Path Truffle tool, so that we can bookmark DevTools URL in Chrome, and do not copy the provided randomly generated URL every time. Created pivotal issues for integrating truffle launcher (https://www.pivotaltracker.com/story/show/183935964), Improve options to the new Truffle option syntax (https://www.pivotaltracker.com/story/show/183934718), and to Integrate JLine in REPL (https://www.pivotaltracker.com/story/show/183936098). Changed CompilerConfig so that its output can be redirected. Fixed issue with displaying HostObject fields of Atoms. Looking into weird behavior of stepping into / stepping over. It should be finished by 2022-12-09. (Enso Bot - Dec 6, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-12-06):

**Progress:** Finished implementation, provided yet more fixes for host object wrapping. It seems that some complex examples work, ale NullPointerException is thrown not often. But if it is thrown, it is concealed in the Truffle debugger and not propagated to other places, so the debugging should continue normally. Published PR and doing some finishing touches. Fixing native-image related issues. It should be finished by 2022-12-09. (Enso Bot - Dec 6, 2022)
<hr />
