### ISSUE TITLE
Slider implementation enhancement

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4775]
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/183816694).
<hr />

## Team
Technical Designer: Wojciech Danilo
Implementer: Galin Bajlekov
Acceptance/QA: Wojciech Danilo

## Why
A slider is one of the most important widgets we will be displaying on nodes. It allows users to manipulate numerical values easily. 

**As** a data analysts
**I want** to be able to easily manipulate numerical values
**So that** I can test different hypotheses and see the results in real time. To learn more about the high-level idea, see https://www.youtube.com/watch?v=ef2jpjTEB5U .

## Technical Description
This is an enhancement to the slider component as described in #183686915. It should add better visual feedback when the precision is changed, different ways to handle value adjustment beyond the initial range, and textual editing of the value.

Requirements:
- Interaction with the slider:
  - Every precision change should be displayed for a short period of time as a pop-up over mouse.
  - When the user drags the slider over the left or right limits, there should be several modes available:
    - Not allowing it (just stopping at the limit, already available in #183686915)
    - Allowing it (the overflow mode), where the value changes and a small arrow is shown next to slider left or right border indicating that the value is over the max value
    - Dynamic mode, where the slider range will automatically adjust to the new value (e.g. the max will be multiplied by 2 if the user goes over the range. It should ofc shrink too, if the user makes the value smaller).
  - After double clicking the value, it should enter edit mode, when the user is able to enter the value by hand. Pressing enter should accept the value, pressing escape should return to the previous one.

- The public API should be controlled via FRP and include:
  - Enabling or disabling left and right overflow.
  - Entering/exiting the text edit mode (`start_editing`, `finish_editing`).
  - Setting the slider orientation (horizontal vs vertical). 
  - Setting the pop-up information. After hovering the slider for a while (controlled by FRP input), a pop-up should be displayed above the mouse cursor (the mouse cursor has built-in support for popups) with the provided text IFF the caption was set.

## Tasks:
- [X] Implement visual feedback on precision change
- [X] Implement alternative handling of value limits
- [X] Implement textual value editing
- [X] Implement slider horizontal/vertical orientation
- [X] Implement component pop-up information

## Comments:
**Galin Bajlekov** reports a new **STANDUP** for today (2022-11-17):

**Progress:** I've explored the tooltip system and timed events in the FRP network. I've implemented a tooltip to indicate when the precision of the slider is adjusted. It should be finished by 2022-11-23.

**Next Day:** Next day I will be working on the [#183816694 task](https://www.pivotaltracker.com/story/show/183816694). I'll implement the component's information tooltip. I'll also work on alternative behaviors when adjusting the value beyond the slider's limits. (Enso Bot - Nov 17, 2022)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2022-11-18):

**Progress:** I've implemented the following additional slider limit behaviors in addition to hard limits. Soft limits: the value can be adjusted beyond the slider's range, and an overflow indicator is displayed. Adaptive: the range is extended to fit the value when the value becomes of range. I've also implemented a generic tooltip that pops up when hovering over the component. It should be finished by 2022-11-23.

**Next Day:** Next day I will be working on the [#183816694 task](https://www.pivotaltracker.com/story/show/183816694). I'll work on textual value entry and a vertical slider mode next. (Enso Bot - Nov 18, 2022)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2022-11-21):

**Progress:** I've cleaned up the code for the slider limit handling and precision and information tooltips. I've added a basic textual value input integrated with the shortcut system. It still needs better value formatting and precision handling. It should be finished by 2022-11-23.

**Next Day:** Next day I will be working on the [#183816694 task](https://www.pivotaltracker.com/story/show/183816694). I'll finish up the textual input, add a vertical slider mode, and clean up the code for review. (Enso Bot - Nov 21, 2022)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2022-11-22):

**Progress:** I finished the slider component's textual value editing. Cleaned many edge cases and interactions between value dragging/value editing/hovering for tooltip display/disabled nodes. Added vertical slider mode. It should be finished by 2022-11-23.

**Next Day:** Next day I will be working on the [#183816694 task](https://www.pivotaltracker.com/story/show/183816694). I'll review the code and check the newly implemented behavior more thoroughly. (Enso Bot - Nov 22, 2022)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2022-11-23):

**Progress:** I've finalized the slider component implementation and prepared the PR for review. It should be finished by 2022-11-23.

**Next Day:** Next day I will be working on the [#183874358 task](https://www.pivotaltracker.com/story/show/183874358). I'll familiarize myself with the relevant structure of the GUI, how shortcuts are handled, and how snapshots of the project state are to be saved in a VCS. (Enso Bot - Nov 23, 2022)
<hr />
**Acceptance/QA** review set to **pass** (Paweł Grabarz - Dec 9, 2022)
<hr />
