### ISSUE TITLE
Developer can promote and release IDE through CLI.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4781]
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/180302842).
<hr />

## Why
**As** a release manager
**I want** to be able to promote releases (nightly to RC, RC to final) using CLI tool
**So that** I can quickly make releases without worrying about version numbering.

## Acceptance Criteria
```gherkin
Scenario: 
Given I want to promote nightly release to RC
When I issue appropriate CLI command
Then all the work needed for the RC release gets done
```

## Notes
To be decided what the exact format of version strings will look like.

## Tasks:
- [X] Unify Engine and IDE versioning.
- [X] Rewrite Engine release workflow.
- [X] Rewrite GUI build scripts
