### ISSUE TITLE
Speed Meta.is_a up

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4815]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/183970789).
<hr />

Investigation in #183918642 shows that the problem for the _Count/Min/Max_ benchmark is in implementation `Meta.is_a`.

Marcin pointed out that with the existence of `TypesLibrary.getType` there is no need for such a complex implemnetation of `Meta.is_a` and that it could be a simple builtin.

Marcin is right: by rewriting `Meta.is_a` to builtin we can gain the so needed speed. We just need to get back the original behavior and/or discuss how it should be changed as [it is somewhat weird](https://github.com/enso-org/enso/pull/3949#discussion_r1040058599).

## Tasks:
- [X] Should `Meta.is_a x x` be `True` for all `x`?
- [X] Write unit tests
- [X] Fix stdlib where needed

## Blockers:
[#183918642](https://www.pivotaltracker.com/story/show/#183918642) resolved
