### ISSUE TITLE
Add GetMetaObject to Enso built-in types

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4818]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/183686167).
<hr />

Currently when working with a `Value` in the polyglot world, if you try to `getMetaObject` you just get a `null` returned.
This ticket is to add this functionality to all the built-ins.

There is a prototype adding it to `Atom`: https://github.com/enso-org/enso/commit/c02c1ffc38b2d1d31bb05ff6bab042da2d8f2448

This would need to be done for all built-ins and then should be tested to ensure it is everywhere (and to allow least effort) to keep this true.

## Tasks:
- [X] Write a test to verify all Enso objects (including plugins) have a type/metaobject
- [X] Make sure the test fails when we add new plugin type
- [X] Make sure the test passes with all existing types

## Comments:
See also #183779855 where proper `getMetaObject` functionality might be useful. (jaroslavtulach - Nov 11, 2022)
<hr />
Here is the test to check all buitins: https://github.com/enso-org/enso/pull/3949/commits/492dd34b61474bffc4ea19bd68702c800b42deaf#diff-9202e6a4f05f9aa7784806e733e32c17a0c4496f40bc1710d80ce9b772ae996fR63 - and it is currently failing. (jaroslavtulach - Dec 19, 2022)
<hr />
**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2022-12-20):

**Progress:** Enhancing `MetaObjectTest` and fighting/bisecting with _regressions_; some regression caused by `containsValues() = true`; debugging `ModuleScope.withTypes` - static methods are at wrong type according to Marcin. It should be finished by 2022-12-26.

**Next Day:** Polish getMetaObject; get closer to integration (Enso Bot - Dec 21, 2022)
<hr />
**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2022-12-21):

**Progress:** Fixed all Java tests. Fixed standardlibrary test/Tests. Meetings. It should be finished by 2022-12-26.

**Next Day:** Adjust test/Table & co. to `getMetaObject`; integrate before Christmas (Enso Bot - Dec 22, 2022)
<hr />
**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2022-12-22):

**Progress:** `Meta.is_a` integrated. `getMetaObject` for Enso objects integrated. Investigation and controversies about _greying out nodes_ in the IDE: [discord](https://discord.com/channels/401396655599124480/1052571174376329287/1055467459915829318); Re-planning `Text.to_text`: https://www.pivotaltracker.com/n/projects/2539304/stories/181499256 It should be finished by 2022-12-26.

**Next Day:** Merry Christmas (Enso Bot - Dec 23, 2022)
<hr />
**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2022-12-25):

**Progress:** Final exam of Advent of code: convert SNAFU to decimal: https://discord.com/channels/401396655599124480/1056550038676979833 - Advent of code: decimal to SNAFU It should be finished by 2022-12-26.

**Next Day:** Vacation & a bit of IGV (Enso Bot - Dec 26, 2022)
<hr />
