### ISSUE TITLE
Fix Text.to_text

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4821]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/181499256).
<hr />

Calls to `Text.to_text` should be an identity. There is an overall consensus in the discussion that `Text.to_text` shall be an identity. Additionally there are many ideas [on discord](https://discord.com/channels/401396655599124480/1044586488823808101/1044586488823808101) yielding many interesting additional requests:

> a method named to_text shouldn't exist at all, we have conversions for that

and

> current version of to_text is the correct implementation of pretty and Text.from "foo" should be a no-op.

moreover as Hubert points out

> we already have `to_display_text` for various types

Wojciech [approves](https://discord.com/channels/401396655599124480/1044586488823808101/1044901847678337054) and adds additional requests that are now tracked as #184088618

## Tasks:
- [X] Make Text.to_text an identity
- [X] Make sure `Text.from` conversion works
- [ ] Use `Text.from` instead of `Text.to_text` where possible
- [X] Write some tests

## Comments:
Following discussion with Marcin need to do a large change (James Dunkerley - Mar 15, 2022)
<hr />
Discussion is [happening on discord](https://discord.com/channels/401396655599124480/1044586488823808101). (jaroslavtulach - Nov 23, 2022)
<hr />
	The outcome of Discord discussion:
- Instead of `to_text` it should be `to Text` and it should be an identity conversion for `Text`
- There should be a method `pretty` or `display` that do escapes (current behavior of `to_text`). In other words, rename `to_text` to `display` or `pretty` (Dmitry Bushev - Nov 30, 2022)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for today (2022-12-13):

**Progress:** Started working on the task. Implemented Any.to conversion. Started writing tests. As as side task, did a benchmark of the compilation process, and reported to the thread. As a side task, spent a bit of time trying to reproduce the issue with visualizations reported by Radek in the Advent of Code thread It should be finished by 2022-12-15.

**Next Day:** Next day I will be working on the [#181499256 task](https://www.pivotaltracker.com/story/show/181499256). Continue working on the task (Enso Bot - Dec 13, 2022)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for yesterday (2022-12-14):

**Progress:** Reviewed the issues reported in the AoC threads, and created pivotal tasks under the aoc2022 tag. Reproduced the issue when visualization updates are not showing for collapsed node. Started investigation It should be finished by 2022-12-15.

**Next Day:** Next day I will be working on the [#181499256 task](https://www.pivotaltracker.com/story/show/181499256). Continue working on the task (Enso Bot - Dec 15, 2022)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for today (2022-12-15):

**Progress:** Found separate issue with the language server updates, when the message pointer can be excluded from the update. And some updates are duplicated. Fixed and created a PR. Investigated another issue when the runner got stuck if error happened in the update-manifest job. Fixed as well and created a PR. It should be finished by 2022-12-15.

**Next Day:** Next day I will be working on the [#181499256 task](https://www.pivotaltracker.com/story/show/181499256). Continue working on the task (Enso Bot - Dec 15, 2022)
<hr />
**Dmitry Bushev** reports a new **🔴 DELAY** for yesterday (2022-12-27):

**Summary:** There is **14 days** delay in implementation of the [Fix Text.to_text (#181499256) task](https://www.pivotaltracker.com/story/show/181499256).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** Returning to the issue after we decided on the new approach of fixing to_text. (Enso Bot - Dec 28, 2022)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for yesterday (2022-12-27):

**Progress:** Returned to the fixing to_text after we decided on the new approach. Implemented the new pretty method for pretty printing. It should gradually replace the existing to_text usages. It should be finished by 2022-12-29.

**Next Day:** Next day I will be working on the [#181499256 task](https://www.pivotaltracker.com/story/show/181499256). Continue working on the task (Enso Bot - Dec 28, 2022)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for today (2022-12-28):

**Progress:** Continue working on the task. Fixed to text conversion and made it an identity for Text. Went through stdlib, fixed test and created the PR. It should be finished by 2022-12-29.

**Next Day:** Next day I will be working on the [#181499256 task](https://www.pivotaltracker.com/story/show/181499256). Continue working on the task (Enso Bot - Dec 28, 2022)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for today (2022-12-29):

**Progress:** Continue working on the task. Was working on the review comments. Updated the pretty implementation. Added more tests. Merged the PR It should be finished by 2022-12-29.

**Next Day:** Next day I will be working on the [#181499256 task](https://www.pivotaltracker.com/story/show/181499256). Continue working on the task (Enso Bot - Dec 29, 2022)
<hr />
There are _four unresolved tasks_ in this pivotal. Shouldn't they be marked as fixed, before this story is _accepted_? CCing @dmitry_bushev , @gregociepka - or from a different angle: does it make sense to create _tasks_ in pivotal at all? (jaroslavtulach - Dec 30, 2022)
<hr />
	@jtulach @dmitry_bushev Yes Jaroslav they should. Dmitry please mark them as done if that's accepted. If any of those is still relevant and not done please create separate pivotal issue for it. (Greg Ociepka - Jan 2, 2023)
<hr />
	@jtulach @gregociepka 
All tasks done except "Use `Text.from` instead of `to_text`". It will be fixed in #184088618 by replacing `to_text` with a proper `.to Text` conversion (Dmitry Bushev - Jan 2, 2023)
<hr />
