### ISSUE TITLE
`Any.==` should be a built in

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4822]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/183338334).
<hr />

Currently `Any.==` is implemented within Enso code and takes a significant amount of time to execute (currently depends on Meta a lot). Ideally this would be a built-in method with good performance as this is so fundamental. Moreover the `==` operator shall not be overridden by any type - all the logic shall be in the _builtin_. There are currently following overrides of `==`:
```bash
enso.update$ grep -r '==[a-z ]*=' --include "*enso" distribution/
distribution/lib/Standard/Image/0.0.0-dev/src/Data/Matrix.enso:    == self that = Java_Matrix.is_equals self.opencv_mat that.opencv_mat
distribution/lib/Standard/Image/0.0.0-dev/src/Data/Image.enso:    == self that = Java_Image.is_equals self.opencv_mat that.opencv_mat
distribution/lib/Standard/Base/0.0.0-dev/src/Network/URI.enso:    == self that = self.internal_uri.equals that.internal_uri
distribution/lib/Standard/Base/0.0.0-dev/src/Network/Http/Header.enso:    == self that = (self.name.equals_ignore_case that.name) && self.value==that.value
distribution/lib/Standard/Base/0.0.0-dev/src/Data/Locale.enso:    == self other = case other of
distribution/lib/Standard/Base/0.0.0-dev/src/Data/Boolean.enso:    == self that = @Builtin_Method "Boolean.=="
distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso:    == self that = self.to_vector == that.to_vector
distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso:    == self that =
distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso:    == self that = @Builtin_Method "Decimal.=="
distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso:    == self that = @Builtin_Method "Integer.=="
distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso:    == self that = case that of
distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text.enso:    == self that = if Meta.is_same_object self Text then Meta.is_same_object that Text else
distribution/lib/Standard/Base/0.0.0-dev/src/Data/Any.enso:    == self that = if Meta.is_same_object self that then True else
distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso:    == self that = case that of
distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso:    == self that = case that of
distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Period.enso:    == self that =
distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso:    == self that =
distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Zone.enso:    == self that =
distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso:    == self that = case that of
distribution/lib/Standard/Base/0.0.0-dev/src/Error/Common.enso:    == self that = if Meta.is_error self then self else
distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso:    == self that = @Builtin_Method "File.=="
distribution/lib/Standard/Database/0.0.0-dev/src/Data/SQL_Type.enso:    == self that = case that of
distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso:    == self other = self.make_binary_op "=" other new_type=SQL_Type.boolean
distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso:    == self other =
```
they all need to disappear (except `Database` and `Table` ones which James will handle himself) and be replaced with the logic in `Any.==` builtin. That logic will recognize all _builtin types_ and also provide a generic `==` implementation for all `Atoms`.

There is a [google doc](https://docs.google.com/document/d/10Ee2lJy2LUNfVf4EsToJJmRF2ZVGjPpGE2tNEmC9ruQ) sumarizing to `Any.==` and `hash_code` review discussions.

## Tasks:
- [X] Turn `Any.==` into a builtin
- [X] Remove all other `==` overrides (except in databases)
- [X] Handle `==` for builtin types in the builtin
- [X] Provide generic `==` for `Atom` that delegates to all its components
- [ ] Consider: when comparing two atoms, it'd be great to also compute their hashcode - relates to #181027272
- [X] Create benchmarks for `==`

## Blockers:
[#181908162](https://www.pivotaltracker.com/story/show/#181908162) resolved
[#183369386](https://www.pivotaltracker.com/story/show/#183369386) resolved

## Comments:
If #181027272 is implemented and we have a hashCode inside of each `Atom`, we can significantly speed the negative answer to `Any.==` by comparing the `hashCode`s. (jaroslavtulach - Oct 21, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-12-06):

**Progress:** Implementing `Any.==` builtin specialization for `EnsoDate` so far. Removing `Date.==` and evaluating `date1 == date2` does not dispatch to `Any.==`, but should. Investigating this issue. Turns out it was my stupid mistake with wrong usage of Builtin_Method annotation. It should be finished by 2022-12-16. (Enso Bot - Dec 6, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for yesterday (2022-12-07):

**Progress:** Dealing with weird performance issues of Date.==. Trying to write some specific microbenchmarks for that. Playing with the IDE a bit. It should be finished by 2022-12-16. (Enso Bot - Dec 8, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for yesterday (2022-12-08):

**Progress:** Implementing specializations for various interop types. Proceeding step by step. So far, I have implemented Date, Date_Time, Duration and Period types. Some tests are still failing though. It should be finished by 2022-12-16. (Enso Bot - Dec 9, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-12-12):

**Progress:** Resolved issue with `Date`, and `Date_Time`. Writing more specializations for polyglot arrays, invocable objects, strings, exceptions, primitive types ... It should be finished by 2022-12-16. (Enso Bot - Dec 12, 2022)
<hr />
Would you find [ValuesGenerator](https://github.com/enso-org/enso/pull/3949/files#r1040645210) useful? If so, feel free to copy it. (jaroslavtulach - Dec 13, 2022)
<hr />
> Would you find ValuesGenerator useful? If so, feel free to copy it.

Yes, I definitely would. I will copy it. Thanks. (Pavel Marek - Dec 13, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for yesterday (2022-12-13):

**Progress:** All of the specializations implemented. Vast majority of tests pass, the only failing test is the one that tries to invoke `Map.==`, but can't, because `Any.==` is a builtin method. It should be finished by 2022-12-16. (Enso Bot - Dec 14, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-12-14):

**Progress:** Providing reproducer for https://github.com/oracle/graal/issues/5485. Investigated why `Json.==` does not work - `Json` type has `Map` as its atom field, which overrides `==`. This means that in our `EqualsNode`, in the specialization for atoms, we have to dispatch to `==` on the fields, if there is `==` method. It should be finished by 2022-12-16. (Enso Bot - Dec 14, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for yesterday (2022-12-15):

**Progress:** Fixing tests in filtering SQL tables. It should be finished by 2022-12-16. (Enso Bot - Dec 16, 2022)
<hr />
**Pavel Marek** reports a new **🔴 DELAY** for today (2022-12-16):

**Summary:** There is **3 days** delay in implementation of the [`Any.==` should be a built in (#183338334) task](https://www.pivotaltracker.com/story/show/183338334).
It **will cause 3 days delay** for the delivery of this weekly plan.

**Delay Cause:** Investigation of the issue in database test was painful, spent 1.5 hours on that with Radoslaw. Now, all the tests are passing, but I have not yet compared benchmarks. I will need another day to write benchmarks and compare them to develop. (Enso Bot - Dec 16, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-12-16):

**Progress:** Debugging session with Radoslaw. We have managed to pinpoint the problem with old `==` behavior. Some final touches to my script that downloads all the benchmark engine reports and puts them in CSV files. It should be finished by 2022-12-19. (Enso Bot - Dec 16, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-12-19):

**Progress:** Add new test for recursive atoms without == overriden. Benchmarks for primitive values and recursive atoms. Generating huge vectors of primitive values and recursive atoms. Struggling with custom types in benchmarks. Finally got the benchmarks working, and compared the to develop: for recursive atoms, the performance increased by roughly 20%. Ready to merge. Waiting for reviews It should be finished by 2022-12-19. (Enso Bot - Dec 19, 2022)
<hr />
**Pavel Marek** reports a new **🔴 DELAY** for today (2022-12-20):

**Summary:** There is **3 days** delay in implementation of the [`Any.==` should be a built in (#183338334) task](https://www.pivotaltracker.com/story/show/183338334).
It **will cause 3 days delay** for the delivery of this weekly plan.

**Delay Cause:** I forgot to get rid of all the unnecessary `==` overrides, and had to fix some tests when I have finally done it. Moreover, there are a lot of comments on the PR. (Enso Bot - Dec 20, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-12-20):

**Progress:** Removed all the, now unnecessary, `==` overrides in std lib. Resolving PR reviews. It should be finished by 2022-12-22. (Enso Bot - Dec 20, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-12-21):

**Progress:** Split benchmarks into "equalsPrimitives", "equalsStrings", and "equalsTrees". Will re-measure all the benchmarks on develop and my branch tomorrow. Addressing more comments from reviews. It should be finished by 2022-12-22. (Enso Bot - Dec 21, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-12-22):

**Progress:** Compare benchmarks with develop and integrate remaining review comments. Remove `Error.==` override. PR is ready to merge. I have some failures on the CI now, but they seem spurious. It should be finished by 2022-12-22. (Enso Bot - Dec 22, 2022)
<hr />
**Pavel Marek** reports a new **🔴 DELAY** for today (2022-12-29):

**Summary:** There is **7 days** delay in implementation of the [`Any.==` should be a built in (#183338334) task](https://www.pivotaltracker.com/story/show/183338334).
It **will cause 7 days delay** for the delivery of this weekly plan.

**Delay Cause:** Addressed PR review comments after Christmas, it should be merged today/tomorrow morning. (Enso Bot - Dec 29, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-12-29):

**Progress:** Integrating some PR review comments. Adding some polyglot tests. Have all the required approvals. Waiting for the PR to merge. It should be finished by 2022-12-29. (Enso Bot - Dec 29, 2022)
<hr />
