### ISSUE TITLE
Enso objects should effectively participate in HashMap/HashSet

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4866]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/181027272).
<hr />

This task went/will undergo many changes. See [review meeting nodes](https://docs.google.com/document/d/10Ee2lJy2LUNfVf4EsToJJmRF2ZVGjPpGE2tNEmC9ruQ) document.

### Why

**As library developer**
**I want ** to have a _Map_ that associates values to keys with O(1) time
**So that ** I can effectively implement for example `Vector.distinct`

### Acceptance Criteria

```gherkin
Scenario: 
Given any enso objects that doesn't override `==`
When when it is put into _such a Map_
Then it behaves properly
```

** Polemic **

Exposing both `==` and `hashCode` turns Enso into [Hash Oriented Language](http://wiki.apidesign.org/wiki/Smalltalk) - just like Java is. However @marcinkostrzewa thinks this is the best to do: "I'll be honest with you... I think java is right... it's ugly, it's bad api design, it stinks philosophically and yet it's the best solution I've ever used the alternative is some sort of Hashable interface. which turns out to the same code, but now you have to annotate your objects with it's `Hashable`  it isn't more elegant, it's just more annoying (most languages that go this route make Hashable auto-derivable anyway)"

** How to hide these gory details? **

_Update on Nov 29_ the [inception meeting](https://docs.google.com/document/d/10Ee2lJy2LUNfVf4EsToJJmRF2ZVGjPpGE2tNEmC9ruQ) concluded we need to expose _equality_ and `hash_code` in order to allow proper representation of _rational numbers_ and/or _AVL trees_. E.g. the next plan is unlikely to work:

We want all the Enso objects to be able to participate in the _Map_. We don't want  to expose _hash code_ to the developers (unlike Java) and still have the _Map_ (like JavaScript). To do so, and to make this consistent with `==` we have to prevent `==` to be overridden.  Rather we want `==` to be a built in that provides default behavior. Tracked as #183338334

Moreover there is a problem that `Long(2) != Double(2)` while they are `==` in Enso. To accommodate this difference and hide it, it better to provide own _Map_ implementation ready for Enso objects rather than rely on standard `java.util.HashMap`. Having such implementation makes it possible to tailor it to Enso needs, make it _partial evaluation_ (e.g. **PE**) ready. and still allows the Java code to access it as `java.util.Map`. The idea is that the _Map_ will be created in the Enso code and can  be passed to Java - creating the _Map_ from Java isn't currently supported.

**Constraints**

> OK, what should be the default `hashCode` of Enso `Atom` then - identity just like in Java? Or something computed in constructor based on nested atoms?

computed based on nesting, it must be compatible with `==` - e.g. when two objects are `==` then they must have the same `hash_code`

> Ahh, the default equality does deep comparision...

I think it should be cached lazy computation.

There is a [google doc](https://docs.google.com/document/d/10Ee2lJy2LUNfVf4EsToJJmRF2ZVGjPpGE2tNEmC9ruQ) related to `Any.==` and `hash_code`.

## Tasks:
- [X] Compute `hashCode` for `Atom` objects
- [X] Cache value of `hashCode` for `Atom` objects once computed
- [X] Compute `hashCode` for all the builtins
- [X] Compute `hashCode` for foreign/polyglot values. Probably using `InteropLibary.identityHashCode`
- [X] Design Enso API for the new _Map_
- [X] Make sure the new *Map* conforms to hash interop API
- [X] Make sure the new _Map_ can be viewed from Java as `java.util.Map`
- [X] Polyglot hash maps, like Python dict, are treated as `Map`
- [X] Replace existing `Standard.Base.Data.Map` with the new map, if possible. Or justify why that cannot be done.
- [X] Make sure null/Nothing can be used as a key in the Map

## Blockers:
[#183338334](https://www.pivotaltracker.com/story/show/#183338334) resolved

## Comments:
We could use `org.graalvm.collections.EconomicMap`, which is PE-friendly. So the problem is actually reduced to provide a hashing function for every Enso Atom, and builtin type. Maybe compute hashCode for every atom in its constructor? (Pavel Marek - Oct 26, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-11-15):

**Progress:** Implemented a prorotype and some tests. Hashing atoms and transitively all its fields does not seem to be difficult. HashMap can be implemented via Truffle's PE friendly EconomicHashMap. It should be finished by 2022-11-21. (Enso Bot - Nov 15, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-11-16):

**Progress:** Started a discussion about the design. The main concern is whether we really want our users to override `hash_code` method. It should be finished by 2022-11-21. (Enso Bot - Nov 16, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-11-18):

**Progress:** Got all the inputs from other engine and lib members, now the idea of the implementation is clear, I can move on to actual implementation. It should be finished by 2022-11-21. (Enso Bot - Nov 18, 2022)
<hr />
	Comment for archeological purposes:

**How this is done in Haskell:**

There are two hash tables in Haskell:
- https://hackage.haskell.org/package/base-4.5.0.0/docs/Data-HashTable.html -  mutable data structure and is O(1) but it is imperative and mutable
- https://hackage.haskell.org/package/base-4.5.0.0/docs/Data-HashTable.html - functional O(log n)

EdwardKmett
> we need to talk through what a hashmap is vs. a hash array mapped trie and what the circumstances are here
> Data.HashTable and Data.HashMap in haskell are very different
> the HashMap is a purely functional data structure 
> and has good asymptotics and very good constant factors in practice 

> Data.HashMap is a bit different instead of being a binary tree off of some ordered key, 
> it uses a 16-way fanout off the hashcode. and it uses a cute little popcount indexing scheme to only have 
> as many children as there are actual occupied branches. phil bagwell popularized this first for scala, then
>  it became an idea haskell picked up and ran with
> the asymptotics there are logs, but they are effectively log_16's so the constants are lower than binary trees often by about a factor of 4

> _Cache oblivious_ lookahead array work, which worsens the asymptotics of reads on paper, and 
> in practice reads are about 2x slower, but makes writes 7x faster until you have maybe 50 billion
>  entries or so. 
> https://hackage.haskell.org/package/structures-0.2/docs/Data-Vector-Map.html
> https://www.youtube.com/watch?v=6nh6LpcXGsI

One property of our cache implementation might be: _good to be _partially evaluated_ by Truffle. That probably means the simpler, the better - as it is going to inline well. E.g. simple linear hashing may have its beauty as well.
 (jaroslavtulach - Nov 24, 2022)
<hr />
**Pavel Marek** reports a new **🔴 BLOCKER** for yesterday (2022-11-24):

**Summary:** The [Enso objects should effectively participate in HashMap/HashSet (#181027272) task](https://www.pivotaltracker.com/story/show/181027272) is blocked by the [#183338334 task](https://www.pivotaltracker.com/story/show/183338334).

I expect the blocker to be rather coplicated. Moreover, it is still not 100% clear how to proceed with the whole Enso object hashing and equality. There will be a meeting about that next week. (Enso Bot - Nov 25, 2022)
<hr />
**Pavel Marek** reports a new **🔴 DELAY** for yesterday (2022-11-24):

**Summary:** There is **14 days** delay in implementation of the [Enso objects should effectively participate in HashMap/HashSet (#181027272) task](https://www.pivotaltracker.com/story/show/181027272).
It **will cause 14 days delay** for the delivery of this weekly plan.

**Delay Cause:** There is a major blocker that I have already reported. Until the blocker is finished, I cannot do anything on this issue. (Enso Bot - Nov 25, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for yesterday (2022-11-24):

**Progress:** Updated the PR to be more in sync with the last ideas - added Hash_Map prototype and a way how to efficiently cache the hash codes in atoms. It should be finished by 2022-12-05. (Enso Bot - Nov 25, 2022)
<hr />
**Pavel Marek** reports a new **🔴 DELAY** for today (2022-12-23):

**Summary:** There is **32 days** delay in implementation of the [Enso objects should effectively participate in HashMap/HashSet (#181027272) task](https://www.pivotaltracker.com/story/show/181027272).
It **will cause 32 days delay** for the delivery of this weekly plan.

**Delay Cause:** I have not worked on this issue for a very long time, which was expected and announced. There was an end date that was very outdated. I am updating the end date to the beginning of the January 2023. (Enso Bot - Dec 23, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-12-23):

**Progress:** Implemented Any.hash_code builtin method. Specializations for primitives, arrays, and others. Added tests with ValueGenerator. Added many values to ValueGenerator. It should be finished by 2023-01-06. (Enso Bot - Dec 23, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-12-29):

**Progress:** `Hash_Map.Builder.build` creates snapshots in O(1) - thinking about the implementation. It should be finished by 2023-01-06. (Enso Bot - Dec 29, 2022)
<hr />
	@ensobot 

> thinking about the implementation

`Vector.distinct` needs only `append` & `build` operations. Those two need to be implemented effectively. Always put into the map (Value+Index), when calling `build` remember the highest index present at a moment. Additional `append` (with higher index) will be ignored. Subsequent `build` remembers the new highest index, but otherwise share the same data structure with previous `build`. (jaroslavtulach - Dec 30, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2022-12-30):

**Progress:** Implemented `Hash_Map.Builder` . Operations `insert`, `build` and `get` are in `O(1)`. `Hash_Map.to_vector` caches the vector representation. `Builder.build` returns a snapshot. Created unit test for the hash map. Implemented hash map specific interop messages. Implemented many methods from `Map`. It should be finished by 2023-01-06. (Enso Bot - Dec 30, 2022)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2023-01-02):

**Progress:** Implementing more methods from `Map` into `Hash_Map`. Implementing equality comparison of two hash maps. Our `Hash_Map` should accept polyglot keys, and use nodes for hash code computation and for equality comparison. How to effectively turn  `org.graalvm.collections.EconomicMap` into a map that takes polyglot keys? Optimally, `EconomicMap.get` would take some nodes as arguments, and pass them to our callbacks that compute hash code and compare for equality. We cannot simply save nodes as fields of `HashMapBuilder`, that is a bad practice. Tomorrow, I shall take some inspiration from graalpy, and other truffle langs. It should be finished by 2023-01-06. (Enso Bot - Jan 2, 2023)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2023-01-03):

**Progress:** `Hash_Map` now supports the same API as `Map`. The only difference is in `to_text` method. All tests are passing, especially the old `Map_Spec`. Writing more polyglot tests - foreign maps are treated as Enso maps, can use foreign (Host/polyglot) objects as keys and values to map. Deleted `Hash_Map.Builder` - we have `Hash_Map.insert`, so the builder is no longer necessary. Both `Hash_Map.get` and `Hash_Map.insert` use `EqualsAnyNode` and `HashCodeAnyNode` for searching for a particular key - I had to implement linear probing in order for this to work, but the underlying storage is still `org.graalvm.collections.EconomicMap`.  In the future we may change probing strategy (i.e. what to do when two keys have same hash code, but are not equal) if there are any performance problems. It should be finished by 2023-01-06.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/181027272). Ensure hash code is cached in every `Atom`. (Enso Bot - Jan 3, 2023)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2023-01-04):

**Progress:** Do not implement linear probing in hash map builder, put a reference to `EqualsNode` and `HashCodeNode` into equivalence strategy to `EconomicMap` instead. Stepped on a weird parser failure - created https://www.pivotaltracker.com/story/show/184151801 . Adding more polyglot tests, fixing, ... It should be finished by 2023-01-06. (Enso Bot - Jan 4, 2023)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2023-01-05):

**Progress:** Preparing the implementation for foreign hash map handling - we want to treat foreign hash maps like Enso hashmaps, optimally without any wrapping or conversions - just use Truffle interop API. Add more polyglot hash map tests. Implemented `runInContext` in tests - now, we are able to explicitly create some Truffle nodes and execute them in tests. So far, there are three different types of tests for hash maps. It should be finished by 2023-01-06. (Enso Bot - Jan 5, 2023)
<hr />
**Pavel Marek** reports a new **🔴 DELAY** for today (2023-01-06):

**Summary:** There is **7 days** delay in implementation of the [Enso objects should effectively participate in HashMap/HashSet (#181027272) task](https://www.pivotaltracker.com/story/show/181027272).
It **will cause 7 days delay** for the delivery of this weekly plan.

**Delay Cause:** PR is almost ready for review - I only need to specify some more tests for hash code / equals contract and do some cleanup. As mentioned on previous two meetups, I expect the review to take some time. I will publish the PR for the review on Monday. (Enso Bot - Jan 6, 2023)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2023-01-06):

**Progress:** Fixed rest of the bugs with treating polyglot maps as Enso maps. Specified more polyglot tests. All the tests are passing now. It should be finished by 2023-01-13.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/181027272). Simple benchmark to compare the performance with old Map implemented as binary tree, write more tests for hash code and equals contract. (Enso Bot - Jan 6, 2023)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2023-01-09):

**Progress:** Fixed a bug with comparing NFD normalized strings in both equals and hash_code, with help from Radek. Add tests for hash codes (hash code is used indirectly via singleton hash maps). Fixed hash code computation for recursive atoms. Writing documentation and cleaning up the PR. Should be marked as "Ready for review" tomorrow. It should be finished by 2023-01-13. (Enso Bot - Jan 9, 2023)
<hr />
**Pavel Marek** reports a new **STANDUP** for yesterday (2023-01-10):

**Progress:** Fixing native image build. Adding documentation. Cleaned up the PR before marking as ready for review. Fixed some tests in `Table_Tests`. Removing `Any.hash_code` from tests - use Truffle nodes directly. It should be finished by 2023-01-13. (Enso Bot - Jan 11, 2023)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2023-01-11):

**Progress:** Removing `Any.hash_code` altogether - using Truffle nodes directly. Trying to migrate tests to jUnit theories. Tests work, executing in context, and executing nodes directly works. Seems bit slow though. It should be finished by 2023-01-13. (Enso Bot - Jan 11, 2023)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2023-01-12):

**Progress:** Fixed the performance issue with tests that use jUnit theories. Fixing MetaIsATest. Completely removed Any.hash_code. Fixing some Enso Table tests after merging latest develop. It should be finished by 2023-01-13. (Enso Bot - Jan 12, 2023)
<hr />
**Pavel Marek** reports a new **🔴 DELAY** for today (2023-01-13):

**Summary:** There is **5 days** delay in implementation of the [Enso objects should effectively participate in HashMap/HashSet (#181027272) task](https://www.pivotaltracker.com/story/show/181027272).
It **will cause 5 days delay** for the delivery of this weekly plan.

Radek provided failing test for case when there are non-linear inserts to the map. I am working on a workaround that duplicates the underlying builder in certain cases, but it still does not pass all the tests.

**Delay Cause:** Integrating suggestions from reviews taking too much time. Fixing some bugs after latest develop merge. (Enso Bot - Jan 13, 2023)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2023-01-13):

**Progress:** Handling the case when inserts to map are non-linear - already got something working, but some Json tests are broken now. Added multilevel atoms to `ValuesGenerator`. Fixing some bugs after latest develop merge. It should be finished by 2023-01-18. (Enso Bot - Jan 13, 2023)
<hr />
Split the issue to https://www.pivotaltracker.com/n/projects/2539304/stories/184236714 (Pavel Marek - Jan 16, 2023)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2023-01-16):

**Progress:** Fixing tests with non-linear key insertions. Turns out there can be some complicated situations. Wrapping my head around some failing corner cases, and how should the newly duplicated `HashMapBuilder` should look like. Most of the tests are now successful. It should be finished by 2023-01-18. (Enso Bot - Jan 16, 2023)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2023-01-17):

**Progress:** Finished the PR - finished non-linear key inserts workaround, added some tests, got all the approvals. At first, performance was bad, but managed to improve it with `@TruffleBoundary(allowInline=true)`. Now, the performance is for text vectors 3x better than old map, and roughly the same for integer vectors (`Vector.distinct` benchmark). There is some test that connects via JDBC that fails, because it tries to call something like `java.util.Properties.removeKey` - I have to implement `Map.remove` for that. Should be straightforward. It should be finished by 2023-01-18. (Enso Bot - Jan 17, 2023)
<hr />
**Pavel Marek** reports a new **STANDUP** for today (2023-01-18):

**Progress:** Implemented Map.remove. Didn't help with Postgres tests. How to reproduce them? Tried to initialize Postgres in Docker, but bailed out after some time - too much work. Add some logging to see what is going on in CI. Found out, that I should invoke methods on java.util.Properties with Polyglot.invoke. Found small reproducer. Works locally. Pushing, and hope that everything works and will merge in the night. If not, tomorrow morning. Meanwhile working on Book club week 2 and compiling some notes. It should be finished by 2023-01-18. (Enso Bot - Jan 18, 2023)
<hr />
