### ISSUE TITLE
Get Espresso ready for use in Enso/Java Interop

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4877]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/183260380).
<hr />

#182486022 investigates whether Enso can be built by Native Image - yes, it can. An open question however is: How shall we load the:
```
polyglot java import xyz
```
statements? Can we use [Espresso](https://github.com/oracle/graal/tree/master/espresso)?

Yes, we can, once the remaining glitches are fixed. Make sure you have GraalVM 22.1+ and try this [commit](https://github.com/enso-org/enso/commit/e1b2e1cc5883fd907ae67ef2acbe5e2a8ecaadd0). Make sure `gu install espresso` is installed. Engine can then execute:
```
polyglot java import java.lang.System

main =
    System.console.printf "Hello World!  ...   " empty_arr
    result System.currentTimeMillis



foreign js result x = """
    throw x;

foreign js empty_arr = """
    return [ ];

```
e.g. it can import `java.lang.System`, call `currentTimeMillis` method on it and even invoke `System.console.printf`. 

The goal of this story is to track the additional issues that need to be resolved.

## Tasks:
- [X] Allow calls to overloaded methods - e.g. call `System.out.println`
- [X] Dynamically add JARs to the Espresso runtime
- [X] Add a switch to [use Espresso instead](https://github.com/enso-org/enso/commit/e1b2e1cc5883fd907ae67ef2acbe5e2a8ecaadd0) of Host-interop

## Blockers:
[#182845176](https://www.pivotaltracker.com/story/show/#182845176) resolved

## Comments:
Reported https://github.com/oracle/graal/issues/4939 to the Espresso team. (jaroslavtulach - Sep 13, 2022)
<hr />
Espresso improvements [PR-4954](https://github.com/oracle/graal/pull/4954) has just been merged into `master` branch of GraalVM. However after [testing the latest version b88490b](https://github.com/oracle/graal/issues/4939#issuecomment-1269480771) I realized that while `Integer.valueOf` works, `System.out.println` still doesn't. (jaroslavtulach - Oct 6, 2022)
<hr />
I've just updated https://github.com/enso-org/enso/tree/wip%2Fjtulach%2Fespresso_183260380 branch on top of most recent `develop` and used most recent GraalVM with [PR-5694](https://github.com/oracle/graal/pull/5694) bugfix. `IO.println` now works!

Steps to reproduce:
```bash
graalvm/graal/vm$ git checkout b0a1bc977a94a85ae323d5e6279e8d568eaa817e
graalvm/graal/vm$ git log | head -n3
commit b0a1bc977a94a85ae323d5e6279e8d568eaa817e
Author: Allan Gregersen <allan.gregersen@oracle.com>
Date:   Mon Jan 9 09:32:22 2023 +0100
graalvm/graal/vm$ mx --dy /espresso,graal-js,graalpython,truffleruby build
graalvm/graal/vm$ ./latest_graalvm_home/bin/espresso --version
openjdk 11.0.15 2022-04-19
OpenJDK Runtime Environment GraalVM 23.0.0-dev (build 11.0.15+7-jvmci-22.1-b04)
Espresso 64-Bit VM GraalVM 23.0.0-dev (build 11-espresso-23.0.0-dev, mixed mode)
```
and then I set `graalvm/graal/vm/latest_graalvm_home` as my JDK and rebuild and re-run Espresso. Following program:
```haskell
import Standard.Base.IO

main = IO.println <| "Hello World!"
```
executed as 
```bash
enso$ ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --run ~/h.enso
Hello World!
```
prints a lot of warnings, but also the desired `Hello World!` message! (jaroslavtulach - Jan 11, 2023)
<hr />
Since [39e87014](https://github.com/enso-org/enso/commit/39e87014d35668e94f98e6dbbff6a34c892a0e4f) we dynamically add JARs to Espresso. One can use `ENSO_JAVA=hosted` to run without Espresso - or don't set the value to use Espresso. Certain tests can be executed properly. Certain fail. Interop between `EnsoDate` & Espresso needs some improvements - tracked as [PR-5041](https://github.com/oracle/graal/issues/5041) (jaroslavtulach - Jan 16, 2023)
<hr />
Final conclusions. There is a commit [af84531963](https://github.com/enso-org/enso/commit/af8453196395bcaf30913748de105556f65ea628) on the branch [espresso_183260380](https://github.com/enso-org/enso/compare/wip/jtulach/espresso_183260380). With that commit one can perform following experiment.

### Building

Build 23.x version of [GraalVM](https://github.com/oracle/graal/):
```bash
graal/vm$ git log | head -n5
commit 27863428b0fd617797f246304be2df935f1b0233
Date:   Sun Jan 15 00:36:52 2023 +0000
graal/vm$ mx --java-home /labs-17 --native-image=nic --dy graal-js,/substratevm,/espresso build
```
and then use the JDK created in `latest_graalvm_home` to build Enso from the commit [af84531963](https://github.com/enso-org/enso/commit/af8453196395bcaf30913748de105556f65ea628):
```bash
enso$ sbt --java-home /graal/vm/latest_graalvm_home bootstrap
enso$ sbt --java-home /graal/vm/latest_graalvm_home buildEngineDistribution
enso$ sbt --java-home /graal/vm/latest_graalvm_home engine-runner/buildNativeImage
Finished generating 'runner' in 5m 17s.
[info] Native Image build successful.
[success] Total time: 445 s (07:25)
```
a file `runner` is created in the root of the enso repository.

### Running

With the compiled `./runner` you can execute a simple hello world program:
```haskell
import Standard.Base.IO
polyglot java import java.lang.System

main = 
    vm = System.getProperty "java.vm.version"
    IO.println <| "Hello World from " + vm
```
put the above into `h.enso` file and then you can:
```bash
enso$ JAVA_HOME=/graal/vm/latest_graalvm_home ./runner --run h.enso
Hello World from 17-espresso-snapshot
```
bunch of exceptions is printed too but clearly Espresso can be used for interop via standard Enso libraries.

### Conclusion

Espresso can replace the classical Java interop. However it doesn't deliver so expected fast startup as it is slower to boot than JVM. It doesn't matter Enso starts fast when compiled by native image. As soon as a Java interop is requested, Espresso needs to boot and that takes time. The above "hello world" program takes 4s to print its output. If I run it with regular Enso:
```bash
enso$ sbt --java-home /graal/vm/latest_graalvm_home runtime/clean buildEngineDistribution
enso$ ENSO_JAVA=hosted JAVA_HOME=~/bin/graalvm-dev/ time ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --run h.enso
Hello World from 17.0.6+2-jvmci-23.0-b04
```
it similarly takes also 4s. The slowness is caused by initializing Espresso as can be seen by running a program that doesn't need Java interop:
```haskell
main = "Hello world!"
```
that takes just 0.15s:
```
enso$ JAVA_HOME=/graal/vm/latest_graalvm_home/ time ./runner --run h.enso 
'Hello World'
0.02user 0.03system 0:00.15
``` (jaroslavtulach - Jan 18, 2023)
<hr />
**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2023-01-18):

**Progress:** Closed the "Espresso issue" by writing summary of investigation://www.pivotaltracker.com/story/show/183260380/comments/235121649; send email to OracleLabs guys; created new new "investigation" task: https://www.pivotaltracker.com/n/projects/2539304/stories/184256209; meetings and planning; one more bugfix for https://github.com/enso-org/enso/pull/4021/commits/aff9255cffa4404a7a2a9f1167afb2146a425aaf; reproducing and analyzing: https://www.pivotaltracker.com/story/show/184249780/comments/235124894; duplicating and closing: https://www.pivotaltracker.com/n/projects/2539304/stories/184151801 It should be finished by 2023-01-19.

**Next Day:** Enable asserts in tests & bugfixes (Enso Bot - Jan 19, 2023)
<hr />
