### ISSUE TITLE
Improve Enso's peak performance that is slower than other Truffle languages by not boxing numbers

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4892]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/182485940).
<hr />

### Why

**As Enso User**
**I want my programs to run fast **
**So that they can process my bigdata workloads more quickly**

### Acceptance Criteria

```gherkin
Scenario: 
Given sieve of Eratosthenes program
When written in Enso
Then it shall run as fast as when written in GraalVM JavaScript or Python
```

**Notes:**

Currently the Enso version is eight times slower than JavaScript one.

## Tasks:
- [X] Run the program obtain IGV graphs
- [X] Search the IGV graphs for needless allocations/invocations
- [X] Rewrite parts of the code to JavaScript and compare
- [X] Don't box Long/Double when stored in Atom
- [ ] Prototype and measure what it would take to not box long in the `Filter` atom of [sieve.enso](https://github.com/jtulach/sieve/blob/5b32450da35415322e683bb9769aa45f0d71f1df/enso/sieve.enso) implementation
- [ ] Create a List<long> benchmark to demonstrate the speed up at the end

## Comments:
The [sieve.enso](https://github.com/jtulach/sieve/blob/5b32450da35415322e683bb9769aa45f0d71f1df/enso/sieve.enso) program uses _unsafe_, but as such it should have the same runtime characteristics as the [JavaScript](https://github.com/jtulach/sieve/blob/5b32450da35415322e683bb9769aa45f0d71f1df/js/sieve.js) version. However it is eight times slower.

Build Enso distribution with `sbt buildEngineDistribution` then use:
```
PATH=/graalvm/bin/$PATH
./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --run sieve.enso
```
Use `JAVA_OPTS` to obtain the IGV graphs:
```
JAVA_OPTS=-Dgraal.Dump=:1 ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --run sieve.enso 
```
 (jaroslavtulach - Jun 16, 2022)
<hr />
	Just looking at the IGV graphs didn't show anything significantly wrong - at least there were no invocation of not-inlined methods. However the graph is huge and it is not easy to find out what is going on even with all [the new tools](https://github.com/enso-org/enso/tree/develop/tools/enso4igv) we have. However yesterday I got an idea: What if parts of the code are rewritten to JavaScript?
- rewriting the `natural` number generator to JavaScript didn't speed anything up: https://github.com/jtulach/sieve/commit/6361017bf5f6f5851254e8bf305e8ce57b23bbb3
- rewriting the `Filter` linked list makes the execution 50% faster! Compare: https://github.com/jtulach/sieve/commit/32186dd6f507b55f99b7994a59c6fca95b0143bf

Instead of 320ms for a single round we got down to 160ms (that'd be comparable with Python GraalVM implementation). Future investigation shall thus focus on this _Filter linked list_ area to find out what is slowing Enso down. **Update on Aug 5**: The hypothesis after discussion with @marcinkostrzewa1 is that the problem is boxing of number values. Enso creates twice as much objects than JavaScript because each number is wrapped into `java.lang.Long`. (jaroslavtulach - Jul 1, 2022)
<hr />
I rewrote the [sieve.enso](https://github.com/jtulach/sieve/commit/5ff0f8881aed3d0b772c532e22665361ad8f0854) and I know that it is using `Layout_Atom_1_1` to store the `Filter.Item`, but it still takes more than 300ms.

Reported as #184345250 chore for future investigation. (jaroslavtulach - Jan 29, 2023)
<hr />
