### ISSUE TITLE
Build script updates / cleanups for precompiling shaders

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4926]
This task is automatically imported from the old Task Issue Board and it was originally created by Michał Urbańczyk.
Original issue is [here](https://www.pivotaltracker.com/story/show/184214607).
<hr />

No description provided.

## Tasks:
- [X] Make it work on Windows
- [X] Make it use build script functions
- [X] Building spirv-cross
- [X] Repackaging shaderc
- [X] Hosting and downloading all the tools
- [X] Code cleanup

## Comments:
**Michał Urbańczyk** reports a new **STANDUP** for today (2023-01-25):

**Progress:** Participating in AMA. Code cleaning, applying CR feedback and minor fixes. Some preliminary debugging of Windows-specific issues with file locking. Discussing all these with Wojciech. It should be finished by 2023-01-26.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/184214607). Time Off. (Enso Bot - Jan 25, 2023)
<hr />
