### ISSUE TITLE
Developers should be able to use the rustc version in line with the Rust 1.66.0 release

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4954]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/184229094).
<hr />

## Description
This ensures our code is compiled with an up-to-date compiler, which allows us to use more new rust features, avoids us into running old compiler bugs, potentially speeds up compilation and ensures that all our dependencies still support the compiler version we use. 

This requires bumping of the tool chain in the `rust-toolchain.toml` and fixing all new errors and warnings that appear. In general, this should not take too long, but if larger fixing of legacy code is required, this should be spun out into a separate task that is blocking this chore.

## Tasks:
- [X] Bump compiler version
- [X] Check new warnings / errors
- [X] Create separate tasks for larger refactoring required to fix warnings / errors
- [X] Fix all warnings / errors

## Comments:
**Michael Mauderer** reports a new **STANDUP** for yesterday (2023-01-12):

**Progress:** Finished the cleanup of the Lazy Text PR and requested reviews of the updated PR. Started working on the Rust Bump. It should be finished by 2023-01-17.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Continue work on the rust bump, do bookclub task. (Enso Bot - Jan 13, 2023)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (2023-01-13):

**Progress:** Did the book club task. Continued work on the rust bump. There appears to be a compiler bug that prohibits some tedious updates to be applied via the Clippy fix command, but no major blockers appeared so far. It should be finished by 2023-01-17.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Finish rust bump. (Enso Bot - Jan 13, 2023)
<hr />
**Acceptance/QA** review set to **pass** (Michael Mauderer - Jan 31, 2023)
<hr />
