### ISSUE TITLE
Freeze Mode in the engine

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5004]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/184161332).
<hr />

[PR-3942](https://github.com/enso-org/enso/pull/3942) implemented _Implement SKIP/FREEZE in parser/TreeToIr_ - the implementation removes the `FREEZE` macro from the IR. That's probably not correct.

The engine has to recognize the `FREEZE` macro and propagate it thru `IR` and `Truffle` nodes, so `IdExecutionInstrument` sees it and can modify the caching behavior according to it.

The [specification says](https://github.com/enso-org/design/blob/main/epics/component-browser/design.md#icons-1): 

> Freeze Mode
In case the Freeze Mode is activated, the output of the node should not be recomputed even if the expression on the node is edited. If the visualization is shown, it should not be updated neither, but it should have a warning caption about enabled Freeze Mode during expression editing.

## Notes
After discussing the issue, decided that we can implement the desired FREEZE behavior on the compiler level. What we need to do is
- Update IR to store the information about whether the nodes is frozen or not (FREEZE flag)
- Extract this information during the compilation (probably an extra compiler phase is needed)
- Do not invalidate the cache for the frozen nodes (with the FREEZE flag)
- The case when the node gets unfrozen is a bit tricky. I can see two solutions here, we can either
  - Compare new and previous IRs to identify that the node's state has changed (FREEZE flag was removed), and drop the cache for this node.
  - Maintain a set of "changed but frozen" nodes for which we keep the cached value. When the FREEZE flag is removed, invalidate the cache depending on whether or not it was changed in the past (i.e. if the node is in the "changed but frozen" list). In this case we get an optimization that we don't invalidate the cache for nodes that were not changed. After a second thought, I think that this is the desired logic because the previous case with comparing IRs can be intricate and difficult to do right.

## Tasks:
- [ ] Represent FREEZE macro in the IR
- [ ] Extract FREEZE information from the compiler
- [ ] Do not invalidate cache for frozen nodes
- [ ] Handle unFREEZE operation (somehow)

## Blockers:
[#183919788](https://www.pivotaltracker.com/story/show/#183919788) blocked
[#183413964](https://www.pivotaltracker.com/story/show/#183413964) blocked

## Comments:
**I am TFO!** Few months ago I was discussing support for `FREEZE` with @wdanilo and Wojciech told me that the goal for `FREEZE` is to download and cache necessary bits inside of the project. E.g. not to do _caching_ just while the IDE is running, but make the _caching persistent_! My fault for not remembering this, sorry.

The design we created here doesn't support **persistent caching**. E.g. it is not good enough.

Moreover the _freeze button_ is going to be removed from the January release UI. E.g. we are not in hurry.

I am closing this pivotal for now. (jaroslavtulach - Jan 9, 2023)
<hr />
The caching for `FREEZED` nodes needs to be persistent. (jaroslavtulach - Jan 9, 2023)
<hr />
