### ISSUE TITLE
Review `Missing_Input_Column` and `Column_Index_Out_Of_Range` warnings

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5010]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/184226383).
<hr />

In general, if a column is missing (or index is invalid) it should be an error unless it will not cause an error.
Add `allow_missing_columns` to control behavior. In general, defaults to `False` (except for `remove_columns` and `reorder_columns`).  If true then the problem will follow the `on_problems` behaviour.

Functions:
- select_columns
- rename_columns
- order_by
- distinct
- transpose
- remove_columns (allow_missing_columns=True)
- reorder_columns (allow_missing_columns=True)
- filter (no allowing for missing columns)
- set (no allowing for missing columns)
- join (no allowing for missing columns) 

One slightly more involved one, `aggregate`:
- If a Group By then a hard error.
- If a computed aggregation, then follow Problem_Behavior and drop the column.
  - Can result in a hard error if all columns dropped (warnings promoted to error in this case).

`cross_tab` follows the same as `aggregate`: `group_by` and `name_column` follow Group_By, rest are computed.

## Tasks:
- [ ] Update tests
- [X] Update code
- [ ] Update docs: rename, reorder, remove
- [X] Figure out cross_tab and aggregate - do we add allow_missing?
- [X] Selectors
- [X] Order by, distinct
- [X] Transpose
- [X] Filter, set
- [X] Join
- [X] Aggregate
- [X] Cross_tab
- [ ] Update tests: Invalid_Aggregate
- [ ] Update docs: order by, distinct
- [ ] Update docs: transpose
- [ ] Update docs: aggregate, cross_tab

## Comments:
allow->error_on_missing_columns (Radosław Waśko - Feb 1, 2023)
<hr />
aggregate and cross_tab - have the error_on_missing control but it applies only to the computed fields, not group by (Radosław Waśko - Feb 1, 2023)
<hr />
**Radosław Waśko** reports a new **STANDUP** for yesterday (2023-02-01):

**Progress:** Updated specification and tests for select,remove, reorder,rename,order_by,distinct,transpose; verified that filter, join and set seem to be up-to-spec. It should be finished by 2023-02-03.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/184226383). Clarify some more stuff, do the adjustments for aggregate and cross_tab. Update docs, prepare PR. (Enso Bot - Feb 2, 2023)
<hr />
**Radosław Waśko** reports a new **STANDUP** for yesterday (2023-02-02):

**Progress:** Some bookclub bookkeeping as requested. Work on aggregate errors, further clarifying specification. It should be finished by 2023-02-03.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/184226383). Finish cross_tab, check expression errors in aggregate. Prepare a PR. (Enso Bot - Feb 3, 2023)
<hr />
