### ISSUE TITLE
Consistent ordering for `<`, `>`, `<=` and `>=`

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5017]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/183958734).
<hr />

#183945328 introduces the concept of _ordered_ and _unordered_ **comparators** acquired from any object with `Comparable.from` function. Ordered comparators have `compare` method. The goal of this story is to implement all comparison operators `<`, `<=`, `>`, and `>=` with this method.

There is an experimental [DefaultCustomEq branch](https://github.com/enso-org/enso/compare/develop...JaroslavTulach:enso:jtulach/DefaultCustomEq) that already does that. The goal of this story is to extract the useful parts from that branch and polish them for production.

Currently the branch [delegates to compare_to method](https://github.com/enso-org/enso/compare/develop...JaroslavTulach:enso:jtulach/DefaultCustomEq#diff-8e879d3a1f4d00ff84bbde0ce7c694d9f1963b8f4a0e1c1debb18d9c84d131bdL707) in many cases. The goals is to reverse the dependency. The type _comparator_ shall be the primary source of ordering. `compare_to` methods will just delegate to it (if they have to exist at all).

This story isn't as essential as #183338334 and #181027272, however when we get the `Comparable.from` mechanism by #183945328 it feels natural to extrapolate it to ordering as well.

- When two objects `x` and `y` are incomparable, `x < y` should throw `Incomparable_Values` error (confirmed with James).
- Should we get rid of `compare_to` method at all?
  - They can still exist, but at least have to delegate to `Comparator.compare`.

## Tasks:
- [x] Extract definition of `Any.>=` & co. and make them work with `Any.comparator` as shown on the [DefaultCustomEq branch](https://github.com/enso-org/enso/compare/develop...JaroslavTulach:enso:jtulach/DefaultCustomEq)
- [x] Rewrite all `compare_to` methods to delegate to `Any.comparator`
- [X] Consider not throwing "illegal type" error but rather returning `False` if two objects in `Any.<` (and co.) aren't comparable

## Blockers:
[#183945328](https://www.pivotaltracker.com/story/show/#183945328) blocked
[#184380208](https://www.pivotaltracker.com/story/show/#184380208) blocked
