### ISSUE TITLE
Investigate why Enso is still slow on `sieve` example

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5077]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/184345250).
<hr />

This is a continuation of https://www.pivotaltracker.com/story/show/182485940/comments/235284607 - it was known that

Rewriting the `Filter` linked list to JavaScript makes the execution 50% faster! Compare: https://github.com/jtulach/sieve/commit/32186dd6f507b55f99b7994a59c6fca95b0143bf

it was believed that using [unboxed atoms](https://www.pivotaltracker.com/story/show/182485940) will get us closer to the speed of JavaScript. But it doesn't

[My comment](https://www.pivotaltracker.com/story/show/182485940/comments/235284607) concluded: I rewrote the [sieve.enso](https://github.com/jtulach/sieve/commit/5ff0f8881aed3d0b772c532e22665361ad8f0854) and I know that it is using `Layout_Atom_1_1` to store the `Filter.Item`, but it still takes more than 300ms.

The goal of this task is to investigate why we are still over 300ms and not down to 150ms.

## Tasks:
- [ ] Check IGV graphs
- [ ] Try to rewrite (different) parts of the code to JavaScript
- [ ] Nail down where the problem is
- [ ] Schedule subsequent work

## Blockers:
[#182485940](https://www.pivotaltracker.com/story/show/#182485940) blocked

**Comment by Akirathan** [comment]
Today, on the latest develop: 
![image](https://user-images.githubusercontent.com/14013887/225031653-bff9456b-2cf6-4bc1-9305-ea7533824e85.png)

Let's keep this issue still open.

**Comment by JaroslavTulach** [comment]
Things haven't been improved and we may get bitten by this problem when we use JavaScript for something important. Anyway I've just realized that [Sieve & JavaScript benchmarks](https://enso-org.github.io/engine-benchmark-results/stdlib-benchs.html#org_enso_benchmarks_generated_Sieve_Java_Script_File) do not seem to be running.

**Comment by Akirathan** [comment]
> Anyway I've just realized that [Sieve & JavaScript benchmarks](https://enso-org.github.io/engine-benchmark-results/stdlib-benchs.html#org_enso_benchmarks_generated_Sieve_Java_Script_File) do not seem to be running.

There is a failure in stdlib benchmarks when running `Sieve.Java_Script_File`, the latest benchmark run with the failure is at https://github.com/enso-org/enso/actions/runs/12226462185/job/34101757695#step:7:8321

Created new issue for that - https://github.com/enso-org/enso/issues/11808

<blockquote><img src="https://opengraph.githubassets.com/fe5ff76314504dca217159d62101c3b6e42c2f20fc31d3ddcc18ca5e6d47b49b/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Benchmark Standard Libraries · enso-org/enso@81b0fcc</a></strong></div><div>Enso Analytics is a self-service data prep and analysis platform designed for data teams. - Benchmark Standard Libraries · enso-org/enso@81b0fcc</div></blockquote>
