### ISSUE TITLE
Stackoverflow invoking `==` in sieve.enso

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5078]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/184345109).
<hr />

While trying to [measure effect of unboxed atoms](https://www.pivotaltracker.com/story/show/182485940/comments/235284607) on performance of _sieve of Eratosthenes_ written in Enso I got following error:
```
Execution finished with an error: Resource exhausted: Stack overflow
        at <enso> Any.==(Internal)
        at <enso> case_branch<arg-0>(sieve.enso:54:12-22)
        at <enso> case_branch(sieve.enso:54:9-70)
        at <enso> Primes.next(sieve.enso:50-54)
        at <enso> sieve.compute_nth_prime<arg-2>(sieve.enso:61:10-15)
        at <enso> Boolean.if_then_else(Internal)
        at <enso> sieve.compute_nth_prime(sieve.enso:60-62)
        at <enso> sieve.main(sieve.enso:67:9-34)
```
looks like the current `Any.==` implementation isn't ready for deep (one hundred thousand prime numbers) data structures.

To reproduce get [sieve.enso](https://github.com/jtulach/sieve/commit/enso-stack-overflow) and run it. The fix shall replace the current _depth-first-check_ in `Any.==` with a queue comparing `Atom` instances off the stack when the depth is higher than some constant limit.

**Expected** result is: the invocation of `==` for `Filter` works even on deep structure and the current workaround of using `Meta.is_same_object` can be removed.

## Tasks:
- [ ] Switch to queue when depth of Atom structures is too high
- [ ] Verify `==` can be used when comparing `Filter`
- [ ] (optional) include `sieve.enso` in Enso test suite

## Blockers:
[#182485940](https://www.pivotaltracker.com/story/show/#182485940) blocked

**Comment by JaroslavTulach** [comment]
This error hasn't been seen for ages.
