### ISSUE TITLE
JOB_PARALLELISM option isn't registered when running runtime-with-instruments test

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5084]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/184333049).
<hr />

[PR-4074](https://github.com/enso-org/enso/pull/4074) has to introduce a workaround for problems with not registered `JOB_PARALLELISM_KEY` when running `sbt runtime-with-instruments/test`. They fail with `AssertionError`.

The [workaround is here](https://github.com/enso-org/enso/pull/4074#discussion_r1088077307). 

The goal of this task is investigate why the `JOB_PARALLELISM_KEY` is missing and remove the workaround.

## Tasks:
- [ ] Why the  `JOB_PARALLELISM_KEY` is missing?
- [ ] Fix the problem in a standard way
- [ ] Remove the [workaround](https://github.com/enso-org/enso/pull/4074#discussion_r1088077307).

## Blockers:
[#183546453](https://www.pivotaltracker.com/story/show/#183546453) resolved
[#183935964](https://www.pivotaltracker.com/story/show/#183935964) blocked
- [x] #5298

**Comment by JaroslavTulach** [comment]
This is an old issue, maybe no longer valid. Hubert, please take a look and evaluate it.

**Comment by JaroslavTulach** [comment]
Nobody complains. Closing.
