### ISSUE TITLE
Improve initial UX by not sending documentation in suggestion DB

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5091]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/184117587).
<hr />

According to [Dmitry's measurements](https://discord.com/channels/401396655599124480/1055451457576509501) we can speed the initial user experience by 20%:

> turned out the LS spend ~5 seconds in `generateDocumentation` method during
> the startup (of overall ~25 seconds startup time on my machine). So, we can 
> easily shave off ~20% of startup time by at least delaying the sections building.

Making sure the initial _suggestion DB_ is as compact as possible and sending all other information on demand is a standard way to improve the perceived performance. As a prior work, let's mention that the NetBeans IDE _database_ doesn't contain documentation. As a result _code completion_ (aka drop downs) are filled immediately (as they are in the DB), but only when the user selects individual choice a request to the backend is send to provide documentation. Similar system deserves to be adopted by Enso.

### Acceptance Criteria

* redesign the LS protocol to allow _on demand_ request for documentation
* remove the documentation from _suggestion DB_
* speed up the startup of the engine when opening new project by 20%

## Tasks:
- [ ] Confirm the possible speed up is really 20%
- [ ] Delay sending the documentation updates "for later"
- [ ] Measure the decrease in size of suggerstion DB transferred at begining

## Comments:
	```diff
diff --git a/engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala b/engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
index 7a9a0d399..4d2ccb796 100644
--- a/engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
+++ b/engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
@@ -726,36 +726,7 @@ final class SuggestionsHandler(
     * @return the suggestion with documentation fields set
     */
   private def generateDocumentation(suggestion: Suggestion): Suggestion =
-    suggestion match {
-      case module: Suggestion.Module =>
-        val docSections = module.documentation.map(docSectionsBuilder.build)
-        module.copy(documentationSections = docSections)
-
-      case constructor: Suggestion.Constructor =>
-        val docSections =
-          constructor.documentation.map(docSectionsBuilder.build)
-        constructor.copy(documentationSections = docSections)
-
-      case tpe: Suggestion.Type =>
-        val docSections = tpe.documentation.map(docSectionsBuilder.build)
-        tpe.copy(documentationSections = docSections)
-
-      case method: Suggestion.Method =>
-        val docSections = method.documentation.map(docSectionsBuilder.build)
-        method.copy(documentationSections = docSections)
-
-      case conversion: Suggestion.Conversion =>
-        val docSections = conversion.documentation.map(docSectionsBuilder.build)
-        conversion.copy(documentationSections = docSections)
-
-      case function: Suggestion.Function =>
-        val docSections = function.documentation.map(docSectionsBuilder.build)
-        function.copy(documentationSections = docSections)
-
-      case local: Suggestion.Local =>
-        val docSections = local.documentation.map(docSectionsBuilder.build)
-        local.copy(documentationSections = docSections)
-    }
+    suggestion
 }
```

This diff disables the `generateDocumentation` logic. According to [my measurement](https://discord.com/channels/401396655599124480/1070399718649237514/1070708726757064714) the startup time goes down from 11.9s to 11.0s - not really 20%, but it would be an important speed up.  (jaroslavtulach - Feb 2, 2023)
<hr />

**Comment by jdunkerley** [comment]
Very related #5068 - possibly this ticket can be closed once that one is done.

**Comment by jdunkerley** [comment]
This was an alternative to #5068 - so closing as not doing.
