### ISSUE TITLE
Investigate Compilation of StdLib by Native Image

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5093]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/184256209).
<hr />

The investigation of using Espresso to handle Enso/Java interop (#183260380) showed that Espresso isn't currently able to start quickly enough to speed the startup of `enso` interpreter.

Another idea to speed things up is to compile the standard libraries with Native Image as well. This pivotal is reported as a memento to track that effort.

## Tasks:
- [ ] Include stdlib JARs during NI build time
- [ ] Write a feature to mark necessary classes for reflection
- [ ] Demonstrate "hello world" speed

## Blockers:
[#183260380](https://www.pivotaltracker.com/story/show/#183260380) resolved
