### ISSUE TITLE
Split graph node into separate widgets

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5134]
This task is automatically imported from the old Task Issue Board and it was originally created by Paweł Grabarz.
Original issue is [here](https://www.pivotaltracker.com/story/show/184023656).
<hr />

Part of https://www.pivotaltracker.com/story/show/183970089

Currently graph node is constructed using single text view. This solution is not compatible with widgets integration, which will each require their own separate layout and shapes.

- Remove common text view from graph node. Replace it with individual widgets.
- Appropriate widgets should be selected based on AST description provided by the engine. To remain backward compatible, a simple fallback widget should be used for non-recognized widget types.
- In edit mode, the individual widgets should be navigable as if they were a single line of text. Details of this interaction needs to be discussed and decided as part of this task.

## Comments:
	@pawelgrabarz - we need to clarify if this is needed for release. Can you organize a discussion with @wdanilo so we can decide if needed for release?
Please explain in more detail what is needed post that meeting. (James Dunkerley - Feb 3, 2023)
<hr />

```[tasklist]
### Tasks
- [ ] https://github.com/enso-org/enso/issues/5920
- [ ] https://github.com/enso-org/enso/issues/5919
- [ ] https://github.com/enso-org/enso/issues/5921
- [ ] https://github.com/enso-org/enso/issues/5923
```

**Comment by sylwiabr** [comment]
@Frizi @wdanilo please confirm as asked in the comment

**Comment by Frizi** [comment]
This will be a possible prior to https://github.com/enso-org/enso/issues/5631. This task is not necessary for existing dropdown widgets to function, but it will allow more complete dropdown widget design to be implemented.

The most complex part of this task is:
> In edit mode, the individual widgets should be navigable as if they were a single line of text. 

We might want to split that into separate task, and for now rely on node edit mode reverting back to being displayed as a simple line of code. Individual widget types will manage editing of their content appropriately to each case, e.g. dropdown modifying the value on selection, or boolean editor switching between true/false on click. That interaction doesn't involve entering the node edit mode at all.

**Comment by Frizi** [comment]
```[tasklist]
- [ ] Add minimal hierarchical widget definition - an enum variant with child widgets.
- [ ] handle edit mode with a single long editable text, hiding widgets. In edit mode, interactions other than manually editing text are not available.
    - If node is externally updated during edit, that update must be accepted when edit node is cancelled (on esc).
- [ ] build widget tree from span tree, with root widget that handles displaying more widgets
    - The node will contain Root widget, that handles top-level mouse interaction and contains other widgets.
    - Do not handle coloring of text nodes based on types. New designs will not use them anyway.
    - This task will introduce two new widget types: hierarchy widget that contains other widgets, and a text widget.
    - In case it makes the task easier, the existing widget layout might be modified, as long as the functionality is preserved.
    - Widgets will be treated as ports, which can be replaced as a whole during connection. The same logic applies to nested widgets.
- [ ] Implement dropdown widget style according to design.
- [ ] Display vector builder widget as part of node widget hierarchy.
```
