### ISSUE TITLE
Remove Scala based Parser

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5163]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/183900531).
<hr />

The new parser is successfully being used. New features are about to be implemented. It makes less and less sense to keep the old parser around. Let's remove it.

## Tasks:
- [ ] Move old parser into test code
- [ ] Remove no longer needed dependencies
- [ ] Make sure EnsoCompilerTest still works

## Blockers:
[#183958493](https://www.pivotaltracker.com/story/show/#183958493) resolved
[#182497187](https://www.pivotaltracker.com/story/show/#182497187) blocked
