### ISSUE TITLE
Comparing Enso benchmarks results with Enso

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5165]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/183791837).
<hr />

Based on following [discord discussion](https://discord.com/channels/401396655599124480/1020705810046795796/1020705810046795796).

We are able to [execute benchmarks](https://github.com/enso-org/enso/actions/workflows/benchmark.yml) for the engine on a dedicated CI machine. However we don't have a way to be notified of regressions or simplify comparing of the result.

As Enso is data processing oriented system, it would be great testcase of Enso capabilities and stability to process the available data in Enso and render them in a chart rather than manually compare two XML files and search for unacceptable differences.

As an initial step let's use Enso and its libraries for head-less processing:
- Let there be an Enso project
- Let me invoke the project (with some parameters)
- Generate output
- Let me use some tool to display the output and help me understand my _branch is good enough for integration_

## Future Ideas

As a primary tool, let's use the Enso IDE for displaying the charts:
- Let there be an Enso project
- Let me open the project
- Let me see if my _branch is good enough for integration_

## Tasks:
- [ ] Being able to download data from GitHub Actions
- [ ] Process the data into Enso data structures
- [ ] Split the data for various branches
- [ ] Draw charts from the data
- [ ] Allow one to answer question: Can I integrate my branch?
- [ ] Improve Enso libraries where needed

**Comment by jdunkerley** [comment]
We should look to do this as part of case study work

**Comment by Akirathan** [comment]
Blocked by #5714
