### ISSUE TITLE
Open Design Questions

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5181]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/182012523).
<hr />

This ticket is a holder for design questions which come out of other library design work.

As items come up in other design PRs will add them to this ticket and tick off once resolved.

## Tasks:
- [ ] Auto conversion for data columns (https://github.com/enso-org/design/pull/33#issuecomment-1110008595)
- [ ] Additional random distributions such as Normal (https://github.com/enso-org/design/pull/33#issuecomment-1110008595)
- [ ] Weighted average for aggregate (https://github.com/enso-org/design/pull/33#issuecomment-1110008595)
- [ ] Reporting when a database operation requires transferring to in-memory (https://github.com/enso-org/design/pull/33#discussion_r859289930)
- [ ] Statistic and Aggregate column closely related (https://github.com/enso-org/design/pull/33#discussion_r858719476)
- [ ] Regex Split ==> Parse function
- [ ] Auto encoding support https://www-archive.mozilla.org/projects/intl/chardet.html
- [ ] Unicode BOM support
- [ ] Define how relative path support should work (https://github.com/enso-org/design/pull/34#discussion_r871883912)
- [ ] How to handle excess columns in a delimited file (https://discord.com/channels/@me/927873759505961031/978293311678849024)
- [ ] Set maximum number of fractional digits in Data_Formatter to round values for output
- [ ] Do we want to customize the infinity format in Data_Formatter? Currently only `Infinity` is supported, but files may also contain entries like `+inf` or `∞`
- [ ] Specifying line endings in Delimited File_Format
