### ISSUE TITLE
Run Enso on Mac M1 Architecture Natively

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5186]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/182269744).
<hr />

### Why

**As Enso user**
**I want ** to run Enso on my new Mac with M1 architecture
**So that ** I don't have to run on old machine or in emulator

### Acceptance Criteria

```gherkin
Scenario: 
Given A user has M1 Mac machine
When it downloads the right GraalVM
Then then it can build/run Enso on the machine
```

**Notes:**

[GraalVM 22.1](https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-22.1.0) is the first GraalVM version that provides support for Mac M1 architecture. 

Currently however GraalVM Engine builds/tests only against GraalVM LTS version 21.3

Switching to [GraalVM 22.1 is possible](https://github.com/enso-org/enso/commit/adb4c5ea52c776e0765e7526d5341c4ef4255856) and then the engine builds with 14 warnings. Running tests also fails, but the `buildEngineDistribution` succeeds and produces working distribution that is capable to run `.enso` programs.

## Tasks:
- [X] Use RootNode.getCallTarget
- [X] Rewrite Frame access to use index and not FrameSlot
- [X] Fix tests to run on GraalVM 22.1
- [ ] download GraalVM for aarch64 M1 architecture
- [ ] change the build to generate libenso_parser for aarch64 M1 architecture
- [ ] make sure it links and runs OK

## Blockers:
[#183635511](https://www.pivotaltracker.com/story/show/#183635511) resolved
[#182845176](https://www.pivotaltracker.com/story/show/#182845176) resolved

## Comments:
After [trivial cleanup](https://github.com/enso-org/enso/pull/3474) the following warnings in Scala code remain:
```
[info] compiling 129 Scala sources and 395 Java sources to enso/engine/runtime/target/scala-2.13/classes ...
[error] enso/engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala:1245:45: class FrameSlot in package frame is deprecated
[error]         val (argSlots, _, argExpressions) = slots
[error]                                             ^
[error] enso/engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala:1260:35: class FrameSlot in package frame is deprecated
[error]       private def computeSlots(): (
[error]                                   ^
[error] enso/engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala:1305:22: class FrameSlot in package frame is deprecated
[error]       argumentSlots: List[FrameSlot]
[error]                      ^
[error] enso/engine/runtime/src/main/scala/org/enso/interpreter/runtime/scope/LocalScope.scala:40:33: class FrameSlot in package frame is deprecated
[error]   final val frameSlots: mutable.Map[Graph.Id, FrameSlot] = mutable.Map()
[error]                                 ^
[error] enso/engine/runtime/src/main/scala/org/enso/interpreter/runtime/scope/LocalScope.scala:79:36: class FrameSlot in package frame is deprecated
[error]   def createVarSlot(id: Graph.Id): FrameSlot = {
[error]                                    ^
[error] enso/engine/runtime/src/main/scala/org/enso/interpreter/runtime/scope/LocalScope.scala:80:32: method addFrameSlot in class FrameDescriptor is deprecated
[error]     val slot = frameDescriptor.addFrameSlot(aliasingGraph.idToSymbol(id))
```
`FrameSlot` has been [deprecated in 22.0](https://github.com/oracle/graal/blob/master/truffle/CHANGELOG.md#version-2200): 

> 
> Added new APIs to com.oracle.truffle.api.frame.Frame and com.oracle.truffle.api.frame.FrameDescriptor:
>
>   Added a new "namespace" of index-based slots in Frame that is defined during construction of the frame descriptor and cannot be changed afterwards, and that is accessed using int indexes instead of FrameSlots.
>   Added a second new "namespace" of slots (called auxiliary slots) in Frame that can be added to the frame descriptor dynamically (and which only supports "object" slots).
>    In addition to get.../set... methods, the new API also supports copy and swap of frame slots.
>    The FrameSlot-based API methods in Frame and FrameDescriptor were deprecated.
>    FrameSlotTypeException is now an unchecked exception, which simplifies many APIs and removes the need for the FrameUtil class.

Using the new index based API shall be possible, as Enso knows the exact number of local variables after parsing and properly allocate the right amount of slots when constructing the `FrameDescriptor`.
 (jaroslavtulach - May 24, 2022)
<hr />
	Upgrade to GraalVM 22.3 has been done by @pmarek : #182845176 - now we should be able:
- download GraalVM for `aarch64` M1 architecture
- change the build to generate `libenso_parser` for `aarch64` M1 architecture
- make sure it links and runs OK (jaroslavtulach - Nov 29, 2022)
<hr />
	@murbanczyk can give us an `ssh` access to Mac M1, once we needed it. (jaroslavtulach - Jan 31, 2023)
<hr />

**Comment by jdunkerley** [comment]
Nightly release is AArch64 native.
