### ISSUE TITLE
It should be possible to resize the visualization attached to a node

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5211]
```[tasklist]
### Tasks
- [ ] https://github.com/enso-org/enso/issues/7047
- [ ] https://github.com/enso-org/enso/issues/7048
- [ ] https://github.com/enso-org/enso/issues/7049
```

This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/184350984).
<hr />

The square showing the visualization preview is very small and in many cases it is impossible to see the full data.

The fullscreen preview does allow to take a peek at the data, but in many cases, when editing the workflow I want be able to 'track' how the data evolves and fullscreen preview does not serve this usecase (I'd need to enter and quit the fullscreen upon each change, the whole purpose of the node-attached visualization is that I can see how it changes "live").

## Comments:
I think this is data-specific and we already have that for text visualizations. But probably @michael_mauderer can comment more. (Hubert Plociniczak - Feb 1, 2023)
<hr />
Resizing the visualization, should be able to be implemented from the GUI side.

It might need reworking and testing all the visualization to make sure they support arbitrary sizes, so this might be a bigger task to get right.  (Michael Mauderer - Feb 1, 2023)
<hr />
