### ISSUE TITLE
Get rid of TruffleBoundary in Map.insert and Map.get

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5233]
This task is automatically imported from the old Task Issue Board and it was originally created by Pavel Marek.
Original issue is [here](https://www.pivotaltracker.com/story/show/184236714).
<hr />

A follow-up of https://www.pivotaltracker.com/n/projects/2539304/stories/181027272 - the previous story got bigger than we expected, so we have decided to split it.

`EnsoHashMapBuilder.get` is behind `TruffleBoundary`, because a _black listed_ method is reachable from it. It seems that the usage of `org.graalvm.collections.EconomicMap` was not a good idea for a hash map implementation after all. I partially increased the performance by adding `@TruffleBoundary(allowInline = true)` on some places (https://github.com/enso-org/enso/pull/3878/commits/bc953f936c535020c459dc775966b4314ff439b5). Try to investigate the performance more, and ultimately, get rid of `TruffleBoundary` in `Map.insert` and `Map.get` altogether.

## Tasks:
- [X] Consider computing `hashCode` when computing `==` on `Atom` objects
- [ ] Functions shall not be comparable (only use "same object policy" as in #6301)
- [X] NaNs aren't suitable keys as they aren't supposed to be comparable to themselves - done by #6301
- [X] Demonstrate effective implementation of `distinct` via `Map` (for objects that don't provide custom `==` & co.)
- [ ] Show how to use the Enso Map from polyglot Java
- [x] Investigate the performance of `EnsoHashMap` (details in the description)

## For future

- [ ] Implement pattern matching for `Map`
- [ ] Migrate `WithWarnings` to use EnsoHashMap - #8682

## Blockers:
[https://www.pivotaltracker.com/n/projects/2539304/stories/181027272](https://www.pivotaltracker.com/story/show/https://www.pivotaltracker.com/n/projects/2539304/stories/181027272) resolved

**Comment by JaroslavTulach** [comment]
Brainstorming idea. The issue
- #6372 

needs a _partial evaluation_ friendly `Map` (or `Set`) of already attached warnings. It'd be great if we could share the same implementation with `EnsoHashMap`. At the end the needs of `Vector.distinct` and filtering of _"warning duplicates"_ seem to be very similar.
