### ISSUE TITLE
Avoid binaries in Git repository

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5258]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/183911438).
<hr />

As [discussed](https://discord.com/channels/401396655599124480/1047041120154165268) there are few `.png` files accidentally committed into our repository:
```
210309 ./docs/debugger/chrome-debugger.png
  142107 ./docs/debugger/java-debugger.png
    1050 ./tools/enso4igv/src/main/resources/org/enso/tools/enso4igv/enso.png
```
There shouldn't be any binary files in the Git repository to keep the size of the repository small.

Probably the 1st step to begin with is to enhance CI to fail the build when there is an image file being integrated.

No way then to alter the history of the repository. None of the commit IDs since May 10 will remain the same. All the history will be rewritten. However only hashes will change and the author and date can be preserved. Let's rewrite the history to `develop2`, ask everyone to rebase their changes to `develop2` and then remove the old `develop` and rename the new `develop`.

## Tasks:
- [ ] Make sure CI fails when there a `.png` files
- [ ] Rewrite history as of May 10 to not contain `.png` files
- [ ] Co-ordinate with Michal on closing/opening `develop` branch

**Comment by jdunkerley** [comment]
@JaroslavTulach removed the binaries already. We don't want to rewrite git history so closing.
