### ISSUE TITLE
Values WithWarnings mess host Java & Vector & Array interop

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5286]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/183238953).
<hr />

Enso values may be associated with `Warning`s - then they are replaced by `WithWarnings` value that wraps the original value. Such wrapping is problematic, as the values currently have to be _unwrapped_ at certain moments - for example before sending a value to `polyglot java import` objects.

Recently it has come to my attention there is [ReflectiveLibrary](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/library/ReflectionLibrary.html) especially made for such kind of wrapping. Using it shall allow us to _avoid eager unwrapping_, if all subsystems are ready to work with such _wrappers_.

There is an implementation of this idea at [6340361a0d820](https://github.com/enso-org/enso/commit/f6340361a0d82047c56b59f8f2d20a209ba6c0b7#diff-d784205295fc228b108d6ca365bf8371e6fa2337bd8f2c38e7a3bdac721f3a30R14). Alas, it has problems in `Table_Tests` during conversions to _host Java_. 
```
    - [FAILED] should correctly handle problems: duplicate columns
    - [FAILED] should correctly handle problems: unmatched names
    - [FAILED] should correctly handle problems: out of bounds indices
    - [FAILED] should correctly handle problems: aliased indices
    - [FAILED] should correctly handle problems: invalid names ''
    - [FAILED] should correctly handle problems: invalid names Nothing
    - [FAILED] should correctly handle problems: duplicate names
    - [FAILED] should correctly handle problems: too many input names
    - [FAILED] should correctly handle problems: invalid names ''
    - [FAILED] should correctly handle problems: invalid names Nothing
    - [FAILED] should correctly handle problems: duplicate names
```
Looks like an improvement on GraalVM side is needed to make this work smoothly - reported [PR-4916](https://github.com/oracle/graal/pull/4916) to the GraalVM team. With such changes in GraalVM the above _should correctly handle problems_ are gone.

## Tasks:
- [X] Extract the root of the problem and report it to GraalVM team -  [PR-4916](https://github.com/oracle/graal/pull/4916)
- [ ] Once a fix is integrated, turn  [WithWarnings](https://github.com/enso-org/enso/commit/f6340361a0d82047c56b59f8f2d20a209ba6c0b7#diff-d784205295fc228b108d6ca365bf8371e6fa2337bd8f2c38e7a3bdac721f3a30R14) into transparent `TruffleObject`
- [ ] Remove all special conversions that try to unwrap `WithWarnings`
- [ ] Eliminate all `getUncached` on fast path

## Blockers:
[#182194556](https://www.pivotaltracker.com/story/show/#182194556) blocked
[#182221022](https://www.pivotaltracker.com/story/show/#182221022) blocked

## Comments:
The problem has been discussed with Christian Humer. The [PR-4916](https://github.com/oracle/graal/pull/4916) has been updated from 21.3 branch to target current `master` branch. Currently there are some uses of `isHostObject` and co. with `getUncached` on fast path that need to be eliminated. (jaroslavtulach - Sep 19, 2022)
<hr />
**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2022-09-19):

**Progress:** HostInterop `WithWarnings` wrappers interop: https://github.com/oracle/graal/pull/4916#discussion_r969643755 updated to 22.x branch and sent for review to GraalVM team. Meetings, discussions, planning with Greg - send email to Shaun Smith. Testing Hubert's `sbt` integration - good. It should be finished by 2023-01-19.

**Next Day:** Integrating new parser tests with CI (Enso Bot - Sep 20, 2022)
<hr />
I believe that now, when @hubertplociniczak implemented _tainting of arrays_ in #182221022 and #182194556 we don't need any special solution for this problem. (jaroslavtulach - Dec 13, 2022)
<hr />

**Comment by JaroslavTulach** [comment]
This is very old issue...

> - The problem has been discussed with @chumer. 
> - The https://github.com/oracle/graal/pull/4916 has been updated ...
> - Currently there are some uses of `isHostObject` and co. with `getUncached` on fast path that need to be eliminated.
> - (jaroslavtulach - Sep 19, 2022)

- the last rumor (from Oct 2025) is that @tzezula is working on alternative to https://github.com/oracle/graal/pull/4916
- I don't know the status however...
- it makes little sense to work on this issue without coordinating with Tomáš Zezula, closing on Enso side for now
