### ISSUE TITLE
Enso Compiler Improvements

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#532]
### Summary
Although the Enso runtime now has a compiler front-end, that front-end is very much a stopgap solution that needs to be evolved to support much of the functionality planned for the future. This Epic exists to track tasks that deal with improving the compiler functionality of the Enso engine. 

The core of the compiler is the `Core` language, a simplified and restricted form of Enso that is represented as a graph. This graph representation is far more amenable to analysis and transformation, and has robust support for other features such as typechecking. 

### Value
These are miscellaneous improvements and will encompass things that improve performance to things that improve the API and everything in between. 

### Specification

- [ ] Implement a translation from `AST` to `Core` and `Core` to the current IR type (#531, #530).
- [ ] Implement a translation from `Core` to `Node` using the current compiler machinery (#526).
- [ ] Graph and Core improvements to support desugaring (#512, #511, #510, #509, #508).
- [ ] Optimisations for recursion (#550, #533, #527, #525, #547).
- [ ] Core usability improvements (#529, #528), need to look at the `TODO` comments in the core codebase as there are more not yet filed as issues.
- [ ] Function-call optimisations (#582).
- [ ] Add support for format strings (#366). 

### Acceptance Criteria & Test Cases

- All enhancement tasks are getting completed and not languishing.
