### ISSUE TITLE
Methods in standard library should have sensible defaults where possible.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5323]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/182720308).
<hr />

## Who 

Libs Team

## Why

**As** an Engine developer when providing data to IDE
**I want** to have sensible defaults for every function
**So that** I have data to be provisioned to IDE to display.

E.g. 1 in the [screenshot](https://www.pivotaltracker.com/file_attachments/117263858/download?inline=true) a _visualization_ of `read` function shall show something meaningful.

E.g. 2 Scatter plot visualization should show some sample data scattered along the x/y axis in the visualization preview panel.
(just an example not chosen/suggested for first 5 defaults to be provided for testing – more info in the notes)

## Acceptance Criteria

```gherkin
Scenario: 
GIVEN I have a newly created project opened in Enso IDE, and selected one of the nodes
WHEN I open _component browser_, select any component, press enter, and open a visualization
THEN I see some _sensible data in visualization_
```

## Notes

It will be an ongoing task with the aim to cover all of the Library functions with sensible defaults where possible. Starting with the most important ones selected by James. First 5 selected defaults should be used as the test samples to check if the Engine is feeding data properly for the visualization. 

We aim to have defaults for all functions in favorites. If some of them are problematic, please start discussion to add exceptions to Acceptance Criteria.

## Tasks:
- [ ] 5 Test sensible defaults for functions
- [ ] 5 Test sensible defaults for widgets
- [ ] Rest of >1k functions defined in StdLib

## Comments:
Example of a component browser with `read` method selected. In addition to the picture envision we want to have a visualization for the `read` node visible. An advice from @michael_mauderer :

> You can open the IDE in the browser with http://localhost:8080/?enable_new_component_browser=true
and then you should see the new component browser instead of the old searcher (jaroslavtulach - Sep 7, 2022)
<hr />

**Comment by jdunkerley** [comment]
General process to improve things we see.
