### ISSUE TITLE
Add icon sections in documentation of chosen standard library entries.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5324]
This task is automatically imported from the old Task Issue Board and it was originally created by Mateusz Czapliński.
Original issue is [here](https://www.pivotaltracker.com/story/show/182584311).
<hr />

## Why

**As** Enso Developer
**I want** some of the standard library entries to have `Icon:` set to a supported icon name in their documentation
**So that** I can show custom icons for those entries in the Component Browser.

## Acceptance Criteria
```gherkin
Scenario: 
GIVEN the Engine with standard library loaded
WHEN I send a `search/getSuggestionsDatabase` message to the Engine
THEN response contains suggestion entries with a DocSection entry of the `Keyed` variant with the `key` string equal to `Icon` and the value equal to one of the icon names defined in GUI.
```

## Notes
 - Design Doc section: https://github.com/enso-org/design/blob/main/epics/component-browser/design.md#icons-and-aliases
 - Available icon names are defined in: `app/gui/view/component-browser/component-group/src/icon.rs`.

```[tasklist]
### Tasks
- [x] Add missing icons and complete set for Table, Row, Value_Type and Column
- [ ] https://github.com/enso-org/enso/issues/8916
- [ ] https://github.com/enso-org/enso/issues/8926
- [ ] https://github.com/enso-org/enso/issues/8927
- [ ] https://github.com/enso-org/enso/issues/8928
- [ ] https://github.com/enso-org/enso/issues/8929
```

**Comment by jdunkerley** [comment]
All completed.
