### ISSUE TITLE
Progress API

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5329]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/182781062).
<hr />

### Why

**As enso user**
**I want to get approximation about long running tasks**
**So that I know how long I need to wait. **

### Acceptance Criteria

```gherkin
Scenario: 
Given a long running task in a stdlib (like download of a file) 
When the user starts it from an IDE
Then the IDE can display appropriate progress while the task is running.
```

**Notes:**

As requested in #182746079: Report for example that 40% of computations are done. There should be a Progress API in the language allowing the libraries team to report the progress of function evaluation. In case such progress will be reported, we will show a spinner in GUI that will change its length. In case no progress is reported, we will only show a spinner without changing its length. We need to get the information on whether a function reports progress as soon as we got information that the node starts being evaluated because the look of the spinner will be different for functions reporting progress and those that don't.

**Design Assumptions:**

1. the progress reporting shall **always be available** for any library function that feels it wants to report a progress
2. whether or not the progress reporting actually transmits data to the IDE (and how frequently) depends on the infrastructure
3. progress shall be **composable**: function that downloads three files reports progress from `0..3` each _file download_ function reports progress from `0..size_of_the_file` these reports shall automatically aggregate
4. re-running the computations - when the same computation is executed for the second time one can use _time estimates_ from the previous run to be more accurate 

**API sketch**

To make the progress **always available** it needs to be part of the _state_ of the program. Imagine a function downloading many files. It can start to report its progress by creating and obtaining a _progress handle_: `Progress.createWithFixedSteps`. That instructs the system that a long running operation of _Downloading from Network_ has been initialized:

```java
void download(what: URL[]) {
    var p = Progress.createWithFixedSteps("Downloading from Network", what.length);
    for (var u : what) {
      p.report("Downloading " + u);
      downloadURL(u);
      p.progressWithAdditionalSteps(1);
    }
    p.finish();
  }
```

The code invokes `downloadURL` function to handle download of individual file. Such function may also use the **always available** progress reporting capability:

```java
void downloadURL(u : URL) {
  var p = Progress.createWithFixedSteps("Downloading " + u, u.conn().length());
  for (int i = 0; i < u.conn().length(); i++) {
      byte[] arr = new byte[4096];
      int readBytes = u.conn.read(arr);
      p.progressWithAdditionaSteps(readBytes);
  }
  p.finish();
}
```
By default these _nested_ usages **compose** and join each other. Each newly created _progress handle_ is associated with current progress segment of handle created by parent `download` function and is used to deliver more detailed progress based on the number of downloaded bytes.

**Explicit Progress Sharing API**

The progress handle is represented as a regular object in the API and can be used as a function parameter. That opens path to _explicit sharing_ - should the library writer feel the need to orchestrate the progress between `download` and `downloadURL` functions, there is nothing stopping it:

```java
void download(what: URL[]) {
  var totalBytes = what.fold(0, (t, u) -> t + u.estimateLength());
  var p = Progress.createWithFixedSteps("Downloading from Network", totalBytes);
  for (var u : what) {
      downloadURL(p, u);
    }
    p.finish();
}
```
The `download` function first estimates the total number of bytes to download, creates appropriate _progress handle_ and then passes it to `downloadURL` function to fill with download progress:
```java
void downloadURL(p : Progress, u : URL) {
  p.report("Downloading " + u);
  for (int i = 0; i < u.conn().length(); i++) {
      byte[] arr = new byte[4096];
      int readBytes = u.conn.read(arr);
      p.progressWithAdditionaSteps(readBytes);
  }
}
```
sharing the _progress handle_ is a useful technique for functions inside of a single library that _know each other_ and can agree on the counting units and pass the handle as argument.

**Delivering the Status to the IDE **

There already is a protocol for long running tasks. I.e. when IDE tries to open the project, but the Project Manager needs to download and install the Engine bundle first https://github.com/enso-org/enso/blob/0701e762ea25cbed3ac58a2aa0491be16ff0f038/docs/language-server/protocol-project-manager.md#action-progress-reporting

**Prior work:**

Getting **Progress** estimates 100% correct is close to impossible. Estimating future work isn't easy. NetBeans IDE designed such [Progress API](https://bits.netbeans.org/14/javadoc/org-netbeans-api-progress/overview-summary.html) including _simple_ and _aggregate_ mode. Three types of progress indication are supported:

    1. indefinite when it's not known how much time will be needed to complete
    2. definite with time estimate for completion (UI shows time that remains)
    3. definite without time estimate where the UI shows percentage completed.

However there were some mistakes in the API design and I am glad to have a possibility to fix all of them in the **Enso Progress API**!

## Tasks:
- [ ] Sketch API in Enso (instead of the pseudo Java) - probably using State
- [ ] Design interaction between engine & IDE - set of messages
- [ ] Design extraction of the current progress status

## Comments:
An example of progress being reported in the NetBeans IDE. The picture shows two handles (each indefinite). Each of the handles has **generic name** (stable for the whole execution of the task) as well as  _information about current operation_ (changes while the task is running). Some of the tasks are cancellable and have an icon that allows user to do so. By default user only sees one progress, but the UI offers the user to expand the pull-down and inspect details. (jaroslavtulach - Jul 25, 2022)
<hr />

**Comment by jdunkerley** [comment]
Progress API is in product now.
