### ISSUE TITLE
Change True/False without full re-parse

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5397]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/182497943).
<hr />

### Why

**As Enso user**
**I want to click a checkbox **
**So that whole program updates quickly **

### Acceptance Criteria

```gherkin
Scenario: 
Given program that uses `True` 
When IDE changes the value to `False`
Then the program should be updated without full re-parse
```

**Notes:**

`True` and `False` arent' literal values, but no-argument `AtomConstructor`s. The goal of this task is to support _incremental updates_ of all such no-argument constructors. If a value of one no-argument constructor is changed for another, the program should update without full re-parse just like #182412796 suggests.

## Tasks:
- [ ] Find out how is a no-argument constructor represented in Truffle AST
- [ ] Find out how is such constructor represented in IR
- [ ] Make the Truffle AST node `Patchable` and accept the new `IR`

## Blockers:
[#182454001](https://www.pivotaltracker.com/story/show/#182454001) resolved

## Comments:
According to recent measurements done by [wstest tool](https://github.com/enso-org/enso/pull/3578#discussion_r923087814) the `applyEdit` message can be processed in `16ms`. That seems to be _good enough_ for a click on a checkbox. Let's delay further improvements for `True`/`False` (that could get us to [7ms](https://github.com/enso-org/enso/pull/3578#discussion_r923118112) until they are really needed. Moving this issue to icebox. (jaroslavtulach - Jul 20, 2022)
<hr />

**Comment by jdunkerley** [comment]
Recalc is a lot better these days
