### ISSUE TITLE
Sophisticated Static Optimisation

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#544]
### Summary
Though, as part of #925 a basic set of static transformations was implemented, it is necessary to invest time in creating a more robust and complex framework for static transformations of programs. This is a feature that most advanced language compilers have, but is a fairly novel idea for an interpreter. While we can rely on the JIT to provide a significant amount of performance, there are other static transformations specific to functional languages that a JIT will never make. We need a way to perform those. 

This epic is closely related to the work planned as part of #545, as that epic will rely, at least in part, on the workimplemented here. 

### Value
Performance is an important focus for Enso, and this work will help us to deliver better performance for the interpreted code. Furthermore, such functionality is a necessary part of #545, and hence if _that_ epic is to go ahead, so must this one. 

### Specification
The static transformation framework must support the following features:

- [ ] Allow creation of one or more `Pass`es that encapsulate a static transformation from one type `P` to another type `Q` (both `P` and `Q` will most typically be some kind of AST.
- [ ] A `Pass` may have `P == Q` and purely generate additional information. 
- [ ] Provide the ability to pass arbitrary information between passes (e.g. the results of alias analysis). 
- [ ] Allow a `Pass` to declare dependencies on passes, such that those passes must run before it.
- [ ] Provide a type-safe interface that ensures that pass orderings cannot be created in a way that violates the invariants about the passes. 
- [ ] Allow a `Pass` to invalidate the results of other passes. If this happens, the invalidated passes must be run again if they are depended upon.

I imagine the phases being stratified as follows:
- **Parsing:** Turning source code into the Source AST.
- **Desugaring:** Converting any syntax sugar into primitive forms, still using the Source AST. This includes all of the desugaring passes mentioned [above](https://github.com/enso-org/enso/issues/875#issue-482272997). 
- **Typechecking:** Typechecking of Enso code. Tthis will operate on its own structures and may run subsequent phases for the purposes of code execution during typechecking.
- **Lowering:** Conversion of all (or potentially part) of the program into Continuation-Passing Style. This will use its own internal graph representation (the `CPSGraph`).
- **Optimisation:** Transformations from `CPSGraph -> CPSGraph` with the intention of increasing the performance of generated code. 

### Acceptance Criteria & Test Cases

- A flexible static analysis framework has been implemented.
- The framework is written in such a way that it executes its transformations as performantly as possible.
- The framework has been used to implement some common static-transformation-based optimisations for the Enso source language.
