### ISSUE TITLE
Unbounded Recursion

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#545]
### Summary
As a purely functional programming language, Enso uses recursion as its primary construct for performing looping. However, as we're building on top of GraalVM, we are butting up against the JVM's limited stack depth. 

Though we do not have the time to be able to provide a proper solution to this problem at this stage, we need to solve it in order to consider Enso to be complete as a language. 

### Value
Without solving this problem, Enso can't be considered complete as a functional programming language, even with support for limited kinds of recursion such as tail-call recursion. In order to provide a complete implementation of the language's semantics, we need to solve this.

### Specification

- [ ] Explore solutions to providing support for unbounded recursion in Enso, including employing the CPS transform as well as compiling the language to a linearizable representation (e.g. JVM Bytecode via CPS, or similar). These solutions must account for supporting the introspection and caching functionality requried by Enso Studio, as well as functionality for tooling like performance analysis and debugging.
- [ ] Determine the tradeoffs inherent in the solutions that have been explored, with a particular focus on performance, implementation complexity, and maintenance burden. 
- [ ] Implement the solution that has been determined to offer the best overall solution with regards to solving this problem. 

### Acceptance Criteria & Test Cases

- Enso has support for unbounded recursion.
- Said support does not hinder the other goals of the language.
- Said support is performant enough to make use of unbounded recursion feasible in the average user's code.
