### ISSUE TITLE
Investigate Instant Startup of the Engine

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5464]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/182486022).
<hr />

### Why

**As Enso User**
**I want the engine start and work fast**
**So that opening a project doesn't take five seconds or more **

### Acceptance Criteria

```gherkin
Scenario: 
Given newly created project
When it is opened
Then the engine shall work immediatelly without typical _java-like_ warm up.
```

**Notes:**

GraalVM offers AOT - _native image_ - compilation which is the recommended way for Truffle languages to offer almost instant startup and better user experience.

## Tasks:
- [X] Investigate what it would take to compile engine with native image
- [X] Modify build.sbt to invoke `native-image` compilation for the engine
- [X] Investigate why engine+runner combo crashes the compilation
- [X] How to load libraries in NI mode? Espresso - yes, it can work: #183260380
- [X] Make `sbt engine-runner/buildNativeImage` goal part of the CI to verify proper `@TruffleBoundary` annotations: #183136313

## Blockers:
[#183260380](https://www.pivotaltracker.com/story/show/#183260380) resolved
[#183136313](https://www.pivotaltracker.com/story/show/#183136313) resolved
[#183374932](https://www.pivotaltracker.com/story/show/#183374932) resolved
[#183802194](https://www.pivotaltracker.com/story/show/#183802194) resolved
[#184256209](https://www.pivotaltracker.com/story/show/#184256209) blocked

## Comments:
	@hubertplociniczak , if you can take a look at `build.sbt` and modify it to create a new task to invoke native image with proper engine (probably `runtime.jar` and `runner.jar`) class path, that'd be great. Compilation may fail, but it'll be easier for me to take over when we have the `sbt` task. (jaroslavtulach - Aug 5, 2022)
<hr />
I tried to use Hubert's `sbt` changes, but the NI [compilation was crashing](https://graalvm.slack.com/archives/CN9KSFB40/p1660912345522119?thread_ts=1660539227.687399&cid=CN9KSFB40). As such I had to create something simpler. Branch [SimpleLauncher](https://github.com/JaroslavTulach/enso/tree/jtulach/SimpleLauncher) shows the _instant startup benefits_ of using _Native Image_ for compilation & execution. Follow the [readme](https://graalvm.slack.com/archives/CN9KSFB40/p1660912345522119?thread_ts=1660539227.687399&cid=CN9KSFB40) and you will see that executing simple helloworld takes `40ms`:
```bash
time ./target/simplelauncher fac.enso 
3628800

real    0m0,038s
user    0m0,021s
sys     0m0,017s

```
which is **hundred times faster** than traditional `4s` needed to boot the Enso engine in JVM mode. (jaroslavtulach - Aug 19, 2022)
<hr />
With the [help and guidance of Chris Seaton](https://graalvm.slack.com/archives/CN9KSFB40/p1661057653619979?thread_ts=1660539227.687399&cid=CN9KSFB40) I managed to compile the launcher with `sbt engine-runner/buildNativeImage` when I gave the process enough memory (22GB was enough). E.g. the next milestone has been reached. Next goal: make the `sbt engine-runner/buildNativeImage` goal part of the CI run to verify all the  necessary `@TruffleBoundary` annotations are in place. (jaroslavtulach - Aug 22, 2022)
<hr />
Status summary as of Aug 23, 2022: https://docs.google.com/document/d/1yZmj4y-mOswTUHFzYkV7FM6Vh9P9LLXj-plAW3bVzbI + will be discussed at 15:00 CET (jaroslavtulach - Aug 23, 2022)
<hr />

**Comment by JaroslavTulach** [comment]
- #4877

**Comment by JaroslavTulach** [comment]
- many improvements has been made since this issue was created
- `enso` is compiled as native image
   - we have the dual JVM mode
- we have benchmarks https://enso-org.github.io/engine-benchmark-results/stdlib-benchs.html#org_enso_benchmarks_generated_Native_Image_Startup_import_world_startup
- improvements are constantly being delivered - e.g. the issue is fixed

<img width="1646" height="264" alt="Image" src="https://github.com/user-attachments/assets/cc567d43-c2b9-4b08-826b-426038139292" />

<blockquote><div><strong><a href="https://enso-org.github.io/engine-benchmark-results/stdlib-benchs.html#org_enso_benchmarks_generated_Native_Image_Startup_import_world_startup">stdlib benchmark results</a></strong></div></blockquote>
