### ISSUE TITLE
Data analysts should be provided with a unified way to convert between data structures (`from` method)

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5522]
This task is automatically imported from the old Task Issue Board and it was originally created by Dmitry Bushev.
Original issue is [here](https://www.pivotaltracker.com/story/show/180312665).
<hr />

### Why
 
**As data analyst**
**I want** a unified way of converting between different data representations
**So that** I can do my job quicker

### Acceptance Criteria

```gherkin
Scenario: 
Given `.from` Enso function
When converting between built-in Enso data types
Then the data types are converted correctly
```

## Tasks:
- [X] Ensure that conversion methods are generated to a particular spot in the scope.
- [X] Generate a special ConvertValueNode for calls to .from. This limits the scope of the multiple dispatch.
- [X] Write the multi-dispatch lookup in this node in an extensible fashion.
- [X] Ensure that all standard features work with from calls (currying, oversaturated apps, defaults suspension).
- [ ] Write benchmarks covering the new dispatch node.
- [X] Add tests covering the expected behavior.

## Blockers:
[#180539669](https://www.pivotaltracker.com/story/show/#180539669) resolved
[#180956787](https://www.pivotaltracker.com/story/show/#180956787) blocked
[#180956771](https://www.pivotaltracker.com/story/show/#180956771) blocked
[#181150326](https://www.pivotaltracker.com/story/show/#181150326) blocked

## Comments:
**Dmitry Bushev** reports a new **STANDUP** for today (11/16/2021):

**Today:** Started to get into the Universal Conversions task. Refreshed my knowledge of how the method invocations are implemented in Enso. Come up with a plan of what needs to be done in the runtime to support the Universal conversions It should be finished by 2021-11-19.

**Next Day:** Next day I will be working on the [#180312665 task](https://www.pivotaltracker.com/story/show/180312665). Try to decide how to make the suggestions system work with the conversion functions (Enso Bot - Nov 16, 2021)
<hr />
**Edward Kmett** reports a new **STANDUP** for today (11/15/2021):

**Today:** Writing some small .enso files to get more familiar with the language. It should be finished by 2011-11-18.

**Next Day:** Next day I will be working on the [##180312665 task](https://www.pivotaltracker.com/story/show/180312665). Getting truffle/graal graphs out of the runtime and learning to read our intermediate graal representation. Trying to write a ConvertValueNode, and swap it in for InvokeMethodNodes for 'from', without actually changing the dispatch path just yet.

**Additional Information:** I can't submit this at all without specifying a next issue. (Enso Bot - Nov 17, 2021)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for today (11/17/2021):

**Today:** Continue with the Universal Conversions task. Narrowed the scope of changes required in runtime. Split the task into more fine-grained changes and found a good entry point for Edward and discussed it with him. This makes the runtime part pretty much planned. Still, need to work out how to fix the tooling when the conversion support will be added. It should be finished by 2021-11-19.

**Next Day:** Next day I will be working on the [##180312665 task](https://www.pivotaltracker.com/story/show/180312665). Continue working on the suggestions system. (Enso Bot - Nov 17, 2021)
<hr />
**Edward Kmett** reports a new **STANDUP** for today (11/16/2021):

**Today:** Formulated plan of attack for .from dispatch. Info-dumped it to the #engine channel. It should be finished by 2011-11-18.

**Next Day:** Next day I will be working on the [##180312665 task](https://www.pivotaltracker.com/story/show/180312665). Continuing to hack away on adding the new node types to out truffle codebase. (Enso Bot - Nov 17, 2021)
<hr />
**Edward Kmett** reports a new **STANDUP** for today (11/16/2021):

**Today:** Formulated plan of attack for .from dispatch. Info-dumped it to the #engine channel. It should be finished by 2011-11-18.

**Next Day:** Next day I will be working on the [##180312665 task](https://www.pivotaltracker.com/story/show/180312665). Continuing to hack away on adding the new node types to out truffle codebase. (Enso Bot - Nov 17, 2021)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for today (11/18/2021):

**Today:** Continue with the Universal Conversions task. Started to work on the tooling subtask. Designed the index of available conversions. Turned out that we need another index representing `to` conversions. It should be finished by 2021-11-19.

**Next Day:** Next day I will be working on the [##180312665 task](https://www.pivotaltracker.com/story/show/180312665). Continue working on the suggestions system, adding an index of available conversions. Also, have to check if the existing JSONRPC API can handle new conversion functions. (Enso Bot - Nov 18, 2021)
<hr />
**Edward Kmett** reports a new **STANDUP** for today (11/17/2021):

**Today:** Working through how to implement MultipleDispatchFunction, and a bit of how to gather all the attributes from an Enso class list. It should be finished by 2011-11-18.

**Next Day:** Next day I will be working on the [##180312665 task](https://www.pivotaltracker.com/story/show/180312665). Figuring out the node that _invokes_ MultipleDispatchFunction (Enso Bot - Nov 19, 2021)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for today (2021-11-19):

**Today:** Continue with the Universal Conversions task. Started to work on the tooling subtask. Designed the reverse index of available conversions. Turned out that API serving the suggestions also needs to be extended. Deployed the CloudUI with the version selector. It should be finished by 2021-11-19.

**Next Day:** Next day I will be working on the [##180312665 task](https://www.pivotaltracker.com/story/show/180312665). Continue working on the suggestions system, adding an index of available conversions. (Enso Bot - Nov 19, 2021)
<hr />
**Edward Kmett** reports a new **STANDUP** for today (2021-11-19):

**Today:** I now have a plan of attack for how to invoke the multiple dispatch function node. It should be finished by 2011-11-26.

**Next Day:** Next day I will be working on the [##180312665 task](https://www.pivotaltracker.com/story/show/180312665). Implementing that plan, then starting on how to get these nodes constructed. (Enso Bot - Nov 19, 2021)
<hr />
standup for 2021-11-22:

Issue: #180312665

Today: My first plan for the multifunction dispatch node failed due to having forgotten a quirk of truffle calling conventions. Everything has to dispatch through calltargets and all arguments have to be smashed into a naked array of objects, no exceptions. If I implemented it the other way it would have mucked with all the node types that do data retrieval from that environment. Blech. Should be salvageable with some tweaks.

End Date: 2011-11-30

Next Issue: same

Next Day: Implementing my new plan, then starting on how to get these nodes constructed.

Additional Info: I wasn't able to feed this to Enso Bot, for formatting reasons and the fact that this ticket wasn't actually open yesterday.
 (Edward Kmett - Nov 23, 2021)
<hr />
**Edward Kmett** reports a new **STANDUP** for today (2021-11-23):

**Today:** Got distracted by the benchmark system. Trying to get some usable baseline results so I can have a sense of any regressions I might cause. Had covid booster yesterday, so I'm somewhat suboptimal performance-wise today. It should be finished by 2021-11-30.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180312665). Getting back to the "new plan", then starting on how to get these nodes constructed.

**Additional Information:** "Worked on #180312665. But it won't let me mark that fact as the issue wasn't 'started' at the time? I clicked start after doing some rough guestimation at story points without an appropriate scale, but it still won't let me submit." Also @wdanilo reminded me that 2011 /= 2021, so I expect this will now submit. (Enso Bot - Nov 24, 2021)
<hr />
**Edward Kmett** reports a new **STANDUP** for yesterday (2021-11-24):

**Today:** Back into figuring out a dynamic dispatch path for 'from'. Dug out some of the code I used for custom polymorphic inline caching in Cadenza, and I think I might be able to adapt it to our polymorphic inline caching needs around multiple dispatch. It should be finished by 2021-11-30.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180312665). Thanksgiving, then back to implementation. (Enso Bot - Nov 25, 2021)
<hr />
