### ISSUE TITLE
Enso developers should receive automated performance feedback on their PRs

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5557]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/180311786).
<hr />

## Why

Developers want to avoid degrading the performance of the product with new features.
Product owners want to ensure the performance of the product. 

**As** developer/product owner
**I want** to ensure new development does not degrade performance of the product
**So that** Enso stays fast

## Acceptance Criteria

```gherkin
Scenario: 
Given an open PR 
When the PR implements something that degrades performance beyond our performance goals
Then the CI should reject that PR
```

## Resources
https://github.com/enso-org/design/blob/wip/wd/profiling/designs/profiling/implementation.md#continuous-performance-monitoring

## Tasks:
- [ ] Add functionality to compare reports and report the comparison status
- [ ] Create reference report to be used on CI
- [ ] Set up CI to fail PRs that fail the reference benchmark
