### ISSUE TITLE
Tooling Enhancements

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#563]
### Summary
A language without well-integrated tooling is often one that is awkward to work with and harder to manage. Given that these things are the _exact_ opposite of what we aim to provide with Enso, it is incredibly important that we provide a comprehensive set of tools for the language that span the gamut from end-user programming to library implementor and beyond.

This set of tools should include, but isn't limited to, package management functionality to integrate with Enso Cloud, project management tools, build tools, and interactive tools such as a REPL with integrated debugger.

### Value
The better integrated a language's tooling, the more pleasurable it is to work with a language. Enso having well-designed and well-integrated tools (even outside Enso Studio) ensures that it is nice to work with and doesn't stymie its users. 

### Specification
The majority of these tools are exposing features that the IDE Protocol (#912) provides to users explicitly through tools other than Enso Studio. 

- [ ] Design and implement a REPL for developing textual Enso code in an interactive fashion. This REPL should have inbuilt support for a comprehensive Enso debugger.
- [ ] Design and implement an extension to the Enso CLI to support basic project management.
- [ ] Design and implement performance analysis tools for Enso code based upon the analysis data provided over the IDE protocol by the interpreter introspection service. 
- [ ] Design and implement a system that performs automatic concurrency analysis for Enso code, allowing for automatic parallelism. 
- [ ] Design and implement a package registry and the tools for registering, uploading, and downloading packages, and managing dependencies.
- [ ] Implement support for working with project metadata (#517). 
- [ ] Implement support for _very basic_ analysis requests (#516, #515).

### Acceptance Criteria & Test Cases

- Enso is shipped with a comprehensive set of tooling for users and developers. 
- This tooling is so well-integrated with Enso and the interpreter so as to become invaluable.
