### ISSUE TITLE
Ahead-of-Time Typechecking

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#569]
### Summary
Despite the fact that the existing Truffle interpreter for Enso operates in a purely dynamic fashion, the language has always been intended to have comprehensive type-system with near-complete type inference and fast type-checking. 

At first this may seem unnecessary - surely if the dynamic interpreter works then it isn't needed - but the type system can provide the users with a significant number of additional guarantees without any effort of their own. Furthermore, the users that invest their own time and effort into using the types can get comprehensive guarantees about the safety and correctness of their programs. 

All in all, the type system should stay out of the users' ways unless they make a mistake, but give more experienced users the tools to build the programs that they require.

This epic is emphatically _not_ intended to be implemented for the first public release of Luna 2.0, and instead aims to focus 

### Value
On the spectrum of programming type systems ranging from dynamically typed to statically typed, one likes to think that there is a happy medium between the two. A language that feels dynamic, with high levels of type inference, but lets the users add more type information as they want more safety and compile-time checking.

Enso aims to be that language, providing a statically-typed language with a type system that makes it feel dynamic. It will infer sensible types in many cases, but as users move from exploratory pipelines to production systems, they are able to add more and more type information to their programs, proving more and more properties using the type system. This is based on a novel type-inference engine, and a fusion of nominal and structural typing, combined with dependent types.

### Specification

- [ ] Complete the [design](https://github.com/luna/enso/blob/master/doc/design/type-system/types.md) for the Enso type-system, including explicit descriptions of the inference and checking rules.
- [ ] Formalise the portions of this design necessary to produce a correct implementation.
- [ ] Implement the type-checker, operating purely on user-provided type annotations.
- [ ] Implement the type-inference engine, used to feed the type-checker in circumstances where no annotations are provided by the user. 
- [ ] Accompany the implementations of both of the above with comprehensive tests of the inference and type-checking behaviour in order to catch regressions. These tests should accommodate both the simplest and most in-depth usages of the Enso type system. 
- [ ] Improve the performance of the type-inference engine and the type-checker to allow them to operate faster. Additionally, if possible, implement incremental modes for both, using detailed dependency information about the types.
- [ ] Provide pretty and informative type errors, informed by the rust display and information system for the same.

A brief note about the philosphy behind Enso is that it asserts that we want _full beta reduction_ in types. For practicality's sake this may require some recursion bound in the cases where equational reasoning fails. 

In addition, it will be important to design the type system in a way that enables incremental type-checking and inference, in order to enable Luna to remain interactive. This will involve building a type-dependency graph during checking and inference, in order to accurately track the minimal portion of the program for which these processes needs to be run again.

### Acceptance Criteria & Test Cases

- The type-system has been formalised.
- The type-checker and type-inference engines have been implemented. 
- They are able to operate in an incremental mode.
- They are accompanied by rigorous tests and benchmarks.
