### ISSUE TITLE
Foreign Language Interoperability

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#570]
### Summary
In addition to its visual nature, one of the major selling points of Enso is the promised seamless interoperability with other languages (e.g. Python, JavaScript, and R). While GraalVM provides support for calling foreign code, making this seamless will require significant work, and this is what this epic deals with.

### Value
Seamless interoperation with foreign languages will allow users of Enso to better integrate with their existing code and existing systems, making the language an even more invaluable part of their infrastructure. 

### Specification

- [ ] Determine how to make interoperability seamless for users. This means that foreign code, for the most part, should 'just work'. 
- [ ] Improve the language boundary for Enso to allow calling Enso from foreign languages, and foreign languages from Enso, without any noticeable performance loss.
- [ ] Determine how to properly cache foreign language contexts to help speed up interop.
- [ ] Determine how best to package foreign language dependencies alongside (or inside) Enso projects, and implement support for this in the interpreter.
- [ ] Create a design for C-level interoperability, using Sulong (an LLI clone built using truffle) for safe interop, and JNI for when users want the utmost in performance while sacrificing safety. Implement this design alongside appropriate libraries to support low-level usage.
- [ ] Determine how best we can provide for interop with JVM languages (such as Java and Scala), given that they do not have truffle interpreters of their own. This will likely involve reflection, but as far as the users are concerned it should operate identically to any other foreign language. 

### Acceptance Criteria & Test Cases

- Each of the above specification points has been implemented on master.
- All are accompanied with comprehensive tests and rigorous benchmarks in order to catch any performance regressions.
