### ISSUE TITLE
Runtime Introspection

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#571]
### Summary
The main selling point of Enso and Enso Studio is the language's interactivity. However, enabling this interactivity requires deep runtime support for introspection of running code. This allows the GUI to obtain values and type information to display to users, but also allows for the implementation of more complex functionality such as debuggers and a REPL.

### Value
Without the support for runtime introspection it is impossible to provide the promised Enso GUI, so this is inherently very necessary. 

### Specification
The following elements are presented in order as a plan for the introspection functionality into the interpreter in a way that allows it to take place in parallel with the work on the new syntax (#806). Each of these phases should _not_ break interpreter behaviour on master. Additionally, it is very important that the runtime and the engine _only_ talk via `org.graalvm.polyglot`. There should _never_ be an explicit runtime dependency on `runtime` by either `gateway` or `language_server`.

- [x] Implement passing of source-code location information through the interpreter (#752) 
- [x] Take the interpreter's handling of dependencies and the execution flow and streamline it to make it work with interactive workflows (#756). 
- [x] Design the language server protocol (#912).
- [x] Extract values from scopes based on source locations (#779), and use this to enable arbitrary code execution on these values (#778). 
- [x] Implement support for 'entering' functions in the interpreter (#726).
- [x] Implement stub services for the gateway and language server components (#742).
- [x] Implement caching of values in the interpreter (#782).
- [x] Clarify the language server and gateway architecture (#700, #699, #698).
- [x] Design support for multi-client connections in the engine, and record this design in the documentation (#736). From now on, all future functionality should account for multi-client development.
- [x] Implement the required runtime functionality to support the basic language server workflow (#739).
- [x] Implement support for capabilities and write-lock in the language server (#701, #714). 
- [x] Text buffer management (#667, #666).
- [x] Implement the text editing functionality of the language server (#665, #664, #663, #662, #661).
- [x] Implement the file-manager functionality of the language server (#679, #678, #677, #676, #675, #674, #673, #672, #476, #670, #669 ). Care must be taken to avoid conflicts with these operations in a multi-client situation.
- [x] Implement support for execution management (#710, #734, #658, #657, #656, #655, #654, #653, #652, #481).
- [x] Implement the runtime server support for execution management (#649, #648, #647, #646).
- [x] Implement stopgap JSON Serialisation (#637).
- [x] Implement visualisation support (#639, #640).
- [x] Support for working with binary files (#668).
- [x] Fix flatbuffers stuff (#609).
- [x] Project manager uberjar (#614).
- [x] I/O stream redirection (#705).
- [ ] Introduce threaded execution to the runtime server instrument (#606).
- [ ] Add support for dynamic content roots (#486).
- [ ] Execution context enhancements (#471, #481).
- [ ] Bug fixing (#474, #479).

### Acceptance Criteria & Test Cases

- The above requirements have been met.
- They have been rigorously tested, and are accompanied by benchmarks designed to detect regressions.
