### ISSUE TITLE
Interpreter Performance Improvements

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#572]
### Summary
This epic exists to track tasks that do not neatly fall into the product-oriented development phases that are to do with improving the interpreter's performance. These tasks are all considered to be very low priority, but should nonetheless be completed at some point as they will or may yield improved interpreter performance.

### Value
Out of all the outwardly-perceptible things that relate to the interpreter, performance is one of the ones that is most apparent to users. Better performance is better for the users, and for their programs, as it enhances interactivity, but also makes things run faster. 

### Specification

- [ ] Improve the comparative benchmarking suite (#580, luna/luna#566).
- [ ] Experiment with project loom (#581).
- [ ] Improve oversaturated applications for tail recursive functions (#549).

### Acceptance Criteria & Test Cases

- This epic is intended to be ongoing, and hence does not have specific acceptance criteria.
- Please refer to the individual optimisation tasks for more information.
