### ISSUE TITLE
Standard Library 2.0

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#576]
### Summary
A language is nothing without its standard library. With all the changes that the 2.0 alpha release will bring, including the new language semantics, new syntax, dynamic behaviour, and so-forth (all based on top of GraalVM), none of the previous standard library is going to work.

To this end, the standard library needs to be implemented anew with a focus on the core primitives required to enable productive use of the Enso language, and the development of further libraries on top of this. 

### Value
Having a re-implemented standard library is the primary precursor required for the implementation of further libraries for Enso. It provides the primary building blocks for more complex libraries and larger programs, both of which are necessary for Enso's future success. 

### Specification
While Enso eventually wants to provide a comprehensive, batteries-included standard library implementation, this specification deals with what we see as the _minimum_ viable product for the first release of the Enso standard library. 

- [x] Research into how packaging and libraries should work (#612). 
- [x] Implement minimal packaging support (#611).
- [x] Implement support for comments (#610).
- [x] Implement the `Boolean` type, with operators and useful operations (#862).
- [x] Implement a library for working with state (#505).
- [x] Implement `Vector`, with useful operations (#496).
- [x] Implement a framework for performing tests natively in Enso code (#502, #506).
- [x] Implement `List`, with useful operations (#503).
- [x] Implement the basic numeric type `Number` with conversions, operators and useful operations (#584, #507).
- [x] Implement the `Text` type with operators and useful operations (#504).
- [x] Implement a library for working with files on disk (#495).
- [x] Implement a JSON support library for encoding and decoding types from JSON (#494).
- [x] Implement an HTTP library for connecting to other services (#493).
- [x] Implement a library for working with time (#500).
- [ ] Implement a framework for performing benchmarks natively in Enso code, and move all existing benchmarks over to use it (#499, #498).
- [x] Implement `Map`, with useful operations (#497).

This is the point which we currently consider to be a reasonable cutoff for the 2.0 release, but do not consider the basic standard library complete until the following issues have also been completed.

- [x] Implement a system interface library (#492).
- [ ] Implement `Float64` and `Int64` with conversions, operators and useful operations (#501, #491).
- [ ] Implement a `Bytes` type and support for working with binary files (#490, #489).

As a stopgap, much of this will be implemented in terms of primops embedded into the interpreter. Over time, these can be replaced with calls over interop.

In addition, there is a list of miscellaneous fixes and enhancements that help remove pain points from the language: 

- [x] Make execution interruptible (#603). 
- [x] Create an annotation processor to help with defining the standard library (#433).
- [ ] Provide a better error for nonexistent variables (#578).
- [x] Implement exports and imports (#1027).
- [ ] Fix potential interpreter crashes (#468).
- [ ] Support getters and setters (#520).
- [ ] Design and build the enso launcher script (#460, #459). 
- [ ] Thread safety for the language context (#454). 

### Acceptance Criteria & Test Cases

- Enso has a basic standard library that provides enough utility to implement more complex libraries and
- The functionality of the standard library is rigorously tested.
- The functionality of the standard library is rigorously benchmarked.
