### ISSUE TITLE
Write Data flow control vel Execution Context.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#5899]
### Why

When a node is added to Enso, its operation is executed immediately (and evaluated when the node is being entered). For functions with no side effects, this is fine. However, for those with side effects, this can be problematic. 

### How

The exact design is still in progress: https://github.com/enso-org/design/pull/53

```[tasklist]
### Tasks
- [ ] #5713
- [ ] https://github.com/enso-org/enso/issues/5926
- [ ] https://github.com/enso-org/enso/issues/5927
- [ ] https://github.com/enso-org/enso/issues/5928
- [ ] https://github.com/enso-org/enso/issues/5929
- [ ] https://github.com/enso-org/enso/issues/5930
- [ ] https://github.com/enso-org/enso/issues/5931
- [ ] https://github.com/enso-org/enso/issues/5932
- [ ] https://github.com/enso-org/enso/issues/5933
- [ ] https://github.com/enso-org/enso/issues/5934
- [ ] https://github.com/enso-org/enso/issues/6179
- [ ] https://github.com/enso-org/enso/issues/6181
- [ ] https://github.com/enso-org/enso/issues/6177
- [ ] https://github.com/enso-org/enso/issues/6182
- [ ] https://github.com/enso-org/enso/issues/6353
```
