### ISSUE TITLE
Add ability to compare branches to bench_download tool

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#6110]
`tools/performance/engine-benchmarks/bench_download.py` tool, introduced in #5852, should provide functionality to compare two (or more?) branches. This will be useful when one wants to ensure that the changes on their PR won't cause any regressions after merging to `develop`.

```[tasklist]
### Tasks
- [ ] Introduce `--branches <branch1, branch2, ...>` option.
- [ ] Display average for every branch under every graph, optimally with their differences.
- [ ] Display points from all the branches in every graph. Branches will have different X axis (timestamp of benchmark runs).
```

**Comment by Akirathan** [comment]
I would like to implement this before #5998.
