### ISSUE TITLE
Stabilize list editor

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#6522]
After initial implementation, List editor tends to behave erratically. Dropped elements sometimes aren't registered as part of node's expression, and in rare occasions drag or drop also causes a panic. Nested list editors are also completely not supported.

```[tasklist]
### Tasks
- [x] Make sure all drags and drops are registered and handled properly, fix panics.
- [ ] Add support for lists in lists.
- [x] Remove feature flag, permanently enabling the list editor.
```

**Comment by Frizi** [comment]
Adding support for nested lists is for now postponed, as this is definitely way lower priority, but pretty hard to support at the moment.
