### ISSUE TITLE
Improve performance by span-tree removal

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#6834]
The span tree shall be replaced with AST + structure with data necessary for widgets

```[tasklist]
### Tasks
- [ ] #6772
- [ ] Implement AST operations (removing, adding argument, replacing...) in place of SpanTree actions.
- [ ] Create a data structure assiciating data from execution context with AST (so it will be easily used by the widgets)
- [ ] Improve source code reference type in AST.
- [ ] Generate Widgets from AST + data from controllers.
- [ ] SImplify edges and nodes updates in Graph Editor (to not make unnecessary changes).
```

**Comment by farmaazon** [comment]
There's no span-tree in new GUI.
