### ISSUE TITLE
Allow external edits of project files

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#7178]
When an external editor changes the file opened in IDE, IDE should be aware of the changes.

## TODO
- [x] Implement the file reload by keypress in IDE
- [x] Connect the existing file-watching service and implement the file reload by notification from the language server
- [ ] Replace the existing file-watching service with the new JS one

**Comment by wdanilo** [comment]
Dmitry, how do you plan to implement a file watcher? FYI, it's VERY hard and very system dependent. There are many things not working well across different operating systems and we were facing these issues in Rust build system. We investigated tons of libraries in different languages and we've found out that there is one lib working good across systems that can be easily integrated with gitignore files (which is crucial, otherwise it will work slow or crash in bigger git repos). I've built [cargo-watch-plus](https://github.com/enso-org/cargo-watch-plus) on top of it - 300 lines of code with gitignore support, extensive cmd support, etc. It's tested and works well on MacOS (both the new Mac fs, and older fs), Windows and Linux. I'm pretty sure (after this big trouble and research we had) that we want probably to use the same approach here. You can just create a small JS lib using the libs I'm using to create a daemon for watching files and notifying you. Let's have a call tomorrow to discuss this and alternative approaches, please.

**Comment by JanBeelte** [comment]
NodeJS based filewatcher is implemented as discussed under:
https://github.com/enso-org/enso/tree/wip/jbeelte/file-watcher

<blockquote><img src="https://opengraph.githubassets.com/dbc1079670a52162ebdc3b67c91c9fed21f91af56051551ed289b2555c95d246/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">enso/ at wip/jbeelte/file-watcher · enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by 4e6** [comment]
Since the implementation got a bit more involved, I will split the task into three steps:
- Implement the file reload by keypress in IDE
- Connect the existing file-watching service and implement the file reload by notification from the language server
- Replace the existing file-watching service with the new JS one

**Comment by JaroslavTulach** [comment]
> how do you plan to implement a file watcher? FYI, it's VERY hard and very system dependent. 

That's certainly true. Writing this properly is complicated. Luckily NetBeans had already spent quite a significant time solving this problem as well. Quick links before I go deeper into the description:
- linux: https://github.com/apache/netbeans/tree/master/platform/masterfs.linux
- macosx: https://github.com/apache/netbeans/tree/master/platform/masterfs.macosx
- windows: https://github.com/apache/netbeans/tree/master/platform/masterfs.windows
- nio2 (e.g. the java one): https://github.com/apache/netbeans/tree/master/platform/masterfs.nio2

All these modules (e.g. JAR files) implement single [Notifier](https://bits.netbeans.org/dev/javadoc/org-netbeans-modules-masterfs/org/netbeans/modules/masterfs/providers/Notifier.html) interface. These JARs are available on Maven central. As far as I see there are no additional dependencies of these JARs. Enough to copy/specify the [Notifier.java](https://github.com/apache/netbeans/blob/4550e47e6429f7ab16d2ee8637625743d7252ff6/platform/masterfs/src/org/netbeans/modules/masterfs/providers/Notifier.java#L4) in our codebase and then get the [JARs from Maven](https://central.sonatype.com/artifact/org.netbeans.modules/org-netbeans-modules-masterfs-windows/RELEASE170?smo=true) and link them without any dependencies (they have one on `masterfs` module, which depends on `org.openide.filesystems`, etc. but none of that is needed for the `Notifier` part. ... We could even refactor this code in NetBeans project itself and use the `Notifier` modules directly from Maven central without any changes.

> (Wojciech) built [cargo-watch-plus](https://github.com/enso-org/cargo-watch-plus) 

Eating our own food is a viable alternative as well.

> You can just create a small JS lib using the libs 

No _node.js_ please! 

As far as I can see the [cargo-watch-plus](https://github.com/enso-org/cargo-watch-plus)  has `node.js` bindings - that's not something we want in the engine/language server. Using [node.js API from JVM](https://github.com/JaroslavTulach/graal-js-archetype) is possible, but cumbersome. It would add a huge blob of dependencies, that we don't want in the Enso engine and language server.

We could, however, built a [Java JNI wrapper](https://en.wikipedia.org/wiki/Java_Native_Interface) around the Rust code of [cargo-watch-plus](https://github.com/enso-org/cargo-watch-plus)  project - we have some experience doing this gained while binding _Rust Enso parser to Java_.

**Comment by JanBeelte** [comment]
> We could, however, built a [Java JNI wrapper](https://en.wikipedia.org/wiki/Java_Native_Interface) around the Rust code of [cargo-watch-plus](https://github.com/enso-org/cargo-watch-plus) project - we have some experience doing this gained while binding _Rust Enso parser to Java_.

There is no real rust portion. cargo-watch-plus is entirely based on a NodeJS library.
If there is already the netbeans solution AND it is easier to integrate I also think this would be the best approach moving forward!

**Comment by wdanilo** [comment]
@JaroslavTulach I'd prefer not to use `nodejs` as well, but I did not find any alternative that works. IFF your lib works well and doesn't have bugs (like not providing all events or reporting duplicate events) on all platforms, that's great. But if there will be some bugs (as again, this is extremely hard problem), we need to use something that works and this JS library is the only one that I know that really works well cross-platform. What is the plan for testing this Java lib to be sure it works fine on all systems?

**Comment by 4e6** [comment]
Idea spawns native `fsnotifier` process to watch files  https://github.com/JetBrains/intellij-community/tree/master/native/fsNotifier
https://github.com/JetBrains/intellij-community/blob/master/platform/platform-impl/src/com/intellij/openapi/vfs/impl/local/NativeFileWatcherImpl.java#L150-L158

**Comment by JaroslavTulach** [comment]
After few discussions, I believe the following quote:

> ... not providing all events or reporting duplicate events...

...exaggerates the problem of [Java Watch Service](https://docs.oracle.com/javase/8/docs/api/java/nio/file/WatchService.html). I know its Javadoc sounds scary, but I am convinced we should start with it in spite of that. The [Java Watch Service](https://docs.oracle.com/javase/8/docs/api/java/nio/file/WatchService.html) offers many benefits:
- it is packaged in the JDK - e.g. no new library dependencies
- it works on all supported platforms - Windows, Linux, Mac

What do we need? As soon as a file is modified externally on a disk, we need a notification. As soon as a notification arrives, we compare the state of the file on disk with the state of the file in memory and if there is a difference, we update the state in memory and notify the IDE. Should there be an [overflow of the events](https://docs.oracle.com/javase/8/docs/api/java/nio/file/StandardWatchEventKinds.html#OVERFLOW) we just take it as a signal to verify state of all the files we have in memory.

Of course, this implementation shall be _hidden behind an API facade_ and kept in a _separate project/module_ nobody else depends on (except via the API). That will allow us to replace it in the future, if problems in this _simple to implement_ approach are found. 

We can use the [NetBeans approach](https://github.com/apache/netbeans/tree/master/platform/masterfs.linux), we can span a [separate process]( https://github.com/JetBrains/intellij-community/tree/master/native/fsNotifier), we can even use _node.js_, but I'd suggest to start with the simple solution and only complicate it later, if necessary.
