### ISSUE TITLE
EnsoBigInteger should be a BigInteger polyglot type

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#7213]
#7176 integrates GraalVM 17.0.7 (23.0.0 JDK 17) into Enso, which brings support for `BigInteger` polyglot type. After we refactor `EnsoBigInteger` to be a proper `BigInteger` interop type (by implementing `fitsInBigInteger` message), we should measure the performance impact - for example the impact of a sum of a column that is made of big integers, instead of longs. 

This is a follow-up issue of #5300

```[tasklist]
### Tasks
- [x] Once the `BigInteger` support is in, please fix https://github.com/enso-org/enso/pull/4074#discussion_r1087705956
- [x] Revert https://github.com/enso-org/enso/pull/7176/commits/f279100477a38527e26277320a4f67c1678c70c8 - **done** in ad2bae5
- [x] `EnsoBigInteger` shall no longer extend `java.lang.Number - **done** in f20b569
- [x] Ensure that polyglot method with `java.lang.Number` as parameter does not do lossy conversion for `EnsoBigInteger` - **done** shown in 681d7b2
- [x] Ensure interop with JavaScript, Python - see also #7387
```
