### ISSUE TITLE
Implement a benchmark for a builtin Table type

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7316]
As @JaroslavTulach [noted](https://github.com/enso-org/enso/pull/7270#issuecomment-1637434818) on #7270, we want to extend the various approached tested in these benchmarks to also check how the performance will be influenced by making Table/Column a builtin.

It may be best to implement this _after_ #6111, which will slightly influence the API of the relevant functions - so that the new benchmark will reflect the _new_ API which should also make it more powerful.

### Tasks
- [ ] Create a PoC of a builtin Table/Column as a draft PR.
        - [ ] Prototype how a _storage implementation_ can be exposed as a builtin 
	- [ ] It should support LongStorage, StringStorage, BoolStorage and possibly MixedStorage - we can essentially just copy most of the code into the runtime and expose necessary parts of the API.
	- [ ] Expose access to values of a column through the polyglot array interface.
	- [ ] Implement `map` and `zip` operations that take an Enso function.
- [ ] Add cases to the existing `Exploratory_Benchmarks/src/Table` benchmarks that are using these builtin `map` and `zip` that.
- [ ] Analyze the results.

We probably won't be able to merge the draft PR as it would add a prototype into our main codebase - there is no way to implement this builtin as a feature external to the runtime. Unless we plan to proceed with actually making the Table a builtin where we could merge this as a first step towards that goal.
