### ISSUE TITLE
Ability to get the list of target conversion types for a type

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7320]
In order to allow use of [Any.to](https://github.com/enso-org/enso/pull/7704) conversion method easier and conversions more powerful we want to enable **finding a list of target types for a value**. For example: `Column` will be convertible to `Vector`, `Text`, `JSON`, `Table`.

##### Component Browser

The IDE can then display/offer not only `Column` own methods in the **component browser**, but also methods on the _convertible to types_ when having a _value of type_ `Column`. Making it possible to use a value in _all its possible roles_ without requiring the user to do such conversions in multiple steps.

##### Example

If there is a node with value of type `Complex` (just like in [this example](https://github.com/enso-org/enso/pull/7716#issuecomment-1704822519)) and there is a conversion from `Complex` to `Number`, then the **component browser** may offer method like `Number.floor`  and when it is selected, it would insert:
```ruby
complexOperator1.to Number . floor
```
e.g. it would convert the value of type `Complex` to `Number` via `Any.to` method (which effectively invokes the `Number.from(that:Complex)` method and then operated on the result as it was a `Number`. 
```[tasklist]
### Tasks
- [ ] Enable transfer of conversion methods (current it is [disabled](https://github.com/enso-org/enso/pull/7716/files#diff-a371d887fb5a47107c1310b0d3707d3505f2dd28e96b1832e1b6041fcaed2890R749))
- [ ] Cleanup the DB/send data (here is the [list of current problems](https://github.com/enso-org/enso/issues/7320#issuecomment-1704972767))
- [ ] Make sure IDE receives and stores the data
- [ ] Demonstrate the IDE can use the data (showing more methods for example when `Complex` value is present)
```

**Comment by JaroslavTulach** [comment]
"Half" of this issue is going to be fixed by
- #7704 

the _getting the list of target conversion types_ is still pending.

**Comment by JaroslavTulach** [comment]
#### What to Send?

With #7716 we are able to collect following data to the DB:

![all conversions](https://github.com/enso-org/enso/assets/26887752/cbaaea3a-ad75-4a38-8dcd-ef655d3e53fb)

The **return type** is wrong. A conversion [defined for Complex number](https://github.com/enso-org/enso/pull/7716#issuecomment-1704822519):
```ruby
type Complex
    Value re:Number im:Number

Number.from (that:Complex) (ignore_im:Boolean=False) = case ignore_im of
    False -> that.re*that.re+that.im*that.im . sqrt
    True -> that.re
```
is supposed to return `Number`. E.g. the return type should `Standard.Base.Data.Number`.

The **self type** uses short name and not **FQN**. We should be sending **FQN** of `that` argument - e.g. `local.Empty.Main.Complex` in the previous example.

The **name** argument is mangled. If we could avoid it and use just `from`, then the SQL queries would be simpler.

The **reexport** column is important. Some of the conversions may not be available without import. The IDE should make sure that when a conversion is selected, the appropriate **reexport** import is also added.
