### ISSUE TITLE
Renaming Variable or Function Support within a Single File

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7389]
Add an API to the language server protocol which will allow for renaming a variable or a function.

This will need work with the parser to identify the uses of the name and to create a set of edit operations to perform the rename.

```[tasklist]
### Tasks
- [ ] Write a sample unit test (preferably in Java) to execute a piece of Enso code and then operate on IR:
- [ ] Process IR to sufficiently advanced phase
- [ ] Implement _Find Usages_ - e.g. Identify all locations a (local) symbol occurs at
- [ ] Turn the locations into set of `TextEdit`s with a new name
- [ ] Implement error checks - avoid invalid names, avoid names that already exists
- [ ] Apply the edits to in memory buffer and save
- [ ] Execute the generate source (in the test) again to verify it produces the same result
```

**Comment by JaroslavTulach** [comment]
I'd like us to create `runtime/refactoring` module with APIs for doing refactorings and to host the _rename refactoring_ implementation. Such a module should have just a minimal compile time dependency: I believe depending on existing `runtime/parser` module (which provides access to `IR`) is good enough. Tests of that module may (of course) depend on more, including `runtime`, so the code can also be executed.
