### ISSUE TITLE
Ability to invoke all std-benchmarks via JMH

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#7489]
Follow-up of issue https://github.com/enso-org/enso/issues/7323 and of its associated PR https://github.com/enso-org/enso/pull/7101.

```[tasklist]
### Tasks
- [x] Align `Bench_Options` defined in `Bench.enso` with options of JMH's `@Benchmark` annotation.
- [x] Unify names of Enso benchmarks with JMH benchmarks
- [ ] Design `setup` and `teardown` parameters
- [ ] Move rest of the benchmarks in `test/Benchmarks` project to the benchmark builder API, and test their JMH benchmark invocation
- [ ] Fix https://github.com/enso-org/enso/pull/7101#discussion_r1283410133
- [ ] Unify and improve the experience of benchmarks debugging - https://github.com/enso-org/enso/pull/7101/commits/95e6deaeba270cfc0ad70df89b5423d871dd0dba#r1285679966
```
