### ISSUE TITLE
Allow access to caches and instrumentation from Enso

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#7683]
There are various issues related to current implementation of language server:
- #5419
- #5570
- [Akka changing its license](https://github.com/enso-org/enso/issues/5419#issuecomment-1462487661) and the need to migrate away from it
- the need to create stable (and as small as possible) API between IDE and engine/LS: #7639
- AI extensions needing access to caches

While thinking about these issues I concluded that it would be better **expose the core of runtime caching & instrumentation functionality** to Enso programs and use it from _visualizations_. The plan is to **create a builtin type** that would allow _instrumentation of certain nodes_ and registration of functions to _receive a callback_ when a node or expression _evaluation is started and finished_. The callback would receive the _actual values_ flowing thru the program and could control (invalidate) the runtime cache whenever needed.

Exposing these _caching & instrumentation functionality_ would create simple, low-level API that could easily be used to emulate the current behavior and even more easily expand it when needed. Caching & instrumentation related activities shall be as simple as writing a visualization.

We need to spend some time and investigate whether this is a viable approach. Prior work however indicates this is doable and fully functional. There is [GraalVM Insight](https://www.graalvm.org/latest/tools/graalvm-insight/) which exposes the _instrumentation capabilities_ to scripting language. We know that [GraalVM Insight works with Enso](https://github.com/enso-org/enso/pull/7009#issuecomment-1628246071), however following should be investigated:

```[tasklist]
### Tasks
- [x] Expose `IdExecutionInstrument` functionality as a builtin
- [x] Demonstrate Enso program can observe execution of another Enso program
- [x] Provide a builtin to access and control the `RuntimeCaches`
```

**Comment by JaroslavTulach** [comment]
### Making `Standard.Visualization` Part of the IDE

In the light of #7692 discussion and to solve the #7639 problems, let's consider following: Let's make the `Standard.Visualization` Enso library part of the IDE. 

##### What problem this addresses? 

The IDE contains built-in JavaScript parts of the visualizations that expect certain functions in `Standard.Visualization`. Currently `Standard.Visualization` is distributed as part of engine. As a result the IDE is tight to the exact version of engine it can work with - otherwise JavaScript parts of visualization will not find the right methods.

By packaging and distributing `Standard.Visualization` as part of the IDE we avoid mismatch with their JavaScript counter parts. They will always work together.

##### What is Needed?

- the **IDE needs to tell the engine about a special repository** that it should download `Standard.Visualization` & co. from 
- so that modules used by [VisualizationConfiguration](https://github.com/enso-org/enso/blob/develop/docs/language-server/protocol-language-server.md#visualizationconfiguration) can access modules from the special repository

**Comment by JaroslavTulach** [comment]
### Making Language Server Part of the IDE

In the light of #7692 discussion and to solve the #7639 problems, let's consider following: Let's repackage current implementation of **language server as Enso library**!

##### What problem this addresses?

Currently the language server is bundled together with the Enso engine in `enso-engine` bundle. That requires us to version the [language server protocol](https://github.com/enso-org/enso/blob/develop/docs/language-server/protocol-language-server.md) properly, negotiate at the beginning of the session the version that IDE requires and the version engine provides and reject co-operation between these two, when they don't match. The user can then either _downgrade the IDE_ or _upgrade the engine_ or vice versa.

By packaging the language server implementation as an Enso library `Standard.Language_Server` and bundling it together with the IDE we will always guarantee the he [language server protocol](https://github.com/enso-org/enso/blob/develop/docs/language-server/protocol-language-server.md) version required by the IDE is the same as the one supported by the  `Standard.Language_Server` library.

##### What is Needed?

- the **IDE needs to tell the engine about a special repository** that it should download `Standard.Language_Server` from
- the IDE needs to tell the `project-manager` to activate/start `main` method of `Standard.Language_Server` when _launching engine_
- `Standard.Language_Server` needs access to instrumentation and caches from the engine

**Comment by 4e6** [comment]
> Making Language Server Part of the IDE

> the IDE needs to tell the engine about a special repository that it should download Standard.Language_Server from

We already ship IDE with the project manager. We should package the language server with IDE instead of downloading it.
