### ISSUE TITLE
Upgrade Enso to GraalVM for JDK 21

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#7851]
There is new version of GraalVM for JDK21 since yesterday. Here is some information about [Truffle Unchained](https://medium.com/graalvm/truffle-unchained-13887b77b62c). The upgrade is going to be tougher this time:

```[tasklist]
### Tasks
- [x] Change the GraalVM version check to non-fatal error - **done** in #7855
- [x] Avoid `boostrap` & copy of `truffle-api`: `./bin/java -d org.graalvm.truffle` seems to `exports com.oracle.truffle.api` & co.  - **done** in #7855
- [x] Update documentation that mentiones `sbt bootstrap`
- [x] `gu` is gone! Stop calling it... https://github.com/oracle/graal/issues/6855 -  - **done** in #7855
- [x] `option -Dtruffle.class.path.append option is deprecated` - we need to build `module-info.java` for the runtime
- [x] Enable GraalPy on Windows: - https://github.com/oracle/graalpython/issues/321
- [x] Fix a lot of `Inexhaustive_Pattern_Match.Error TRegexReadOnlyIntArray` in `test/Tests`
```
## Follow-ups
- #8313 
- #8294 
- #8290 
- #8280
- #8314
- https://github.com/enso-org/enso/issues/8321

**Comment by JaroslavTulach** [comment]
> A lot of struggling with assembling fat jars and running them.

Yes, the problems with fat JARs were hard to solve. Their occurrence was a kind of _unknown unknown_ to me. I apologize for not being around sooner to [help overcome](https://github.com/enso-org/enso/pull/7991#discussion_r1368521558) the problems with more advanced `ClassLoader` usage. I hope you are unblocked now.

> will cause 7 days delay

Go for it! Still there is still going to be quite a few _know unknowns_, so the deadline is tough. Good luck.

**Comment by JaroslavTulach** [comment]
>     * In 15 seconds generates 5 GB of logs - the configuration is in `runner.jar` and not in `runtime.jar`.
>     * Now fixing the configuration - runtime module sees different configuration, e.g., for logging, than `runner.jar`.

Pavel, @hubertp shall know what resources need to be read to configure SLF4J in the `runtime.jar` properly. The [IsolatedClassLoader](https://github.com/enso-org/enso/pull/7991/files#diff-9ab172d0566c18456472aeb95c4345f47e2db3965e77e29c11694d3a9333a2aaR73) shall:
- **share** the `org.sfl4j` classes  between module path and `runner.jar`
- **load each SFL4J API class only once** into the JVM
- there should be only one implementation of _appenders_ - it should be in `runner.jar`
-  Make sure the configuration resources from `runtime.jar` are visible to `runner.jar` SLF4J implementation
- e.g. override `getResource` and `getResources` in `IsolatedClassLoader`
- to delegate to _system class loader_ to read necessary SLF4J configuration resources
