### ISSUE TITLE
Review and plan the library sharing discussion

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7955]
Update as of January 2026: @Akirathan resurrected the infrastructure for making library sharing possible:
- #14553
- #14469
- including documentation [how to publish](https://github.com/enso-org/enso/pull/14553/changes#diff-89188a9c7d38b63775078dd34d7b1c5111758e91f6dac7ec832e803fd9e2a715R21)

Pick up the design from @radeusgd: https://github.com/orgs/enso-org/discussions/7692

Aim of this ticket is to agree the design and add follow tickets for implementation as needed.

### Tasks
- [x] Prepare sample project and provide [instructions to package it](https://github.com/enso-org/enso/issues/7955#issuecomment-1764041585) as a library
- [x] [Upload sample edition](https://github.com/enso-org/enso/issues/7955#issuecomment-1764041585) with at the single library to local server
- [x] Create a [sample project](https://github.com/enso-org/enso/issues/7955#issuecomment-1764041585) and show it can download the library

**Comment by JaroslavTulach** [comment]
I have created a small project with a `Rand` type. Now I will turn it into a library:
```ruby
from Standard.Base import all

polyglot java import java.util.Random as R

type Rand
    Value value:Float ~next:Rand

    new : (Integer|Nothing) -> Rand
    new seed=Nothing =
        next generator = Rand.Value generator.nextDouble (next generator)

        init s =
            g = if s.is_nothing then R.new else R.new s
            next g

        init seed

    take : Integer -> Vector Float
    take self n = Vector.collect self .value .next n

main =
    r = Rand.new
    [ r.value, r.next.value, r.next.next.value ]
```
btw. the `generator` is completely _private field in the atom_ inaccessible from outside of `Rand.new`. By using _lazy atom field_ any implementation detail can be hidden behind them. Similar trick to [private JavaScript](http://wiki.apidesign.org/wiki/PrivateJavascript) that hides private stuff in local closures.

**Comment by JaroslavTulach** [comment]
#### Upload Sample Library

There is a [Simple Library Server](https://github.com/enso-org/enso/blob/1d124d7770fe233174c4fe00beb35daca0f090e7/tools/simple-library-server/README.md) written by @radeusgd. Run the server as:
```bash
enso/tools/simple-library-server$ ./main.js --port 1273 --upload no-auth --root ~/enso/repository/
```
then upload here in provided [Library_Rand library](https://github.com/enso-org/enso/files/12915897/Library_Rand.zip) with `enso-engine-*/enso-*/bin/enso` using following command:
```bash
$ enso --upload http://localhost:1273/upload --in-project Library_Rand
```
the server will print:
```
Uploading library [local.Library_Rand:0.0.1].
Upload complete.
```
the uploaded files will appear as:
```bash
~/enso/repository$ find libraries/
libraries/
libraries/Jaroslav
libraries/Jaroslav/Library_Rand
libraries/Jaroslav/Library_Rand/0.0.1
libraries/Jaroslav/Library_Rand/0.0.1/manifest.yaml
libraries/Jaroslav/Library_Rand/0.0.1/package.yaml
libraries/Jaroslav/Library_Rand/0.0.1/main.tgz
```

#### Define Edition

Now it is time to register this library as part of `demo-oct-2023.yaml` edition. Following the [instructions describing editions](https://github.com/enso-org/enso/blob/87ce78615afecb8bd8d586c798c97ab5e28083cd/docs/libraries/editions.md), let's create two files in the `editions` subdirectory of the server:
```bash
~/enso/repository$ find editions/
editions/
editions/demo-oct-2023.yaml
editions/manifest.yaml
~/enso/repository$ cat editions/manifest.yaml
editions:
  - "demo-oct-2023"
~/enso/repository$ cat editions/demo-oct-2023.yaml
extends: 0.0.0-dev
repositories:
  - name: demo-oct-2023
    url: http://localhost:1273/libraries
libraries:
  - name: Jaroslav.Library_Rand
    version: 0.0.1
    repository: demo-oct-2023
```
the `engine-version` and `extends` may not be `0.0.0-dev` in your case. Depends what's your engine version!


#### Use it!

Define pointer to your editions server in `global-config.yaml` (located in [ENSO_CONFIG_DIRECTORY](https://github.com/enso-org/enso/blob/e693147c17eef691bfe08d89d3a48b6e281255ba/docs/distribution/distribution.md#installed-enso-distribution-layout) which defaults to `$HOME/.config/enso` on Linux) with following content:
```yaml
edition-providers:
  - http://localhost:1273/editions/
```

Extract [Use_Rand.zip](https://github.com/enso-org/enso/files/12915961/Use_Rand.zip) and just execute with `enso-engine-*/enso-*/bin/enso` using following command:
```bash
$ enso --run Use_Rand
[0.775797284541735, 0.9978377545435057, 0.10628009155666762, 0.6415067077162341, 0.8467575391411488]
```
vector with five random floating numbers from zero to one shall be printed.

#### Troubleshooting

You may want to delete `$HOME/.local/share/enso/editions` when they download something corrupted.
