### ISSUE TITLE
Compress enormous metadata section by 50% while making it friendlier

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#7989]
Various META-DATA related issues
- #7921
- #7994
- https://github.com/enso-org/enso/pull/7833#issuecomment-1749962867
- #7843

indicate the META-DATA section composes a major problem and a bottleneck in the stability of the whole parsing and editing infrastructure. In addition to that and independently of that the format of metadata is extremely verbose and deserves redesign. Instead of:
```json
[{"index":{"value":127},"size":{"value":3}},"00000000-aaaa-bbbb-0000-000000000000"],
```
we should be writing:
```json
[127,3,"00000000-aaaa-bbbb-0000-000000000000"
```
e.g. shorten each record by almost a half. Please modify the parser to support new, shorter format and make it more bulletproof.

```[tasklist]
### Tasks
- [ ] Support shorter _UUID record_ in metadata
- [ ] Avoid #7921 by prefixing all metadata by four spaces - e.g. turn them into comment
- [ ] Support multiline, human friendly format - https://github.com/enso-org/enso/pull/7833#issuecomment-1749962867
```

**Comment by somebody1234** [comment]
an alternative solution would to be to extract the metadata to separate files so that they become regular JSON, which can then be consumed using a regular JSON parser. not sure whether there are any major downsides to this approach though

**Comment by somebody1234** [comment]
an alternative solution would to be to extract the metadata to separate files so that they become regular JSON, which can then be consumed using a regular JSON parser. not sure whether there are any major downsides to this approach though

**Comment by jdunkerley** [comment]
@Frizi and I also discussed this change - we should make it, but we need to make sure we can still read the old format as well, and the change must work in both the new and old IDEs.

**Comment by JaroslavTulach** [comment]
> an alternative solution would to be to extract the metadata to separate files so that they become regular JSON, 

Maybe, but my PR #7683 is blocked and I need (dirty) fix immediately, not a complete architecture rewrite in weeks.

> which can then be consumed using a regular JSON parser. not sure whether there are any major 
> downsides to this approach though

I remember discussing that in the past and there was some reasoning behind having UUIDs at the end of the file. Any comment @wdanilo, @kustosz?

**Comment by JaroslavTulach** [comment]
Obsolete if #9257 gets implemented.

**Comment by JaroslavTulach** [comment]
Obsolete if #9257 gets implemented.
