### ISSUE TITLE
CB: adding imports necessary for suggestions

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8066]
To be done after #7786 (but first task may be started before).

For each suggestion applied to CB input, we should keep in mind what imports are necessary to have it actually working. When editing is finished and input accepted as new expression, those imports should be added to the module if:
1. The imported identifier is still in the input (it could be removed since applying the suggestion)
2. The entity is not already imported.
```[tasklist]
### Tasks
- [x] Managing imports API - listing, adding, removing.
- [x] Realizing what imports are needed for a given suggestion application (depending on how many qualified name segments are written).
- [x] Checking if entity is not already imported
```
