### ISSUE TITLE
Cannot disable private module checks in tests

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#8140]
It [turned out](https://github.com/enso-org/enso/pull/8127/files#r1368897444) that `--disable-private-check` as mentioned in the [docs](https://github.com/enso-org/enso/pull/7840/files#diff-6cf8b56703980950b1660ca6fc2619df6336b359d463f023105a3089ed1345deR170) isn't implemented. As a result the team can't properly benefit from the existing encapsulation provided by

- #7840

while being able to cover the private code with tests.

>  Let's introduce a new CLI flag to the Engine launcher
called `--disable-private-check`, which will disable all the private checks
during compilation and method resolution.

```[tasklist]
### Tasks
- [x] Introduce `--disable-private-check` CLI option
- [ ] Activate it when running tests in CI
- [x] Add a test to verify the encapsulation is disabled and/or report descriptive error otherwise
```
