### ISSUE TITLE
Add the ability to upload file by drag and drop

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#8158]
```[tasklist]
### Tasks
- [x] Handle file drop event
- [x] Upload file contents to language server, putting it into the project directory
- [x] Insert "file read" node to the graph at mouse drop position - do not add any "temporary" nodes if at all possible
- [ ] https://github.com/enso-org/enso/issues/8182
```

**Comment by vitvakatu** [comment]
Closed in #8214
