### ISSUE TITLE
Remove akka dependencies from `runtime` project

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#8222]
`runtime` project, and thus `runtime.jar` fat jar, transitively contains akka dependencies, for example from `runtime` --> `downloader` --> `akka`. We should remove akka from `downloader` and implement the downloading by some simple http component from JDK (or Scala's standard library).

`akka` is unnecessarily heavy-weight, it comprises of a lot of classes that are loaded just because of few simple HTTP requests.
```[tasklist]
### Tasks
- [x] Ensure there is are no `akka` classes in `runtime.jar`
- [x] Remove `akka` from `downloader` (#8953)
- [x] Split `connected-lock-manager` into two projects
```
