### ISSUE TITLE
Set of Component Browser Issues

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8495]
```[tasklist]
### Issues
- [ ] Ctrl + enter in CB does not close it - not reproducible
- [x] Cannot use `del` key in CB input - addressed in #8507
- [x] Editing node with another node selected adds something to the input. - #8507
- [ ] No local variables sometimes - not reproducible
- [x] When selecting node and pressing `Enter`, the text cursor is not at the end - #8507
- [x] Navigating graph closes CB - this is annoying - #8507
- [x] We should not select last entry by default in many cases. - #8507
- [x] Esc still creates a node (when dragged-out an edge). - #8507
- [x] Clicking (+) button when node is selected deselects node first, and makes initial CB content empty - addressed in #8507
- [x] Clicking background does not keep the input - #8507
```

**Comment by somebody1234** [comment]
One other issue: I think sometimes? Pressing `esc` somehow still creates a node (with contents: `source.`)

**Comment by farmaazon** [comment]
Tasks are fixed or not reproduced. Closing.
