### ISSUE TITLE
Epic: New Execution Context Controls

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#8659]
This epic replaces the existing Execution Context Controls

![image](https://github.com/enso-org/enso/assets/1720119/58e320b7-a376-4847-a4f8-fd6a0d48ea3f)

with a new set

![image](https://github.com/enso-org/enso/assets/1720119/ac191df3-9e90-4f2b-8902-7d48cb85fa1c)

### General Notes

- Replaces the existing Design/Live/Run control

![image](https://github.com/enso-org/enso/assets/1720119/58e320b7-a376-4847-a4f8-fd6a0d48ea3f)
![image](https://github.com/enso-org/enso/assets/1720119/4cb7232a-f628-4e34-8e24-6ee98b97a9c2)

- The new buttons are called Play, Play Once, Record, Record Once
- The new controls are no longer nested under the project name
- Project name now displays where main is
- Live mode is now called Record mode

## Record button

- Replaces the Design/Live toggle.
- Is an On/Off toggle
- Defaults Off
- Off 
![image](https://github.com/enso-org/enso/assets/1720119/3d2ed829-d762-4dba-9b82-c5179a679e04)
replaces
![image](https://github.com/enso-org/enso/assets/1720119/c098a412-7fe4-45d5-9de1-d9edcd819c27)
- On
![image](https://github.com/enso-org/enso/assets/1720119/33047b96-ef86-4783-9fae-90e34297648e)
replaces
![image](https://github.com/enso-org/enso/assets/1720119/94bac835-b3cf-4495-8a17-c2b9a9e10025)

## Record Once button

- Replaces the existing run button
![image](https://github.com/enso-org/enso/assets/1720119/cec3096d-f2eb-4425-b065-3b5499a6e24b)
replaces
![image](https://github.com/enso-org/enso/assets/1720119/b05cb6a1-1f33-48ee-a168-2ec1f7c3430d)
- Pressing this button runs the workflow once end to end with outputs enabled

## Play button

- This is a new button
- Defaults On
- Controls continuous running of a workflow
- When turned off the continuous running feature is turned off
- Uses cached data where possible to render the Graph Editor

## Play Once button

- This is a new button
- Pressing it runs the entire workflow from end to end once (with or without writing to outputs controlled by the state of the Record button)
- Clears all caches and gets fresh input data for all inputs
- Special advanced use case - If Play mode is off. Control clicking this button clears caches and everything without evaluating anything

```[tasklist]
### Tasks
- [ ] https://github.com/enso-org/enso/issues/8672
- [ ] https://github.com/enso-org/enso/issues/8673
- [ ] https://github.com/enso-org/enso/issues/8674
- [ ] https://github.com/enso-org/enso/issues/8675
```
