### ISSUE TITLE
Visual improvements and issues.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8708]
A catch-all task for all little visual bugs/improvements.

```[tasklist]
### Tasks
- [ ] Add dark background when CB is opened.
- [ ] Align (+) button in Vector widget with closing bracket
- [ ] https://github.com/enso-org/enso/issues/8995
- [ ] Remove "halo" from output enabled indicator.
```

**Comment by jdunkerley** [comment]
Halo on output enabled indicator: 
![image](https://github.com/enso-org/enso/assets/4699705/07740341-09b1-48c3-ab44-4848fa235d19)

**Comment by farmaazon** [comment]
Done or not obsolete.
