### ISSUE TITLE
Bugs in GUI2

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8745]
This task gather all remaining issues which prevent us for signing-off GUI1 removal.
```[tasklist]
### Tasks
- [x] When clicking at nested selector, two are opened at once (Picture 1). Addressed by #8749
- [x] Sometimes when dropping connection, it's connected to last used selection. Addressed by #8749
- [x] https://github.com/enso-org/enso/issues/8822
- [x] Fullscreen visualizations has areas where mouse is not visible (@farmaazon)
- [x] Reconnecting: highlight does not say which endpoint will be disconnected (@farmaazon)
- [x] Reconnecting: dropping edge with disconnected source does not work (it should disconnect, but it reverts) (@farmaazon)
- [x] https://github.com/enso-org/enso/issues/8854
- [x] https://github.com/enso-org/enso/issues/8756
- [x] https://github.com/enso-org/enso/issues/8534
- [x] https://github.com/enso-org/enso/issues/8810
- [x] create `Table.at` node and set index - the placeholders are broken (Picture 3) - @farmaazon - not reproducible anymore
- [x] Soft wrap of the documentation in CB sometimes does not work (Picture 3) (@vitvakatu)
- [x] https://github.com/enso-org/enso/issues/8884
- [x] https://github.com/enso-org/enso/issues/8684
- [x] https://github.com/enso-org/enso/issues/8799
- [x] https://github.com/enso-org/enso/issues/8801
- [x] https://github.com/enso-org/enso/issues/8899
- [x] https://github.com/enso-org/enso/issues/8932 - quickfix applied.
- [x] CB Preview is evaluating too many things at a time (no canceling of previous evaluation).
- [x] Sometimes, when node is updated while edited in CB, the CB change is discarded
- [x] Code comments are breaking graph
- [x] Alias analysis not working in "Geo analysis" example (from the "home" page)
- [ ] https://github.com/enso-org/enso/issues/8238
- [x] Cloud: Binary connection is dropped after some time
```

![image](https://github.com/enso-org/enso/assets/3919101/50a4fe9b-11b2-4f58-9249-bea6e5454acd)

![Screenshot from 2024-01-18 11-05-18](https://github.com/enso-org/enso/assets/3919101/d580af56-81ce-4d3e-88b0-22c8502f8ead)

![Image](https://github.com/enso-org/enso/assets/3919101/25ee3905-c789-42ff-b814-c70f575719c6)

**Comment by somebody1234** [comment]
re: multiple "you may be a victim of scam" messages

this is intentional, otherwise it's possible that it's scrolled out of view by the time the user opens the console. it's true that *usually* this shouldn't happen because currently no real logging happens, but i think it's better to be on the safe side

**Comment by farmaazon** [comment]
Moved several tasks which are not essential for GUI1 removal to another issues.
