### ISSUE TITLE
Generate benchmark result pages in the CI

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#8857]
Since its inception, the benchmark results have been collected, saved into cache on my local file system, and uploaded to https://github.com/enso-org/engine-benchmark-results. It is scheduled to run as a daily job. The https://github.com/enso-org/enso/blob/49835500895be8b1f779cc2c40df9c03ee3ebcb8/tools/performance/engine-benchmarks/bench_download.py script requires a (local) cache because the GH artifacts are dropped after 3 months (this period cannot be extended, according to the GH policies), so we would lose the benchmark results older than 3 months. The cache is located on my local file system, without any backups.

Let's add another daily GH action that runs `bench_download.py`.

```[tasklist]
### Tasks
- [x] Reimplement the cache from local filesystem to https://github.com/enso-org/engine-benchmark-results
- [ ] Add another daily GH action that runs `bench_download.py`.
- [ ] Generate a GH token (permissions described in https://github.com/enso-org/enso/issues/8857#issuecomment-1914558703)
```

A rather more difficult, but more permanent, solution is to implement just a frontend (hosted as a website in https://github.com/enso-org/engine-benchmark-results repo) that fetches all the bench results dynamically from the GH artifacts. Such a solution would have the following properties:
- Do not collect results older than 3 months into any kind of cache - no need for any kind of backend.
- Benchmark comparison (compare a custom branch to `develop) can be handled by the website
- No more need for a custom `bench_download.py` script - everything could be done on the website.
- The advantage is that we would see all the results immediately.

**Comment by Akirathan** [comment]
We need to look into this task eventually, as the current solution is not sustainable - in case something happens to my laptop, we lose the daily website update. Note that the results could be still recovered from the website itself (the results are plain javascript data structures in the HTML), although, that would require a lot of manual work.

@jdunkerley @JaroslavTulach What do you say about the proposed solution? Should we keep the status quo, but just move its execution into the CI (a bit easier solution, just rewrite some bits of `bench_download.py` script so that it can run as a daily GH action possibly with access to some remote file system), or should we aim for a more permanent solution? Any other propositions?

**Comment by JaroslavTulach** [comment]
CCing @mwu-tow 

> should we aim for a more permanent solution

Start with _Add another daily GH action that runs `bench_download.py`._, generates and uploads the website to the repository.

Personal wish: don't write that GH action in Rust, please.

**Comment by mwu-tow** [comment]
As for the issue — I'd like to chat sometime to better understand it.

> Personal wish: don't write that GH action in Rust, please.

This is not about personal favors, while I want to keep you happy, there are various factors and tradeoffs involved. I think your remark goes beyond this particular issue.

**Comment by JaroslavTulach** [comment]
> 
> > Personal wish: don't write that GH action in Rust, please.
> 
> This is not about personal favors, ... there are various factors and tradeoffs involved. I think your remark goes beyond this particular issue.

Yes, this remark certainly reflects the wider _current CI situation_. The reason why it is mentioned in this issue is that this new CI action pipeline has nothing to do with already existing CI actions and as such it is a **chance to start from scratch** and avoid drawbacks of the _current CI situation_.

**Comment by Akirathan** [comment]
We spoked with @mwu-tow and this is the summary of our discussion:
- Let's create another GH action yaml descriptor for this job
  - There is no need to generate this yaml file from Rust. There would be no benefits of doing so, since this job is a very simple one.
- Let's use the https://github.com/enso-org/engine-benchmark-results repository as the cache itself - just upload the JSON files there directly.
  - Locally, I have 8 MB and 700 JSON files as a cache data for the last year. No need to do this via some sophisticated technology like AWS.
- There is a single simple actionable item that blocks me from implementing this - generate a GH token with the following permissions:
  - Download artifacts from engine jobs in `enso-org/enso` repo.
  - Checkout and push to `enso-org/engine-benchmark-results` repo.

@mwu-tow Please, generate the token for me and let me know how to use that from the yaml file. I will also edit the description of this issue to reflect this conclusion.

<blockquote><img src="https://opengraph.githubassets.com/a250d8a115c0f64e484b9a618c8b626544517c85af1d924bf3db696c9b372abf/enso-org/engine-benchmark-results" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/engine-benchmark-results">GitHub - enso-org/engine-benchmark-results: https://enso-org.github.io/engine-benchmark-results/</a></strong></div><div>https://enso-org.github.io/engine-benchmark-results/ - GitHub - enso-org/engine-benchmark-results: https://enso-org.github.io/engine-benchmark-results/</div></blockquote>

**Comment by mwu-tow** [comment]
@Akirathan 
Thanks for the writeup! 

I have created a secret named `ENSO_BENCHMARK_RESULTS_TOKEN` take contains a Github Token (PAT) that should include the necessary privileges. I haven't used the fine-grained PATs before, so please let me know if there are any issues. I might have missed something.
