### ISSUE TITLE
Dropdown Widget Improvements

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#8995]
This issue covers a number of improvements to the dropdown widget (Some may already be covered by https://github.com/enso-org/enso/issues/8708)

```[tasklist]
### Tasks
- [x] Arrows for widgets: they should be visible only when widget is hovered + they should be a little smaller and less vivid.
- [x] Drop downs should show code. (e.g. Right_Exclusive not Right Exclusive)
- [x] When an option is selected on the dropdown with a mouse click, the selection should be made and the dropdown immediately closed
- [x] If there are a small number of items in the dropdown the height should shrink
- [x] If there are a larger number of items in the dropdown the scrollbar should appear. The last item shoudl be half cropped.
- [x] Dropdown shoud have a 2px border (Confirm the 2px with Figma design)
- [x] The internal border radious should be constant
- [x] Remove "sort" arrows in drop-down list (up/down)
```

**Comment by farmaazon** [comment]
Moved more complex points to #9058.
