### ISSUE TITLE
Epic: 2024 Q1 OKR

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9007]
```[tasklist]
### Tasks
- [ ] https://github.com/enso-org/enso/pull/8990
- [ ] https://github.com/enso-org/enso/issues/8995
- [ ] https://github.com/enso-org/enso/issues/9058
- [ ] https://github.com/enso-org/enso/issues/8681
- [ ] https://github.com/enso-org/enso/issues/8678
- [ ] https://github.com/enso-org/enso/issues/9002
- [ ] https://github.com/enso-org/enso/issues/8570
- [ ] https://github.com/enso-org/enso/issues/8139
- [ ] https://github.com/enso-org/enso/issues/9008
- [ ] https://github.com/enso-org/enso/issues/9009
```
