### ISSUE TITLE
Visualization Small Fixes

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9009]
```[tasklist]
### Tasks
- [x] Big white space above full screen viz.
- [x] Escape should close the full screen visualization.
- [x] Viz shortcuts (Shift-Space, Ctrl-Space) not working.
- [x] Serialize the width of visualizations.
```

**Comment by vitvakatu** [comment]
I moved last point to #8708
