### ISSUE TITLE
Component Browser Alias Behaviour Not Working 

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9107]
The component browser isn't quite working correctly with component aliases.

### Display alias when searching by alias

When I search using an alias I expect that alias to show in the component browser with the actual component name in brackets afterwards. e.g. For component Take and alias First

Expected:

![image](https://github.com/enso-org/enso/assets/1720119/0b2b8c42-40cb-407f-b923-7523d7719f11)

Actual:

![image](https://github.com/enso-org/enso/assets/1720119/905ec643-8e46-4984-a297-73ac3edcfb9d)

### Multiple aliases should work

e.g. For component Take and alias Last

Expected: 

![image](https://github.com/enso-org/enso/assets/1720119/7ccf156a-2868-45dc-bad5-eb8040d34248)

Actual:

![image](https://github.com/enso-org/enso/assets/1720119/07ef8b3e-a917-4d42-afa0-12626e107444)

### Searching by alias initials should work

e.g. Searching for gb should find aggregate via the group_by alias

Expected:

![image](https://github.com/enso-org/enso/assets/1720119/b093a409-2af7-420f-8aa1-d0e03215d0d2)

Actual:

![image](https://github.com/enso-org/enso/assets/1720119/5d07e14e-a13f-4b89-981a-eefc6eed2393)

```[tasklist]
### Tasks
- [ ] https://github.com/enso-org/enso/issues/9148
- [ ] Multiple aliases should work
- [ ] Searching by alias initials should work
```

**Comment by farmaazon** [comment]
> Multiple aliases should work

[We have test for it](https://github.com/enso-org/enso/blob/343a6440510920df78e758208258c056d786be26/app/gui2/src/components/ComponentBrowser/__tests__/filtering.test.ts#L204), and it passes - so probably the problem is in reading aliases from documentation.

**Comment by somebody1234** [comment]
oops... didn't notice kaz was assigned

**Comment by kazcw** [comment]
> oops... didn't notice kaz was assigned

No problem, I hadn't started on parts 2-3 yet anyway
