### ISSUE TITLE
Individually Output/Record enabled component enhancements

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9164]
This is about enhancements to the mode currently enabled with this button

![image](https://github.com/enso-org/enso/assets/1720119/fc5f0b5a-2876-4f44-b43d-bba5b4dbdd36)

### 1 Make the self operator arrows still work when the mode is toggled on.

This is a bug, where we are losing the self argument arrows when the mode is turned on

![image](https://github.com/enso-org/enso/assets/1720119/dfa5a5c5-f7e0-4418-ad39-10db59810116)

### 2 Update the icons

Make the icons be consistent with the new icons for live/design mode in https://github.com/enso-org/enso/pull/9133

i.e. grey circle for off
red circle for on

### 3 When toggled on the button should remain visible when the wheel menu is closed

![image](https://github.com/enso-org/enso/assets/1720119/799d824b-cf17-4b10-86ca-5319621311e5)

Needs to line up with the underlying menu so there is no jump as the menu is opened/closed

```[tasklist]
### Tasks
- [ ] 1 Make the self operator arrows still work when the mode is toggled on.
- [ ] 2 Update the icons
- [ ] 3 When toggled on the button should remain visible when the wheel menu is closed

```

**Comment by farmaazon** [comment]
Refinement notes:
* This task will simplify things: user should be able only to enable output context explicitly. But let's keep code handling it.
* The new icon shape and visibility should not depend on the global execution mode anymore.
