### ISSUE TITLE
Epic: Component Grouping Improvements

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9178]
```[tasklist]
### Tasks
- [ ] https://github.com/enso-org/enso/issues/9159
- [ ] https://github.com/enso-org/enso/issues/9412
- [ ] https://github.com/enso-org/enso/issues/9519
- [x] Ability to name grouped components
- [x] Icon for grouped components
- [x] Output port handling
- [ ] https://github.com/enso-org/enso/issues/11179
- [ ] https://github.com/enso-org/enso/issues/10696
- [ ] https://github.com/enso-org/enso/issues/11180
- [ ] https://github.com/enso-org/enso/issues/11406
- [ ] https://github.com/enso-org/enso/issues/11211
- [ ] https://github.com/enso-org/enso/issues/11347
```

**Comment by AdRiley** [comment]
Follow on epic https://github.com/enso-org/enso/issues/11979
