### ISSUE TITLE
Epic: Improve adding new components

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9181]
```[tasklist]
### Tasks
- [ ] https://github.com/enso-org/enso/issues/9415
- [ ] https://github.com/enso-org/enso/issues/9416
- [ ] https://github.com/enso-org/enso/issues/9423
```
