### ISSUE TITLE
Component comments small fixes

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9261]
```[tasklist]
### Tasks
- [x] Now that we have icons on the full wheel we need the ... option to expand the full wheel from the smaller one.
- [x] The comment icon is always visible when the small menu is open. It should only show when the full wheel is open.
- [ ] The comment widget shouldn't change height/font size when it is being edited
- [ ] There shouldn't be a rectangle when the comment widget is being edited
- [ ] Pressing enter when editing should exit edit mode (not add a new line)
- [ ] This one I think I got wrong in my original ticket, but now I can play with it I feel like you should be able to edit it just by clicking on it (without a CTRL modifier). In the same way you can edit a text widget.
```
