### ISSUE TITLE
Autoscoping for Table filter

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#9277]
The Table [filter method](https://github.com/enso-org/enso/blob/02bd863c29f36e7e952cd0fa6e7dd66b3666c851/distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso#L1443) uses 
```
@filter Widget_Helpers.make_filter_condition_selector
```
make sure the `filter` argument can use autoscoped constructors in the IDE.

```[tasklist]
### Tasks
- [ ] Modify `make_filter_condition_selector` to use _autoscoped constructors_
- [ ] Test the behavior of the IDE remains the same
- [ ] Decide whether a fix needs to be done on the language server side or the IDE
```

**Comment by JaroslavTulach** [comment]
The IDE probably need to handle [.. prefix for autoscoped constructors](https://github.com/enso-org/enso/pull/9285/files#r1519451329) as prefix and not **operator with missing lhs** first to actually test the `Table.filter` behavior.

**Comment by 4e6** [comment]
gui interprets the expression `..Constructor` as a binary operation with the first argument not provided. The work on the parser is needed to recognize `..` as a unary operator applied to constructor.

![enso-autoscope-filter](https://github.com/enso-org/enso/assets/357683/117b52b1-4957-4e79-b809-53ef3c3d9520)

**Comment by 4e6** [comment]
Also, the expression updates for autoscoped constructor calls don't contain the method pointer. The work on the engine side is also needed.

**Comment by 4e6** [comment]
The issue is that during the instrumentation, the result of the `..Constructor` call is an `UnresolvedConstructor` object. To create a method pointer, the engine needs to intercept a node after the method resolution is done. 
\cc @JaroslavTulach

**Comment by JaroslavTulach** [comment]
> The issue is that during the instrumentation, the result of the `..Constructor` call is an `UnresolvedConstructor` object. 

I see. We cannot create Method Call object from `UnresolvedConstructor` as [Adam requested](https://github.com/enso-org/enso/pull/9293#discussion_r1520908000)...

> To create a method pointer, the engine needs to intercept a node after the method resolution is done.

However an `UnresolvedConstructor` gets converted to [real constructor according to docs](https://github.com/enso-org/enso/blob/a01aeab3a4acacf8f6a77ba94097f4cca16c8bc0/docs/syntax/types.md#type-definitions) at the end.

- the call just happens sometimes later
- however that must be similar to suspended arguments
- does IDE handle suspended arguments well?
- if so, what do we need to do to send IDE enough information to also handle _autoscoped constructors_ as well?

**Comment by 4e6** [comment]
It seems that all the problems with autoscope are from the fact that the resolution is happening in runtime. The `..Constructor` is supposed to mean "I'm too lazy to write the type name, you can figure it out yourself". And we indeed should be able to do that in the compile time. Given

```rb
type T
    A
    B
type S
    B
foo t:T|S = t
```

- In the `foo ..A` call, the `..A` expression is consumed by the method `foo`, which first argument has type `T`. This information should be enough to make a resolution and insert a `T.A` application node during the codegen.
- The `foo ..B` should result in a compiler error indicating that the `..B` resolution is ambiguous
- The `foo ..C` should result in a compiler error indicating that the `..C` cannot be resolved
- the `..A` call should result in a compiler error indicating that the `..A` cannot be resolved because we don't have the context of the foo call providing the type information

This will require a kind of type inference (i.e. associating types with expressions) which the compiler cannot do right now. But I think it's a good opportunity to start by implementing this very isolated scenario \cc @radeusgd 

Also, making the name resolution in compile time will not affect the runtime performance.

**Comment by JaroslavTulach** [comment]
> ... autoscope ... resolution is happening in runtime. ... be able to do that in the compile time. 

The possibility of having autoscoping based on _static type inference_ has been [discussed](https://github.com/orgs/enso-org/discussions/8646) and **rejected** before the work started. If you believe _static type inference_ is the only way to fix the problems for `Table.filter`, please [continue the discussion](https://github.com/orgs/enso-org/discussions/8646) in its discussion forum.

Let's leave this issue focused on solving the problem, but feel free to [question the overall concept](https://github.com/orgs/enso-org/discussions/8646).

**Comment by hubertp** [comment]
Should probably be closed once #9259 is closed.

**Comment by JaroslavTulach** [comment]
With commit https://github.com/enso-org/enso/pull/9452/commits/3a986f04fbaee7d30bab6261fbefaf88ed452faa from #9452 I was able to get `operator51546.filter 'Organisation' filter=(..Equal 'SpaceX')` working with following change in `Table`:
```diff
diff --git distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
index a42bc1dd8c..9aaf724a4f 100644
--- distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
+++ distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
@@ -1476,16 +1476,17 @@ type Table
     filter self column (filter : Filter_Condition | (Any -> Boolean) = Filter_Condition.Equal True) on_problems=Report_Warning = case column of
         _ : Column ->
             mask filter_column = Table.Value (self.java_table.filter filter_column.java_column)
-            case filter of
+            f = Panic.catch Any (filter:Filter_Condition) _->filter
+            case f of
                 _ : Filter_Condition ->
-                    resolved = (self:Table_Ref).resolve_condition filter
+                    resolved = (self:Table_Ref).resolve_condition f
                     mask (make_filter_column column resolved on_problems)
                 _ : Function -> Filter_Condition_Module.handle_constructor_missing_arguments filter <|
                     mask (column.map filter)
-        _ : Expression -> self.filter (self.evaluate_expression column on_problems) filter on_problems
+        _ : Expression -> @Tail_Call self.filter (self.evaluate_expression column on_problems) filter on_problems
         _ ->
             table_at = self.at column
-            self.filter table_at filter on_problems
+            @Tail_Call self.filter table_at filter on_problems
 

```
e.g. the inline type ascription `(filter : Filter_Condition | (Any -> Boolean)` is quite problematic. It is the same as `(filter : Filter_Condition | Function)` and _autoscoped constructor_ has type `Function`. E.g. it matches the runtime type without any conversion! Moreover doing `case filter of` and ` _ : Filter_Condition` pattern matching doesn't force the conversion of `UnresolvedConstructor` to real `Filter_Condition` - it just doesn't match. Hence the `f = Panic.catch Any (filter:Filter_Condition) _->filter` attempt to force a conversion. Nasty.

![IDE knows Equal's argument](https://github.com/enso-org/enso/assets/26887752/1182cbe0-1df9-48e9-8726-2b94abaf43f5)

However the IDE seems to know `..Equal` takes one argument and what kind of values it can offer for that argument.

**Comment by radeusgd** [comment]
> e.g. the inline type ascription `(filter : Filter_Condition | (Any -> Boolean)` is quite problematic. It is the same as `(filter : Filter_Condition | Function)` and _autoscoped constructor_ has type `Function`. E.g. it matches the runtime type without any conversion! Moreover doing `case filter of` and ` _ : Filter_Condition` pattern matching doesn't force the conversion of `UnresolvedConstructor` to real `Filter_Condition` - it just doesn't match. Hence the `f = Panic.catch Any (filter:Filter_Condition) _->filter` attempt to force a conversion. Nasty.


Huh, that's an interesting edge case! The `filter` operator taking a function is indeed complicating things a bit - we also need special handling for to more nicely display info about missing args to `Filter_Condition` (see: `unify_condition_or_predicate`). I guess we could move this special 'hack' into `unify_condition_or_predicate` as well.

Hopefully it will not be needed in too many places - fortunately I don't think there's many other places that mix an autoscoped type with `Function`.

**Comment by 4e6** [comment]
https://github.com/enso-org/enso/pull/9293#issuecomment-2035445131 verifies that after fixing the expression updates for autoscope constructors in #9452, the dropdowns with autoscope constructors work in gui the same way as normal constructors
