### ISSUE TITLE
Catch up Season 5 book clubs Weeks 1-4

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9348]
Catch up Season 5 book clubs Weeks 1-4 for @Frizi 

```[tasklist]
### Tasks
- [ ] Week 1 (https://discord.com/channels/401396655599124480/1197244840728088646/1197244840728088646)
- [ ] Week 2 (https://discord.com/channels/401396655599124480/1199763967657127966/1199763967657127966)
- [ ] Week 3 (https://discord.com/channels/401396655599124480/1202285185253769306/1202285185253769306)
- [ ] Week 4 (https://discord.com/channels/401396655599124480/1204826447022395434/1204826447022395434)
```

**Comment by farmaazon** [comment]
Closing now. We'll focus on doing next bookclub seazon on time.
