### ISSUE TITLE
Catch up Season 5 book clubs Weeks 1-4

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9350]
Catch up Season 5 book clubs Weeks 1-4 for @kazcw 

```[tasklist]
### Tasks
- [x] Week 1 (https://discord.com/channels/401396655599124480/1197244840728088646/1197244840728088646)
- [x] Week 2 (https://discord.com/channels/401396655599124480/1199763967657127966/1199763967657127966)
- [x] Week 3 (https://discord.com/channels/401396655599124480/1202285185253769306/1202285185253769306)
- [x] Week 4 (https://discord.com/channels/401396655599124480/1204826447022395434/1204826447022395434)
```
