### ISSUE TITLE
QA GUI Defect Log

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#9354]
This ticket is a holder for discovered GUI defects in the QA process.
```[tasklist]
### Tasks
- [x] ⭐Dropdown showing the code not the labels.
- [x] Parse error on `[ Aggregate_Column.Sum (expr "")]` resulted in incorrect placement within `aggregate`. https://github.com/enso-org/enso/pull/9677
- [ ] ~No longer showing escaped text when not editing a text node. @vitvakatu~
- [ ] https://github.com/enso-org/enso/issues/9379
- [x] Dropdown selected item is indented. - #9516
- [x] ~Showing the dropdown on a text box with values (e.g. column names) is very fiddly.~
- [ ] https://github.com/enso-org/enso/issues/9357
- [x] Zoom steps are not sensible (100 -> 71 -> 50 ...) #9585
- [ ] https://github.com/enso-org/enso/issues/9445
- [x] Parenetheses are sometimes not rendered in the node https://github.com/enso-org/enso/pull/9678
```

**Comment by jdunkerley** [comment]
Dropdown:
![image](https://github.com/enso-org/enso/assets/4699705/69e58e87-051a-4c19-a14c-7591cc3a8dd8)

![image](https://github.com/enso-org/enso/assets/4699705/96e3f386-1625-452d-b476-c318fa851bd8)

![image](https://github.com/enso-org/enso/assets/4699705/fd254231-7ae6-4c19-a3cd-310a97645d3f)

Textbox:
![image](https://github.com/enso-org/enso/assets/4699705/e18b68a8-4133-4caf-9018-59315b58aa62)

**Comment by jdunkerley** [comment]
Join Video: `on= [ (Join_Condition.Equals 'Year'), (Join_Condition.Equals 'Year')]`

https://github.com/enso-org/enso/assets/4699705/768620fe-21eb-41f2-bf1e-1cb558303aab

**Comment by jdunkerley** [comment]
Parse Error: `[ Aggregate_Column.Sum (expr "")]`
![image](https://github.com/enso-org/enso/assets/4699705/e65b9467-5036-48c9-a9a8-2d414a634070)

**Comment by farmaazon** [comment]
Zoom levels should be similar to Chrome's one: `500/400/300/250/200/175/150/125/100/90/80/75/67/50/33/25/10 `

**Comment by vitvakatu** [comment]
Dropping two tasks from the list:
- “No longer showing escaped text when not editing a text node.” – not a priority right now, should rather be fixed by #8753 and #8754, allowing to edit the code of the specific text literal.
- “Showing the dropdown on a text box with values (e.g. column names) is very fiddly.” – seems to be fixed now.

**Comment by vitvakatu** [comment]
All tasks done
