### ISSUE TITLE
Launcher

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#955]
### Summary

To make it easier to manage different versions of enso, we want to provide a launcher script that allows the user to launch different enso versions in each project and manage versions of both enso and GraalVM that it runs on.

The launcher will be used to run the REPL, enso scripts and the language server. Its responsibility will be to select the correct version based on the current directory (based on project configuration), make sure it is downloaded and up-to-date and pass command arguments to the launched component. It must also be possible to update the launcher itself.

### Value

It is easier to use enso releases. The users don't have to bother with downloading new releases from the website, but can just use the update tool. It is possible to maintain different versions of enso for different projects. It is less likely that users will launch enso using wrong version of GraalVM, as its versions will also be managed by the launcher by default.

#### Launcher

- [x] Design the launcher (#954).
- [x] Set-up CI for the launcher with the Native Image build (#973).
- [x] Specify how the launcher is distributed (#987).
- [x] Handle parsing CLI arguments for the launcher and the support for launcher plugins (#995).
- [x] Set-up automation for creating new releases (#980).
- [x] Handle distribution layout and installation (#1010).
- [x] Enso version management (#974).
- [x] Running components through the launcher (#976).
- [x] Launcher distribution uninstall capability (#1011).
- [x] Managing projects and configuration (#977).
- [x] Handling broken releases (#1075).
- [x] Self-update mechanism (#975).
- [x] Self-update fallback (#1013).
- [x] Locking components (#1126).
- [x] Logging service (#1031).
- [ ] Improve launcher UX (#1039, #1052, #1078, #1099, #1143, #1188).
- [ ] Add an integrity check for downloaded packages (#1154).
- [ ] Make manifest and config parsing more resilient to recoverable errors (#1494).
- [ ] Update the README included within the distribution (#1322).

#### Extending the Project Manager

- [x] Update the project manager protocol (#1149).
- Implement components management:
  - [x] Separate the ComponentsManager and its dependencies into a library (#1152).
  - [x] Improve locking mechanism (#1254).
  - [x] Integrate the ComponentsManager with the project manager (#1153).
- [x] Explore how the project manager can be started by the IDE (compiling it to Native Image or using some Java runtime) (#1150).
- [x] Integrate with the logging service (#1144).
- [x] Add a separate version field in engine's manifest (#1323).

### Acceptance Criteria & Test Cases

- The above specification has been completed.
- The launcher is tested and distributed in the CI.
