### ISSUE TITLE
Export FQN without any imports

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#9562]
The [import/export documentation](https://github.com/enso-org/enso/blob/develop/docs/syntax/) has been **incorrectly understood** leading to an **obscure**, **verbose**, **do repeat yourself** usages polluting all our standard libraries. 

>  Qualified Exports
>
>  These exports consist of the word export followed by a qualified name of a module. This can by optionally followed by the as 
>  word, and a referent name of the module as it should be visible in the exporting scope.
>
>    The only name brought into scope by such an export is the name of the module (or the name provided after the as keyword, if provided).

For a while I am puzzled, by our usual code that imports and exports at once:
```ruby
import project.System.Platform
export project.System.Platform
```

as shown for example [in here](https://github.com/enso-org/enso/blob/1872bb66eaad4cde966658b7789c28abc3894a27/distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso#L191C1-L191C31). It is not really DRY, right?

Reading the _Qualified Exports_ section, I believe the specification actually says that we should be able to do just:
```ruby
export project.System.Platform
```
There's **no point to import FQN and export FQN**. Let's not spell FQN twice!  Alternatively one could write:
```ruby
import project.System.Platform
export Platform
```
that'd also logical and rationalistic. But the current use of doubled FQN in export and import is just unnecessary boilerplate.

```[tasklist]
### Tasks
- [x] Support `export project.System.Platform` without any imports
- [ ] Support `import ...` followed by simple non-qualified `export Platform`
- [x] Update  [import/export documentation](https://github.com/enso-org/enso/blob/develop/docs/syntax/)  to explicitly mention these two new schemes are now supported
```

**Comment by JaroslavTulach** [comment]
The #9683 PR fixes all but _"Support import ... followed by simple non-qualified export Platform"_ (low priority) task, right?

**Comment by Akirathan** [comment]
> The #9683 PR fixes all but _"Support import ... followed by simple non-qualified export Platform"_ (low priority) task, right?

@JaroslavTulach No. The following snippet:
```
import project.Mod.Type
export Type
```
Results in a compilation error:
```
Execution finished with an error: org.enso.compiler.core.CompilerError: Compiler Internal Error: Imports should contain at least two segments after desugaring.
        at <java> org.enso.runtime/org.enso.compiler.phase.ImportResolverAlgorithm.tryResolveImportNew(ImportResolverAlgorithm.java:136)
        at <java> org.enso.runtime/org.enso.compiler.phase.ImportResolverAlgorithm.tryResolveImport(ImportResolverAlgorithm.java:72)
        at <java> org.enso.runtime/org.enso.compiler.phase.ImportResolver.$anonfun$addSyntheticImports$2(ImportResolver.scala:205)
        at <java> org.enso.runtime/scala.collection.immutable.List.flatMap(List.scala:293)
        at <java> org.enso.runtime/org.enso.compiler.phase.ImportResolver.addSyntheticImports(ImportResolver.scala:179)
        at <java> org.enso.runtime/org.enso.compiler.phase.ImportResolver.analyzeModule$1(ImportResolver.scala:80)
        at <java> org.enso.runtime/org.enso.compiler.phase.ImportResolver.go$1(ImportResolver.scala:145)
        at <java> org.enso.runtime/org.enso.compiler.phase.ImportResolver.mapImports(ImportResolver.scala:161)
        at <java> org.enso.runtime/org.enso.compiler.Compiler.liftedTree1$1(Compiler.scala:457)
        at <java> org.enso.runtime/org.enso.compiler.Compiler.runImportsAndExportsResolution(Compiler.scala:456)
        at <java> org.enso.runtime/org.enso.compiler.Compiler.$anonfun$runCompilerPipeline$2(Compiler.scala:274)
        at <java> org.enso.runtime/scala.collection.immutable.List.flatMap(List.scala:293)
        at <java> org.enso.runtime/org.enso.compiler.Compiler.runCompilerPipeline(Compiler.scala:269)
        at <java> org.enso.runtime/org.enso.compiler.Compiler.go$1(Compiler.scala:234)
        at <java> org.enso.runtime/org.enso.compiler.Compiler.runInternal(Compiler.scala:241)
        at <java> org.enso.runtime/org.enso.compiler.Compiler.run(Compiler.scala:132)
```

Theoretically, it should work. But since we already support only exports without imports, I don't see any added value to this functionality.
