### ISSUE TITLE
Catch up Season 5 book clubs Weeks 5-8

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9709]
```[tasklist]
### Tasks
- [x] [Week 5](https://discord.com/channels/401396655599124480/1207372697278087208)
- [x] [Week 6](https://discord.com/channels/401396655599124480/1209944770433130567)
- [x] [Week 7](https://discord.com/channels/401396655599124480/1212468677455388682)
- [x] [Week 8](https://discord.com/channels/401396655599124480/1215011676701728848)
```
