### ISSUE TITLE
Type Inference Prototype

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#9811]
A group ticket to track high-level roadmap for the type inference prototype.

- [x] Basic type propagation, starting from literals and atom constructors through typed local function calls
  #8590 
	- [x] PR #8652 - ready but waiting on #9361 to be able to be integrated.
- [x] Propagating through method calls on types #9812
- [x] Lint pass on CI #12775 
- [ ] Handling of default arguments #12776 
	- Needed because most of our standard library methods _have default arguments_, so a type inference that bails out in presence of defaults is rather useless.
	- [ ] Handling of named arguments, possibly done together or split off.
- _Later:_ Send inferred types to the IDE before the result is yet computed to improve node coloring etc.
- [x] Handling of Conversions #12335
	- Needed to be able to actually report type-errors (as warnings).
	- [x] Reporting type warnings.
- [ ] Static check for private methods #12777
- [ ] Static-analysis coverage #13369 
- [ ] Improving the type matching algorithm #13372

**Comment by radeusgd** [comment]
2025 updated road map proposition: https://docs.google.com/document/d/1Tyl5oqgqwd16LdsBXT3VcRkrvOaPguCjK4xbNKN1ZCU/edit?tab=t.0

<blockquote></blockquote>
